### ISSUE TITLE
Question on requirement for 'aux' not to have children (Tswana)

### ISSUE THREAD

**Issue by tanjagaustad** [UniversalDependencies/docs#1018]
As a follow-up to issue [1008 ](https://github.com/UniversalDependencies/docs/issues/1008), I was wondering if we could get some insights from the UD community on the following:

In Tswana, subject concords are used to indicate subject agreement, both with overt and covert subjects.  One issue we have come across when validating, though, are sentences where the subject concord is doubled when an auxiliary is used. We have decided to annotate them with the expl relation in accordance with the UD guidelines. See the tree below with the constructions “o ne a penta” where the aux-AUX "ne" has a dependency to the expl-PRON subject concord. This is a case of “doubling pronoun" in Tswana, with the added difficulty of the aux-AUX expressing tense as well as Aktionsart.

![image](https://github.com/UniversalDependencies/docs/assets/95272341/5f70a305-916f-4e5a-bcc0-00e0e7b82303)

We could simply attach the expl relation for "o" to the main verb "penta", but as the doubling only occurs with an auxiliary, that solution didn't feel right to us as we wanted to explicitly express the dependency between the auxiliary and the doubled subject concord. But then the tree does not validate...
How are other languages dealing with issues like this? Thanks for your help!

**Comment by dan-zeman** [comment]
The assumption in UD is that verbs form a unit with their auxiliaries (making it similar to languages where the function of the auxiliary is carried just by morphology of the main verb), and dependents (including `expl` dependents) should be attached directly to the root node of that unit.

This includes situations where the dependent could not be present without the auxiliary. (I can think of examples from other languages where the other dependent is also an auxiliary; I'm not sure I can come up with an example with `expl`, but there is no reason why it should be treated differently.)

**Comment by nschneid** [comment]
Might be good to include some more examples under [function word modifiers](https://universaldependencies.org/u/overview/syntax.html#function-word-modifiers)

**Comment by tanjagaustad** [comment]
Thanks for these insights! We have now adapted the annotations to link the expl dependents to the main verb.

**Comment by tanjagaustad** [comment]
Resolved for Tswana for now.

**Comment by sylvainkahane** [comment]
I just add that as soon as your UD treebank will be published, it will be converted into SUD (Surface-Syntact UD) and it will be available on Grew-Match. See https://universal.grew.fr/?corpus=SUD_Zaar-Autogramm@2.13.
In SUD, the AUX will be the head of the verbal complex and according to the heuristic we use, the expletive before the AUX will depend on the AUX, which is the surface syntactic analysis that you want. Nevertheless, you are invited to verify that the conversion is really ok, because it is easy to decide what really depends on the AUX and what depends on the VERB and sometimes our heuristics don't work. It was the case at least for German and Wolof and we apply special Grew grammars for the conversion in these cases.
Of course, this invitation to check the SUD version of your treebank is not limited to Tswana. If you see any problem in a SUD treebank converted automatically, please contact @bguil and me.

**Comment by tanjagaustad** [comment]
@sylvainkahane Thanks for this information. We will definitely check it out once the treebank is published.
