### ISSUE TITLE
Comparative constructions

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/docs#104]
I don't see any guidelines (with examples) on annotating comparative constructions.
See http://ufal.mff.cuni.cz/project/depling13/proceedings/pdf/W13-3721.pdf for a possible (pre-UD) solution.

**Comment by dan-zeman** [comment]
Thanks for the comprehensive documentation (http://universaldependencies.github.io/docs/u/overview/specific-syntax.html#comparatives) and sorry if it turns out that I did not read it attentively enough but I could not find a solution (or analogy) to this:

[1] _Home prices have more than doubled in the past decade._

Attaching _doubled_ to _more_ does not seem quite right to me, because _doubled_ contains both the action modified by quantity/degree, and the base quantity for the comparison. A paraphrase easier to analyze would be

[2] _Home prices have increased more than twice in the past decade._

where I guess we would want
advmod(increased, more)
advmod(more, twice)   [or advcl???]
mark(twice, than)

In order to make the two above examples somewhat parallel, I am inclined to analyze the former as
advmod(doubled, more)
mark(more, than)

with the assumption that the quantity compared to has been elided (although it actually has been incorporated into the verb).

The actual example from the data that led me to think about this was a bit different:

[3] _more than thirty-years-lasting experience_
(cs: _více než třicetileté zkušenosti_)

(It was in Czech and thirty-years-lasting is one word, and it is an adjective.) I am not sure whether [3] will have the same solution as [1] though. If we paraphrase it as

[4] _older than thirty-years-lasting experience_

then we have
amod(experience, older/more)
advcl(older/more, thirty-years-lasting)
mark(thirty-years-lasting, than)

What do people think?

**Comment by spyysalo** [comment]
@dan-zeman : just a meta-comment (sorry, I don't have a good solution to propose): I think the original issue (no guidelines on annotating comparative constructions) remains resolved and would like to suggest to keep this closed and open new issues for more specific cases.

**Comment by tdozat** [comment]
We actually consider *more than* to be an `mwe` in quantities when it acts synonymously with *over*, because sometimes the two words (*more* and *than*) are inseparable:

[1]
~~~ sdparse
More than 90 percent
advmod(percent, More)
mwe(More, than)
~~~

[2]
~~~ sdparse
Over 90 percent
advmod(percent, Over)
~~~

[3] *More percent than 90.

While you can't really say *Home prices have over doubled in the past decade*, the fact that *more* and *than* can't be separated suggests that it should be analyzed as a whole chunk acting as an `advmod` rather than as a phrase that has undergone ellipsis of some sort.

This analysis also presents a possible solution to the Czech problem; if Czech has a one-word synonym for *more than* like English *over* that can be substituted in this situation, then *more than* could analyzed as an `mwe` (at least sometimes) functioning as an `advmod` on *thirty-years-lasting*.

**Comment by dan-zeman** [comment]
@tdozat : thanks for the clarification! I will add it to the discussion of comparative constructions in documentation. I cannot think of a one-word synonym for _more than_ in the Czech problem but I believe that these instances of _more than_ are inseparable, which would allow us to analyze them as `mwe`.

**Comment by martinpopel** [comment]
If anyone feels this old discussion is too short, see #507 for a continuation.
