### ISSUE TITLE
`as X as` expressions as `fixed` with ExtPos - what qualifies?

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/docs#1043]
Where is the line to draw for `as X as` expressions?  There are some marked in EWT, such as

```
**as well as** the fun filled social dance evening held every Saturday evening
I will often have **as many as** one per kitten
```

but then many others are not marked, such as

```
We should know **as much as** we can
```

**Comment by nschneid** [comment]
https://universaldependencies.org/en/dep/fixed.html has:

- `fixed` for "dogs as well as cats" (coordinating)
- `fixed` for [quantity approximators](https://universaldependencies.org/en/dep/fixed.html#approximators-quantity-modifiers) like "as much as fifty percent"

But regular comparatives like "I am as tall as you" or "I have as much as you" are not `fixed`. Does that answer the question?

**Comment by AngledLuffa** [comment]
The line gets a bit blurry on the quantity approximators for `as much as`.  Several which might qualify are left unmarked in EWT. 
 (In fact, all cases of `as much as` are not marked as `fixed`)  Consider:

```
# text = We should know as much as we can.
# text = Senior officials have been quoted in the press as saying that the searches were for the purpose of excluding him as much as including him.
# text = They want to squeeze as much as they can from you
my husband and I chose 4 types of pizza and the servers brought out as much as we wanted.
```

dev set:

```
# text = actually i have an project on it so please give meas much as you have information about migratory birds in punjab
```

test set:

```
will help you as much as they can with thier years of hands on practice
```

In some cases it seems to be easier to separate and therefore perhaps doesn't warrant `fixed`

```
prepare pay twice as much as they tell you initially
```

**Comment by nschneid** [comment]
Going by the example "as much as fifty percent", I think the `fixed` usage is for hedging a number that modifies a noun.

**Comment by dan-zeman** [comment]
Given that it is syntactically regular, is there a good reason to treat _as much as fifty percent_ as `fixed`?

**Comment by sylvainkahane** [comment]
I think that the test for "as X as Y" could be to see if it can replaced by X:
- I am as tall as you => I am tall
- I have as much as you => I have much
- dogs as well as cats => *dogs well cats

For the other examples, I let you native guys decide, but I don't  see why "as much as fifty percent" should be necessary fixed:
- as much as fifty percent of the butter has been wasted => much of the butter has been wasted

**Comment by nschneid** [comment]
> For the other examples, I let you native guys decide, but I don't see why "as much as fifty percent" should be necessary fixed:
> 
>   * as much as fifty percent of the butter has been wasted => much of the butter has been wasted

This gets into semantics but "as much as one percent" does not entail "much". :) It means "up to one percent".

With the caveat that the `fixed` list was originally developed at Stanford, and I wasn't involved, I think the goal is to analyze some of these expressions as modifying a number that attaches as `nummod`. So [[[as much as] fifty] percent]

**Comment by sylvainkahane** [comment]
The fact that "as much as fifty percent" could be non compositional doesn't qualify it as a "fixed" expression because we are not annotating semantics. If the construction is syntactically regular it must be annotated with regular syntactic relations.
Moreover I don't see why this expression is not compositional and does not entail "much". What would have been expected as a compositional meaning? Moreover the same construction is possible with "many":
- as many as 1,000 species of finch have been identified

**Comment by nschneid** [comment]
A canonical use of the as-as comparative for quantities would be like (1):

(1) I have as many cookies as you (have).

This describes two distinct sets of cookies and says their sizes are **equal**. There is a variant

(2) I have as many cookies as you have bagels.

where the two sets are of different kinds of things, but again, their sizes are the same.

Whereas

(3) I have as many as five cookies.

likely describes only one set of objects, and is imprecise about its size. It reflects bounded uncertainty: the speaker thinks they *might* have five cookies, or possibly less, but not more than 5.

One could read (3) as having two nominals with ellipsis in the first, i.e.

(4) I have as many cookies as five cookies.

which is oddly redundant, but if forced to interpret it I get not the imprecision meaning, but the same-quantity meaning. That is why one could argue "as many as" is morphosyntactically fixed with an idiomatic meaning.

What does this mean for UD? The guidelines [say](https://universaldependencies.org/en/dep/fixed.html#approximators-quantity-modifiers):

<img width="397" alt="image" src="https://github.com/user-attachments/assets/014f6279-753e-4180-8904-9b176678e933">

The guidelines also list similar uses of "more than", "less than", "up to", and "all of" as `fixed`. They don't provide a test except to say that it is used with quantities. I suspect the actual test that was assumed is, does it indicate *sameness* (that would be the standard as-as comparative) or does it indicate an *bounded imprecise* quantity?

If the test is semantic, it would also apply to

(5) In this neighborhood, houses are on the market for **as much as** a million dollars.

But I wonder if the construction is actually more productive, and could include "as high as", "as long as", etc.:

(6) In this neighborhood, house prices are **as high as** a million dollars.

I can get (6) to mean the same thing as (5), i.e. the houses have a range of prices and the most expensive ones are a million dollars. (Though "as high as a million dollars" is clearly not a nominal. "As much/*high as a million dollars was spent on the project.")

So this makes me wonder if we are bringing too much semantics into the syntactic analysis. Maybe the UD structure should be the same for standard comparatives where the head noun is omitted, and noncompositional or noncanonical meaning belongs in a different layer.

(P.S. I take back the bracketing I gave earlier—I was confusing the CGEL analysis with EWT's.)
