### ISSUE TITLE
Clitic doubling

### ISSUE THREAD

**Issue by prokopidis** [UniversalDependencies/docs#129]
Hi,

This is a question about how clitic doubling should be treated in UD-compatible guidelines for languages with this phenomenon.

In Greek we have

<pre><code>1. έδωσε της Καίτης τον αναπτήρα
gave ART.Fem.Gen Keti.Gen ART.Masc.Acc lighter.Acc</pre></code>

<pre><code>2. της τον έδωσε
PRON.Fem.Gen PRON.Masc.Acc gave</pre></code>

but also

<pre><code>3. Της τον έδωσε της Καίτης τον αναπτήρα
PRON.Fem.Gen PRON.Masc.Acc gave ART.Fem.Gen Keti.Gen ART.Masc.Acc lighter.Acc</pre></code>

I am thinking of using the expl relation for 3, something like ...

<pre><code>3. Της τον έδωσε της Καίτης τον αναπτήρα
expl(έδωσε, Της-1)
iobj(έδωσε, Καίτης)
expl(έδωσε, τον-2)
dobj(έδωσε, αναπτήρα)</pre></code>

while keeping the core argument annotations for 2.

<pre><code>2. Της τον έδωσε
iobj(έδωσε, Της)
dobj(έδωσε, τον)
</pre></code>

Thanks for your comments.

**Comment by manning** [comment]
This is a good question! Clitics and clitic doubling are common enough procedures that we should have something to say about what to do in our guidelines. Of course, this is in turn difficult because there are various analyses in the syntactic literature. And it may well be that different analyses are better for different languages -- at the end of the day, clitic phenomena are usually part of grammaticalization processes. Nevertheless, as much uniformity of analysis as is reasonably possible would be nice for UD.

In brief, what you propose seems the best idea to me. I'll add a bit to the definition of `expl` to include this case.

Long version: There are various analyses and cases of pronominal clitics. In some languages (like French), clitics are in complementary distribution with full nominals ("Kayne's generalization"). In such cases, there seems no doubt that whichever occurs should get the relation `dobj`, `iobj`, etc. But in other languages you get both the clitic and a full nominal ("clitic doubling"). In some cases, it may be possible to analyze the full nominals as `dislocated` -- such as for colloquial French cases where you do get doubling, and I take Greek as having such dislocation constructions, but it doesn't seem plausible to claim that all clitic doubling in Greek is dislocation, pace [Androulakis 2001](http://www.reading.ac.uk/internal/appling/workingpapers/androulakis.pdf). Another analysis, roughly as in [Philippaki-Warburton et al. 2002](http://www.reading.ac.uk/internal/appling/wp6/clitics.pdf) is to say that the clitics fill the main grammatical role position (are `dobj`, `iobj`) and the full nominals are an adjunct (which would become `obl` in UD). Such an analysis has also been used in languages such as Warlpiri. I'm pretty suspicious of this analysis for Greek, and at any rate adopting such an analysis would greatly undermine cross-linguistic parallelism, so that analysis seems dispreferred. A third analysis is that the clitic and lexical head somehow start together in syntax and are then moved apart. It's not quite clear what a dependency implementation of this approach would look like -- perhaps the clitic would be some kind of dependent of the lexical head of the nominal -- but it also doesn't seem very appealing to me, since this seems to be using a dependency for coindexation not syntactic relationship. A fourth analysis is to treat clitics as morphology, e.g., [Miller and Sag 1997](http://www.jstor.org/stable/4047813) for French, but that often doesn't seem right, and doesn't seem a popular analysis for Greek. The final analysis would be to see the clitic as some kind of pronominal dependent of the verb, but for full nominals to be at least the preferred recipient of dependencies like `dobj` and `iobj`. In an analysis like [Harizanov 2014](http://stanford.edu/~bharizan/pdfs/Harizanov_2014_NLLT.pdf), the clitic and lexical nominal are two positions of the same constituent in a movement chain. That kind of analysis isn't exactly available in dependency grammar, but nevertheless some major aspects of it are relevant. If the lexical nominal is in an argument position, it seems right to regard it as the `dobj`/`iobj` when present. If the pronominal clitic behaves like a copy (different position) of the nominal, then it seems reasonable to regard it as the `dobj`/`iobj` when there is no lexical nominal. When both occur, it seems like the contentful role should go to the lexical nominal, and then the clitic is effectively like an agreement marker and does not itself get a semantic role, and so `expl` seems a plausible analysis in UD -- even though this use of `expl` is somewhat different to the original use of `expl`.

**Comment by manning** [comment]
This issue is quiet and there doesn't seem any disagreement, so I'm going to close it for now and regard this as settled for UD version 1.
