### ISSUE TITLE
Remnants without correlates

### ISSUE THREAD

**Issue by prokopidis** [UniversalDependencies/docs#136]
Hi,

This issue is about gapping when a non-core remnant does not correspond to a correlate in a preceding clause. For example, in the following

~~~ sdparse
Mary will come today and Tom tomorrow , if he finds a ticket .
remnant(Mary, Tom)
cc(come, and)
remnant(today, tomorrow)
~~~

and in similar examples in other languages, where should we attach the adverbial clause?

If there isn't a relevant analysis that I missed, one solution would be to allow promotion of elements without a correlate, as dependents of the first clause predicate, _come_ in the example. This would have obvious side-effects. An alternative trick - which maybe allows the reconstruction of correct structure at a later stage - would be to label the problematic remnant with its understood relation to the elided predicate, and to attach it to the closest relevant token bearing the `remnant` relation: 

~~~ sdparse
Mary will come today and Tom tomorrow , if he finds a ticket .
remnant(Mary, Tom)
cc(come, and)
remnant(today, tomorrow)
advcl(tomorrow, finds)
~~~

Thanks.

**Comment by tdozat** [comment]
Our approach in the English Universals Dependencies branch is basically your second suggestion, to attach the adverbial to the nearest argument that belongs to the same event as it (e.g. the event of "Tom [coming] tomorrow" in your example). If it should come in between two such `remnant` arguments--which normally degrades the acceptability of the sentence, but anything is possible in the web domains we've been working with--it should attach to the leftmost argument (out of a preference for having heads to the left in English when all else is equal). So we'd have:

~~~
Mary will come today and Tom , if he finds a ticket, tomorrow .
remnant(Mary, Tom)
cc(come, and)
remnant(today, tomorrow)
advcl(Tom, finds)
~~~

This is a little weird because it has an `advcl` depending on a noun, which shouldn't ever happen under normal circumstances (we'd use `acl` instead), but this might be a good thing because it would help end-user applications identify this as something weird. On the other hand, if we were to go with your first suggestion, making it a `remnant` on the head verb, we produce highly ambiguous sentences in the (admittedly rare in English) instance of recursive gapping, where the gapping event that "sprouts" the adverbial is a gapped argument itself:

~~~
Mary told John that *he* was bringing coke and *Cindy* beer , and John 's wife that *Cindy* was bringing coke and *John* beer , if he was coming .
remnant(bringing-1, bringing-2)
remnant(bringing-2, coming)
~~~

Under this parse and the pre-existing rules dictating the use of `remnant`, "if he was coming" is a `remnant` on a `remnant`, which means that it should be part of a `remnant` "chain", such as we find in sentences like "Miriam went to Paris, Marie to Prague, Chris to Tokyo, and Masoud to Moscow." The effect of this is that the dependency labels indicate that it means "Mary told John's wife, if he was coming". This is problematic because the resulting interpretation is semantically well-formed, structurally unremarkable, and clearly wrong (the intended meaning is "Mary told John's wife that *John* was bringing beer, if he was coming", with the adverbial modifying an entirely different clause). Since we want to avoid assigning multiple wildly differing meanings to single dependency parses, `remnant` should *only* be used between two parallel dependents when one of them is gapped, and it should *never* be used between a head word and a sprouted dependent of a gapped clause. This approach doubtless introduces its own ambiguities, but I would hold that they're much less severe than those introduced by the alternative.

I hope that clears it up!
