### ISSUE TITLE
Updated Universal POS tagset

### ISSUE THREAD

**Issue by aboSamoor** [UniversalDependencies/docs#152]
The original universal POS tagset published [here](https://code.google.com/p/universal-pos-tags/) has 12 POS tags. However, it seems that your [universal tagset](http://universaldependencies.github.io/docs/u/pos/index.html) has 17 POS tags.

Is there any mapping I am not aware of that we can use to map conll datasets to the new universal POS dataset?

**Comment by dan-zeman** [comment]
Yes, it is here:
http://universaldependencies.github.io/docs/tagset-conversion/index.html
and you can use it to map to both the universal POS tags and universal features.

**Comment by aboSamoor** [comment]
Is there any written converter script?

**Comment by dan-zeman** [comment]
Yes. One option would be using Treex (http://ufal.mff.cuni.cz/treex). But it is a whole NLP infrastructure and it is a heavy weight for people who just want to convert tags in a CoNLL-X file.

You can also use Interset without Treex. It is a Perl library and it is available at CPAN as Lingua::Interset. You should be able to install it calling

<pre>cpanm Lingua::Interset</pre>

or, if you do not have <tt>cpanm</tt> (but you do have Perl installed), try <tt>cpan</tt> instead.

Then this Perl script would convert a, say, Slovenian CoNLL-X file so that there are universal POS tags and features in the output (note that the only Slovenian-specific thing in the code is the <span style="color:red"><tt>sl::conll</tt></span> identifier of the tagset):

<pre>#!/usr/bin/env perl
use open ':utf8';
binmode(STDIN, ':utf8');
binmode(STDOUT, ':utf8');
binmode(STDERR, ':utf8');
use Lingua::Interset::Converter;

my $c = new Lingua::Interset::Converter ('from' => <span style="color:red">'sl::conll'</span>, 'to' => 'mul::uposf');

# Read the CoNLL-X file from STDIN.
while(<STDIN>)
{
    unless(m/^\s*$/)
    {
        chomp();
        my @f = split(/\t/, $_);
        my $tag = "$f[3]\t$f[4]\t$f[5]";
        my $utag = $c->convert($tag);
        my ($upos, $ufeat) = split(/\t/, $utag);
        $f[3] = $upos;
        $f[5] = $ufeat;
        $_ = join("\t", @f)."\n";
    }
    # Write the modified line to the standard output.
    print();
}</pre>

**Comment by dan-zeman** [comment]
I just tested a modification of the script where the input tagset is indicated using the -f (from) option.

<pre>conll_convert_tags_to_uposf.pl -f sl::conll &lt; sltest.conll &gt; sltest-uposf.conll</pre>

where <tt>conll_convert_tags_to_uposf.pl</tt> contains the following:

<pre>#!/usr/bin/env perl
# Reads CoNLL-X from STDIN, converts CPOS+POS+FEAT to the universal POS and features, writes the result to STDOUT.
# The output contains the universal POS tag in the CPOS column and the universal features in the FEAT column.
# The POS column is copied over from the input.
# Copyright © 2015 Dan Zeman <zeman@ufal.mff.cuni.cz>
# License: GNU GPL

use utf8;
use open ':utf8';
binmode(STDIN, ':utf8');
binmode(STDOUT, ':utf8');
binmode(STDERR, ':utf8');
use Getopt::Long;
use Lingua::Interset::Converter;

sub usage
{
    print STDERR ("Usage: conll_convert_tags_to_uposf.pl -f source_tagset &lt; input.conll &gt; output.conll\n");
}

# Get options.
GetOptions('from=s' =&gt; \$tagset1);
if($tagset1 eq '')
{
    usage();
    die();
}

my $c = new Lingua::Interset::Converter ('from' =&gt; $tagset1, 'to' =&gt; 'mul::uposf');

# Read the CoNLL-X file from STDIN.
while(&lt;&gt;)
{
    unless(m/^\s*$/)
    {
        chomp();
        my @f = split(/\t/, $_);
        my $tag = "$f[3]\t$f[4]\t$f[5]";
        my $utag = $c->convert($tag);
        my ($upos, $ufeat) = split(/\t/, $utag);
        $f[3] = $upos;
        $f[5] = $ufeat;
        $_ = join("\t", @f)."\n";
    }
    # Write the modified line to the standard output.
    print();
}</pre>

**Comment by manning** [comment]
Although there is a warning at the top that these tables will not and cannot always give the right answer, I suspect it is insufficiently strong. Would it be okay if I added a bit more text to that effect?

**Comment by dan-zeman** [comment]
Feel free to do so, thanks!

**Comment by manning** [comment]
Done!
