### ISSUE TITLE
POS for words like "kolik" = "how much"

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#154]
In Czech, these words are traditionally classified as (pronominal) numerals. Their behavior is indeed similar to numerals in some respects. In Czech UD, we tag them as DET to make the annotation of counted phrases parallel to the annotation of quantifiers in other languages. This is quite justifiable in sentences like "Kolik jablek má Martin?" = lit. "How-many apples has Martin?" In these cases, "Kolik" will also be attached as "det:numgov" to "jablek".

However, pronominal numerals can also be attached as "dobj", as in the sentence "Kolik to stojí?" = lit. "How-much it does-cost?" One could say that this is an elliptical sentence, really meaning "Kolik korun/eur/dolarů... to stojí?" ("How many crowns/euros/dollars... does it cost?") But we still want to attach "Kolik" as "dobj" to "stojí". At the same time, we probably do not want its UPOS tag to be "DET", or do we?

This is parallel to a distinction that we do with Czech pronouns: in attributive positions they are tagged as DET, elsewhere they are tagged as PRON: "Které/DET auto chceš?" ("Which car do you want?") but "Auto, které/PRON chceš, je drahé." ("The-car, that you-want, is expensive.") Only it is not clear whether we want to also extend the PRON tag to the pronominal numerals like "kolik".

Perhaps we do because the only other possibility I see is to tag them NUM, and that would violate the rule that NUM always indicates a definite, known quantity.

  * `DET` ... if used, it will not hold that `DET` always co-occurs with `det` (or its subtypes).
  * `NUM` ... if used, it will not hold that `NUM` always indicates a known quantity.
  * `PRON` ... tentatively the least weird solution?

**Comment by dan-zeman** [comment]
Comments welcome. I will have to decide this somehow for version 2, but I guess there are other languages where this is an issue?

**Comment by manning** [comment]
Hi Dan, I suspect that you have to decide wha you think is best here yourself, since there just isn't a ton of other Czech expertise - certainly not from me - but, here's an attempt at an answer. I think analogous situations arise in many places, and you have to make a decision as to whether they are in some sense elliptical, and then you can say that a word retains its normal, lexical category, or if you view it as non-elliptical, and then you might say that the word has a POS ambiguity to a new category (perhaps as zero derivation).  I think the elliptical analysis is sometimes to be preferred. E.g., in English, you can omit a noun head, and say things like "[The unhappy] will manage to be unhappy anywhere." Here you have an analogous situation. Do you say that "unhappy" is still an ADJ, even though it is not an `amod`? For the English construction here, I think that is the preferred analysis, since that construction is fairly marked - though I think it might be more freely available in Czech. So I guess the question is how elliptical this construction appears in Czech. I did find this one (Chomskyan) syntax article on the topic: http://www.oldanglistika.upol.cz/quant.pdf . It suggests that the nominal after *kolik* can't be elided, which if true would perhaps favor a non-pronominal analysis.  I think that is what I would do for English.  For "You bought how many?", I would keep *many* as an `ADJ`, allowing it to take normal modification by an `ADV` via an `advmod`, and just live with the fact that the `ADJ` is not the `amod` of anything.

**Comment by jnivre** [comment]
I think this is something that needs to be discussed more generally. In some other cases, notably verb particles, we have decided that the part of speech doesn't change, only the syntactic function. Similarly, in multi-word expressions, the component words still retain their normal part-of-speech tag. Therefore, I agree with Chris that it makes most sense to tag "unhappy" in "the unhappy" as ADJ, and I think this is what we do in the Swedish treebank. However, there are also many cases where we have to recognize that a word can be used with more than part-of-speech tag even though one of them may be (at least historically) primary. For example, "run" is presumably a verb originally but is now well established as a noun. It seems to me that, if you make a DET/PRON distinction elsewhere, then you should make the same distinction for _kolik_. But I also suspect that this is one of the areas where we are still not consistent across languages. I think some language always use DET, some always use PRON, and some use DET/PRON depending on whether the word is used as a determiner or as a nominal head on its own. And it is not immediately clear to me whether the DET/PRON case is more similar to "unhappy" or to "run".

**Comment by manning** [comment]
Agree with @jnivre. In principle, I think it would be highly productive to do a number of cross-language studies of how phenomena like this have been and should be treated and then to have guidelines and corpus updates that reflect perceived best practices. In practice, I doubt we have the energy to initiate this, and so what will happen is some enterprising graduate student will write a paper pointing out all the inconsistencies in UD annotation, and then that will finally give us the direction and motivation necessary to lift our game. ;)

**Comment by manning** [comment]
But I've done one little comparison that I'll put in a different issue, which will be of interest to @dan-zeman

**Comment by manning** [comment]
I'm closing this for now, but have opened issue #159 on the more general case, which I suggest we put off resolving until after release 1.1.

**Comment by dan-zeman** [comment]
Late as with the other issues today, but I'd like to thank for the comments anyway!

I completely agree that _unhappy_ is still adjective, although I am not sure whether _kolik_ is similar enough. Let's see how #159 evolves. If we keep the borderline between `PRON` and `DET` as it is now, then I will probably make _kolik_ a `PRON` as well... until the PhD student (or anyone else) brings order to the chaos :-) I am also discussing the PRON/DET distinction with folks working on Croatian and Slovenian, so hopefully we can coordinate views at least within the Slavic language space. More in #159.
