### ISSUE TITLE
Completing docs for intended POS-Feature combinations 

### ISSUE THREAD

**Issue by spyysalo** [UniversalDependencies/docs#158]
Most features in the universal documentation identify the parts of speech that they are intended to apply to, e.g. http://universaldependencies.github.io/docs/u/feat/Mood.html:

> Mood is a feature that expresses modality and subclassifies finite verb forms.

This is very helpful for validation and configuring tools for annotation. However, some features still lack an explicit statement of the parts of speech the feature is intended to apply to, namely

* http://universaldependencies.github.io/docs/u/feat/Aspect.html
* http://universaldependencies.github.io/docs/u/feat/Tense.html
* http://universaldependencies.github.io/docs/u/feat/Voice.html

Based on release 1.0 data, it seems that all three apply to verbs (`VERB` and `AUX`) as well as to adjectives(?).

(Tentatively assigning @dan-zeman )

**Comment by dan-zeman** [comment]
Yes, verbs (including auxiliaries) are the primary candidates here. Adjectives, adverbs and nouns cannot be excluded because of the verbal/deverbal word forms that live on the border between categories. So I propose the following:

X is typically a feature of verbs. It may also occur with other parts of speech (nouns, adjectives, adverbs), depending on whether borderline word forms such as gerunds and participles are classified as verbs or as the other category.

**Comment by dan-zeman** [comment]
Done, closing.
