### ISSUE TITLE
Inconsistent treatment of clausal complements of copulas

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#161]
I think I have detected an inconsistency in the universal guidelines. In the description of the cop relation it is stated:

"Finally, ccomp is used with copulas. Only in this case, the structure is different, and we take the form of be as a head."

However, in the description of the csubj relation I find the following statement, which seems to contradict the above:

"A clausal subject is a clausal syntactic subject of a clause, i.e., the subject is itself a clause. The governor of this relation might not always be a verb: when the verb is a copular verb, the root of the clause is the complement of the copular verb."

Which one is correct? In the Swedish treebank, I have implemented the latter analysis, which means that copulas are never heads.

**Comment by dan-zeman** [comment]
It was my understanding that copulas are never heads. I believe this is how I implemented the conversion of the Czech treebank.

**Comment by jnivre** [comment]
This was my understanding too. It seems most consistent with everything else, now that the previous exception involving prepositional phrases has been eliminated.

**Comment by ngiordani** [comment]
These guidelines are not exactly inconsistent, although admittedly not ideal. The first one is about sentences like this:

The problem is that we don't know what to do here.
ccomp(is, know)
nsubj(is, problem)

And the second is about structures like this:

Not knowing what to do was the problem.
csubj(problem, knowing)
cop(problem, was)

**Comment by jnivre** [comment]
Okay, thanks for clarifying, then there is no internal inconsistency at least. But I find it weird to adopt the copula-as-head analysis only for the case with a clause as predicate. The fact that one and the same predicate gets two subjects in this case is just a special instance of the fact that dependency structures can't distinguish between head modification and phrase (or clause) modification. What was the solution adopted by the Finnish team, using nsubj-cop?

In the Swedish treebank, we would have:
nsubj(know, we)
nsubj(know, problem)
cop(know, is)

I am not sure I will have time to modify this for the next release.

**Comment by manning** [comment]
Following up on what Natalia wrote, I would agree that what we have now is weird/inconsistent. (Prior to the reanalysis of PPs as noun-headed, things were less weird, since there were other cases where the copula did still end up the head, but now this is indeed a rare weird exception.) It would be good to have a better solution. The problem is deciding a better solution....  Ideas welcome!

I think what you have for Swedish now isn't very viable because you lose control of what is the internal subject of the predicate clause versus what subject is equated with it. That is, if I make the example slightly more adversarial:

_The newspaper headline was that the consensus needs to be rewritten._

Then under what you (@jnivre) proposed, this would have the identical dependency representation to the sentence:

_The consensus was that the newspaper headline needs to be rewritten._

This seems to me an unacceptable loss of information about sentence structure. Agree? And your proposal is also very weird in that these sentences have 2 subjects, whereas normally sentences only have 1 subject (even in languages with multiple objects). I think that is another strike against such an analysis.

But I don't like our analysis either. The only alternative I know is what the Finnish TDT used, which, yes, was to have the relations nsubj-cop and csubj-cop for the subject of the copula. Then these two subjects can be distinguished. I can certainly see the appeal of this analysis, and I'd be game to consider adopting it ... though not for May 15. But, the disadvantage of it is that for all the usual cases of copula subjects they all become nsubj-cop, whereas for ones like _The mat is dry_ it would seem better to just have _mat_ just be an `nsubj` like other `nsubj` rather than it being given a different relation.  One could use `nsubj-cop` only when the predicate is a clause with its own internal subject; the potential disadvantage of this analysis is that the relation `nsubj-cop` is guaranteed to be exceedingly rare.

Thoughts?

**Comment by jnivre** [comment]
I agree that we don't want two subjects, and I have for the time being changed the analysis in the Swedish treebank to align with the one for English. Let's keep this for v1.1 and then decide whether to join the Finns or convince them to join us. :)

A quick follow-up: What about the infinitival case:

The trick is to avoid two subjects.

If all we care about is avoiding two subjects, it is fine to have:

nsubj(avoid, trick)
cop(avoid, is)

This is what we currently have for Swedish, but it means we lose the parallelism between finite and nonfinite clauses and it is slightly misleading to say that "trick" is the subject of "avoid", so perhaps this should be analyzed using ccomp as well (xcomp would be wrong since there is no control here, right?).

If we go with the latter analysis, the generalization would be that we never allow the copula to depend on a verb, only on a nonverbal predicate. Not sure what is best here, but I can easily go either way for Swedish in v1.1, so I would appreciate knowing what you have done for English.

**Comment by ngiordani** [comment]
We use ccomp for this too, for exactly the reasons you brought up. And
you're correct that xcomp is not right here.

**Comment by jnivre** [comment]
Great, thanks.

**Comment by jnivre** [comment]
One more question: What do you do with copula-like verbs like "become"? Are adjectival and nominal complements treated as xcomp. For example:

she is a teacher
nsubj(teacher, she)
cop(teacher, is)

she becomes a teacher
nsubj(becomes, she)
xcomp(becomes, teacher)

**Comment by ngiordani** [comment]
Yes, exactly! Only 'be' is a copula.

**Comment by jnivre** [comment]
Thanks. Then I think I know what to do. :)

**Comment by fginter** [comment]
You move fast. :) Anyway: @jnivre -> yes, nsubj:cop + nsubj is what we would have the first hit of http://bionlp-www.utu.fi/dep_search/?db=Finnish&search=_+%3Ensubj%3Acop+_+%3Ensubj+_  means "Main_thing [is] that the_device works".
