### ISSUE TITLE
 Extraction/pre-posing

### ISSUE THREAD

**Issue by yoavg** [UniversalDependencies/docs#176]
Often in newspaper articles, we have an alternation where some "unimportant" element is being extracted and proposed. Examples

- the source of the confusion is still unknown
-->
- the confusion, the source of-it is still unknown.

The general structure is NP S where S is self contained but typically contains some anaphor that points to the extracted element. This is very different than a modified NP such as, that serves as an NP on the whole, as in:

- the confusion which has an unknown source.

It is an overall S with the antecedent of the anaphor being proposed for rethoric reasons (maintaining focus, entity chains, etc).
Note that the element can be extracted from any part of the sentence (an object, a prepositional object, etc), as in:

- the nice garden, we were sitting in-it for long hours.

How would you then annotate and label the relation between S and NP in such cases?

**Comment by spyysalo** [comment]
[`dislocated`](http://universaldependencies.github.io/docs/u/dep/dislocated.html) might apply.

**Comment by yoavg** [comment]
This is sort-of fitting, though I think the `dislocated` relation as currently described may end up being overloaded for many different phenomena.

**Comment by manning** [comment]
Tend to agree with @spyysalo. I think there are two choices, which depend on a decision of headship.
 - If the clause (2nd part) is taken as the head, then I think there is no doubt that this should be `dislocated`. This is the kind of sentence that this relation was made for.
 - If there was a reason for taking the noun phrase (1st part) as the head, then you'd need to do something else. Using `parataxis` would seem the best option.

**Comment by jnivre** [comment]
As far as I understand, these are both prototypical examples of dislocation:

- I think the confusion, the source of-it is still unknown
- the nice garden, we were sitting in-it for long hours

Especially given the resumptive pronoun. This makes them exactly parallel to:

- Dislocation, I don't like it
- Universal Dependencies, it has really caught on

The only difference is that in the latter cases, the dislocated element corresponds to a core argument, rather than a modifier. I think this issue can be closed.
