### ISSUE TITLE
Tricky case of right node raising

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#179]
I found the following tricky case of RNR in the Swedish treebank [literally translated]:

... able to [handle the tasks] and [assume the responsibility] which is required by ...

Unlike the classic case of RNR, where two transitive verbs share an object ("bought and ate an apple"), we here have two conjoined verb phrases where the direct objects share a relative clause modifier. In the current version of the treebank, we analyze this as follows:

dobj(handle, tasks)
conj(handle, assume)
acl:relcl(tasks, required)
dobj(assume, responsibility)

The problem is that there is no conj relation between "tasks" and "responsibility", so there is nothing explicitly capturing the fact that the acl:relcl dependency should be propagated. The alternative seems to be a remnant analysis along these lines:

dobj(handle, tasks)
conj(handle, assume)
acl:relcl(tasks, required)
remnant(tasks, responsibility)

But it is not clear that this captures the propagation any better, so given the rule that a remnant analysis should only be used when nothing else works, I currently prefer the first analysis.

Any thoughts on this?

**Comment by dan-zeman** [comment]
Extended dependency between the other object and the relative clause?

Otherwise, I would take the first analysis but instead of acl:relcl(tasks, required), I would go for acl:relcl(responsibility, required). If the relcl really modifies both objects, it will not hurt to select the one that is closer to the relcl - but the advantage is that we avoid nonprojectivity. Then there is also the optional reading that the relcl actually modifies only the second object. Or does the morphology exclude this? Anyway, if it is at all possible to understand the relcl as modifying only one object, I bet it will be the second one, not the first one, which is more distant.

**Comment by jnivre** [comment]
Good points, but the morphology actually rules out the possibility that the relative clause only modifies the second noun. Attaching it to the second noun is tempting because it avoids non-projectivity, but it goes against the general principle of taking the first conjunct as the head. So it seems that attaching it to the first noun is compatible with it modifying either only the first noun or both nouns, whereas attaching it to the second noun would unambiguously describe a reading where it only modifies the second noun. Therefore, I think I will stick to the current analysis but add an additional dependency in the enhanced representation.

**Comment by dan-zeman** [comment]
Agree. If the narrow reading is ruled out, then the first conjunct should win.

**Comment by jnivre** [comment]
This one seems taken care of. Closing for now.
