### ISSUE TITLE
Multi-word abbreviations

### ISSUE THREAD

**Issue by slavpetrov** [UniversalDependencies/docs#181]
Hi folks,
I see there was a discussion that touched on multi-word abbreviations, but I couldn't figure out what the verdict is. In German there are abbreviations such as ("u.a." - among others, "z.B." - e.g.). What should the POS tag for these be?
Thanks!
Slav

**Comment by spyysalo** [comment]
I believe this was suggestion was adopted (from in #112):

> 
1. General guidelines apply to (candidate) abbreviations. For example, *$* and *%* should be annotated `SYM`, but *kg* should not, following the [guidelines for symbol](http://universaldependencies.github.io/docs/u/pos/SYM.html).
2. Abbreviations for single words are assigned the part of speech of the full form. For example, *Mr.* (*mister*) and *kg* (*kilogram*) should be tagged [`NOUN`](http://universaldependencies.github.io/docs/u/pos/NOUN.html).
3. Acronyms for proper names such as *UN* and *NATO* are assigned [`PROPN`](http://universaldependencies.github.io/docs/u/pos/PROPN.html).

Documented in part under http://universaldependencies.github.io/docs/u/pos/SYM.html .

**Comment by dan-zeman** [comment]
And I would add, multi-word abbreviations should be split to syntactic words in the same fashion as we do with fused words:

z.B. => z. B.

I would be fine with stopping here and saying that "z." is `ADP` and "B." is `NOUN`. Although in fact the meaning is _zum Beispiel_ and _zum_ also happens to be a fused word, which (if spelled in full) would be further split to "zu" (`ADP`) and "dem" (`DET`). So we may as well want to split "z.B." to three syntactic words, and the tags will be `ADP DET NOUN`.

**Comment by slavpetrov** [comment]
Sounds good to me.

Would "etc." then become "et cetera"? And "eg" -> "exempli gratia"?

Fine by me just wanted to double check...

**Comment by dan-zeman** [comment]
If we take this approach seriously, then yes, they would. I am unsure though, whether we want this to become a rule. It seems in line with what we are doing elsewhere but maybe we want to limit the splitting to cases where it is necessary? I must admit I am not attempting to do this in Czech. (We have significantly fewer multi-word abbreviations because of lower-lever tokenization, but there are still cases like "etc".)

The "syntactic-word" segmentation is a cure for cases where the POS would otherwise be unknown. But we could as well say that these MWEs are adverbs, because that is how they work. (As a matter of fact, the Czech equivalent of "etc" is tagged as adverb already in the original treebank, that's why it hasn't been an issue for me.)

**Comment by manning** [comment]
I am rather suspicious of the idea that we wish to split "etc.". The fact that something has a multiword origin (in another language!) just doesn't seem to me a convincing argument for splitting it in synchronic usage. Certainly, for English, we don't split "etc.". And the idea of claiming that there was a CC/cc "et" and a ??/conj "c." doesn't seem very appealing to me.

**Comment by jnivre** [comment]
I agree with Chris here. And I wouldn't like to split "e.g." either, as a matter of fact. As far as I'm concerned, "for example" is a multiword expression, which should really be tagged as an adverb. However, because it is written with spaces, we have to treat it as consisting of two words, and assign the tags ADP and NOUN to them. However, when we get the abbreviation "e.g.", which is regularly tokenized as a single word/token, then I see no reason to split it up. I think it should just be tagged ADV.

**Comment by dan-zeman** [comment]
Fair enough. But this becomes another item on the growing list of things that require more attention and harmonization across the treebanks. Maybe we should start to maintain the list physically as a new issue?

**Comment by jnivre** [comment]
Starting a list of known harmonization issues is an excellent idea, especially in view of the upcoming Uppsala meeting. Should this be in the form of a github issue or is it better to start a Google doc or something?

**Comment by dan-zeman** [comment]
What about a Github page here in the documentation?

+: keeping all stuff at one place; can include the tree visualizations if desirable
-: the ever growing time lag between saving and seeing the changes. But without the visualizations, saved changes are visible immediately (the page that the editor shows after saving)

**Comment by jnivre** [comment]
Yeah. That's probably the best option.

**Comment by dan-zeman** [comment]
OK. I started the list at http://universaldependencies.github.io/docs/issues.html.

**Comment by jnivre** [comment]
Thanks, Dan. I could make some additions myself and then send an announcement on the UD list, asking for contributions. Is that a good idea?

**Comment by dan-zeman** [comment]
Sure, please go ahead. I just picked the first two issues I had on my mind but I know that at some point the other threads must be searched for other topics.

**Comment by jnivre** [comment]
I think the only conclusion drawn at the Uppsala meeting about the original issue was that, if multiword abbreviations are split, the "mwe" relation should be used. Regarding postags, we would just have to use the same heuristics as for ordinary words. Thus, if "i.e." is split into "i." and "e.", then "e." is linked to "i." by an "mwe" relation, and I suppose the postags would have to be PRON and VERB, based on the original latin expression. On the other hand, if it is not split, then ADV seems a more appropriate postag for the whole.

**Comment by dan-zeman** [comment]
I am now looking at the Czech data to see what (and whether anything) should be done w.r.t. multi-word abbreviations. It turns out that the vast majority of instances are abbreviated multi-word expressions that are not function words (expressions). There are normal syntactic relations between the member nodes, so I am not going to change them to `mwe`. The most frequent examples:
- _a . s ._ = _akciová společnost_ = “joint-stock company” ... amod(s, a)
- _s . r . o ._ = _společnost s ručením omezeným_ = “limited liability company” ... nmod(s, r); amod(r, o)
- _n . p ._ = _národní podnik_ = “national enterprise” ... amod(p, n)

**Comment by jnivre** [comment]
I am still not convinced that it is a good idea to split them at all. But if you do split them, you say that the components should be treated exactly as the words they abbreviate, contrary to the recommendation of the discussion group in Uppsala. Is that right? Do you also think that, let's say, USA (which is sometimes written U.S.A., although less frequently so, it seems) should be analyzed as amod(S, U); nmod(S, A)? If, yes, I don't think it is a good idea. If not, where do you draw the line?

**Comment by dan-zeman** [comment]
Unfortunately I was not present in that group so I do not know what exactly was the discussion about. Until now I had the impression that this was mostly about abbreviations that are closer to function words than to content words. The report from Uppsala does not say that, but on the other hand, we used the `mwe` relation only for function expressions so far, so this supported my impression.

I should have examined the data earlier. I thought we would have functional MW abbreviations, too, but they are actually quite rare. Some of them can (and some even must) be written together, with only one period, then no splitting occurs (for instance, “e.g.” is written _např._ even though it is also derived from two words).

My examples above were not split at all (or better: the period was cut off but the letters were not). The correct ortho/typography is _a. s._ (two separate abbreviations). These three examples also happen to be multi-word terms, but that will not hold for every sequence of abbreviations, so it is also not clear how we would decide where to change the current syntactic relation to `mwe`.

_USA_ is easy, as long as you stay in Czech. It is (or at least should be) never written _U.S.A._ I think it explains why the Czech tokenizer is so fine-grained. So this could be the line: if it is a functional MWE, use `mwe`. If not, but the grammar says that the whole thing must be written without spaces on the surface, use also `mwe` as the Uppsala group recommended (and BTW, I also don't find it optimal to split such abbreviations). If the grammar says that it must be written separately, then it is not a multi-word abbreviation but several consecutive single-word abbreviations and they should be treated as the words they represent. That holds even if the MWE folks would treat the whole thing as a semantically non-compositional multi-word term (because non-compositionality is irrelevant for us: if the term was not abbreviated, it would also receive the normal syntactic relations).

**Comment by jnivre** [comment]
Thanks for clarifying, Dan. I had obviously misunderstood this issue completely, perhaps because of some of the earlier discussion about splitting etc. into "et" "cetera" and so on. So the general conclusion is that we prefer a compositional analysis whenever possible and resort to mwe only when the choice of head (and relations) would be completely arbitrary. This applies regardless of whether the words involved are themselves abbreviations or not. I'll update the recommendation accordingly. I will close this issue now.
