### ISSUE TITLE
expl for Ro

### ISSUE THREAD

**Issue by CatalinaMaranduc** [UniversalDependencies/docs#184]
I disagree that appears on Ro page to the expl label.
We are in Ro a lot of dobj and iobj expl 
they are mandatory, the expression is incorrect without them. Ex.:

 Ion a rugat-o și el pe mama să-i dea lui mai întâi banii.
John /asked/-her/and he/his mother/to/-him/give/to him/first/the money.

”and he” is expl, for ”John”; we are also ”-her” which is dobj:expl for ”his mother”, and we are also   ”-him” which is iobj:expl for ”to him”.
If we not use more labels, anyone do not understand anything.
I believe that we must rank among UD but also to have a coherent system for our language.
A label do not cover a lot of different (core) things.

In the example posted on our page  
 ”a apucat-o la stânga” is, (comply with all Romanian dictionaries) mwe, and not expl.

So, we used in our treebank annotation (UAIC-Ro-Tb) the label expl only for the word which repeat the nsubj. 
We used also the labels ”dobj:expl” and ”iobj:expl”.
Can you accept these labels as our language-specific?

**Comment by manning** [comment]
I'm not very expert on Romanian, but my general understanding is that Romanian has a rich and complex system of clitic doubling of dobj and iobj arguments, somewhat similar to Spanish, but more common and with a more developed "verbal complex". Often times this doubling clitic is compulsory.

Anything is open to revision at some point - though as you probably know, @jnvre is very keen on keeping things stable for a while. The general idea of the current standard was that for core arguments there should be one thing marked as `dobj` or `iobj` per semantic role in the sentence. Additional markers of the same semantic role become `expl`. This still seems to me a position with some appeal.

Would the solution of doing the opposite, and using `expl:dobj` and `expl:iobj` seem okay to you? That would seem more consistent with the current guidelines.

**Comment by CatalinaMaranduc** [comment]
Yes, that's very good, we will have the label expl and his subclassifications: expl:nsubj, expl:dobj and
expl:iobj.

**Comment by KirilSimov** [comment]
Dear All,

Just a comment about another language with clitic doubling – Bulgarian. 
We are happy with just one label for all verbal clitics because in 
Bulgarian there is no way to mix them. Having grammatical features 
accusative/dative case and dependency label 'expl' (clitic in our 
previous encoding) uniquely determines the role played by the clitic – 
imposing additional agreement features on the direct/indirect object. 
In this respect, it seems that labels like expl:dobj and expl:iobj 
would be redundant for Bulgarian.

Our only doubt in the current approach is the assignment of different 
roles to the clitics depending on the fact whether the full-fledged 
dobj or iobj is expressed (role: expl) or not (role: dobj or iobj). Our 
opinion is that the clitics play the same role in all the cases – they 
just impose agreement features on the direct or indirect object, 
independently from the fact whether these are explicit, implicit or 
recoverable within the context.

For example:

Ivan ya       podari na Maria
Ivan it/FEM   gave   to Maria
Ivan gave it to Maria.


Ivan ya       podari kartinata    na Maria
Ivan it/FEM   gave   picture/FEM  to Maria
Ivan gave the picture to Maria.


Ivan kupi   kartina     i   ya     podari na Maria.
Ivan bought picture/FEM and it/FEM gave   to Maria.
Ivan bought a picture and gave it to Maria

In our view, in all these cases the clitic has to be marked as 'expl' only.
If it is necessary to assign additional labels, this might be done by
a simple rule.

The idea is to keep the things as simple as possible.

With best regards,

Kiril
