### ISSUE TITLE
Value for Czech "Foreign"

### ISSUE THREAD

**Issue by TomazErjavec** [UniversalDependencies/docs#185]
Czech documentation (http://universaldependencies.github.io/docs/cs/feat/Foreign.html) specifies the values of Foreign = [Foreign, Fscript, Tscript], but the Treebank (and /tools/data/feat_val.cs) set the value as [Yes]. Which is correct?

**Comment by dan-zeman** [comment]
Oops, this is a bug in the data, thanks for reporting. "Yes" was correct previously but should have been changed to "Foreign" in this release.

**Comment by TomazErjavec** [comment]
Drat, I changed it from Foreign to Yes in our corpus, seemed to make more sense.
Will change it back at some point so we don't diverge.

**Comment by jnivre** [comment]
This issue seems to be resolved, so I will close it.

**Comment by dan-zeman** [comment]
@TomazErjavec : I am myself unsure what is better: `Foreign` or `Yes`. The idea was that `Yes` occurs with boolean features and by adding the `Fscript` and `Tscript` possibilities this feature stopped to be boolean. On the other hand, the other two values are used rarely.

I am now fixing the bug in the conversion tool I use for the Czech data but I can revert to `Yes` (and change documentation) if people think it is better. The main point is we should use the same value in all treebanks that tag it.

I am reopening the issue and adding @fginter to the discussion, since Finnish is the only other language currently using this feature, according to http://universaldependencies.github.io/docs/ext-feat-index.html. If you guys are fine with the currently documented approach, We can close the issue after some time again.

**Comment by dan-zeman** [comment]
The Czech data have been updated in the repository. `Foreign=Yes` has been changed to `Foreign=Foreign`, so the data are currently in line with the documentation. The list of language-specific feature values in the tools repository has been updated likewise.

**Comment by dan-zeman** [comment]
There do not seem to be diverging opinions and Czech has been fixed, so I am closing the issue again.
