### ISSUE TITLE
Universal Dependency mapping for Hindi-Urdu

### ISSUE THREAD

**Issue by riyazbhat** [UniversalDependencies/docs#188]
Hi all,

I have upload an initial version of the UD mapping for the dependencies in Hindi-Urdu treebanks. Both the treebanks use around 85 dependency labels, many of them are mapped to ``nmod`` in UD due to their finer nature. I am not sure whether I should drop the finer dependencies or use eloboration instead, for example for ``k3`` (stands for instrument) I can either use ``nmod:instrument`` or just leave it to ``nmod``.

And, is there any other solution for ellipsis apart from using ``remant``? Hindi-Urdu includes all the elided head nodes,  identifying a remant relationship with some previous node for the child nodes of elided element seems prety diffuclt. I tried to automate it, but with lots of errors. There doesn't seem to be any deterministic way. There are around 2K sentences with ``NULL`` nodes out of 30K sentences. 

Looking forward to your suggestions.

**Comment by dan-zeman** [comment]
Hi Riyaz,

in my opinion `nmod:instrument` is a good idea. Other people have also used language-specific relations to encode finer information that would otherwise get lost, even if that information was not really specific to their language.

As for ellipsis, I personally do not think we have a good solution in UD1. As you know, `NULL` nodes are currently not used in UD, but I feel we should discuss the possibility for future versions of the standard (see also issue #164). For the time being I would suggest you try to convert to the `remnant` analysis wherever applicable, and devise some heuristics elsewhere.

**Comment by riyazbhat** [comment]
Thanks Dan for your suggestions. Elobaration is a neat way to keep language or scheme specific information and I will be using it where ever I feel a need of it. My only concern is it may double the size of UD labels. But I guess that should not matter as treebank specific information can be easily droped whenever necessary. 

I am able to handle a subset of ellipsis like the ellided conjuctions. The major problem comes with the verb ellipsis and pro drop. They are hard to handle. For now I am just ignoring them. It is not necessary that the whole treebank should be converted to UD. Or is it?

**Comment by dan-zeman** [comment]
Nobody is perfect :-) Quite a few of us started with an approximate conversion of their treebank and then gradually try to improve it. I have to admit that I have not been able to correctly convert ellipsis in Czech so far; not even in the cases where the `remnant` relation should apply. Something is usually better than nothing, although we should obviously try to do it as good as possible.

**Comment by dan-zeman** [comment]
And BTW, any differences between the current data and the desired annotation style must be documented in the language-specific documentation.
