### ISSUE TITLE
Names in non-person entities

### ISSUE THREAD

**Issue by tdozat** [UniversalDependencies/docs#196]
Quick question: I'm working on implementing the `name` relation in the English treebank, and I'm wondering what to do for compounds with a proper name in them but that refer to something other than a person, like "Eastman School of Music", "Leland Stanford Jr. University", "the Colbert bump", or "the Mason Dixon line". According to the docs, `name` "is used for proper nouns constituted of multiple nominal elements"--is this intended to mean that the `name` relation is used only when the head noun of the compound refers to a person, or does it permit the `name` relation in compounds for any proper nouns (allowing the first two examples only), or is it misphrased, and really any element that refers to a person can receive the `name` label in a compound, even if the compound itself refers to something else?

Let me know and I'll make the documentation a bit more explicit.

**Comment by ftyers** [comment]
The documentation seems reasonably explicit here:

"For example, name would be used between the words of Hillary Rodham Clinton, New York, or Carl XVI Gustaf but not to replace the usual relations in a phrasal or clausal name like The king of Sweden or the novels The Lord of the Rings and Captured By Aliens. Words joined by name should all be part of a minimal noun phrase; otherwise regular syntactic relations should be used. "

This would suggest e.g.:

    det(line, the)
    conj(Mason, Dixon)
    compound(line, Mason)

    det(bump, the)
    compound(bump, Colbert)
 
    case(Music, of)
    nmod(School, Music)
    name(School, Eastman)

    name(Leland, Stanford)
    name(Leland, Jr.)
    compound(University, Leland)

Although, not having worked on English, I welcome others to weigh in.

**Comment by tdozat** [comment]
My concern is that the documentation only gives examples where the whole compound refers to a proper noun, but it doesn't give any examples where only a sub-part does (or refers to a different one). For example, in "Eastman School of Music", there is clear syntactic structure in "School of Music", so according to the documentation "the dependencies should reflect the syntactic modification structure using regular syntactic relations". Should I take this to mean that "Eastman" also gets the "regular" label `compound`, since "School" seems like the syntactic head (unlike in names like in "Hillary Rodham Clinton", where equally strong cases could be made for "Hillary" or "Clinton" being the head), or does it get the `name` relation on account of being part of a proper noun? Presumably "Leland Stanford Jr." should be joined together in a chain by the `name` relation, but then does that phrase count as a `compound` or a nested `name`, since the whole of "Leland Stanford Jr. University" is technically a "proper nouns constituted of multiple nominal elements"? That is, do we have:

~~~
compound(School, Eastman)
compound(University, Leland)
~~~
or 
~~~
name(School, Eastman)
name(University, Leland)
~~~

My intuition prefers the `name` relation in these cases (but it could certainly be wrong!). It's a little fuzzier on the cases where common nouns contain people's names in them, though, because it seems to me like the names in "the Colbert bump" or "the Mason Dixon line" perform essentially the same function as the names in "Eastman School of Music" or "Leland Stanford Jr. University", which suggests (though certainly doesn't entail) that they should receive the same label. The documentation, however, explicitly rules it out by restricting `name` to dependents of proper nouns, so I'm wondering to what extent this restriction is justified.

I hope that made sense! Let me know what you think.

**Comment by ftyers** [comment]
Thinking in terms of machine translation (and perhaps other applications), I would prefer to have "(the) Mason-Dixon line" as analysed compositionally, given its compositional translation in other languages (cat: Línia Mason-Dixon, rus: Линия Мэйсона-Диксона, nor: Mason-Dixon-linjen, etc.) This also goes for "Eastman School of Music" and "Leland Stanford Jr. University", which could be fairly trivially rendered "L'escola de música Eastman" and "L'universitat Leland Stanford Jr." respectively. I'm not sure what I'd do with "Colbert bump", but I would probably err on the side of compositionality.

**Comment by jnivre** [comment]
I agree that these cases are tricky, but I think the rule of thumb is to use the name relation only when no syntactic relation makes sense, not because one of the elements is a proper noun. In "Eastman School", there is a clear intuition that "School" is the head (isn't there?), and using the "name" relation would distort this by making "Eastman" the head. However, it is still clear that there will always be borderline cases. In city names like "New York", "Los Angeles" and "San Francisco", any linguist can see that the second element is etymologically the head, but unlike "Eastman School" they now seem completely frozen. Whereas you can refer to the Eastman School as "the school" or "it", you cannot refer to New York as "the York" or to Los Angeles as "they" (because "Angeles" is plural).
