### ISSUE TITLE
Converter from Stanford Dependencies to Universal Dependencies

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/docs#199]
Hi, 

I have a question: is there a script converting Stanford Dependencies to Universal Dependencies for English? I've seen the POS conversion script and Treex/Interset, but I can't seem to find a converter that takes native CoNLL data with the non-universal Stanford Dependencies and outputs Universal Dependencies (I realize this is a non-trivial task because of issues like flipping the pobj/case construction in PPs etc.). 

Thanks!
Amir

**Comment by manning** [comment]
I think the general answer is: no, sorry, there isn't. We have two converters that do the best job they can to convert Penn Treebank trees to each of Stanford Dependencies and Universal Dependencies, but we don't really have the 3rd side of the triangle.

That said, @ngiordani has written various code to convert various of these pieces of structure for various experiments, and you could ask her whether she has stuff that she could give you. But I think that the truth is that it would need quite a lot of additional work much involving difficult corner cases to achieve the accuracy of the constituency to dependency converters.  Because we've done said work on those....

**Comment by amir-zeldes** [comment]
OK, thanks! Someone pointed me to the code here:

https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/trees/UniversalEnglishGrammaticalStructure.java

So I hope I can get some idea of what it's doing. I think I might try to write something myself for dep -> unidep directly, since I have manually annotated dependency data that doesn't exist in constituent trees. I can let you know when I have something to show, if you're interested.

**Comment by amir-zeldes** [comment]
@manning @ngiordani I've written a basic configurable Python script to find/replace some dependency edges. There's a configuration file doing a first try on Stanford typed to universal dependencies included:

http://corpling.uis.georgetown.edu/depedit/

It doesn't do everything yet - in particular I'm not sure how to go about changing 'nn' to 'name' and reversing the order if something is a proper name, since without lexical resources it looks the same as the case of 'compound'. But it does solve some of the problems I had, and maybe others will find it useful too. 

Please let me know if you test it and have some feedback!

**Comment by ngiordani** [comment]
Thanks, @amir-zeldes! This is useful, I'll definitely play with it and let you know if I have any suggestions. I'm sure people will find this useful. As for the problem you mentioned: we ended up using NER. I don't think there's a good way of doing it from just the dependency tree, unfortunately.

**Comment by amir-zeldes** [comment]
OK, great, feel free to use the issue tracker to report bugs or requests directly. 

I was thinking the same thing with the NER, I'm not entirely sure if the guideline for 'name' is going to be 100% decidable. I might do a heuristic using a large list whenever the head and modifier are proper nouns, and have a human go over my particular corpus to produce a stop list.
