### ISSUE TITLE
Faster documentation update

### ISSUE THREAD

**Issue by fginter** [UniversalDependencies/docs#211]
A faster back-end has now been deployed for the docs system by @fginter and @spyysalo. The documentation regeneration times, i.e. from push to edit visible online, are now about 1 minute give or take. Only few seconds of this is spent on the regeneration, the rest is GitHub's webserver update which is out of our control. The new back-end relies on a beta version of Jekyll so it may break. Sorry if that happens. File an issue or comment here if the system fails to regenerate some content.

**Comment by msimi** [comment]
Sorry if this is only a temporary problem, but it seems that clicking on the links under Alphabetical listing in a page like http://universaldependencies.github.io/docs/u/dep/index.html http://universaldependencies.github.io/docs/u/dep/index.html
leaves you in the same page so that I cannot see the details.

— Maria

**Comment by fginter** [comment]
Thanks for the report. Yes, this is broken. I'm temporarily switching over to the older, slow version, pending a proper fix.

**Comment by dan-zeman** [comment]
Is the older version so slow that 30 minutes is not enough, or is it broken too?

**Comment by fginter** [comment]
Thanks. I re-adjusted a timer, now it works. Update time is about 9 min.

**Comment by spyysalo** [comment]
@msimi: thank you for the report! I've fixed what I believe was the root issue in the Annodoc library (a change in the jekyll `site.collections` data structure; see https://github.com/spyysalo/annodoc/issues/16).

@fginter : I think we could try the update again.

**Comment by fginter** [comment]
Switched over to the faster version. Thanks you for the fix @spyysalo.

**Comment by dan-zeman** [comment]
Due to the recommendation of the Uppsala groups, the Czech documentation now (a2030edf6d36a62d794c025500642e5454637a99) has a page on `expl` that did not exist before. The page has been generated and can be viewed at http://universaldependencies.github.io/docs/cs/dep/expl.html.
However, the short links from other pages do not work. The page on specific syntax (http://universaldependencies.github.io/docs/cs/overview/specific-syntax.html) just displays the link in red and says that it failed to find the entry in any collection. The table of Czech relations (http://universaldependencies.github.io/docs/cs/dep/index.html) links to the corresponding Catalan page instead.

I am not sure whether this problem is related to the new rendering process. I think I have always struggled with adding new pages to the site.

**Comment by spyysalo** [comment]
@dan-zeman : thanks for reporting this. I think this is almost certainly related to the new rendering; @fginter can confirm by running `jekyll --full-rebuild` on the generating server.

The links to other pages are generated using data from https://github.com/UniversalDependencies/docs/blob/pages-source/lib/local/collections.js, which was previously regenerated (along with everything else) every time there was an update. I suspect the new jekyll iterative build fails to trace the dependency (which is pretty subtle -- a JS include) and thus doesn't regenerate this file every time a new page is added.

We should look into ways of telling jekyll to always regen some files.

**Comment by fginter** [comment]
`--full-rebuild` broke all links. I'm falling back on the slow rendered. @spyysalo - nothing changed on the site as far as I can tell, have you changed the annodoc include possibly?

**Comment by spyysalo** [comment]
No changes to annodoc after the first post-switch fix (https://github.com/spyysalo/annodoc/issues/16). A reset should surely work -- just `rm -r _site` and regenerate.

**Comment by fginter** [comment]
Same problem persists. Switching back to the slower version and let's get back to this... Most peculiar.

**Comment by spyysalo** [comment]
Huh. You've got me, I thought that would do it for sure. I'll have time to look into this in detail tomorrow, hope to have good news then.

**Comment by spyysalo** [comment]
Note: 3acd140bfd12f6f3e63f7b6e1a0da3e5ae372349 fixes the issue introduced in attempting to fix Dan's issue; the original requires a separate fix (being implemented by @fginter).

**Comment by fginter** [comment]
@dzeman's issue should now hopefully be fixed. When a new file is added or an existing file detected, `--full-rebuild` is forced now, to make sure all the inter-linking of the pages works. Please report any new issues and bear with us. :)  @spyysalo FYI https://github.com/fginter/jekyll-hook/commit/66bdb0677ba01efe5f672e653b7b1064a14a71f9

**Comment by fginter** [comment]
I think this has been quite reliable recently, so closing.
