### ISSUE TITLE
Universal feature for Transitivity

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#213]
In our work on Kazakh, we have labelled verbs as transitive or intransitive. Transitive basically means they can take an object (either bare accusative or definite accusative) and when passivised the object becomes the subject. 

I have looked for an equivalent in UD but have not been able to find it. Should I new feature be made or should we leave out this information when converting the morphological features ?

**Comment by dan-zeman** [comment]
It is not in the Universal Features and it is not even mentioned (yet) in the list of language-specific features at http://universaldependencies.github.io/docs/ext-feat-index.html, although it actually is in Interset (because there are a few tagsets that distinguish it). I did not find it interesting enough to propose it for UD (because subcategorization in many languages is much more complicated than just the intransitive/transitive distinction) but feel free to do it if it makes sense in Kazakh. May I suggest that the feature is called `Subcat` and the values `Intr` and `Tran`? (I'm being selfish here, this is what I have in Interset.)

**Comment by dan-zeman** [comment]
The feature `Subcat=Intr|Tran` has actually been used in UD 1.2 Dutch:

<code xml>
    &lt;feat name="Subcat" value="Intr" upos="AUX,VERB,X"&gt;6964&lt;/feat&gt;
    &lt;feat name="Subcat" value="Tran" upos="AUX,PUNCT,VERB,X"&gt;12217&lt;/feat&gt;
</code>

It is a conversion from the original tagset (apparently with at least one error, otherwise it could not co-occur with `PUNCT`). So I think the original question has been answered and I'm closing the issue.
