### ISSUE TITLE
ext-dep-index.html has many broken links

### ISSUE THREAD

**Issue by fginter** [UniversalDependencies/docs#220]
http://universaldependencies.github.io/docs/ext-dep-index.html does not seem to be particularly up-to-date. This file could be generated from the https://github.com/UniversalDependencies/tools/tree/master/data  deprel files of the validator and be kept in sync.

**Comment by dan-zeman** [comment]
I recently added many relation-language instances, trying to sync it manually. But I did not add the corresponding documentation pages. Maybe it is even better to leave the links "broken" so that it is highlighted that the doc is pending (I mean better than just creating a template page, which makes the link ok but the target is still useless).

The same holds for features, http://universaldependencies.github.io/docs/ext-feat-index.html

**Comment by fginter** [comment]
Some of these do not exist in the languages. E.g. `ccomp:nf` is not used in Finnish (it used to be at some point in the past). Agreed, let's not force-create the documentation and leave the red links for those relations that do exist in the data but have no docs.
