### ISSUE TITLE
Auxiliary chains in Spanish

### ISSUE THREAD

**Issue by ngiordani** [UniversalDependencies/docs#222]
I noticed that in Spanish the auxiliaries are chained together. The UD standard recommends that they be annotated flatly (here: http://universaldependencies.github.io/docs/u/dep/aux_.html). Is there a specific reason for this? Are there plans to change it in v 1.2? (I can help!)

@miguelballesteros @dan-zeman @hectormartinez 

Natalia

**Comment by riyazbhat** [comment]
I have the same problem with Hindi and Urdu. VPs follow an X-bar style hierarchical structure rather a flatter one.

**Comment by dan-zeman** [comment]
It is a violation of the UD guidelines. Either the data or the guidelines should be changed (preferably the data, because we had a lot of endless discussions about this particular bit of guidelines last year).

I don't think it is on the TODO list for this release and I probably won't be able to do it now. If you, @ngiordani , want to fix it yourself, please coordinate with @hectormartinez and @miguelballesteros so that you prevent edit conflicts in the repo.

**Comment by miguelballesteros** [comment]
the token is free on my part. Hector (in cc) is the last one working on the
Spanish data,  we should wait for his confirmation.

On 25 October 2015 at 16:25, Dan Zeman notifications@github.com wrote:

> It is a violation of the UD guidelines. Either the data or the guidelines
> should be changed (preferably the data, because we had a lot of endless
> discussions about this particular bit of guidelines last year).
> 
> I don't think it is on the TODO list for this release and I probably won't
> be able to do it now. If you, @ngiordani https://github.com/ngiordani ,
> want to fix it yourself, please coordinate with @hectormartinez
> https://github.com/hectormartinez and @miguelballesteros
> https://github.com/miguelballesteros so that you prevent edit conflicts
> in the repo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UniversalDependencies/docs/issues/222#issuecomment-150965876
> .

## 

Miguel Ballesteros
http://miguelballesteros.com

**Comment by ngiordani** [comment]
Let me know when you're done with the data; I can probably fix this
auxiliary problem!

**Comment by hectormartinez** [comment]
Great, I need to change a couple things from the transformations I am
running. So @ngiordani , if I get two days, you are free to modify the
Spanish treebank.

2015-10-25 22:13 GMT+01:00 ngiordani notifications@github.com:

> Let me know when you're done with the data; I can probably fix this
> auxiliary problem!
> 
> On Sun, Oct 25, 2015 at 2:07 PM, Miguel Ballesteros <

**Comment by hectormartinez** [comment]
Just pushed an update to UD_Spanish. @ngiordani you are free to rearrange
the aux chains.

2015-10-26 7:59 GMT+01:00 Hèctor Martínez hector.martinez.a@gmail.com:

> Great, I need to change a couple things from the transformations I am
> running. So @ngiordani , if I get two days, you are free to modify the
> Spanish treebank.
> 
> 2015-10-25 22:13 GMT+01:00 ngiordani notifications@github.com:
> 
> > Let me know when you're done with the data; I can probably fix this
> > auxiliary problem!
> > 
> > On Sun, Oct 25, 2015 at 2:07 PM, Miguel Ballesteros <

**Comment by ngiordani** [comment]
Great, will look into it later today. More soon.

N.

**Comment by ngiordani** [comment]
Hi @hectormartinez, @dan-zeman and @miguelballesteros -- I just ran a script that moves aux and auxpass dependents of auxiliaries and copulas (i.e., nodes labeled aux, auxpass or cop) to their parents. Auxiliaries now uniformly attach to predicates. I just pushed.

In French, I talked to @mcdm about also moving negation and cliticized objects or reflexives (which in the Spanish corpus, as in French, can attach to auxiliaries) to predicates. But in Spanish it seems like some of the reflexives really should attach to copulas, because there are some contentful verbs labeled cops and it seems like they may actually take arguments.

I think it would be good to move reflexives and objects from auxiliaries to predicates and negation from auxiliaries and copulas. Does it make sense to push a version with these changes, maybe to a new branch?

**Comment by dan-zeman** [comment]
I was tempted to close this issue because @ngiordani has fixed the aux chain issue in UD_Spanish. However, we now (UD 1.3) have 28 hits in UD_Spanish-AnCora (http://bionlp-www.utu.fi/dep_search/?search=_+%3Caux+%28_+%3Caux+_%29&db=UD_Spanish-AnCora-dev) and 36 in UD_Catalan (http://bionlp-www.utu.fi/dep_search/?search=_+%3Caux+%28_+%3Caux+_%29&db=UD_Catalan-dev), so I am leaving it open for the moment. @hectormartinez, I believe my current conversion scenario can get rid of the aux chains. If I re-run it, can you then re-apply your clitic splitting and stuff so we don't lose it?

**Comment by hectormartinez** [comment]
Of course. I will also wait for that before closing issue #298 (misplaced
multiword tokens on Spanish Ancora)

**Comment by dan-zeman** [comment]
I have now fixed the auxiliary chains in both UD_Catalan and UD_Spanish-AnCora (I have also converted them to UD v2, and this fix is a side effect). @hectormartinez it's your turn - please re-run your scripts that split/mark multi-word tokens, because another side effect is that I rewrote these changes of yours. Warning: you may need to tweak your software first, as the data now contains the SpaceAfter=No attribute (it should be moved to the mw token line where applicable) and the sentence-level attribute `text` (it has to reflect the surface form, so if you identify a pair of tokens as verb+clitic mw token, the space between them in `text` must be removed, and the actual word forms may have to be modified too: _vamosnos_ to _vámonos_ in Spanish).

As the remaining steps are a different issue, I am closing this one now.
