### ISSUE TITLE
Inconsistencies in German usage of compound label

### ISSUE THREAD

**Issue by jimmycallin** [UniversalDependencies/docs#228]
I noticed that there are quite a few more compound relations in German compared to similar languages like Swedish. Looking closer, I found that there is a discrepancy in how German uses the label. If there is a hyphenated word, such as _T-shirt_, the treebank splits this into three tokens, _T_, _--_, and _shirt_, with a dependency from _T_ to _shirt_ labeled as _compound_. In the Swedish treebank, this would be considered to be just one token. 

Here's an example:

```
9   in  _   ADP _   _   10  case    _   _
10  Filmen  _   NOUN    _   _   8   nmod    _   _
11  und _   CONJ    _   _   10  cc  _   _
12  TV  _   NOUN    _   _   14  compound    _   _
13  -   _   PUNCT   _   _   14  punct   _   _
14  Serien  _   NOUN    _   _   10  conj    _   _
15  .   _   PUNCT   _   _   2   punct   _   _
```

More examples can be found with:

```
grep -C 3 -E "\scompound\s" de-ud-train.conllu
```

**Comment by manning** [comment]
The choice of tokenization is not something that we have strongly dictated so far, and so there is variation. For what it's worth, this is something that changed in the history of English Penn/LDC treebanks: In the original Penn Treebank, "TV-series" would be one token, but in the revised LDC tokenization used for OntoNotes and the Web Treebank – and hence for the data annotated for UD English, since we use the Web Treebank tokenization without change – then English also treats the word as 3 tokens.  (The current LDC tokenization is a little complex: certain commonly hyphenated prefixes like "co-" are not separated and so "co-indexation" would be kept as one word, but in most cases tokens are split on hyphens, certainly when they join multiple independent words, as here.

**Comment by dan-zeman** [comment]
Closing. No new comments for a long time, and there does not seem to be plans for standardizing this in the foreseeable future.
