### ISSUE TITLE
Master + Dev branches, source of data for the main page table

### ISSUE THREAD

**Issue by fginter** [UniversalDependencies/docs#250]
One of our problems is that some users tend to grab data directly from GitHub, often unaware of the fact that the data may have been updated since the last official release and might even be broken. This has far-reaching consequences for result comparability etc. I would suggest that the `master` branch of every language repository holds the last officially released version of the data and a `dev` branch of some sort  (maybe `dev-1.3` for the next one) is used for active work on the data. That way, a user who simply clones the repo using the default commands would get the right data. In a related issue, I would suggest that the main page at-a-glance table would source its data from the official release for languages that have been released already, and from the dev- branch (with a warning) for the languages that have no data as of yet.

**Comment by dan-zeman** [comment]
Sounds reasonable. But you would have to watch ourselves because now _we_ cannot use the default commands :-) if someone accidentially modifies the `master` branch, someone has to notice it and revert the change (or better: to move the commit under the `dev` branch. Also, we would need a rule, who and when exactly merges the `dev` branch into the `master` branch. (It could be the last step of the release process.)

I do not think it is necessary to number the `dev` branch though. We can keep using the `dev` branch after 1.3, preparing 1.4/2.0...

**Comment by fginter** [comment]
Yes. I am hoping it is easier to watch ourselves than to watch anonymous users. Agreed on having `dev` as the official dev branch and source for validation. Makes automation easier. I think there may be a way to lock the master branch between the official releases to avoid mishaps. Will investigate.

**Comment by dan-zeman** [comment]
As for locking a branch, people have proposed to use the update hook:
http://stackoverflow.com/questions/2471340/is-there-a-way-to-lock-a-branch-in-git

**Comment by fginter** [comment]
I have now a setup which can warn on push to master of any UD language repository. Got it running few hours ago. It uses the webhooks of the UD project. Same thing will also react to data updates in dev. Etc. It's getting there.

**Comment by dan-zeman** [comment]
Great!

I have a related issue that I want to discuss here: the statistics in the docs pages. Personally, I am most interested in statistics of the current development version, to spot potential bugs. (And we just discussed with @vcvpaiva that it would be useful to see them for the new datasets such as UD_Portuguese-BR.) And I want to see them on the website, because of formatting, visualization etc. But it would be confusing to show all the users something that does not match the officially released data.

Should we make a developement branch in the docs repo, too? (And make it a parallel website somewhere?) Probably too complicated to handle, also from the point of view of editing the docs. So maybe I would just generate two sets of statistics for each treebank, one mark "official release" and the other "development version"?

**Comment by fginter** [comment]
Yes. That's in the works - giving people access to stats / validation / etc. for the `dev` branch of the language repos. I am working on this, but it needs a while yet. Since we now have good 40 language repos, a cron job like we had for v1.2 doesn't really cut it.

The `docs` I would leave be as-is before we have a real use-case for a `dev` branch, setting this up would be a little bit of a nightmare.

**Comment by dan-zeman** [comment]
We now have dev branches in all repositories but we have not really solved locking the master branches, and we have not reached a consensus about what statistics the docs should show, so I am leaving the issue open, with a new milestone.

**Comment by spyysalo** [comment]
Bumping to later milestone.

**Comment by fginter** [comment]
This issue now got worse because the test sets were removed from `dev` and the token counts on the main page dropped accordingly. As a stopgap measure, I think we should switch the source of the stats to `master`. That is at least less wrong. :)

**Comment by dan-zeman** [comment]
In principle I agree. But for datasets that have not been released so far, should we perhaps show the current statistics from dev, if it is not empty? Maybe marked somehow, in brackets or whatever.

**Comment by dan-zeman** [comment]
Or maybe simply shift them to the "upcoming" section. That will be even more accurate. And maybe it will happen automatically, because Sampo's code will find master empty. Only the optional drawing information from dev would have to be added, if desirable.

**Comment by spyysalo** [comment]
The piece of code I wrote for `index_page.py` is only aware of a single data source (i.e. either dev or master) (https://github.com/UniversalDependencies/docs/blob/pages-source/gen_index/index_page.py#L209) and is currently just pointed to dev (https://github.com/UniversalDependencies/docs/blob/pages-source/gen_index/generate_index.sh#L5).

(@fginter please correct me if I'm wrong.)

A bit of a rethink of the generation process would be required to support falling back to master if dev is found empty. I don't think this would be too difficult, but I'm frankly terrified of touching this bit of the codebase ...

**Comment by fginter** [comment]
On my TODO

**Comment by dan-zeman** [comment]
The discussion has shifted from the original issue and the documentation ecosystem has changed a lot, so I am closing this issue but feel free to open new, more focused issues.
