### ISSUE TITLE
Progressive Aspect in Turkish

### ISSUE THREAD

**Issue by MemduhG** [UniversalDependencies/docs#252]
The Turkish verbal suffixes _-mAktA_ and _-(I)yor_ are both marked as progressives in the METU-Sabancı Treebank. We use the same convention in our own treebanks at ITU and mark _-(I)yor_ and _-mAktA_  as `Prog1` and `Prog2` respectively. I believe Prof. Çağrı’s TRmorph uses the labels `cont` for  _-(I)yor_ and `impf` for _-mAktA_ .

_Eve&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gid-**iyor**_
Home.Dat go.PROG.3-SG (Prog1)

_Seni&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;düşün-**mekte**-yim_
you.Acc think.PROG.1-SG (Prog2)

As demonstrated by the examples, both of these suffixes denote the progressive aspect, and are largely interchangeable. The choice of which one to use mostly depends on the context and on how formal the speaker needs to be (_-mAktA_ is more formal), but there are also cases where one of the suffixes works in certain collocations and the other does not, e.g. in some multiword expressions.

We need separate values for the aspect as these suffixes can have different meanings in a number of contexts. For example when _-DIr_ is added to express modality, the sense of certainty is modified differently.

_Okul güzel**dir**._ (I suppose the school is nice / [the fact stands that] School is nice.) 
This can express both certainty and uncertainty.

_Oraya&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; git-mekte-dir._ (certainty, does not convey uncertainty)
There.DAT go.PROG.3-SG.GM
_Oraya&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gid-iyor-dur._ (uncertainty, does not convey certainty)
There.DAT go.PROG.3-SG.GM
Here if we do not have distinct values for the `Aspect` the distinction in the modality will be lost.

I am not quite sure where (or if) we will use the tag `Aspect=Imp`, but as both of of these suffixes (along with the Aorist tense suffix) are imperfective, I would prefer to find suitable distinct values for both of the progressive suffixes for the `Aspect` feature.

**Comment by coltekin** [comment]
I think both of these suffixes primarily indicate `Aspect=Prog`.  However, both may sometimes indicate a _habitual_ aspect which currently does not have a label in UD. I mark ([here](https://github.com/coltekin/gk-treebank)) clear cases of  _habitual_ aspect  as `Aspect=Hab`, but not these two suffixes.  

The labels produced by TRmorph are just labels that correspond to suffixes. And, although Turkish is famous for its agglutinative morphology with clear functions for each suffix, tense/aspect/modality(/evidentiality) suffixes violates this quite often:
- A single suffix may have multiple functions. For example, famous _-mIş_ alone will mark `Tense=Past,Evidentiality=Nfh` (not in UD, Nfh stands for non-first-hand).
- The suffixes indicate different features based on interaction with others. For example, although _-mIs_ indicates non-first-hand evidentiality, there is nothing evidential about _Oraya git-miş-ti-m_ 'I had gone there (I had done it, and I know it first hand)'.  Here _-mIş_ functions only as a tense modifier. _miş_ and _-ti_ in this example together indicate a tense that is past of a given reference, which matches `Tense=pqp` in UD specification.

In summary: the suffix-to-feature mapping is not always trivial.

If we return to '-mAktA' and '-(I)yor' with your examples,

```
1. Oraya         git-mekte-dir.  
   There.DAT     go.PROG.3-SG.GM
2. Oraya         gid-iyor-dur.
   There.DAT     go.PROG.3-SG.GM 
```

Ignoring the effect of _-DIr_, for now, both sentences are ambiguous between a progressive reading 'he/she is going there now' and a habitual 'he/she goes there (every day)'. With respect to aspect, these two morphemes basically act the same ambiguous way, indicating either progressive or habitual aspect. The difference is rather pragmatic (maybe stylistic). _-mAktA_ is just the 'formal register' counterpart of _-Iyor_. AFAIK, there is no clear mechanism for marking this distinction in UD (yet).

And a few words on the interaction with _-DIr_... _-DIr_ is an interesting suffix. Göksel & Kerslake (2005) describes it as 'generalizing modality marker'. It is used for stating either "facts" or "hypotheses". It is also ambiguous between these two readings (the aorist marker _-Ir_ has the same mood effect). In general, context disambiguates:

```
3. Kışlar       yazlardan daha soğuk-tur.
   Winter.PL    summer.PL more cold.GM 
   Winters are colder than summers. (I am stating a fact)
4. Orası  buradan   daha soğuk-tur. 
   There  here.ABL  more cold-GM
   There, it must be colder than here. (I suppose so)
```

In (3), the context says that this is a general fact, so interpreting this as speaker's inference is really difficult. The statement in (4) does not look like a general fact, so it must be speaker's inference/hypothesis.  Note that general facts tend to be about things that span a longer time. (3) states something that is correct during a long span of time (like habitual aspect), and (4) is a statement about now (like progressive aspect). If you, for example, add _her zaman_ 'always' to (4) it becomes a "general fact" rather than speaker's point of view or educated guess.  

Returning to the interaction between _-DIr_ and _-(I)yor_/_-mAktA_: since _-mAktA_ is typically used in official/authoritative language, it tends to refer to things with long term validity, and more certainty. Hence, we interpret (1) as habitual, and more certain, but (2) as progressive, so it is someone's subjective generalization. If you provide the right context, you can reverse the interpretation. If you modify (1) above, by adding _şimdi_ 'now', _Ayşe şimdi oraya gitmektedir_ my interpretation is that this is a inference/guess of the speaker, not something that is happening with certainty.

**Finally, here is my proposal:**

Both -(I)yor_ and _-mAktA_ should mark `Aspect=Prog`, or `Aspect=Prog,Hab`. If one wants to disambiguate between progressive and habitual use, it is fine but it will be tricky.  I think distinguishing these two suffixes outside their contribution to `Aspect` makes sense and it would be useful for some tasks, but it is not an aspectual difference.

I believe we need a new feature for distinguishing -(I)yor_ and _-mAktA_, unless I miss an already existing feature that serves for this purpose. I'd suggest, `Register=Formal` `Register=Informal`.

For _-DIr_, I propose a new `Mood` value, e.g., `Gen` (which I currently use).

**Comment by MemduhG** [comment]
Distinguishing between the two `Aspect=Prog` suffixes using a `Register` feature seems like a good idea to me. 

This might be better discussed in a separate issue, but is there no case in which _-DIr_ can be a copula? Beyond the possiblity of any such case I would also support the `Mood=Gen` for generalizing modality.

With regards to _-mişti_ I am assuming, then, that we will not segment the past copula _idi_ for verb forms?

**Comment by dan-zeman** [comment]
@coltekin : Do you suggest to remove the value `Tense=Nar` (http://universaldependencies.org/docs/u/feat/Tense.html) and replace it by two feature-value pairs, `Tense=Past|Evidentiality=Nfh`? (I am not objecting, just making sure I understand.)

As for adding the `Register` feature, Interset currently has a feature called `politeness`, and a corresponding feature `Polite` has been proposed in UD as a language-specific feature, with values `Inf` and `Pol` (http://universaldependencies.org/ext-feat-index.html#polite). Maybe `Register` is a better name for the feature, what do people think? (But slightly abbreviated values would better match what we have elsewhere in UD, perhaps `Register=Inf` and `Register=Form`?

**Comment by coltekin** [comment]
@dan-zeman: Yes, `Tense=Nar` can go. "Narrative" does not fit into `Tense` as I understand it. The `+Nar` symbol in most tools and resources around maps to `Tense=Past|Evidentiality=Nfh` most of the time, but it interacts with others. For example, as in my earlier example, if it is together with the symbol `+Past`, it does not indicate non-first-hand evidentiality, but just `Tense=Pqp`, or if we annotate the default value `Tense=Pqp|Evidentiality=Fh`).

I think `Register` fits the Turkish _-mAktA_/_-Iyor_ difference better. Since it is not about politeness, but about being "formal" or "informal". Formal language is often also polite, but I can imagine there may be cases one can be formal but impolite or informal but polite.  For compatibility with other treebanks, I would not mind using `Polite` as described in the link above either.

@MemduhG: Kornfilt (1997, p.81) calls _-DIr_ "epistemic copula", I think this is where marking it as a copula in Turkish NLP came from.  With the same reasoning, though, we should also mark _-mIş_ in _gidiyor-muş_ or _-(y)DI_ in _gitmekte-ydi-m, even _-(y)-_ in_gitmekte-y-im_ as copulas. There are some linguistic and historical reasons why these things are called copula, but, even if so, these being copula do not contribute any information regarding the features that the word carries.  The suffix `-DIr`, wherever it is attached, affects the `Mood` (*). For this reason, I like the approach in Göksel & Kerslake (2005) who simply document it as a modal suffix.

And, I agree, we should not segment the "copula" _-ti_ _-mişti_. It was never segmented in the earlier annotation work I am aware of, anyway.

(*) The whole _modality_-_evidentiality_ difference is not always clear to me, but the suffix _-DIr_ feels like affecting evidentiality rather than modality. Now that we are discussing introducing evidentiality as another dimension, we may consider modifying `Evidentiality` rather than `Mood`, but I think this is a minor point which can be changed automatically if we happen to change our minds.

**Comment by spyysalo** [comment]
@dan-zeman : was this issue resolved in v2? (i.e. should this be closed or moved to a later milestone?)

**Comment by dan-zeman** [comment]
@spyysalo : I think it has been resolved and any further discussion would deserve a new issue, referencing v2 docs (and possibly also referencing this issue if relevant).

All: UD v2 now has `Evident` (evidentiality) as a universal feature. `Aspect=Hab` is also available. `Register` stays language specific (there is now universal `Polite`(ness) but it does not seem to be suitable for this case).
