### ISSUE TITLE
Light verb constructions and avoiding semantics

### ISSUE THREAD

**Issue by spyysalo** [UniversalDependencies/docs#255]
(Detached from #248)

@mojgan-seraji:

> It doesn't seem that UD explicitly avoids semantics. So far UD has nicely supported LVCs, with their underlying syntactic structures hand-in-hand with semantics. If UD chooses to go for pure syntax then the entire Persian verbal system will be collapsed (as LVCs are pervasive in the language). Let's have a look at the following example:
> 
> Form (transcribed): Sam zamin xord-ø.
> Gloss: Sam floor eat.past-3sg.
> Translation: Sam fell down.
> 
> Avoiding semantics in the above example, makes the "floor" to be the direct object. In other words, "Sam" should literally have been eaten the floor. But is that really what UD supports? Although the verb "eat" is normally used as a main verb in Persian, in some cases, it functions as a light verb with a more abstract semantic interpretation and the above example is one such case. 

@jnivre:

> Can "floor" be inflected in this usage? Can it take modifiers? Or is it frozen in combination with "eat" when it means "fall down"? If it is, then it should NOT be treated as a regular direct object. Then it is different from (most) English support verb constructions, which do allow modification and inflection:
> 
> She took a photo of the cathedral.
> She took two photos of the cathedral.
> She took a nice photo of the cathedral.

**Comment by mojgan-seraji** [comment]
Other elements such as the future auxiliary verb, negative morpheme, and adverbs can be placed between the preverbal element (floor) and the light verb (eat). The meaning of "floor" in combination with "eat" is always "fall down" and this is frozen regardless what comes in between them, e.g.:

Form (transcribed): Sam zamin xāh-ad xord-ø.
Gloss: Sam floor will.fut-3sg eat.past-3sg.
Translation: Sam will fall down.

Form (transcribed): Sam zamin na- xord-ø.
Gloss: Sam floor not- eat.past-3sg.
Translation: Sam didn't fall down.

Form (transcribed): Sam gol xord-ø, zamin ham xord-ø.
Gloss: Sam goal eat.past-3sg, floor also eat.past-3sg.
Translation: Sam conceded a goal (in football) and also fell down.

**Comment by dan-zeman** [comment]
For reference, the [Uppsala meeting](http://universaldependencies.org/uppsala.html) had a discussion of light verb constructions, see the report [here](http://universaldependencies.org/2015-08-23-uppsala/mwe.html). From what I see in the report, it looks like the current recommendation is to treat [fa] _eat floor_ as if there was no difference to _eat apple_, and mark the idiomacity elsewhere (enhanced / semantic level).

**Comment by jnivre** [comment]
I agree. This was definitely the conclusion at the Uppsala meeting.

**Comment by mojgan-seraji** [comment]
Thank you Dan and Joakim! LVCs have already been marked accordingly in the Persian UD. However, I am still not convinced with your earlier comment that UD avoids semantics. Because it doesn't. On the contrary, UD in some extent supports semantics even now when the semantic layer is not officially applied to all tokens. The labels "mwe" and "compound", for instance, are to be mentioned as such cases, because these cross word boundaries.

My point is: we cannot claim that UD follows a pure syntactic structure (or can we?). My argument is that if we say så, then we are not allowed to apply the labels "mwe" and "compound" at syntactic level. This means that we should label both "apple" in "eat apple", and "ground" in "eat ground" (to fall down, in Farsi) as direct object. But we don't do that. According to the UD's annotation scheme for Farsi, "apple" is labeled as "dobj" and "ground "as "compound:lvc". Both the "apple" and "ground" have the verb "eat" as their head, where in the first case it is a main verb and in the latter case is a light verb.
