### ISSUE TITLE
Auxiliaries and copula verbs in Scandinavian languages (and English for comparison)

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#256]
This document gives an overview of the verbs used with the functions "aux", "auxpass" and "cop" in Danish, Norwegian and Swedish. English verbs have been added for comparison:
http://stp.lingfil.uu.se/~nivre/download/scand-aux.pdf

The table gives rise to a number of observations:
- The "aux" verbs that are found in all languages are (the equivalents of) "have", "can", "must", "shall" and "will", which looks like a very plausible core set of auxiliary verbs in Germanic languages.
- The verb "vara/være" ("be") is used as "aux" in Danish and Norwegian but not in Swedish. Is this due to the perfect sense sometimes being formed with "være" (instead of "have") in Da/No but not in Swedish?
- Norwegian has the largest class of "aux" verbs (even though some low-frequency verbs like "danse" look like bugs), so either Norwegian needs to be more restrictive or the other languages more permissive. 
- Danish has both "blive" and "være" as "auxpass", whereas Norwegian and Swedish have only "bli/blive". Is this a genuine difference or an inconsistency?
- Danish has both "blive" and "være" as "cop", whereas Norwegian and Swedish have only "vara/være". This is clearly an inconsistency, but the question of where to draw the line for copula verbs needs to be settled in harmony with other language groups and is perhaps a v2 issue.

**Comment by hectormartinez** [comment]
About the Danish treebank:

2) For the second item of the list (være as "aux"), it indeed, is for the
perfect of movement verbs ('er ankommet', is arrived).

3) For "være" as auxpass, we used it during conversion for
copula-participle structures like "is mentioned" (er nævnt), where
"mentioned" was labeled as verb in the original treebank. We kept
'mentioned' as verb instead of making it an adjective.

4) Using "blive" as 'cop' is an inconsistency.

2016-02-16 14:36 GMT+01:00 Joakim Nivre notifications@github.com:

**Comment by jnivre** [comment]
I agree that drawing the line between passives and copula + adjective is tricky in many cases. In Swedish (and I guess Danish too), we have series like: 

han jagas av vargar = morphological passive
han blir jagad av vargar = periphrastic passive
han är jagad av vargar = ?

A good thing is that "jagad" will be the root regardless of which analysis is adopted, so it is only the label on "är" that changes. I think this needs to be treated within the larger issue of how to delimit copula constructions.

**Comment by dan-zeman** [comment]
For comparison, here is the corresponding query for German: http://hdl.handle.net/11346/PMLTQ-YVNV
German UD 1.2 does not contain lemmas, so it shows word forms. A manual list of lemmas follows (but without deprels and counts). I marked with question marks verbs that look suspicious to me.

sein (be)
werden (become)
zu (not a verb!)
können (can)
haben (have)
sollen (shall)
müssen (must)
wollen (want)
bleiben (remain) ???
bezeichnen (mean) ???
gelten (hold) ???
nennen (name) ???
mögen (like)
betragen (involve) ???
ernennen ???
dürfen (may)
um (not a verb!)
wählen (choose) ???
lassen (let) ???
heissen (mean) ???
bedeuten (mean) ???
machen (make) ???
umbenennen (rename) ???
erheben ???
lauten (sound) ???
ansehen ???
scheinen (look) ???
° (not a verb) ???
bedienung (not a verb) ???

**Comment by dan-zeman** [comment]
And here for Dutch:
http://hdl.handle.net/11346/PMLTQ-CRP8

**Comment by liljao** [comment]
Thanks @jnivre, this is really useful. I will have a look at the low-frequency Norwegian verbs.

Wrt the use of _være_ "to be" as `auxpass`, this difference is partially an inconsistency and partially based on a real linguistic difference. In the conversion from the Norwegian Dependency Treebank, there is no way of automatically differentiating a _være_-passive from an auxiliary use of the same verb (as discussed above). So in the Norwegian case, this is definitely a known inconsistency.
In a corpus study of the passive construction in Scandinavian, Laanemets, (2004) reported that 14% and 15% of all passives in Danish and Norwegian were reported to be _være_-passives, whereas only 7% in the Swedish data set. So, it seems that the Swedish data may simply be reflecting this difference. 

@hectormartinez, regarding the 'blive' copula, I don't necessarily think this is a bad analysis. In traditional Norwegian grammar there is a group of verbs called "uselvstendige" verb ("dependent" verbs): _være_, _bli_, _hete_, _synes_ and _kalles_ which are the verbs that take a subject predicative (more or less a copula analysis). I think this is something that definitely needs to be discussed and that probably involves more languages also.

**Comment by jnivre** [comment]
Thanks, Lilja. With regard to copulas, the traditional list in Swedish is "vara, bliva, heta, kallas", sometimes extended to a longer list with "utses, väljas, verka, förefalla, anses, betraktas, tyckas, synas, ...". I think this needs some discussion, but I think at least "bli" is a serious candidate as essentially an aspectual variation on "vara". The fact that it is also used to form passives in all Scandinavian languages supports its status as an auxiliary verb. The closest equivalent in English would probably not be "become" but "get".

**Comment by gossebouma** [comment]
For Dutch, I prefer a somewhat more restricted list than Dan's. 

Passive auxiliaries: worden or zijn, if marked by the parser as 'passive' or the (original, non-UD) dependency tree co-indexes the subject with an object in a subordinate clause, or the sentence has no subject (impersonal passive)
Other auxiliaries: zijn/to be, hebben/to have, zullen/shall, mogen/may kunnen/can, gaan/go , laten/let, willen/will, or hoeven/need, and only in certain grammatical configurations.
Copula: verbs marked by the parser as copula, cleft, or predicative, or having only a subject and predicative complement.

**Comment by jnivre** [comment]
@gossebouma: This sounds completely right to me, except for the fact that, as Dan has pointed out to me, copulas should not be tagged AUX under the current version of the guidelines. Will you be able to produce a new conversion of Dutch for the upcoming release?

**Comment by jnivre** [comment]
We seem to converge on having a restricted set of auxiliaries that can be clearly motivated on syntactic grounds. This means that we need to do some pruning for Norwegian, Dutch and German (at least). In addition, we should only allow the verb corresponding to "be" with the relation "cop" (but with the postag "VERB").

Is there anything else we need to discuss before closing this issue?

**Comment by wbwseeker** [comment]
about the German list of auxiliaries that Dan made (a while ago, sorry that it took so long):

these are the classic auxiliaries:
sein (be)
haben (have)
werden (become)

these are the classic modal verbs which are labeled as aux as well
können (can)
sollen (shall)
müssen (must)
wollen (want)
dürfen (may)
mögen (may)
(and maybe brauchen (need) depending on usage)

the standard copula is
sein (be)

but one could argue for these two as well.
werden (become)
bleiben (remain) ???

the corresponding examples would mean something like
Peter is a doctor / Peter is quiet
Peter becomes a doctor / Peter becomes quiet
Peter stays a doctor / Peter stays quiet

This is used for the causative construction in German, which gives it a special role. Annotation is inconsistent comparing between English and German.
lassen (let) ???
And from what I understand in the Dutch treebank, laten is usually annotated as an auxiliary.

In English, let is made the head of the construction with the content verb being an ccomp.
In German, sometimes it is like in English but with xcomp instead of ccomp, sometimes the content verb is made the head and lassen is the xcomp dependent.
The latter case looks like an error to me.

The rest are annotation errors:
zu (not a verb!)
bezeichnen (mean) ???
gelten (hold) ???
nennen (name) ???
mögen (like)
betragen (involve) ???
ernennen ???
um (not a verb!)
wählen (choose) ???
heissen (mean) ???
bedeuten (mean) ???
machen (make) ???
umbenennen (rename) ???
erheben ???
lauten (sound) ???
ansehen ???
scheinen (look) ???
° (not a verb) ???
bedienung (not a verb) ???

**Comment by liljao** [comment]
I have had a look at the auxiliaries reported for the Norwegian data set and observe the following:
- a few of the low-frequency verbs (_danse_, _høre_) are bugs and will be fixed
- the other verbs which are found in the Norwegian data result from the automatic conversion where verbs that have a direct, non-finite dependent are auxiliaries. For example: _har blitt erklært avgjort_ "has been declared decided", where _erklært_ becomes `aux`. These should probably be given an `xcomp` analysis, which is the analysis for these verbs when we have an adjective instead of a non-finite verb (_erklært uønsket_ "declared unwanted").

So I will definitely do some pruning here and will probably settle on the verbs that the Scandinavian languages have in common (ref your previous document @jnivre) as auxiliary verbs.

**Comment by jnivre** [comment]
@wbwseeker: Sounds good. Regarding copulas, the current position is to use "cop" only for the equivalent of "be". I agree that one could argue that "bleiben" and "werden" (or their Swedish counterparts "förbli" and "bli") could be given the same analysis, but for consistency under the current version of the guidelines we should keep it restrictive.

@liljao: Sounds great!

**Comment by dan-zeman** [comment]
@wbwseeker : I would restrict the list as you suggest, i.e. _sein, haben, werden, dürfen, können, mögen, müssen, sollen, wollen._ I would not include _lassen._ (And the current UD_Dutch is messy, hence not a good source of inspiration.)

In general, I don't think that every verb that takes an infinitive as argument should necessarily be tagged modal and auxiliary.

**Comment by wbwseeker** [comment]
I wouldn't include lassen either, it is still different from the other auxiliaries. I just noted the inconsistency there because it is sometimes annotated as an auxiliary.

one more thing about mögen: this one is tricky because it can be used either as an auxiliary or as a proper main verb. Some of the other auxiliaries can do this too,
but with mögen, the auxiliary usage is less frequent than the usage as main verb. Now, I'm unsure but I think that the policy is not to tag the auxiliaries according to their
usage but mark them as AUX at all times. In that case, it might be better to not include mögen in the list because this will look weird more often than not.
If I'm wrong about the policy, then it's fine to include it of course.

**Comment by jnivre** [comment]
I don't think we assume that verbs that can function as auxiliaries will always be tagged AUX, regardless of their actual use. Think of "have" and its correspondents in other languages, for example. This should be tagged VERB when it is used as a main verb ("I have no clue") but AUX when it is used to form the perfect tense ("I have lost"). 

It is true that we are still discussing whether part-of-speech tags should be more formally or functionally oriented, but I don't think we ever want to go so far as to require that "have" was always tagged VERB or always tagged AUX. And then the same principle should be applied to other verbs that have both uses.

**Comment by dan-zeman** [comment]
Re: the "policy". This is something that keeps popping at various places and there probably is no single good policy. My position: actual usage should not be the main guiding principle for assigning POS tags, **but:** it is useful to be able to say that a word is ambiguous between two or more tags. `AUX` vs. `VERB` is a good example. Other verbs, such as _sein_, can also be both, depending on usage.

**Comment by wbwseeker** [comment]
okay, great. then there is no problem with mögen. thanks for the clarification :)

**Comment by gossebouma** [comment]
For the 500 sentence Dutch (sample of Lassy Small)  fragment I am currently working on, I define aux and auxpass lexically (i.e. it is a restricted set of the verbs that take a non-finite VP complement). 

Copula is not restricted lexically (although the annotation guidelines might contain a  list), but I select those verbs that in a given sentence,  take only a subject and a predicative complement in the original treebank annotation. Van Eynde et al (2014) point out, using our treebank data, that there is indeed reason to consider the copula as a somewhat wider class of verbs than the list commonly given in reference grammars. 
(The paper by van Eynde et al ' Het verrassende resultaat
van een copulativiteitspeiling' appeared in a local Leuven publication,and is in Dutch...)

the counts for aux, auxpass and copulas in this small sample:

aux: 
  41 kunnen
     35 zullen
     26 hebben
     22 zijn
     10 willen
      6 mogen
      2 laten
      2 gaan
      1 hoeven

auxpass: 

```
64 worden
 25 zijn
```

cop:
     92 zijn
     10 worden
      5 raken
      2 staan
      2 blijven
      1 mogen
      1 moeten
      1 maken
      1 komen
      1 heten
      1 gelden
      1 gaan
      1 blijken
      1 beschouwen

**Comment by jnivre** [comment]
When you say that aux and auxpass are defined lexically, I assume it means that only a fixed set of verbs can have these relations, but not that every token of these verbs have such a relation. For example, I assume that the equivalent of "have" ("hebben"?) is aux when used to form a perfect tense but root when used as an ordinary transitive verb. 

For copulas, the current guidelines explicitly say that it should be restricted to the equivalent of "be",  in this case "zijn". All the others should be analysed as main verbs with an xcomp. I am very much aware that this can be debated -- the Swedish treebank also uses a more comprehensive definition of copula -- and it may change in later version of the guidelines, but for cross-linguistic consistency we should adopt the most restricted definition for now.

**Comment by jnivre** [comment]
It seems that we have converged on this one. I have fixed Swedish and Lilja Norwegian. Not sure about Danish, but I am closing the issue for now.
