### ISSUE TITLE
Verbal amod

### ISSUE THREAD

**Issue by liljao** [UniversalDependencies/docs#260]
Participial adjectives in attributive position, e.g. _the shouting boss_ are treated differently in Germanic treebanks:

Swedish and Norwegian: are adjectives (i.e. no verbal amod's)
Danish and English: are often verbal (i.e. have verbal amod's)

Clearly, delimitation of verbal participles and adjectives is difficult. It seems that the Swedish solution has been to adopt an adjectival analysis, but with a VerbForm=Part feature.

**Comment by jnivre** [comment]
Yes, this is tricky. Participles behave more like adjectives, more like verbs in some languages, and (perhaps) more like nouns in some languages. This is also related to the more general issue of whether postags should be (more) formal, or (more) functional. For Swedish, participles are predominantly used adjectivally, and verbal uses are rather marginal. This is especially true for the past participles, where there is a distinct form (supine) used to form perfect tenses.

This is related to another issue that I meant to bring up, namely the use of "acl:relcl" for participial constructions as in:

ovnsbakt piggvar dandert/acl:relcl med ingefærmarinert klasetomatbåter

Here you seem to adopt a "reduced relative clause" analysis, and the participle is tagged as VERB here, not ADJ. In Swedish, I think this would be analysed as "amod" but I haven't managed to find any examples.

**Comment by yoavg** [comment]
An additional data-point re the participle form is the Hebrew treebank.

Participles are very common in Hebrew, and are ambiguous between adjectives, verbs and nouns ("shouting" as above can be either verb or adjective, while "guarding" can mean either a present verb or the occupation "a guard". That is "he is guarding" can mean "he is guarding _now_" (verb) or "his job is guarding" (noun) ).

The original annotation had a special tag (BEINONI in Hebrew) for these ambiguous cases, while cases in which the reading is clear (e.g. the particular instance is undoubtedly a verbal reading, or undoubtedly a noun) are annotated with the corresponding part of speech.

When adopting to the UD format, we chose to uniformly convert the ambiguous cases to VERB with VerbForm=Part.

**Comment by jnivre** [comment]
In the western grammatical tradition, participles were for a long time treated as their own part of speech, distinct from both verbs and nouns (and adjectives). Perhaps it is time for a revival?

**Comment by jnivre** [comment]
Do we have enough information to resolve this issue either way, or should we postpone this until v2 and let language differ in the meantime?

**Comment by dan-zeman** [comment]
FYI, I have been trying to find a consistent solution of the same problem in the Slavic group and it is hard (just to find it – not speaking about convincing others to use it :-)). Some types of participles are closer to adjectives than others. Some are used only attributively, some only predicatively, and many work both ways. I think we have to accept that participles share properties of both verbs and adjectives, so we should not be surprised to find them in contexts where either verbs or adjectives are expected. And I would advocate for assigning the UPOS tag based on criteria that are somewhat more persistent (at least on _most frequent_ usage, rather than actual usage in the given sentence).

**Comment by dan-zeman** [comment]
Tentatively closing, although there does not seem to be a single conclusion.
