### ISSUE TITLE
Slavic l-participles should not be VerbForm=Fin

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#281]
The l-participle, also called past participle, active participle or just past tense (because it can be used without auxiliary in some languages and contexts) is still a participle and thus it should be `VerbForm=Part`, not `VerbForm=Fin`. It also has (should have) `Tense=Past` (or in some cases in Bulgarian `Tense=Imp`) and `Voice=Act`. Further features are `Aspect` (lexical), `Gender`, `Number` (but no `Mood` and `Person`).

`VerbForm=Fin` is currently used in Bulgarian (@osenova) and Polish (@dan-zeman). Petya, do you agree that we should change it to `Part`?

**Comment by osenova** [comment]
Hi Dan,

Yes, I agree that we should do that. Actually, it applies to all the participles.

Best,
Petya

**Comment by olesar** [comment]
VerbForm=Fin is in use for Russian forms like pisa-l, too. Could we stick to it? Otherwise we would get a language without any past tense (or just with the Past Passive) and lots of decisions related to this feature would be lost.

At present, Russian -l- fails all possible diagnostics to be a Part.
Natasha (@gnatko), what about Ukranian?

Olga Lyashevskaya

School of Linguistics, Faculty of Humanities
 Higher School of Economics, Moscow

13.04.2016, 23:02, "Dan Zeman" notifications@github.com:

>  The l-participle, also called past participle, active participle or just past tense (because it can be used without auxiliary in some languages and contexts) is still a participle and thus it should be VerbForm=Part, not VerbForm=Fin. It also has (should have) Tense=Past (or in some cases in Bulgarian Tense=Imp) and Voice=Act. Further features are Aspect (lexical), Gender, Number (but no Mood and Person).
> 
>  VerbForm=Fin is currently used in Bulgarian (@osenova) and Polish (@dan-zeman). Petya, do you agree that we should change it to Part?
> 
>  —
>  You are receiving this because you are subscribed to this thread.
>  Reply to this email directly or view it on GitHub

**Comment by dan-zeman** [comment]
@olesar : The diagnostic for Part is that it inflects for `Gender` (unlike any verb form that I would call finite) and it does not inflect for `Person` (ulike most finite forms, except conditional auxiliary _by_, which is frozen in Russian, but inflects for `Person` in other Slavic languages).

Why would you have a language without past tense? `Tense=Past` can and should be one of the features of _pisal_.

**Comment by sjut** [comment]
The l-form is grammaticalized into tense form in Russian. There is no contexts where it has any property of a participle. It is not possible with auxiliary/copula verbs, for instance. In grammars and in all the standards it is never treated as a participle (only in historical grammars). The only position it can occupy in a sentence is a position of a finite verb. 
(As for typological glossing, the forms that cannot be used with copula and occupy the position of finite verbs are often treated as tense forms, even in the cases, when they are  homonymous to participles (cf. tungusic languages))

As for morphological properties, unlike participles it lacks case. We have full-fledged paradigm of participles without l-forms. If l-forms are participles, how then we should differentiate two past participles: l-forms vs. traditional -вш/-ш (-vsh/-sh) past participles?

**Comment by olesar** [comment]
@dan: And what about Kayardild or Lugbara which have case-marking on verb in one morpheme with tense? You are trying to formulate constraints that are just wrong from a wider typological perspective.

We really need a Bielorussian team to get more votes:)

Olga

14.04.2016, 00:06, "Dan Zeman" notifications@github.com:

> @olesar : The diagnostic for Part is that it inflects for Gender (unlike any verb form that I would call finite) and it does not inflect for Person (ulike most finite forms, except conditional auxiliary by, which is frozen in Russian, but inflects for Person in other Slavic languages).
> 
> Why would you have a language without past tense? Tense=Past can and should be one of the features of pisal.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

Olga Lyashevskaya

School of Linguistics, Faculty of Humanities
 Higher School of Economics, Moscow

**Comment by ftyers** [comment]
I vote for писал to be Fin in Russian. The "inflects for gender not person" is not the best diagnostic in this case. A better one is co-existence (or not) with other finite-verb forms.

**Comment by dan-zeman** [comment]
@sjut: I think we have a clash of terminologies here. The l-form is called participle in some traditions while it sounds alien in others. So the question is whether we want to maintain that the l-forms are still parallel across Slavic languages, with different established names in different languages, one of them selected for UD. Or we want to admit that in the East Slavic languages they are so different that it no longer makes sense to enforce unified annotation. (The two UD slogans: _don’t annotate the same thing in different ways_ vs. _don’t make different things look the same_.)

Yes, the l-participle lacks `Case` and it cannot be used attributively (or with copula), in all Slavic languages AFAIK. Distinguishing it from the _-вш/-ш_ participles is tricky; I suggest that the latter are tagged `ADJ Tense=Past|VerbForm=Part|Voice=Act …` (while the former are `VERB Tense=Past|VerbForm=Part|Voice=Act …`). In the Czech grammar it is even preferred to call them “verbal adjectives” rather than participles.

@olesar: I do not claim that the gender/person criterion works outside the Slavic group. I do not believe that any morphological criterion (and, quite likely, any criterion whatsoever) will work for all languages.

Yes, I would love to see a Belarussian team on board! But you do not need more votes. If I fail to convince you that my view applies to Russian then you just do what you see as best fit for Russian :-) Then it would be very appropriate to do the same thing for the other Slavic languages that behave the same way (probably Ukrainian and Belarussian, although I have not searched for evidence).

@ftyers: The coexistence criterion indeed makes sense but it does not work well with (some of) the West Slavic languages. In Czech, Slovak and Polish it would mean that 3rd person usage is `VerbForm=Fin` while the 1st and 2nd persons are `VerbForm=Part`. On the other hand, a past tense clause is finite, and I admit that it sounds a bit strange if the only verb in the clause is tagged as non-finite. (But in this case the person of the clausal subject is determined by the personal pronoun in Russian, and by the absence of finite auxiliary in Czech.)

**Comment by natko5** [comment]
@dan-zeman, @olesar: Actually there are a few remnants of l-participles in Ukrainian with a wider functioning than just past finite verbal forms, e.g. замерзла вода (= frozen water), compare: Вода замерзла. (= Water _has_ frozen.). The former is treated as an adjective, moreover, it has a different (long) masculine form: замерзлий (adjective) vs замерз (verb). It is possible to say Вода є замерзла (= Water _is_ frozen) but this utterance will never have a dynamic meaning, so the similarity is only formal and historical. (This is in fact analogous to treating perfective non-past verbal forms as present tense ones -- may blow one's mind at first). On the other hand, I understand your reasons for wanting to treat similar forms in a similar way and would like to try to stick to the guidelines. In fact, for East Slavic languages this would just mean an additional layer of annotation (l-participle is the single component making the past tense form, compared to 2 or 1 1/2 in other Slavic languages). The question is do we mark parts of analytical forms or the forms themselves -- we could have both, it's just a technical question how to implement this. At the moment we tag this form directly as past finite. At the sentence level, I believe, this is a better solution because l-participle in East Slavic corresponds to the bundle aux+l-participle in other Slavic languages, not to the second part itself.

**Comment by manning** [comment]
I'm no expert on Slavic, but under the current lexicalist view of UD, we should be marking word forms not the analytical parts of word forms, and to the extent that I understand the arguments, I think I agree with @olesar & @ftyers that treatment of pisa-l as a finite verb is right for Russian. There is always going to be a conflict between diachronic and synchronic behavior, and some messiness in between since grammaticalization is gradual but UD is still a categorical theory, but if one analysis seems clearly right synchronically, I think we have to favor it over the diachronic motivation of maintaining parallelism over diachronically related forms in a language family.

**Comment by dan-zeman** [comment]
I have fixed the Polish data for UD 1.3.

**Comment by osenova** [comment]
It was fixed also in the Bulgarian treebank for UD 1.3.

**Comment by dan-zeman** [comment]
I think the issue can be closed then. The majority vote is that l-forms are `VerbForm=Fin` in Russian (and probably in the whole East Slavic group). In West and South Slavic languages they are `VerbForm=Part` and the data have been updated accordingly.
