### ISSUE TITLE
Subordinating conjunctions as parts of imperatives

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#289]
In Russian there is an example of the use of 'чтоб(ы)', meaning something like 'that' or 'in order to'

  Чтоб ты сдох!

It is similar to Spanish

  Qué te mueras! 

Which would translate something like "Die!" (imperative)

I haven't been able to find examples in the Spanish UD corpus. It seems a bit strange to use `mark` here. Does anyone have thoughts on how this might be treated ?

**Comment by dan-zeman** [comment]
This usage looks similar to the Czech particles _ať, kéž, nechť_ (http://universaldependencies.org/cs/pos/PART.html). I am not sure what should be the best relation to attach them. Based on the original PDT annotation and on my conversion procedure, they currently often end up as `mark`. Examples here: http://hdl.handle.net/11346/PMLTQ-4E4E, but some of them are genuine subordinate clauses, although the words are primarily not subordinating conjunctions. I don't mind this analysis. Subordinating conjunctions may occasionally also introduce an (orthographically) independent sentence, even in something similar to your imperative usage:

_Že se nestydíš!_ ~ _Styď se!_ = “Be ashamed!”

(The second form is imperative. The first form is formally negative indicative, introduced by the subordinating conjunction _že_ “that”. Could be interpreted as “[I am surprised] that you are not ashamed!”)

**Comment by kajad** [comment]
I agree with Dan on the diachronic elliptical interpretation. Slovenian has
similar modal constructions with both subordinate [1] and coordinate [2]
conjunctions, not necessarily limited to imperatives. Although the
traditional grammar also treats them as particles, due to their
syntactic/discourse function, we prefer to annotate them as SCONJ/mark and
CONJ/cc in the current annotation scheme, although examples are rare.

(1) Da ne govorimo = lit. _da.SCONJ we don't talk about ... \* = Not to
mention the ...
(2) Saj samo spiš! = lit. *saj.CONJ you only sleep_ = All you do is sleep!

After all, stand-alone subordinates also appear in English idioms, such as _if
only I knew, as if I care_ etc.

2016-04-21 11:34 GMT+02:00 Dan Zeman notifications@github.com:
