### ISSUE TITLE
Missing Portuguese-BR specific info pages

### ISSUE THREAD

**Issue by pedrobalage** [UniversalDependencies/docs#295]
In the landing page (http://universaldependencies.org/#pt_br), the linked pages for Portuguese-BR are the same as the Portuguese (European) ones.

http://universaldependencies.org/pt/overview/introduction.html

This might be an issue because the corpora used are different for both variants of Portuguese. The Portuguese (European) is correct, hence it is missing the Portuguese-BR pages.

**Comment by dan-zeman** [comment]
The first part is actually a feature rather than a bug, we want to have one documentation per language, not per treebank. And the two varieties of Portuguese are considered one language for this purpose.

But you are right that the Introduction does not reflect UD_Portuguese-BR, which was added later. So we need to extend the Intro.

**Comment by dan-zeman** [comment]
Introduction fixed in cb01eb38b69b2489fad36be3b9fcb21dc384f568. Closing the issue.
