### ISSUE TITLE
Broken contractions in Spanish AnCora

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#298]
Reported by Alessandro Raganato:

It seems that there are cropped sentences in the Spanish-AnCora treebank. 
For example in the es_ancora-ud-test.conllu file, in the "sent_id es-s8" "orig_file_sentence 001#8", the last four lines of the sentence are the following:

43  un  uno DET DET Definite=Ind|Gender=Masc|Number=Sing|PronType=Art   45  det _   _
44  único  único  ADJ ADJ Gender=Masc|Number=Sing 45  amod    _   _
45  candidato   candidato   NOUN    NOUN    Gender=Masc|Number=Sing 41  nmod    _   _
46-47   al  _   _   _   _   _   _   _   _
46  .   .   PUNCT   PUNCT   PunctType=Peri  8   punct   _   _

another example for the sentence id "sent_id es-s149" "orig_file_sentence 002#49"

72  la  el  DET DET Definite=Def|Gender=Fem|Number=Sing|PronType=Art    73  det _   _
73  autoconciencia  autoconciencia  NOUN    NOUN    Gender=Fem|Number=Sing  69  nmod    _   _
74-75   del _   _   _   _   _   _   _   _
74  ?   ?   PUNCT   PUNCT   PunctSide=Fin|PunctType=Qest    8   punct   _   _

After the word "al" and "del" the sentence is finished, which would not make sense in Spanish (the English translation for the first example would be "an only candidate to the.").

**Comment by dan-zeman** [comment]
@fginter : Shouldn't the validator have caught this? If there is a "74-75" line, then the "74" and "75" must follow, otherwise the format is not valid.

**Comment by fginter** [comment]
:-( I checked the code and it looks for the interval starting at the right place, but doesn't check the end of the interval. Ah. There's always the next way to break the data... I'll add a check for this.

**Comment by hectormartinez** [comment]
Chances are that also happens on UD_Catalan. I'm on it.

2016-05-18 12:22 GMT+02:00 Filip Ginter notifications@github.com:

**Comment by hectormartinez** [comment]
A Filip said,"there's always new ways to break the data." There was some discord between the module that splits verbal clitics and the module that splits ADP+DET contractions, which caused a retokenization problem in sentences that showed both phenomena. This also means it only happens in UD_Spanish-Ancora but not UD_Catalan because verbal clitics are treated differently.

I am pushing the corrected version on the dev branch right now but will close the issue when I have had more time to revise the results. For the time being it looks ok on manual inspection, the initial errors reported by Alessandro are not there anymore.

**Comment by spyysalo** [comment]
@hectormartinez : should we still keep this issue open?

**Comment by hectormartinez** [comment]
I fixed it a while ago but forgot to notify. Please close it.
Also, the bug only applies to Ancora-Spanish and not Catalan.


2016-12-05 19:48 GMT+01:00 Sampo Pyysalo <notifications@github.com>:
