### ISSUE TITLE
complement of 'llamar' in Spanish

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#299]
In the Spanish corpus, the verb "llamar" (when used like X is called Y) takes `iobj` for X and `acl:relcl` for Y... But Y is not a clause, it is often just a noun phrase.

I couldn't find anything in the language-specific docs about this, so thought I'd ask it here...

```
21      a       a       ADP     _       _       22      mark    _       _
22-23   llamarse        _       _       _       _       _       _       _       _
22      llamar  llamar  VERB    _       VerbForm=Inf    24      cop     _       _
23      se      él      PRON    _       Case=Acc,Dat|Person=3|PrepCase=Npr|PronType=Prs|Reflex=Yes      22      iobj    _       _
24      Fort    fort    PROPN   _       _       15      acl:relcl       _       _
25      Ticonderoga     ticonderoga     PROPN   _       _       24      name    _       _
26      )       )       PUNCT   _       _       24      punct   _       _
```

Also sometimes it's just bare `acl`:

```
# sent_id es-train-005-s66
1       Ahora   ahora   ADV     _       _       3       advmod  _       _
2       se      él      PRON    _       Case=Acc,Dat|Person=3|PrepCase=Npr|PronType=Prs|Reflex=Yes      3       iobj    _       _
3       llama   llamar  VERB    _       Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   0       root    _       _
4       La      el      DET     _       Definite=Def|Gender=Fem|Number=Sing|PronType=Art        5       det     _       _
5       Cañita  cañita  PROPN   _       _       3       acl     _       _
```

And also sometimes `xcomp`:

```
# sent_id es-train-007-s17
1       Se      él      PRON    _       Case=Acc,Dat|Person=3|PrepCase=Npr|PronType=Prs|Reflex=Yes      2       iobj    _       _
2       llama   llamar  VERB    _       Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   0       root    _       _
3       astronomía      astronomía      NOUN    _       Gender=Fem|Number=Sing  2       xcomp   _       _
4       extragaláctica  extragaláctico  ADJ     _       Gender=Fem|Number=Sing  3       amod    _       _
```

**Comment by dan-zeman** [comment]
The first example looks wrong to me. Not only because of `acl:relcl` but also because _llamar_ is analyzed as copula there.

Otherwise I suppose that the annotators attempted to analyze it as double predication, described here: http://universaldependencies.org/u/overview/specific-syntax.html#secondary-predicates
That would explain `xcomp` and maybe even `acl`, although then it should not be attached to _llamar_.

BTW, I would not map _se_ to X in the English counterpart "X is called Y" because X is subject and _se_ is not. (There could be a subject, such as in _esta <b>muchacha</b> se llama María_.) I think a more literal English counterpart would be "X calls itself Y" where _itself = se_ should be `dobj` (not `iobj`). Then if Y were optional depictive and thus it were `acl`, it should be attached to this pronoun. But I don't think it is optional. Thus I would attach it as `xcomp` to _llamar_.

NB: The "X calls itself Y" can be considered a reflexive passive. We have not reached a consensus whether and how to annotate it in the Romance treebanks; but at least X would then be attached as `nsubjpass` instead of `nsubj`.

**Comment by ftyers** [comment]
(You're right about the English gloss, it was poorly thought out). 

Regarding copula analyses for 'llamar'... there are 38 in the treebank.

I agree with the `xcomp` analysis, some more examples:

```
La chica se llama Begoña.
La gente le llama a la chica Begoña.
Los historiadores llama el sistema feudalismo.
```

I think all of these {Begoña, feudalismo} would work with `xcomp`, following the "paint the house red", although it would be good to hear from people working on the Spanish treebank who have more experience.

**Comment by dan-zeman** [comment]
Yeah, but I'm afraid those people aren't listening, as this is a converted version of a Google treebank (later improved by @miguelballesteros , @hectormartinez, @ngiordani and myself, but we did not do the annotations). So if we identify a bug, it's up to us to fix it.

**Comment by ngiordani** [comment]
Funnily I am right at this moment revising a 40-page chapter for my dissertation which touches on both of these issues -- SE and xcomp vs. cop. :)

The Spanish treebank tags every instance of SE as iobj. It's true that we don't have a consensus yet (in fact, I'd be more inclined to call this a true reflexive than a passive, @dan-zeman! This stuff is hard!) but I think it's safe to say that iobj is just wrong here.

llamar is often tagged cop and I think there's very strong arguments against that. I think the correct analysis is the one with xcomp, and would argue that for a bunch of things currently labeled cop in this treebank. Sounds like we all agree about that, so it may just be an issue of implementing the changes? I may be able to do that at some point...

Maybe we'll wait for native-speaker endorsement.

**Comment by miguelballesteros** [comment]
If you are thinking about me, my knowledge about this is limited, I'm more
in the computational side :-), but I think @dan-zeman description is
correct.

Note that "llamarse" is a pronominal verb in all the examples of the first
mail of this chain: (
http://www.elearnspanishlanguage.com/grammar/verb/pronominalverbs.html)

_Nos llaman *
*Les llaman_
_Se llama_
_Me llamo_

and it is different from _llamar_

ps: btw: these 2 sentences are not even grammatical:

La gente le llama a la chica Begoña. _should be_ La gente llama a la
chica Begoña.  (since here it is not a pronominal verb, it is just
_llamar_)

Los historiadores llama el sistema feudalismo.  _should be (llaman is
not correctly inflected, and again it is not a pronominal verb)_ Los
historiadores llama_n_ al sistema feudalismo.

@hectormartinez https://github.com/hectormartinez, @ngiordani
https://github.com/ngiordani, @dan-zeman correct me if I'm wrong

On 19 May 2016 at 17:45, ngiordani notifications@github.com wrote:

> Funnily I am right at this moment revising a 40-page chapter for my
> dissertation which touches on both of these issues -- SE and xcomp vs. cop.
> :)
> 
> The Spanish treebank tags every instance of SE as iobj. It's true that we
> don't have a consensus yet (in fact, I'd be more inclined to call this a
> true reflexive than a passive, @dan-zeman https://github.com/dan-zeman!
> This stuff is hard!) but I think it's safe to say that iobj is just wrong
> here.
> 
> llamar is often tagged cop and I think there's very strong arguments
> against that. I think the correct analysis is the one with xcomp, and would
> argue that for a bunch of things currently labeled cop in this treebank.
> Sounds like we all agree about that, so it may just be an issue of
> implementing the changes? I may be able to do that at some point...
> 
> Maybe we'll wait for native-speaker endorsement.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/UniversalDependencies/docs/issues/299#issuecomment-220366067

## 

Miguel Ballesteros
http://miguelballesteros.com

**Comment by ftyers** [comment]
@miguelballesteros: yes, argh the agreement, this is what you get for copypaste examples :)  ... but I think "le llama a la chica Begoña" is ok... I checked here in the office (in Donostia) and people say it's a bit redundant but grammatical (unlike in Italian), maybe "A la chica la gente le llama Begoña" sounds better?

**Comment by jipatsaa** [comment]
Llamarse, apodarse, particular verbs.
Definitely is not a passive, nor reflexive or aspectual clitic.

Pasive: se venden pisos (Flats are sold)
Reflexive: Ella _se_ seca las manos (she dries her hands, in a literal  
reading she _herself_ dries hands)
Aspectual: Ella _se_ bebe 12 cervezas (she drinks _up_ 12 beers)

In general the clitics of these pronominal verbs (llamarse, apodarse)  
are called predicative clitics. In a sense when we say "la chica se  
llama María" is almost as if we were saying "La chica es María".

So, what are the options? xcomp?

Aitziber

Francis Tyers notifications@github.com erabiltzaileak idatzi du:

**Comment by dan-zeman** [comment]
The "almost" bit is significant because UD currently restricts `cop` to the equivalents of English _to be_ and people seem to agree that in Spanish both _ser_ and _estar_ qualify, but not other verbs. So `xcomp` seems to be the right solution, optionally with a secondary dependency in DEPS:

<pre>
1 La    el     DET   _ _ 2 det   _       _
2 chica chica  NOUN  _ _ 4 nsubj 5:nsubj _
3 se    se     PRON  _ _ 4 dobj  _       _
4 llama llamar VERB  _ _ 0 root  _       _
5 María María  PROPN _ _ 4 xcomp _       _
</pre>

**Comment by manning** [comment]
I agree that acl is definitely wrong -- this is an argument of _llamar_. The most likely choice is xcomp for the secondary predication. That is definitely the right analysis for something like Engish "Sue called him a liar" where "[be] liar" is predicated of "Sue". It's probably the right analysis here too, though it's a little less motivated for naming sentences like "She called the tortoise Fred".
