### ISSUE TITLE
English nsubj documentation could use more examples

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#303]
The text of the [`nsubj` documentation](http://universaldependencies.org/en/dep/nsubj.html) notes that the governor is not always a verb. I think it would be helpful if it listed examples of: 
- a governor which is a predicate adjective or nominal (e.g., "we are lazy")
- a governor which is the object of a predicate PP (e.g., "we are in the barn")
- a relative pronoun, like "who" or "that" ([as in special constructions example (69)](http://universaldependencies.org/en/overview/specific-syntax.html))

**Comment by nschneid** [comment]
@sebschu

**Comment by manning** [comment]
Hi Nathan, thanks so much for all your feedback on the documentation and on UD in general! We probably won't be able to deal with many of them for a while, since Stanford is still in session for another couple of weeks.... Maybe we should work out a way to get you more directly involved. Would you be interested in that?

At any rate, I have dealt with this one, and have added a better range of exemplification to both the universal and English nsubj pages!

**Comment by nschneid** [comment]
Thanks! And yes, I'd be happy to get more directly involved, as I'm now starting some projects that will make heavy use of UD.
