### ISSUE TITLE
Serial verbs

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#323]
What is the convention for serial verbs? I don't know any Chinese, so looking at the Chinese data won't help me.

In English we have `go get me a sandwich`. Hebrew has something similar. @omriabnd

Presumably a solution should be documented at http://universaldependencies.org/u/overview/specific-syntax.html.

**Comment by nschneid** [comment]
If I had to guess I'd say `compound`, but it doesn't really feel like compounding.

Any thoughts on this, @ngiordani? @dan-zeman? @jnivre?

**Comment by dan-zeman** [comment]
I would not use `compound`. I see two possible parallels:
1. Coordination. _Go [and] get me a sandwich._ `conj(Go, get)`
2. Subordination. _Go [there so that you can] get me a sandwich._ `advcl(Go, get)`

Of these two, coordination sounds more natural to me.

**Comment by nschneid** [comment]
What is done for languages like Chinese where serial verbs are frequent?

**Comment by dan-zeman** [comment]
No idea. @ryanmcd, could you ask Mo?

**Comment by nschneid** [comment]
Any opinion, @amir-zeldes?

**Comment by amir-zeldes** [comment]
Well, my Chinese is pretty rudimentary, but from what I can see they seem to be tagging qu4, which I guess is the most similar to 'go' in this context in at least two ways - either as governing xcomp (go VP, go to do something), or as a mark to the verb following it. This is because as a 'light verb' qu4 is kind of ambiguous between 'go' and a function word 'in order to'. Here are some graphs instantiating these readings, if I'm getting this right:

```
# Reading 1, go do as xcomp (X and Y go pick up Z from a mental institution together - the qu4 is token 8, a root governing an xcomp)
1   隨後  _   ADV RB  _   8   advmod  _   _
2   ,   _   PUNCT   ,   _   8   punct   _   _
3   王 _   PROPN   NNP _   4   nmod    _   _
4   稼祥  _   PROPN   NNP _   8   nsubj   _   _
5   和 _   CONJ    CC  _   4   cc  _   _
6   嬌嬌  _   PROPN   NNP _   4   conj    _   _
7   一同  _   ADV RB  _   8   advmod  _   _
8   去 _   VERB    VV  _   0   root    _   _
9   接 _   VERB    VV  Voice=Cau   8   xcomp   _   _
10  賀 _   PROPN   NNP _   11  nmod    _   _
11  子珍  _   PROPN   NNP _   12  nsubj   _   _
12  離開  _   VERB    VV  _   9   ccomp   _   _
13  精神  _   NOUN    NN  _   14  case    _   _
14  病 _   PART    SFN _   15  case    _   _
15  院 _   PART    SFN _   12  dobj    _   _
16  .   _   PUNCT   .   _   8   punct   _   _

# Here's another one, 'go put on a show' (of a producer)
# Token 9 is 'go' token 10 is 'give a performance'
1   有 _   VERB    VV  _   19  dep _   _
2   報道  _   NOUN    NN  _   3   nsubj   _   _
3   說 _   VERB    VV  _   1   ccomp   _   _
4   百老匯   _   PROPN   NNP _   7   nsubj   _   _
5   多 _   NUM CD  _   6   nummod  _   _
6   次 _   NOUN    NNB _   7   advmod  _   _
7   請 _   VERB    VV  Voice=Cau   3   ccomp   _   _
8   他 _   PRON    PRP Person=3    9   nsubj   _   _
9   去 _   VERB    VV  _   7   ccomp   _   _
10  上演  _   VERB    VV  _   9   xcomp   _   _
11  他 _   PRON    PRP Person=3    14  det _   _
12  的 _   PART    DEC Case=Gen    11  case:dec    _   _
13  但丁  _   PROPN   NNP _   14  case:suff   _   _
14  劇 _   PART    SFN _   10  dobj    _   _
15  ,   _   PUNCT   ,   _   19  punct   _   _
16  但是  _   ADV RB  _   19  mark    _   _
17  他 _   PRON    PRP Person=3    19  nsubj   _   _
18  始終  _   ADV RB  _   19  advmod  _   _
19  拒絕  _   VERB    VV  _   0   root    _   _
20  了 _   X   UH  _   19  discourse   _   _
21  .   _   PUNCT   .   _   19  punct   _   _

# Now the other construction
# I think token 17, qu4 tagged as an ADV + mark is now something like:
# (... the male will spend close to an hour) *in order* to chase the female (lit. 'go chase')

1   雖然  _   ADP IN  _   2   case    _   _
2   沒有  _   VERB    VV  _   18  xcomp   _   _
3   求偶  _   VERB    VV  _   5   acl:relcl   _   _
4   的 _   PART    DEC Case=Rel    3   acl:relcl   _   _
5   表徵  _   NOUN    NN  _   2   dobj    _   _
6   ,   _   PUNCT   ,   _   18  punct   _   _
7   但 _   ADV RB  _   18  mark    _   _
8   雄性  _   NOUN    NN  _   18  nsubj   _   _
9   仍 _   ADV RB  _   18  advmod  _   _
10  會 _   AUX MD  _   18  aux _   _
11  花上  _   VERB    VV  _   18  acl _   _
12  近 _   ADV RB  _   14  advmod  _   _
13  一 _   NUM CD  _   14  nummod  _   _
14  小時  _   NOUN    NN  _   16  det _   _
15  的 _   PART    DEC Case=Gen    14  case:dec    _   _
16  時間  _   NOUN    NN  _   11  dobj    _   _
17  去 _   ADV RB  _   18  mark    _   _
18  追逐  _   VERB    VV  _   0   root    _   _
19  異性  _   NOUN    NN  _   18  dobj    _   _
20  .   _   PUNCT   .   _   18  punct   _   _
```

**Comment by amir-zeldes** [comment]
I think the case we're talking about here is more similar to the xcomp one in Chinese, but I think for Hebrew and English it's not a very intuitive analysis, since you can insert 'and' with no real difference in meaning. So overall I'd be for the coordination analysis (`conj`).

I'd like to point out against my own opinion that in colloquial Hebrew, where you find this 'go do' construction more, there are some interesting morphological phenomena that may distinguish it from plain coordination when 'and' is used. If you don't use 'and', I find it acceptable to use a morphological imperative in the first slot, but not so much in the second slot. Maybe @omriabend can chime in on this. 

The following is good for me for 'go sit next to him', with morphological imperative coupled with morphological future:
`lex teshev leyado`

The following with two explicit imperative forms is weird if I take it as a serial verb - I parse it as two utterances:
`lex shev leyado`

So I read the latter as 'go! Sit next to him!'. But maybe that's my own personal grammar. Still, I think if I had to support one UD guideline across at least Heb + Eng, I'd go with `conj`. I don't know enough Chinese to really comment on the practice above, and I may have misunderstood what the sentence was saying.

**Comment by danielhers** [comment]
You mean @omriabnd :)

**Comment by amir-zeldes** [comment]
I did, thanks! Actually, your judgment is good too - what do you think: is lex teshev the same as lex shev?

**Comment by danielhers** [comment]
Well, pragmatically, I think they are the same. I feel they are the same syntactically, too, and the only difference is the imperative, which gives a stricter tone.

**Comment by nschneid** [comment]
It sounds to me like none of the options are ideal. Should we just go with `dep`, leaving the possibility of a more appropriate label later?

**Comment by dan-zeman** [comment]
Dep is not ideal either and should be avoided if possible. I think conj is better.

**Comment by nschneid** [comment]
A colleague points me to this Zwicky paper which may be relevant: http://web.stanford.edu/~zwicky/serial-verbs.pdf

**Comment by omriabnd** [comment]
Amir, all,

I agree that the serial verb construction analysis is not the most
intuitive for the Hebrew and English examples above (I don't have a strong
intuition about the Hebrew distinction you mentioned).

We're currently working on converting the CHILDES dependency annotation to
UD, trying not to correct things unless we see them as clearly wrong. Hence
our question as to whether UD recognizes (or should recognize) serial verb
constructions under some definition as part of its inventory. This question
won't go away if we decide to mark this specific construction as conj,
because it may not be a good fit for other constructions in a variety of
langauges. For instance, Aikhenvald [1] defines an SVC as:

> A serial verb construction (SVC) is a sequence of verbs which act
> together as a single predicate, without any overt marker of coordination,
> subordination, or syntactic dependency of any other sort.

Omri

[1] "Serial Verb Constructions in Typological Perspective", in Aikhenvald,
Alexandra Y. and R.M.W. Dixon. (eds.) 2006. _Serial Verb Constructions: a
cross-linguistic typology_

**Comment by dan-zeman** [comment]
@nschneid : thanks for the pointer to the Zwicky paper. He has quite a variety of examples there and I don't think that all of them should be analyzed the same way (nor do I think that Zwicky thinks they should). I start to think that your original suggestion to use `compound` is not too bad either, although you are right that it does not really feel like compounding. (But note that Zwicky advocates for subordination in the case of the English _go do X_ construction.)

If you actually have pre-UD annotation that marks serial verbs, you can define a relation subtype to preserve that distinction. Something like `compound:serial`, `conj:serial` or `[xc]comp:serial`. If nothing else, it will facilitate automatic conversion when (if) some other solution is standardized in the future.

**Comment by amir-zeldes** [comment]
I could see `conj` or `xcomp` (potentially with `:serial` if that's used), but I really feel `compound` is not appropriate. I see compounds as 'morphological', meaning they are 'complex words'. What this means in different languages varies a lot, but generally, there is some way in which they are 'one thing'. 

In English or German, compounds only take one agreement marker (case/number/gender), so we have "car park(s)" but not "cars park(s)" (only one plural, on the head). In Semitic, compounds only take one article, whereas proper syntagms, such as PP modification, allow an article per noun. Even English and German phrasal verbs, which are separable, are kind of compound-y, in that many are lexically predetermined and behave as a verb for all practical purposes: they only inflect once (on the verb) and the particle can be seen as part of the lexical item in some analyses.

The serial verb constructions that we are talking about here are basically two full verbs, with reduced or special semantics. We can talk about which one governs the other, whether they should be treated as equal or not, etc., but I don't think we should be treating them as 'one verb', which is what `compound` means for me (hence also my interest in whether they have reduced paradigm options in Hebrew, but it seems not).

**Comment by danielhers** [comment]
After reading the Zwicky paper @nschneid linked to, I'm not sure the 'go
<verb>' construction should even be analyzed a serial verb construction at
all (meant in a specific theoretical sense as something we don't yet know
how to analyze, rather than in the umbrella term sense). Why not tag the
'go' as a modal? I think it should be similar to the 'do' imperative marker
in 'do <verb>'.

**Comment by nschneid** [comment]
It looks like there is a solution for serial verbs in v2. From the [MWE changes](http://universaldependencies.org/v2/mwe.html):

> Serial verb constructions are typologically important and inadequately covered by UD v1. In the absence of a deeper analysis of this class of expressions, which may be worth a special universal relation, we propose to treat them as a subtype of `compound` and use `compound:svc` in analogy with the existing subtypes `compound:prt` for particle verbs and `compound:lvc` for grammaticized light verb constructions.

**Comment by jnivre** [comment]
Indeed there is. It may not be perfect, but it is a start. 

In case you are interested, you can have a sneak preview of v2, which went live 5 min ago. We are still working on some parts of it, and it will not be publicly announced until tomorrow, but if you promise not to tell anyone. :)

**Comment by spyysalo** [comment]
@nschneid and other issue participants: as v2 as now being published, I would suggest to close this issue. If some questions relating to this issue remain open, you can open new issues referencing the relevant parts of this discussion and the v2 documentation. (Of course, if you disagree, feel free to reopen this :-))
