### ISSUE TITLE
Verbs, aspect and choice of lemma in Russian

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#341]
I've been looking at the Russian-SynTagRus data, and there is a choice made in selecting the lemma, that aspect seems to be treated as an inflectional feature. So, the lemma of the perfective verb is the imperfective. 

```
65  съесть    СЪЕДАТЬ  VERB    _   Aspect=Perf|VerbForm=Inf    64  xcomp   _   _
```

I'm bringing this up here, as I think for other Slavic languages (I've looked at least at Polish and Czech), the lemma is always the same aspect. Is this something that we want to standardise ?

**Comment by dan-zeman** [comment]
Wow! I did not know that. I believe we should standardize this Slavic-wide, and the standard should say that aspect is lexical / changing aspect is derivation. (Edit: although it may be useful to keep the information about aspect pairs somewhere.)

**Comment by ftyers** [comment]
Yeah, I agree with you. I think this is basically because in SynTagRus it is done like that. It should be possible to convert it automatically using a morphological analyser. The original (aspect pair) lemma could be left in the MISC column.

**Comment by dan-zeman** [comment]
I just did some investigation. (WRT Slovak, this data has not been released for UD, but I have access to it and was curious how they do it.)

Czech
- aspect is lexical
- many verbs lack the feature although they are not biaspectual (incomplete lexicon)

Slovak
- aspect is lexical
- biaspectual verbs have "Imp,Perf" instead of omitting the feature
- present participles are tagged VERB but have adjectival lemma and no aspect feature

Polish
- aspect is mostly lexical
- but biaspectual verbs seem to be disambiguated by context, i.e. the same lemma appears sometimes with Imp and sometimes with Perf

Russian/Google
- no lemmas

Russian/Syntagrus
- aspect is (treated as) inflectional
- imperfective lemma for perfective verbs
- that also means that biaspectual verbs are disambiguated by context

Slovenian
- aspect is lexical
- biaspectual verbs omit the feature
- "biti" also omits it but I would say it is imperfective

Croatian
- no Aspect feature in the corpus

Bulgarian
- aspect is mostly lexical
- some biaspectual verbs (анализирам) omit the feature but it may be only a gap in the lexicon because others seem to disambiguate by context (алармирам)

Old Church Slavonic
- aspect is not lexical; the feature seems to be used to distinguish certain verb forms rather than perfective/imperfective pairs

**Comment by daghaug** [comment]
For Old Church Slavonic, we use the aspect feature to code the 
inflectional distinction between Imperfect and Aorist, since they are 
both past tenses and the difference is clearly aspectual. I actually 
think there is also a lexical aspectual system in OCS, but this is 
controversial and so not suitable for corpus annotation.

As far as I know, modern Bulgarian has the same double system, with both 
derivational/lexical and inflectional/non-lexical aspect, but it seems 
the inflectional system is treated as a tense feature (Past vs. Imp). 
But I'm not sure that standardization is warranted here since the 
systems aren't identical anyway.

Dag

**Comment by dan-zeman** [comment]
`Tense=Imp` admittedly differs from `Tense=Past` in aspect rather than in tense proper. The feature is available because of Bulgarian, where it can occur even with perfective verbs. I guess it could be used in OCS, too.

The other option would be to re-design the system using layered features, e.g. `Aspect[infl]`. I am not sure I am proposing this—I kind of got used to the current system, and like how it lines up also with Bulgarian l-participles—but maybe it would be cleaner. The current `Tense=Imp` feature pre-dates the invention of layered features in UD.

**Comment by osenova** [comment]
As it was already pointed out, in Modern Bulgarian the Aspect feature is lexical (imperfective/perfective), while Aorist/Imperfect distinction is treated as a Tense difference.
Thus, these features combine. Verbs in both aspects can inflect in both tenses as a rule. The situation should be quite close to the one in Old Church Slavonic.

**Comment by olesar** [comment]
In the first round of conversion (v.1.3), lemmatisation in Russian treebanks was not changed. SynTagRus was initially parsed by ETAP-3, a tool developed for machine translation (Russian-French-Russian and Russian-English-Russian, as far as I know). That is why aspectual pairs there are treated as inflectional.However, in v.1.4 we are going to convert lemmas according to the Russian National Corpus guidelines (using Mystem-RNC tagger and additional checks). So we are voting for\* aspect is lexicalThe same lemmatisation style will hopefully apply to UD-Russian-Google v.1.4. We will look closer at biaspectual verbs as well, thanks a lot, Dan. Other changes in v.1.4:\* mwe-s are treated as separate tokens\* words with hyphen are treated as separate tokens linked with "goeswith", in line with UD-Russian-Google # do we really need this?# http://universaldependencies.org/u/overview/tokenization.html has no guidelines on that.Olga

**Comment by dan-zeman** [comment]
Closing, as the original issue has been fixed in UD_Russian-SynTagRus.
