### ISSUE TITLE
Repeated items in Swedish Sign Language

### ISSUE THREAD

**Issue by borstell** [UniversalDependencies/docs#347]
I'm part of the group annotating a set of Swedish Sign Language (SSL) data using the UD scheme. One issue that is particularly common for SSL data (and several other sign languages) is the repetition of certain items. The most notable ones are (1) repeated pronominal subjects, and (2) so-called "verb sandwiches". Examples are given below (sign glosses translated to English for convenience).

> (1) 
> **PRO1** PERF EAT **PRO1**
> 'I have already eaten (I)'
> 
> (2)
> PRO1 **TYPE** ESSAY **TYPE**(++)
> 'I was typing away on my essay'

For example (1), the repeated subject does not really add meaning, but it is a common feature to repeat pronominal (i.e. pointing) subjects _within_ clauses.

For example (2), the repeated verb may or may not be identical to the first one. Relatively often, the second (normally clause-final) verb has some additional morphology (e.g., reduplication, as marked by the "++" in (2)), often said to carry some aspectual meaning.

The question is: What would be the preferred solution for dealing with these items? Are there other languages already featured in the UD database that have similar features, and if so, how do they deal with these questions? We were considering the category `remnant`, at least for cases like (1), but weren't sure this would be the most suitable.

**Comment by dan-zeman** [comment]
While I am not sure about the best solution, I would advise against `remnant`. It was meant for ellipsis and it is becoming obsolete: it is probable that it will be removed from UD v2 guidelines, which are being prepared now.

The reduplicated pronouns in (1) somewhat resemble clitic doubling that we already have in a couple of languages (e.g. Bulgarian). The solution there is that the superfluous pronoun is attached as `expl` to the same parent as the main argument. (But in your case it is not clear which argument is the main one; probably the first one.)

It does not really solve (2) though. I don't think we have a relation suitable for this sort of construction. Perhaps I would go for `aux`, because the two verbs form a unit, and the additional morphology applies to both. But it differs from the usual usage of `aux` in that you expect a relatively small set of lemmas to appear as `aux` dependents, while here any verb could serve as its own auxiliary. There are some other possibilities (`compound`, `conj`) but none of them seems any better to me.

**Comment by hectormartinez** [comment]
Well, Turkish has a compound:redup, would that fit?

2016-10-13 8:35 GMT+02:00 Dan Zeman notifications@github.com:

**Comment by manning** [comment]
(I also know nothing about Swedish sign language, of course...)

For the repeated _I_ in (1), I would strongly suggest that the right relation is `dislocated`. I think it would be correct to say that this is the same phenomenon as you get with right dislocated repetitions in languages including French, as illustrated at the bottom of this page: [dislocated](http://universaldependencies.org/u/dep/dislocated.html). The other choice is `expl`, but I suspect it is wrong here. At any rate, though, the different possible analyses are discussed somewhat in the middle of the page ("A second, related, use ...") of the page for [expl](http://universaldependencies.org/u/dep/expl.html). 

For (2), I'd need to know more, but I suspect that this might best be thought of as a serial verb construction. Certainly, this analysis has been used for other sign languages, see for instance [Benedicto et al.](http://www.ub.edu/ling/tislr8/Benedicto-Cvejanov-Quer.doc) or [Nyst](http://www.ub.edu/ling/tislr8/Nyst.doc). I've argued that UD has to provide more to support serial verb constructions, which are widespread in many language families (West Africa, Austronesia, Chinese lgs, etc.). Maybe if a Swedish language also has serial verb constructions, then @jnivre will become more active on this issue! 😃  At the moment, I think I would go with `compound:svc` and hope for better support in the future. (I think `conj` is clearly wrong, and `aux` seems problematic for the reason @dan-zeman gives.)

**Comment by jnivre** [comment]
Swedish does not have serial verb constructions, but I should probably become more active anyway. I think compound:svc is a good compromise for now, but I hope we can provide something better for v2.

**Comment by olesar** [comment]
The repetition of words and word parts is an important property of spoken languages associated with many semantic and pragmatic functions rather than just "self corrections / mistakes". I believe that the sign languages and spoken languages are kind of similar in this respect. If we get the data of the clinical linguistics (somewhere somehow in the distant future), we'd come across yet more functions of repetitions. So, I would go for taking them seriously. Olga

**Comment by dan-zeman** [comment]
Tentatively closing the issue, as it seems that we do not have much more to say to the original question.
