### ISSUE TITLE
Lost links?

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/docs#361]
I cannot find a link from the [main page](http://universaldependencies.org/) to [contributing.html](http://universaldependencies.org/contributing.html), only to [contribute.html](http://universaldependencies.org/contribute.html), which I cannot find in this repo (not even under [_v2](https://github.com/UniversalDependencies/docs/tree/pages-source/_v2)).
As a result, I cannot find a link to [visualization.html](http://universaldependencies.org/visualization.html) and I don't know how to fix it.

**Comment by nschneid** [comment]
contribute.html is generated from contribute.md at the root of this repo (on the pages-source branch). Does that answer your question?

**Comment by dan-zeman** [comment]
The page contributing.html is still reachable via contribute.html and http://universaldependencies.org/release_checklist.html (very end). I am not sure whether this is what we want, @jnivre ? Maybe contribute.html should list a separate item, when you want to contribute to this documentation site?

**Comment by martinpopel** [comment]
> contribute.html is generated from contribute.md at the root of this repo (on the pages-source branch).

Oops, I was blind.

> Does that answer your question?

Only partially. What is the relation between `contribute.md` and `contributing.md`? A replacement or should there be a link "for details see [contributing.md]"?
My main point is that `visualization.md` is unreachable now.

**Comment by jnivre** [comment]
Short answer: Someone should clear up this mess!

Long answer: The problem with all of these links was that things were reachable in too many ways, which made it very hard to know where to go. In addition, the links to contributing.md were confusing (in context) because they gave the impression that it was about contributing to UD in general and not to the documentation. My intention with reorganisation this was (a) to make it (almost) a tree instead of a (highly interconnected) graph and (b) to make it intuitively understandable for newcomers. I am sorry if vizualisation.md got lost in the process. But rather than just putting contributing.md back, I think we need to rethink the structure of these things. This is essentially what @manning pointed out a long time ago. The problem is that we have all been super-busy with the new guidelines, so there simply wasn't time to do this properly. (Another thing that really needs to be improved is the tools-page, but I guess that's another story.)

Perhaps @spyysalo could take the lead on this?

**Comment by spyysalo** [comment]
This was actually confusing me too, I was trying to remind myself of the syntax for `# visual-style` yesterday and had to use google because I couldn't find http://universaldependencies.org/visualization.html by clicking around the new site.

I wouldn't mind a densely interlinked site as long as it's clear what the links are pointing to. I do agree that "contributing" is a bad name for the page http://universaldependencies.org/contributing.html . Maybe we could make http://universaldependencies.org/contribute.html into a "hub" page that points to all pages relevant to contributing to the project (instead of the root of a tree)?

I'm afraid I'll be very busy until after Coling. If this is urgent, I'd like to ask for someone else to take charge; if not, please do assign me.

**Comment by jnivre** [comment]
Having contribute.html as a hub is what I was aiming it, but I admit that it was only a first hack. Post-COLING is probably the only realistic thing for many of us, so perhaps we should just put a link to visualization.html somewhere temporarily and then fix this properly. Couldn't visualization go under tools for example?

**Comment by dan-zeman** [comment]
Added a pointer to the hub page (http://universaldependencies.org/contribute.html) and added another link to visualization from the Brat section in tools.
