### ISSUE TITLE
Relative clauses documentation

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/docs#364]
The [v2 documentation of enhanced dependencies](http://universaldependencies.org/u/overview/enhanced-syntax.html#relative-clauses) shows two simple sentences where the relative pronoun is attached to the main predicate of the relative clause in basic dependencies. However, there are "more complex" relative clauses (sorry for not knowing the correct linguistic name), e.g. "I saw a man whose mother become a pirate" (suggested by @zabokrtsky). I guess it should be annotated as http://universaldependencies.org/sandbox.html#pirate-example.

I suggest
- [ ] The documentation should include at least one such more complex example (with full CoNLL-U annotation using [tabs=yes](http://universaldependencies.org/visualization.html#editing)).
- [ ] The documentation should fix the claim "the governor of the relative clause is attached as an argument to the main predicate of the relative clause", which is not applicable to the more complex relative clauses (if my [annotation](http://universaldependencies.org/sandbox.html#pirate-example) is correct; if it is wrong, we would need to define what is the deprel of this enhanced dependency).

**Comment by nschneid** [comment]
Agree that a "whose" example would be good. Relative clause examples of "whose" can be found in [the English data](http://bionlp-www.utu.fi/dep_search/).

Relatedly, an annotator I work with was unsure about "whose" questions, e.g., "Whose mother became a pirate?" Unfortunately there are no examples in the data. The closest I can find is "Which one should I get?", but there the relation between the verb and the WH-word is `det` rather than `nmod:poss`.

**Comment by dan-zeman** [comment]
The documentation of the enhanced representation of relative clauses has improved, so I am closing this issue.

@nschneid : I believe that in _Whose mother became a pirate?_, we have either `det(:poss)` or `nmod(:poss)` between _mother_ and _Whose_, depending on how the language distinguishes possessive determiners/pronouns. I suspect that in English it would be `nmod:poss` but I did not check.
