### ISSUE TITLE
"Let PRONOUN VERB" inconsistencies

### ISSUE THREAD

**Issue by brendano** [UniversalDependencies/docs#371]
We noticed these recently in the UD_English treebank... (version 1.4)

For "let PRONOUN VERB", it seems to always have either xcomp(let,VERB) or ccomp(let,VERB).

But for some cases there's
 - dobj(let, PRONOUN)

and in others
 - nsubj(VERB, PRONOUN)

I could see arguments either way of course.  Here are two examples for "let me know" with the inconsistency.  Or is there a consistency we're not seeing?

These are from `grep -n ... | cut -f1,2,7,8` so the line numbers are included.

```
en-ud-dev.conllu:5363:1 Let     0       root
en-ud-dev.conllu-5364-2 me      3       nsubj
en-ud-dev.conllu-5365-3 know    1       ccomp

en-ud-train.conllu:71801:1      Let     0       root
en-ud-train.conllu-71802-2      me      1       dobj
en-ud-train.conllu-71803-3      know    1       ccomp
```

and some others

```
en-ud-train.conllu-53321-3      please  4       discourse
en-ud-train.conllu:53322:4      let     0       root
en-ud-train.conllu-53323-5      us      6       nsubj
en-ud-train.conllu-53324-6      know    4       ccomp

en-ud-train.conllu-85530-7      please  8       discourse
en-ud-train.conllu:85531:8      let     0       root
en-ud-train.conllu-85532-9      me      8       dobj
en-ud-train.conllu-85533-10     know    8       xcomp
```

and a more complex nsubj(VERB,PRONOUN) example (where VERB is replaced by predicate due to copula handling):

```
en-ud-train.conllu:103715:1     Let     0       root
en-ud-train.conllu-103716-2     your    3       nmod:poss
en-ud-train.conllu-103717-3     mind    9       nsubj
en-ud-train.conllu-103718-4     and     3       cc
en-ud-train.conllu-103719-5     body    3       conj
en-ud-train.conllu-103720-6     be      9       cop
en-ud-train.conllu-103721-7     totally 9       advmod
en-ud-train.conllu-103722-8     at      9       case
en-ud-train.conllu-103723-9     peace   1       ccomp
en-ud-train.conllu-103724-10    .       1       punct
```

**Comment by brendano** [comment]
Oh yeah I guess the construction actually is "Let NP VERB"

**Comment by nschneid** [comment]
"Make" can also have this argument structure, right? "let/make them eat cake"

Unlike classic examples of control (e.g., "want them to eat cake") the second verb is not preceded by infinitival "to". Nevertheless, [xcomp](http://universaldependencies.org/u/dep/xcomp.html) seems to fit.

("Let X know" is an idiom, but that probably doesn't affect its syntactic analysis.)

**Comment by brendano** [comment]
On Friday, December 9, 2016, Nathan Schneider <notifications@github.com>
wrote:

> "Make" can also have this argument structure, right? "let/make them eat
> cake"
>
> Unlike classic examples of control (e.g., "want to eat cake") the second
> verb is not preceded by infinitival "to". Nevertheless, xcomp
> <http://universaldependencies.org/u/dep/xcomp.html> seems to fit.
>

this interp has obj(let/make, them)
and not nsubj(eat, them)
?




-- 
-brendan [mobile]

**Comment by nschneid** [comment]
Judging by [this query](http://bionlp-www.utu.fi/dep_search/query?search=encourage&db=UD_English-dev&case_sensitive=True&hits_per_page=50) of "encourage", the pronoun is the dobj of the matrix verb. I will add this to the documentation of [xcomp](http://universaldependencies.org/docs/u/dep/xcomp.html).

**Comment by nschneid** [comment]
FYI, `dobj` is renamed to `obj` in UD v2.

**Comment by amir-zeldes** [comment]
I agree with @nschneid (I think he's saying it is nsubj(eat,them)). What's strange is I remembered the Stanford Parser outputs the structure @nschneid is suggesting, but with `ccomp` instead of `xcomp`, despite the non-subject pronoun being governed as a subject in the subordinate clause. I was just able to reproduce it with the Stanford parser and its conversion from gold PTB data, so it seems intentional:

```
root(ROOT-0, Let-1)
nsubj(eat-3, me-2)
ccomp(Let-1, eat-3)
dobj(eat-3, cake-4)
```

And this is the result of converting:
```
(ROOT
  (S
    (VP (VB Let)
      (S
        (NP (PRP me))
        (VP (VB eat)
          (NP (NN cake)))))
    (. .)))
```

Replacing 'let' with 'make' produces the same parse.

**Comment by nschneid** [comment]
No, I meant dobj(make, them). I've updated http://universaldependencies.org/u/dep/xcomp.html to reflect what I understand the convention to be based on the data. AFAIK this wasn't listed as one of the changes for v2.

**Comment by jnivre** [comment]
This looks like inconsistencies and/or conversion errors to me. It is definitely not a change in v2. As far as I know, the intended analysis has always been:

obj(let, them)
xcomp(let, know)

This is the "object cum infinitive" analysis, as opposed to the small clause analysis, which has been popular in generative grammar and which would yield:

ccomp(let, know)
nsubj(know, them)

But @manning or @sebschu should confirm this for English.

**Comment by mcdm** [comment]
Joakim is right. We talked about this construction and the analysis we adopted (obj and xcomp) in our DepLing 2013 paper "More constructions, more genres: Extending Stanford Dependencies".

**Comment by jnivre** [comment]
Or @mcdm of course. Sorry, Marie. :)

**Comment by brendano** [comment]
It may be helpful to have that paper on this list: http://universaldependencies.org/introduction.html

**Comment by nschneid** [comment]
> It may be helpful to have that paper on this list: http://universaldependencies.org/introduction.html

Good suggestion. Done!

**Comment by manning** [comment]
Thanks @brendano, @nschneid and everyone! Yes, should be `obj` and `xcomp`, but doesn't seem to have been very consistently/reliably so annotated….

We’ll try to correct this shortly in UD_English dev branch.

@amir-zeldes:  As @jnivre notes, UD uses an "object cum infinitive" or "raising to object" analysis, not the kind of small clause/ECM analyses of GP/P&P/MP. The nsubj(know, me) dependency appears only as an additional dependency in the enhanced dependencies representation.

**Comment by amir-zeldes** [comment]
@manning : thanks for the clarification, I also agree with this analysis, and we've been following it in an English corpus we're building as well. I was just surprised to see the Stanford parser seems to regularly produce this in the conversion from gold constituent data.

**Comment by manning** [comment]
I've also added a description and some examples of the object control case to the [Complex Clauses documentation page](http://universaldependencies.org/u/overview/complex-syntax.html#subordination).  (Fixes to the corpus are yet to come, but hopefully soon!)

There is some code in the Stanford parser that tries to get this right, but one of the reasons why it is difficult is that the Penn Treebank uses the Chomskyan generative grammar "small clause" or ECM analysis, and so there's some kind of tricky remapping to try to convert things. (Also, I think the xcomp case is just rarer, and so the common case tends to win in the analysis.)

**Comment by manning** [comment]
I've just corrected this for all cases of the lexeme _let_ in the original UD_English files in the v2 dev branch. (Most of the examples were previously wrongly annotated. We should check over some other xcomp-taking verbs at some point.)

**Comment by nschneid** [comment]
Noting here for posterity that the "let PRON know" can be followed by a direct object, making the pronoun an indirect object:

- Please let me know [a date and time that is convenient for you]. 

Under current EWT policy, there is no iobj without an obj, so this does not affect the analysis of the simple case.

**Comment by amir-zeldes** [comment]
I don't think I understand this issue - they are objects of two different verbs, no?

obj(let, me)
obj(know, date)

So nothing needs to be iobj, right?

**Comment by nschneid** [comment]
Historically that would make sense, but my intuition is that "let...know" is now more or less equivalent to "tell".

I don't think you can say

- *Let me know when the party starts and know what I should bring.
- *Let me know the start time and know the guest list.
- ?Let me know the start time and him know the guest list.

which should be licensed if *know* formed a constituent with what followed it.

**Comment by amir-zeldes** [comment]
Mm, I don't think that has to do with argument structure; repeating an identical verb is generally odd, though perhaps not ungrammatical. For example:

  * ? Let me have the start time and have the guest list
  * ? let me have the start time and him have the guest list

I don't even really find the "know" examples worse than the "have" examples, so I would say they are not ungrammatical, just really odd (for probably Gricean redundancy reasons). In any case, "let" does not license a second object; it's the knowing which licenses the "thing known" argument.

**Comment by nschneid** [comment]
> - ? Let me have the start time and have the guest list

You're right, the repetition is weird. How about VP coordination with different verbs:

- Let me cook breakfast and order dinner.
- ??Let me know the start time and bring the wine. — feels zeugmatic, but perhaps it's a semantic incompatibility that makes it odd to coordinate "know" and "bring".

The corpus has:

- I knew what it was and told the guy that it wasn't a fps. 

Changing that to something more compatible with permission:

- I knew what it was and told the guy he was a liar.

Adding "let" individually is fine:

- She let me know what it was
- She let me tell the guy he was a liar

But:

- ?She let me know what it was and tell the guy he was a liar.

"Let"+"know" really feels like an idiom that resists internal coordination of another VP.

>   * ? let me have the start time and him have the guest list

That sounds totally fine to me with contrastive emphasis on "me" and "him". The 2nd "have" can be omitted as well. Sounds much odder to do that with "know".

**Comment by amir-zeldes** [comment]
> Sounds much odder to do that with "know"

I don't disagree that 'let me know', being more entrenched, sounds more odd to modify; but I don't think that alters the underlying syntax. What about less common configurations? Would you assign different trees to these two as well?

  * We can't let Kim know the secret!
  * We can't let Kim discover the secret!

**Comment by nschneid** [comment]
There I think it's ambiguous, and I would distinguish them prosodically. We can't let Kim know | the secret ('tell' interpretation, idiomatic) vs. We can't let Kim | know the secret ('allow' interpretation, literal).

Semantically, the first reading means none of us should tell her. The second reading means we can't allow her to find out by any means (cf. We can't allow Kim to know/discover the secret).

The passive is rare with "let" but you could say "the secret was let known to Kim" or "Kim was let known the secret". This is similar to 'tell' right? The secret was told to her vs. she was told the secret. COCA: "something she was most anxious to be let known" => she was anxious ~to be let known something~ for something to be let known i.e. announced widely [I checked the wider context which was a different interpretation from what I expected]. Google Books: "She was simply handed an envelope, was **let known** her financial circumstances at the college and that was it." (i.e. told)

I can't think of another verb that works with "let" in this way (*the secret was let given to Kim / the secret was allowed to be given to Kim, *Kim was let given the secret / Kim was allowed to be given the secret).

**Comment by amir-zeldes** [comment]
Even if there is a possibility for different semantic readings of "let someone know something", I don't think those should play out differently at the syntactic level: the entrenchment of "let know" makes it possible for it to assume meanings, but those meanings still piggyback on the syntactic structure "let NP VP". I don't think it's feasible to ask annotators to try to figure out if Kim is allowed to find out about the secret from other sources, and in any case, I still believe that syntactically "know" is what licenses "thing known" as an object, not "let" (otherwise, not only does "let" have two objects, but "know" is bizarrely missing its normal object argument too).

**Comment by nschneid** [comment]
I suspect "let"+"know" *together* (as an idiom) license argument structures similar to those of "tell".

Otherwise how do you explain the "let known" passives?

**Comment by amir-zeldes** [comment]
I don't disagree it's an idiom, I just still think the two arguments are licensed by the separate parts of the idiom. For me "the secret was let known to Kim" and "the secret was let given to Kim" are equally bizarre (they are borderline ungrammatical for me, but I understand what they both mean). But I don't see why passivization is a test of who controls which argument - it's still xcomp either way right? I mean, we can say "Kim was let go" (meaning "was fired"), and it's still xcomp(let, go), no? Or what do you think is the head and deprel of "know" in "let me know"?

**Comment by nschneid** [comment]
[Twitter discussion](https://twitter.com/DailySyntaxTree/status/1489228156917760008)

"was let known" works for me, not "was let given".

Notice it's "was let go", not "was let gone"!

**Comment by nschneid** [comment]
I realize that there may be no perfect solution to this type of idiom in UD. But the parallels with "tell" are strong:

1. tell
   - The employer told Kim she was fired.
   - Kim was told she was fired.
   - The employer told Kim the bad news.
   - Kim was told the bad news.
   - The bad news was told **to** Kim.
   - The employer told Kim. / Kim was told.
   - ?The employer told the bad news. / ?The bad news was told. (maybe would be OK in the right context)
2. let know (idiom)
   - The employer let Kim know she was fired.
   - Kim was let known she was fired.
   - The employer told Kim the bad news.
   - Kim was let known the bad news.
   - The bad news was let known **to** Kim.
   - The employer let Kim know. / Kim was let known.
   - *The employer let know the bad news. / ?The bad news was let known.
3. let believe (non-idiom)
   - The employer let Kim believe she was fired.
   - *Kim was let believe(d) she was fired.
   - The employer let Kim believe the bad news.
   - *Kim was let believe the bad news. (OK: Kim was led to believe the bad news—but that's another idiom.)
   - *The bad news was let believe(d) to Kim.
   - *The employer let Kim believe. / *Kim was let believe(d).
   - *The employer let believe the bad news. / *The bad news was let believe(d).
4. let go (idiom)
   - *The employer let Kim go she was fired.
   - *Kim was let go(ne) she was fired.
   - *The employer let Kim go the bad news. (Of course this doesn't make sense, but I can't think of *any* valid complement of "go" with this idiom)
   - The employer let Kim go. / Kim was let go.

So, if we accept that the idiom "let X know Y" is basically equivalent to "tell X Y" except for the unusual presence of "know", this suggests `iobj` is a good label for X, and maybe compound(let, know) rather than xcomp(let, know).

**Comment by dan-zeman** [comment]
I still don't prefer any special treatment for _let know_ but if X is attached as `iobj` to _let_, then the relation between _let_ and _know_ **must** be `compound` and not `xcomp`.

**Comment by amir-zeldes** [comment]
> iobj is a good label for X, and maybe compound(let, know) rather than xcomp(let, know)

This is why I was asking what you think the deprel of let + know is - for me "Kim was let known the secret" is simply not grammatical, and it seems clear to me that there is the usual argument sharing of xcomp: "I let Kim know the secret" means that Kim is the object of letting and the subject of knowing. The knower is Kim, and the thing known is the secret, so to accommodate the structure sharing, the usual `xcomp` is the expected analysis IMO. If my grammar is wrong and the odd passivization is really possible, but you also think there is a second more compositional reading where others may or may not be the source of Kim finding out, then it seems like such a subtle judgment to make in the active cases that I would not trust annotators to make it consistently.

That said, I understand that if there were such a complex verb "let know" then it could be compound and iobj. It just seems like a very radical re-analysis of the construction which I don't share, so I guess the real question is how common the judgment is? It also begs the question why it does not become "I let-know Kim the secret", or "know-let" or anything else. I'm not even sure what the POS tags and FEATS would be for something like "let known"? 

Just to reassure myself that my grammar is not totally idiosyncratic, I went ahead and searched in UKWAC01 (.uk domains, 277M tokens) and ENCOW01 (300M tokens) for "was let know", "was let known" and "was let VBN/VBD". Since "let NP know" is quite common, if it were normal to passivize this in any of these ways, I would expect at least one hit, but there are zero for all queries in all corpora. How many examples were you able to find in COCA, and which COCA was it? If it's COCA spoken, it may have been a CC error, since it's all based on automatic captioning of TV data.

**Comment by nschneid** [comment]
COCA has 6 hits of the bigram "let known" but a couple are a completely different construction and the ones that are closest are a different meaning, something like 'publicly revealed'. I found better examples in Google Books though—see my edited post above for one of them. It may differ between dialects.

**Comment by amir-zeldes** [comment]
Well, COCA is about 1G tokens, so if the frequency of this is so low, and some of the hits are not the construction/possible closed caption errors, this all suggests to me that "X was let known Y" is marginal at best (and maybe it's grammatical for some speakers, but personally it really triggers my asterisk :)

Of course it could be ongoing language change and maybe one day we'll even see "I let know Kim the secret". But for now I  think all of this doesn't look like a reason to deviate from the expected obj+xcomp for "Let NP know NP" to a non-compositional discontinuous compound with iobj.

**Comment by rueter** [comment]
I think there might be a problem with one exception @nschneid 

?She let me know what it was and tell the guy he was a liar.

The verb `know' takes a direct object, but the verb `tell' takes an indirect object.
So if we use two verbs with direct objects, it doesn't sound that bad at all, IMO.

She let me [know] what it was and [say] the guy was a liar.
She let me hear what it was...
She let me see what it was...

So, could it be a matter of coordinating two different argument structures?

**Comment by nschneid** [comment]
> She let me [know] what it was and [say] the guy was a liar.

I still get the 'allow' reading of "let" here. But I've been convinced that that can be explained on semantic idiosyncrasy grounds.

**Comment by nschneid** [comment]
For fun I did a Twitter poll. Evidence of variation even among native speakers! https://twitter.com/complingy/status/1493651021536452610

Anyway it seems like we don't have widespread and conclusive evidence that this idiom is syntactically exceptional, so I'm convinced that the more conservative `xcomp` solution is the way to go.
