### ISSUE TITLE
about neg and the Polarity=Neg

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/docs#372]
Not clear for me what word should receive the feature `Polarity=Neg` and what relation to use between the negative indicator and the word being negated.

How should we annotate the english example:

```
They didn't write the report.
```

In Portuguese, the `neg` relation is used many times to negate a verb. I didn't find any example in the documentation besides the general comments in the pages:

1. http://universaldependencies.org/v2/summary.html
2. http://universaldependencies.org/v2/semantic-categories.html

My first try was:

https://github.com/own-pt/bosque-UD/commit/9df18b0378e567b16addd1096b186212f3844e6a

but I suspect that the Polarity should  be marked in the 'não' word, am I right?

**Comment by jnivre** [comment]
Thanks for raising this issue, which clearly is important and needs to be clarified in the guidelines. I would say the default assumption is to use "advmod" for clause-level negation like English "not" and to add the feature Polarity=Neg to this word, rather than to the verb. This is analogous  to putting Definite=Def on "the" rather than "dog" in "the dog". Other languages that use a morphological marking on the verb to express negation will of course have Polarity=Neg on the verb. I am at COLING right now, but I will try to find the time to add this to the guidelines as soon as I can.

**Comment by livyreal** [comment]
Thanks, Joakim.

"advmod" works for most of the cases in Portuguese, but we still need guidelines for cases as:

`No, I don't believe.`

Where "No" is an `INTJ`. I would use the `parataxis` relation, but I'm not sure if it is the best relation to be used here.

**Comment by jnivre** [comment]
We recommend "discourse" for yes and no in this position. See http://universaldependencies.org/u/overview/specific-syntax.html#paratactic-constructions.
In case of "no", adding the feature Polarity=Neg seems fine to me.

**Comment by livyreal** [comment]
another Portuguese issue we need to address is double negation: "nobody sees nothing", "I did not see nothing" and "never nobody asks nothing". Should all negative words have this polarity feature, right? Including "nobody"?

In "I did not see nothing", we could mark "nothing" as `obj` but double negation in Portuguese is an interesting phenomenon to mark differently. We also have "I did not see not", and it should be odd mark this "not" as `obj`.

**Comment by dan-zeman** [comment]
- _nobody_ is `PRON PronType=Neg` and `nsubj`
- _nothing_ is `PRON PronType=Neg` and `obj`
- _never_ is `ADV PronType=Neg` and `advmod`
- _not_ is `PART Polarity=Neg` and `advmod`; in the "odd" example it is `obj` because the word is mentioned there, not used, i.e. it functions as a noun (our rules say that the POS tag should not change to `NOUN` when the word is mentioned, but I think the dependency relation should change because the function has changed)

**Comment by martinpopel** [comment]
Another related issue: I think we should distinguish between _inflectional_ features and _lexical_ features and we should define for each language which feature is inflectional/lexical and when. (I am sure the linguists here have better names than _inflectional_ and _lexical_, so let's take these names just as placeholders.) I think this is very important for downstream applications.

What I mean by _lexical feature_ is that it has the same value in all forms of a given lemma. If it differs, it is inflectional (or agglutinative).
If a word has inflectional feature with value `Neg`, then the negation should not be present in the lemma. E.g. if we mark "unhappy" with `Polarity=Neg` and we consider `Polarity` an inflectional feature, we should lemmatize the word as "happy". If the negation is present morphologically in the lemma (e.g. "nobody, nothing, never") and we mark those words as `PronType=Neg`, then we should consider `PronType` a lexical feature.

I guess, the guidelines for most languages could be that `PronType` is always lexical, while `Polarity` is inflectional with some exceptions, e.g. "not" (or generally `upos=PART`), where we probably want to keep the lemma "not".

**Comment by olesar** [comment]
@martinit is not that easy.. Sometimes we have the "plural only" nouns, and then have to switch between Number as an inflectional feature and Number as a lexical classifier. And even if you compile the list of nouns belonging to both categories, then some of them occur ... occasionally... in the "odd" number.In the Russian National Corpus, we had such a practice initially, but refused to move data back and forth.However, it is a good idea to fix such properties in individual language FEAT guidelines as either the strong classification or as a tendency.Btw there can be some occasional properties such as an "archaic"/historical case form in adjectives etc. Should we document them as well?

**Comment by arademaker** [comment]
Hi @martinpopel , this is indeed a meaningful discussion and good point. @livyreal and @claudiafreitas, what do you think for Portuguese? @olesar this example of exceptions that you gave invalided the idea or only makes the task more difficult?

**Comment by arademaker** [comment]
BTW, I recently came across another distinction of features: variable vs. inherent features. This variation is not covered by UD, right?

> Nouns in both English and Italian have both singular and plural forms: one and the same noun can be rendered in both the singular and the plural. We say therefore that the number is a variable feature of nouns. But gender in Italian (as in many other languages) attaches to nouns in a different way: a noun is either masculine or feminine, instead of having both masculine and feminine forms. We say therefore that gender is an inherent feature of Italian nouns.

> The distinction between variable and inherent features is reflected in the way words are presented in dictionaries. For example, a dictionary entry for pizza might look as follows: `pizza, pl. pizze: n.f.`

> Variable and inherent features are connected to each other via the mechanism of agreement. In agreement, a variable feature of one word is determined by an inherent feature of another one. For instance, in the adjectival modification of nouns, the variable gender of the adjective is determined by the inherent gender of the noun. Agreement is thus asymmetric: we say that the adjective agrees to the noun, rather than the other way round.

source: http://www.grammaticalframework.org/gf-book/

**Comment by dan-zeman** [comment]
@arademaker : This seems to be exactly the distinction that @martinpopel (and the UD documentation) call inflectional vs. lexical features.

**Comment by olesar** [comment]
@alexander: exactly, it makes it invalid (i.e. practically inapplicable in corpus annotation). I can provide tons of examples for each pos class, if you want.Structuralism is dead, guys;) The modern theories work with scales rather than "black or white" categories. A scale between coordination and subordination, a scale between participles and deverbal adjectives, and so on.

**Comment by martinit** [comment]
Why do I get these letters? 14.12.2016, 10:11, "Olga Lyashevskaya" <notifications@github.com>:@alexander: exactly, it makes it invalid (i.e. practically inapplicable in corpus annotation). I can provide tons of examples for each pos class, if you want.Structuralism is dead, guys;) The modern theories work with scales rather than "black or white" categories. A scale between coordination and subordination, a scale between participles and deverbal adjectives, and so on.13.12.2016, 21:11, "Alexandre Rademaker" <notifications@github.com>:Hi @martinpopel , this is indeed a meaningful discussion and good point. @livyreal and @claudiafreitas, what do you think for Portuguese? @olesar this example of exceptions that you gave invalided the idea or only makes the task more difficult?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.Olga Lyashevskaya School of Linguistics, Faculty of Humanities Higher School of Economics, Moscow—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by dan-zeman** [comment]
@martinit : Because @olesar made a typo when attempting to address @martinpopel .

Please click on "mute this thread" at the end of this message and you should no longer get copies.

**Comment by livyreal** [comment]
I agree with @olesar, however most of the features are inflectional (at least in Portuguese).

@martinpopel, do you think the lemma of "unhappy" would be "happy"? I would not go for it.

@dan-zeman you said `never is ADV PronType=Neg`. Why do not use `Polarity=Neg` in this case? It is not clear to me how to document polarity in the case of adverbials.  If we try to distinguish `PronType` as more lexical and `Polarity` as more inflectional, it would be fine to use `PronType=Neg` to `never`, but "never" seems too related to `not PART Polarity=Neg`.

Why do not use only a single way to mark polarity in all POS?

**Comment by martinpopel** [comment]
> @martinpopel, do you think the lemma of "unhappy" would be "happy"?

My primary point is that we should not have lemma=unhappy and `Polarity=Neg` and treat `Polarity` as inflectional/variable feature. This does not make sense from the semantic (and downstream applications) point of view.

In case of regular negative adjectives, I would vote for lemmatizing the negative prefixes. So yes, form=unhappy, lemma=happy, Polarity=Neg. This is in line with the UD guidelines for many languages, e.g. in Czech we have form=nešťastný, lemma=šťastný, Polarity=Neg. It's also common in many English treebanks/corpora. My guess is that the UDv1 English style of lemmatization is a heritage of missing lemmas in PennTB and GoogleUDT.
I can help with the code for lemmatizing English UD as I did it in past. It is not as simple as `s/^(un|in|im|non-?|dis-?|il|ir)//`. There are many words starting with these prefixes which are not negative (e.g. _unique_) or where the negation is already lexicalized (e.g. _nonchalant_) or questionable (e.g. _uneasy_).

I think it is up to each language to specify the lemmatization rules and which morphological phenomena it concerns. If there is a language where it is common that a single word can be combined with several negative prefixes, each with a different meaning (something like _unexpensive_ and _inexpensive_ according to [some sources](http://www.wikidiff.com/unexpensive/inexpensive)), I would not vote for lemmatizing these prefixes as it would lead to a loss of information.

In general, I think that we should be always* able to reconstruct the form from the lemma, upos and features (and misc).
*) There may be cases of exact synonymy, e.g. spelling differences (e.g. both _labelling_ and _labeling_  have lemma _label_ and `VerbForm=Ger`), so in practice it will be almost always.

**Comment by amir-zeldes** [comment]
+1 for the lemma/negation decision being language specific. I agree with @martinpopel that reconstructibility of the form is desirable, but this is generally not 100% possible (think about capitalization in the word form - this is not predictable from lemma+feats).

In general I think lemmatizing away negation is more common in languages where the negation is more or less inflectional, in the sense that it is close to universally applicable (e.g. any adjective can negate) and predictable (affix choice shows virtually no free variation). 

This is common in agglutinative languages like Turkish or Japanese. For example in Japanese, depending on the token units used, for bunsetsu or "MUW" sized tokens (in Tanaka et al.'s recent LREC paper), negations in Japanese like "oishikunai" 'untasty' would be lemmatized to the positive form "oishii" 'tasty' (though the most granular tokenization convention for Japanese, or SUW, actually tokenizes the affix meaning 'un' completely separately). But I don't think any lemmatization convention for Japanese has negative adjective lemmas.

**Comment by jnivre** [comment]
Note that UD annotation covers inflection but not derivation, because we are covering grammar but not lexicon. I cannot vouch for all languages, of course, but I would say that "unhappy" in English is a clear case of derivation and that the lemma should therefore be "unhappy".

**Comment by dan-zeman** [comment]
@livyreal : `PronType` is more or less lexical feature, a finer categorization of pro-forms, i.e. pronouns, pro-adjectives (determiners) and pronominal adverbs. `Polarity` is inflectional, used e.g. for verbs or non-pronominal adjectives when switching their polarity is regarded as inflection rather than derivation.

The negating particle does not fit well into this picture. Its negativeness is rather lexical than inflectional, but at the same time it is not a pro-form, and `PronType` is not well suited either. If we had particle type as a universal feature, maybe `PartType=Neg` would be the best solution. On the other hand, its function is identical to that of bound morphemes that are responsible for negative polarity in other languages, so it actually makes sense to use `Polarity=Neg` here as well.

**Comment by livyreal** [comment]
@dan-zeman what is pronominal adverbs? Is "never" a pronominal adverb?

In Portuguese we do not have inflectional negativeness, it is always lexical (inherent or derived, but for sure a lexical feature). However, if we want to document the polarity of words as "unhappy", we need to use `Polarity=Neg`, right? Or there is any feature to document polarity of adjectives? If labeling adjectives with `Polarity=Neg` is the best solution, the claim that `Polarity` is inflectional would be too strong. There is also the case of interjections, that should be marked as `Polarity=Neg`, but the negativeness there is lexical. I imagine you do not want to have "no" (in "No, you cannot do it") tagged with `Polarity=Neg` and having the lemma "yes".

Now I ask myself if we should label all negative words in corpora with one of these features or if we should look only to the words that in V1 belong to a `neg` deprel.

**Comment by LarsAhrenberg** [comment]
A feature is basically a specification of a set of words (cross-linguistically). Words with a clause-level negative impact form a natural linguistic class whatever their part-of-speech. So to me, unlike @dan-zeman words such as English _no_ or _nothing_ could well be both `PronType=Neg` and` Polarity=Neg`. This is not saying the same thing twice, as 'Neg' in itself has no independent meaning in the UD framework, but if this is unwanted, a way out would be to reclassify negative pronouns and determiners as  `PronType=Ind|Polarity=Neg`, thus treating negative pronouns and determiners in par with possessives.
