### ISSUE TITLE
Empty nodes syntax in CoNLL-U

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/docs#397]
http://universaldependencies.org/v2/conll-u.html says empty nodes should have ID starting with "E", e.g. E5.1.
http://universaldependencies.org/format.html says empty nodes should have ID without any prefix, e.g. 5.1.
So should we use the "E" prefix or not?

Filtering out empty nodes is easy in both cases (ID =~ /./). Personally, I have very slight preference for the 5.1 syntax.

**Comment by fginter** [comment]
Good catch. I would like to keep the `E` prefix. 
1) it is agreed upon in Prague (the format page is just somehow ends up missing it) 
2) it is trivially grepable 
3) it is less likely to be confused with the token/word notation

**Comment by dan-zeman** [comment]
My impression was that it was not agreed upon _in Prague_ (at least I do not remember it) but then it somehow appeared in the post-Prague write-up, no one objected, then it somehow disappeared again from the final documentation, again without objections (until now) :-)

I am personally undecided – I agree with @fginter's argumentation but still I like the form without `E` more (just a matter of taste). That's why I did not object to either of the shifts. Changing the guideline now, if it happens, may come as a surprise to contributors who already implemented something, but they should be able to fix it easily, and they have to wait for the official validator anyway.

**Comment by jnivre** [comment]
The E-prefix was not agreed in Prague. My preference is definitely to **not** have the E-prefix.

**Comment by fginter** [comment]
Oh, okay. I think "1-3" and "1.3" are unpleasantly similar and mean totally different things, so the E is a safety measure screaming "I am different". But whatever, really, feel free to drop it.

**Comment by ftyers** [comment]
+1 for no E-prefix.

**Comment by fginter** [comment]
Removed now from the docs. If anyone finds it yet somewhere, eradicate. I would have liked to keep it in as a visual clue for people who read the data files and not the docs which come with them, but I don't care enough. :smiley:
