### ISSUE TITLE
clarification about flat

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/docs#400]
In the [documentation page of the `flat` relation](http://universaldependencies.org/u/dep/flat.html) , I don't understand how one should annotate examples 7 and 8?
In _Ludwig van Beethoven_, how _Ludwig_ is connected to _van Beethoven_?
In _Miguel de Cervantes y Saavedra_, how _Miguel_ is connected to the other part of the structure?

**Comment by dan-zeman** [comment]
It is `nmod` (caused by the `case` dependents).

**Comment by mcdm** [comment]
@dan-zeman: I am actually not convinced using nmod is the best analysis ;-) I would use a flat relation. It's unclear what the head is between Ludwig and Beethoven.

**Comment by dan-zeman** [comment]
Depends on language. In English it would be flat because van is not a preposition in English.

**Comment by sebschu** [comment]
@dan-zeman I'd argue that even if part of the name is a preposition in the respective language, names like _Ludwig van Beethoven_ should always be analyzed as `flat`. For example, in German, there also exist names like _Hubertus von Hohenlohe_, which contain the preposition _von_ ('from') but _von Hohenlohe_ has the same distribution as any other last name and therefore it can also be used without a first name. If you then have a sentence like _Von Hohenlohe gewann das Rennen._ ('Von Hohenlohe won the race'), we would have an `nsubj` with a case marker attached to it, which seems  very strange to me and I don't see what advantage we would get from not treating such names as `flat` NPs. Further, it would improve cross-linguistic consistency if analyzed names the same way in all languages instead of treating them in a special way in one (or very few) languages.

**Comment by jnivre** [comment]
This argument makes a lot of sense to me.

**Comment by bguil** [comment]
Agree with @sebschu. I don't see the benefit of annotating syntactic structure inside proper name.
For example in the Sequoia French corpus, we have "Dominique de Villepin" which is a French name, so _de_ should be ADP and "Hermann de Croo" which is a foreign name where _de_ is not preposition... For instance, I don't know the status of the _de_ in @mcdm's name!

**Comment by spyysalo** [comment]
I'm not a great fan of marking structure in *Ludwig van Beethoven* either, but how about *Lord of the Rings*? What would the rule be for when to annotate structure in names and when to mark them with `flat`?

**Comment by arademaker** [comment]
The POS tags will still be propositions and nouns etc, right ?

**Comment by dan-zeman** [comment]
While I tend to agree with @sebschu 's arguments, I'm afraid that a "catastrophe" is unavoidable at the other end of the scale: is there an exact boundary between _Hubertus von Hohenlohe, Ludwig von Bayern, Ludwig Prinz von Bayern, König von Bayern_ etc.?

@arademaker : I strongly believe that _von_ should be `ADP` in German corpora, whether or not it occurs in a name, and regardless the dependency structure. However, it could be `PROPN` or even `X` in English corpora because the English vocabulary does not know such a preposition.

**Comment by jnivre** [comment]
@spyysalo _Lord of the Rings_ is definitely a compositional phrase. This has been discussed and settled long ago. As Dan says, a catastrophe is always looming large in these cases. For example, I have been told that, in "Leonardo da Vinci", "da Vinci" is not a a name in the modern sense, only a disambiguating locative modifier ("from Vinci"), but today I think most people regard "da Vinci" as similar to "van Beethoven". In the end, borderline cases will always be judgment calls.

**Comment by manning** [comment]
I do think it is essential that we at least have clear documentation of such cases, since several of them are quite common. Even if the decisions are only conventions, and ones on which there is not full agreement, I think we need clear guidelines to try to achieve the goals of intra- and inter-treebank consistency.

I don't think the catastrophe argument is proof of anything, since if (in our symbolic UD), we judge grammaticalization to have taken place, then necessarily there is a catastrophe. And we all know that things get grammaticalized.

I've changed the flat docs to say that in foreign languages, such as when these names appear in English, then they should definitely be flat. But it seems that we're hearing from both French and German speakers that they regard the names as (in the 21st century) also grammaticalized in French and German. If that is the analysis we are going with, we should alter the wording of the page a bit more. But, certainly, thinks like "the President of France" should be still treated as compositional.

A closely related issue is the treatment of titles/honorifics like "Ms.". I think that also really needs to be documented, and isn't at present. My understanding of the discussions in Prague was that the decision was to treat the title as part of the flat multi-word construction. I'm not sure I agree with that either (though nor am I sure it is wrong).

And similarly, I think we could only gain by more clearly indicating how to annotate date expressions, measurements, etc., or at least a default way of doing so....

**Comment by amir-zeldes** [comment]
On `Mr.` etc. see also #324 (closed but was never really concluded, and there are a lot of interesting cases and points regarding titles there)
