### ISSUE TITLE
When can empty nodes be used?

### ISSUE THREAD

**Issue by spyysalo** [UniversalDependencies/docs#404]
I proposed an empty node example of the following type for the test suite

> The food is warm and the drink [is] cold

(where *[is]* is the empty node) and @fginter commented

> But this null is not needed because it's not a head of anything. So actually we might want to be paranoid and fail on this one..? 

I don't think this rule (empty nodes must be heads) is clear in the documentation.

We may wish to further clarify the rules on when empty nodes can be used. If hard rules of the type "empty nodes must be heads" are established, we may also want to enforce these in validation.

Comments / feedback very welcome!

**Comment by jnivre** [comment]
Filip is right, and it is clearly stated in the documentation here:http://universaldependencies.org/u/overview/specific-syntax.html#ellipsis

Case 1 says: If the elided element has no overt dependents, we do nothing.

**Comment by martinpopel** [comment]
>  Filip is right, and it is clearly stated in the documentation here:http://universaldependencies.org/u/overview/specific-syntax.html#ellipsis
> Case 1 says: If the elided element has no overt dependents, we do nothing.

This is not the right link because [specific-syntax.html#ellipsis](http://universaldependencies.org/u/overview/specific-syntax.html#ellipsis)
discusses only basic dependencies, not the enhanced ones which can contain empty nodes.
Please correct me (and more importantly the documentation) if I am wrong.

The correct link is [enhanced-syntax.html#ellipsis](http://universaldependencies.org/u/overview/enhanced-syntax.html#ellipsis) which says
> In the enhanced representation, we add special null nodes in clauses **in which a predicate** is elided.

I guess that in UD, copula is not considered a predicate.

Anyway, I would vote for reopening this issue because predicates can be leafs.
So it is still not clear whether empty nodes can be leafs or not.

**Comment by fginter** [comment]
I suggest "a null node must have at least one dependent" be the principle.

**Comment by dan-zeman** [comment]
Agreed with @fginter 's formulation, but I think this is one more candidate where a general CoNLL-U file could optionally allow more than UD released treebanks. I think the check could be optional in the validator, turned on by default.

**Comment by spyysalo** [comment]
OK by me. I can add this to the validator.

**Comment by spyysalo** [comment]
Done a while ago, forgot to close.
