### ISSUE TITLE
Analysis of titles/honorifics with internal structure

### ISSUE THREAD

**Issue by sebschu** [UniversalDependencies/docs#415]
I know we've debated what to do about titles/honorifics already a lot, so sorry for bringing it up again, but I'm not sure how we should analyze NPs with multi-word titles such as the following example:

_Minister of Defense Hazem Shaalan_

I would analyze _Minister of Defense_ as `nmod(Minister, Defense)`, and _Hazem Shaalan_  is clearly a flat NP, but I'm not sure how we should connect these two. I think this example should be analyzed similar to _President Barack Obama_, i.e.,

```
nmod(Minister, Defense)
flat(Minister, Hazem)
flat(Minister, Shaalan)
```

However, if we do this, then we end up with a `flat` constituent that contains an `nmod` and the way I understand `flat`, this shouldn't be allowed. Any thoughts on that?

**Comment by dan-zeman** [comment]
I strongly support `nmod(Minister, Defense)`.

I am less sure about the rest. I admit that I have not foreseen `flat` with embedded non-flat constituent but do we really need to ban it? Maybe this is one of the differences between `flat` and `fixed`. The `flat` analysis essentially just says that we do not see good reasons to make any one of _Minister_, _Hazem_ and _Shaalan_ the syntactic head dominating the other two. Such an argument is not invalidated by inserting _of Defense_ in the middle. So I think it is OK to do `flat(Minister, Hazem); flat(Minister, Shaalan)`.

There is another option, which is (I believe) used in some UD treebanks for this: apposition. We lack a robust and cross-linguistically valid definition of apposition, and especially the borderline between `appos` and `flat`. But my intuition is that by using `appos` we assert that there is a reason to mark one of the parts as the head. So in _Hazem Shaalan, Minister of Defense_, we would use `flat(Hazem, Shaalan); appos(Hazem, Minister)` because the title is pronounced and marked by punctuation as something additional, syntactically not as important as the name.

**Comment by dan-zeman** [comment]
Older related issues: #324, #400.
For `appos`, #180 is also relevant.

**Comment by jnivre** [comment]
I don't think there is any reason to ban other relations inside "flat" structures. In fact, this is precisely why we have the "flat" relation in addition to "fixed". We use "fixed" for fixed MWEs, where nothing can be changed and nothing can be inserted. And we use "flat" for semi-flexible (exocentric) MWEs, which precisely allow its elements to have some internal structure.

I would advise against using "appos" for this type of construction. It is true that some grammatical tradition (including the Swedish one) would use "appos" for "President" in both of these constructions:

President Hollande
Hollande, the president of France

But we had a lengthy discussion earlier and decided to reserve "appos" for the latter type of construction. The only alternative is then "nmod", which is what we recommended for v1, but now that we have a broader "flat" relation (instead of "name"), I think "flat" is better (although I have to admit that it is still "nmod" in UD Swedish).

**Comment by arademaker** [comment]
In the cases above, in what extend the suggestions above apply equally for titles like `President` and `Minister` and ordinary positions and professions, e.g., 'O professor Leitão de Abre' (the professor Leitão de Abreu)? First hint [here](http://bosque.mybluemix.net/query?search=Leit%C3%A3o&db=bosque&case_sensitive=True&hits_per_page=50).

**Comment by dan-zeman** [comment]
@arademaker : Does _professor_ behave syntactically differently in Portuguese from _presidente_ or _ministro_? If they are syntactically equivalent then I believe they should get the same analysis.

**Comment by arademaker** [comment]
The only difference is that they are not capitalized. We have the distinction between some titles (military ones, for example) that can be used as part of the name and general positions/professions that are not part of the name.

BTW, in "The New York city is amazing." the http://corenlp.run/ is giving me `compound(city, York)`. I expect all agree that it would be `nmod(city, New) flat:name(New, York)`, right?  Of course, I know that corenlp is not trainned with UD v2, I am just trying to make sure that I got right the above discussion somehow related.

**Comment by nschneid** [comment]
@arademaker: There are a few ways to spell it: "New York City" (often abbreviated NYC), "the City of New York" (this may be the official name of the city government), "the city of New York" (i.e., disambiguating from the state of New York). For the first two, I think it would be reasonable to include "City" in the named entity. But I don't know what this implies for UD.

**Comment by arademaker** [comment]
Hum , unfortunate example. Please replace New York for any other name of city! :-)

**Comment by amir-zeldes** [comment]
This was discussed already in the issues mentioned by @dan-zeman , but briefly, I think the lack of independent article use in the two parts is what speaks against appos for the normal titles:

```
Hollande, the president of France
=This= man, =the= president of France (2 articles OK, separate NPs in appos)
President Hollande
```
But ungrammatical:

```
* President this man
```

This suggests `President Hollande` is a single NP (or DP in a DP analysis) with internal structure, not two separate NP/DPs.

**Comment by arademaker** [comment]
> This suggests President Hollande is a single NP (or DP in a DP analysis) with internal structure, not two separate NP/DPs.

Perfect! This is the justification for 'nmod' (if not flat:name) in my example too.

**Comment by sebschu** [comment]
Thanks, @dan-zeman and @jnivre! I'm also in favor of using `flat` and I just wanted to make sure that this doesn't go against the guidelines.
