### ISSUE TITLE
Is upos=SYM deprel=punct allowed?

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/docs#421]
[svalidation.html](http://universaldependencies.org/svalidation.html#relation-punct-is-used-for-node-that-is-not-punct) says
"Only nodes tagged PUNCT can be attached using the punct relation."
and this test is not marked as experimental, i.e. all treebanks should pass it.

However, there are several treebanks (RO, KK,...) which use upos=SYM and deprel=punct e.g. for the slash in "km / h" and several other types of constructions.

[SYM definition](http://universaldependencies.org/u/pos/SYM.html) says "Many symbols are or contain special non-alphanumeric characters, similarly to punctuation. What makes them different from punctuation is that they can be substituted by normal words. This involves all currency symbols, e.g. $ 75 is identical to seventy-five dollars."

However, [punct definition](http://universaldependencies.org/u/dep/punct.html) does not explicitly say upos=PUNCT is required (i.e. it does not forbid to use deprel=punct for punctuation symbols which **could** be substituted by normal words).
If we agree on this, I think the sentence from svalidation.html ("Only nodes tagged PUNCT can be attached using the punct relation.") should be added to both upos=PUNCT and deprel=punct definitions (with a few examples).

Another question is what deprel should be used for the slash in various cases (another examples are "2017/1" or "2017/xy" if these are tokenized into three words and/or written with spaces). Yet another example is "and/or":-).

**Comment by dan-zeman** [comment]
Slash is tough and I do not know whether it should be always PUNCT, always SYM, or both, depending on context.

But I think it should not be used with the punct deprel. By using SYM you are saying that it is NOT punctuation. And the "punct" relation is reserved for punctuation.

**Comment by dan-zeman** [comment]
No new posts for more than a year, so I am closing this. I'd say that the outcome is (still) that `PUNCT` <=> `punct`.

**Comment by martinpopel** [comment]
OK, so if this is the outcome, we should first fix the guidelines before closing this issue.
Otherwise, someone else will open a new issue on the same topic.
I don't see any changes in http://universaldependencies.org/u/dep/punct.html
Should I add the rule "upos=PUNCT iff deprel=punct" there?

**Comment by olesar** [comment]
Any emoji as a full stop / question mark / bracket mark? Sometimes they do not fulfill any other (discourse) function.If one labels them as PUNCT, I assume that PUNCT is not a closed class anymore.24.04.2018, 15:30, "Martin Popel" <notifications@github.com>:OK, so if this is the outcome, we should first fix the guidelines before closing this issue.
Otherwise, someone else will open a new issue on the same topic.
I don't see any changes in http://universaldependencies.org/u/dep/punct.html
Should I add the rule "upos=PUNCT iff deprel=punct" there?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Olga Lyashevskaya School of Linguistics, Faculty of Humanities& Linguistic Convergence LabHigher School of Economics, Moscow Dept. of Corpus Linguistics and Linguistic PoeticsVinogradov Institute of the Russian Language
