### ISSUE TITLE
Contributing to UDv2.0 language documentation

### ISSUE THREAD

**Issue by lauma** [UniversalDependencies/docs#423]
What is the proper way to contribute to language documentation for the upcoming version?

Should I wait for the new release? Or I should I continue to change existing documentation and after release the message "This page still pertains to UD version 1." will be removed automatically? What about pages for new or renamed features?

**Comment by jnivre** [comment]
We are working on this and will provide more detailed guidelines as soon as we can (but producing the data has priority right now). In the meantime, you can start changing the existing documentation. All the static pages can be edited as usual, and you can also create new pages for new or renamed features. But the overview tables will have to be generated by the documentation team later.

**Comment by ermanh** [comment]
Since I've been updating the Chinese pages to v2 just recently, according to @dan-zeman you can remove the yellow v1 warning banner and change it to the green v2 banner by adding `udver: '2'` in the header at the top of the page. If I understood correctly, and to clarify, the v1 documentation is currently frozen and cannot be modified, the ones you see now on the UD main pages (that have yellow banners) are technically placeholder copies waiting to be updated to v2(?), whereas the [archived v1 documentation](http://universaldependencies.org/docsv1/index.html) have red banners instead.

**Comment by dan-zeman** [comment]
@ermanh is right. The only issue here is that people writing v2 documentation would benefit if we managed to automatically modify the tables of labels, generate or rename templates for features etc. But as  Joakim said, we are unfortunately unable to attend to this right now.

**Comment by lauma** [comment]
It is good to know that I will not break the version 1 documentation by contributing now. Thanks.

I got the understanding I needed, feel free to close this issue or leave it open until till the documentation force has time for updating documentation or whatever is appropriate.

**Comment by jnivre** [comment]
The v1 documentation has been archived here: http://universaldependencies.org/docsv1/index.html
