### ISSUE TITLE
NumType for numerals with decimal point (2.3)

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/docs#425]
Which NumType tag should be applied to numerals such as 3.14? 
If they are written in digits, we tokenize them as one token but the documentation seems to miss this case.
In some languages, they behave like normal Card's (and in oral speech this would correspond to the coordination of Card and NP like "two and a half"), but I am not aware of the situation in general.

**Comment by dan-zeman** [comment]
I don't think much thought has been given to this case (at least not on my part) but the general idea is that they are `NumType=Card` as well.

**Comment by msklvsk** [comment]
For the next release of Ukrainian we went unorthodox and now split decimals in 3 tokens because, well, let’s admit, they _are_ separate tokens and the sole existence of this issue proves it.

![image](https://user-images.githubusercontent.com/473012/28465165-7c74189c-6e30-11e7-8cd8-03ac43dcb3fd.png)
(slide 13 of [Tutorial on Universal Dependencies](http://universaldependencies.org/eacl17tutorial/morphology.pdf))

We also split time and scores (58:59). This way we keep the concept of a numeral clean, and the analysis reflects the natural way we read such text: as two separate integers.
