### ISSUE TITLE
How do I map these Chinese PoS tag to universalde dependencies tag

### ISSUE THREAD

**Issue by eromoe** [UniversalDependencies/docs#426]
Hi,

I am trying to map Chinese PoS tag (Modern Chinese corpus processing specification by Peking University, Chinese Doc here: http://icl.pku.edu.cn/icl_groups/corpus/spec.htm . ) to universalde PoS tag

But I found there are some tags can't not map:

- h/前接成分  (some post-decorator of word, not adj, maybe either meaningless or meaningful like `non-` in `non-profit`)
- k/后接成分 (some tail-decorator of word, not adj, may have meaning or not)
- t/时间词 (date, time, today, 2016年12月，6:33)
- i/习语 (idiom, may be adj, adv, v, n)
- j/简称 (abbreviation, words for short,  may be adj, adv, v, n)
- o/拟声词 (words mimicking sound of objects)

Any idea?

**Comment by dan-zeman** [comment]
The last one seems easy—`o` should be `INTJ` in UD.

In general, it is not guaranteed that each tag in a non-UD tagset will have a clear counterpart in UD. A full conversion often means you have to re-tag words, considering not only their original tag, but also lemma, word form, possibly even syntactic context. Thus for abbreviation you should decide whether the word is `ADJ`, `ADV`, `VERB` or `NOUN`, and then add the UD feature `Abbr=Yes`. If this is not possible for whatever reason, I would probably go for the `X` tag and the feature `Abbr=Yes`.

Words like _today_ are nouns or adverbs in various languages, depending on their behavior (when compared to the behavior of other nouns and adverbs in the language). Numeric date and time expressions are not yet very well standardized in UD, _6:33_ will often end up as `NUM`, entire dates are usually split into multiple words.

As for your post/tail-decorators, I am not sure whether they should be independent words with their own UPOS tags at all. The other option would be to say that they are just bound morphemes, contributing only a feature to the main word. (For instance, _non-_ in _non-profit_ could be viewed as contributing the feature `Polarity=Neg`.)

**Comment by ermanh** [comment]
I second @dan-zeman on everything except for the `o` category because it's actually referring to "onomatopoeia", which can have different parts of speech depending on its usage in context. In Chinese they often function as an adverb describing the (physical or metaphorical) sound of the action conveyed by the verb, in which case ADV would seem more appropriate I think.

The "decorators" are more or less equivalent to affixes (mostly on nouns), or at least bound morphemes. The Google data currently in the UD repository actually does separate (at least some of) these into individual tokens and use `PART` for the UPOS tag and `case:pref` and `case:suff` for the syntactic relations. (I'm personally not comfortable with the labels (or tag) themselves, even if they should be tokenized apart. The google data also uses `case:aspect` on aspect markers, by the way, which should have a home in UDv2 under `aux` now.)

To give a concrete example, in the case of the suffixes (the `k` category), they are actually usually nouns themselves (etymologically if not also synchronically). For example, 機 _ji_ 'machine/device' (which I believe usually cannot stand alone as a word) may be seen in words like 手機 _shouji_ 'mobile phone (lit. hand device)', 電視機 _dianshiji_ 'television set (lit. electric vision machine)', and 吸塵機 _xichenji_ 'vacuum cleaner (lit. suck dust machine)' -- but these seem to be cases of lexical formation rather than syntactic formation.

**Comment by kanayamah** [comment]
For Japanese, we use ``NOUN`` for ``k`` category (接尾辞/suffix in Japanese).
http://universaldependencies.org/ja/overview/morphology.html
It is because 機 of 吸塵機 is a head of a noun phrase both in terms of syntax and semantics, and we want to reduce impacts of changes in tokenization (tokenizer may split  吸塵機 into  吸塵 and 機 or may not).

**Comment by Oneplus** [comment]
Hi @ermanh, I went through the UD_Chinese-CFL dataset and didn't found an example of the suffix (`k` category). I believe it's because UD_Chinese-CFL follows the CTB segmentation standard. Well, for other standards, like that for CDT and sinica dataset, suffix (or decorator) is treated as a single word. So what's the UD suggestion on their POS tags? It seems UD guideline didn't document this.

I tend to NOUN because such suffix is not a closed class of words. What's more, @kanayamah gave their solution on the Japanese dataset, So NOUN can be a consistent solution for both Japanese and Chinese.

If NOUN is the solution, shall we document it in the guideline?

**Comment by ermanh** [comment]
@Oneplus, yes, UD_Chinese-CFL currently follows the [CTB segmentation guidelines](http://repository.upenn.edu/cgi/viewcontent.cgi?article=1038&context=ircs_reports), which does not seem to recommend tokenizing the so-called "suffix" (k) or "prefix" (h) categories apart in many cases.  As for the Chinese UD guidelines, tokenization is described [here](http://universaldependencies.org/zh/overview/tokenization.html) between the different treebanks and it doesn't currently specify which is the standard. 

The [UD guidelines](http://universaldependencies.org/u/overview/tokenization.html) take a lexicalist stance on tokenization, but whether the Chinese compounds in question are a morphological or syntactic phenomenon is probably exactly the point of contention here I think (other considerations aside; we took the morphological view in this case). 

There were definitely different considerations within our group (paging @kimgerdes, @wongtaksum, @XinyingChen). I didn't have enough time to scour and look deeper into the theoretical literature on Chinese wordhood, but San Duanmu seems to be one of the linguists specializing in this topic. I'll leave it at that -- and to you guys to discuss further specifics.
