### ISSUE TITLE
Why §, %, © are SYM but not NOUN?

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#429]
[SYM](http://universaldependencies.org/u/pos/SYM.html) page says to mark _§_ as `SYM`. But isn’t it a loss of information?

You read “§ 8” same as “section eight”, section symbol functions as noun and you even draw nummod(§, 8). Moreover, you feel something is wrong when language-specific validation scripts have to account for `SYM` in nominal contexts. Also, English [marks](http://bionlp-www.utu.fi/dep_search/query?search=%22%23%22&db=UD_English-dev&case_sensitive=True&hits_per_page=10) _#_ as `NOUN`.

Is it a good idea to annotate those symbols as nouns and `Variant=Sym`?

**Comment by dan-zeman** [comment]
I think that the English annotation of _#_ is a bug according to the current guidelines. Getting rid of `SYM` would have to be a major change of the guidelines, i.e., UD v3.

Personally, I am indifferent about this. I agree that treating _§_ as a `NOUN` would have some advantages because you could say that only `NOUN` is allowed in certain constructions. But the current approach has its own advantages, namely that you can say that only `SYM` or `PUNCT` is allowed if the token consists solely of punctuation characters.

**Comment by msklvsk** [comment]
Even those three asterisks between sections…

\* * *

…are better be treated as `PUNCT` instead of `SYM`. It seems like everything that can be read out loud can have a real POS — the POS of the word you pronounce, and `PUNCT` covers everything else. 
Still not convinced `SYM` is a thing.
