### ISSUE TITLE
Guidelines for language-specific documentation

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#43]
We need a page summarizing what a language-specific description should contain as a minimum. @jnivre suggested the following:

For the language-specific entry pages, I am not sure how to structure it, but I think the following info should be compulsory:

1. A description of how words and tokens are defined (including whether range tokens are used, etc.)
2. A description of the morphological annotation, including the use of universal tags, universal features used, and language-specific features if any.
3. A description of the syntactic annotation, including the use of universal dependencies, and language-specific relations if any.
4. A list of known discrepancies with the universal guidelines (Ryan’s language-specific diff).

What else do we need?

Joakim

**Comment by jnivre** [comment]
We still don't have any general instructions for the language-specific documentation, right? I think it would be very useful to add this in preparation for the second release, where the goal is to have complete documentation for the first ten languages. I could have a first go at drafting this.

**Comment by spyysalo** [comment]
I'm afraid that's right, there are still no general instructions for this.
It would be excellent if you could start a draft.

**Comment by jnivre** [comment]
Here is a proposal for guidelines for the language-specific documentation, organized by sections. I have tried to make the Swedish documentation conform to these guidelines as an example.

overview/introduction.html
Short description of the treebank, size, types of texts, annotation/conversion process, etc.
Optional subheadings: "Acknowledgments", "References"

overview/tokenization.html
Short description of the principles for word segmentation with references to additional documentation and/or standard tokenizers as appropriate. The description must state whether the treebank contains multiword tokens and, if so, describe the major cases in a separate subsection (see the Czech documentation for an example of this).
Optional subheadings: "Multiword tokens", "References"

overview/morphology.html
Short description of the use of universal tags and features making clear whether language-specific features have been added (but without describing them). Short description of language-specific tags if relevant.
Optional subheading: "References"

pos/index.html
List of universal tags with unused tags crossed out (see Finnish for an example). Each tag is linked to a subpage with a language-specific definition and examples. Minimally, this should be a restatement of the universal definition with at least one language-specific example added. Preferably, it should add more information, for example, about inflectional categories of a part of speech in the specific language (see Swedish ADJ documentation for an example).

feat/index.html
List of morphological features with unused universal features crossed out and language-specific features preceded by a + (see Finnish for an example). Each features is linked to a subpage with a language-specific definition and examples. Minimally, this should be a restatement of the universal definition with at least one language-specific example added. It should also make clear which values are used for a given feature, since this may vary across languages (see Swedish Case documentation for an example).

overview/syntax.html
Short description of the use of universal dependency relations making clear whether language-specific subtypes have been added (but without describing them).

overview/specific-syntax.html
Optional description of specific constructions (see Finnish for examples). Ideally, this should be structured in the same way as the universal documentation, but since the latter is not very developed it seems hard to enforce this. If possible, use the main headings "Elements of a clause", "Elements of a nominal", "Adjectival and adverbial constructions", and add additional headings as needed (for example, "Coordination", "Compounding", etc.) Use any subheadings that are appropriate.

dep/index.html
List of universal dependencies with unused relations crossed out and language-specific subtypes indented below their supertype (see Finnish for an example). Each relation is linked to a subpage with a language-specific definition and examples. Minimally, this should be a restatement of the universal definition with at least one language-specific example added.

**Comment by jnivre** [comment]
I forgot to say that known discrepancies from the guidelines should be mentioned under the most relevant heading.

**Comment by jnivre** [comment]
One more thing I forgot: The owners of each language should also make sure that their language-specific features and relations are added to:
http://universaldependencies.github.io/docs/ext-feat-index.html
http://universaldependencies.github.io/docs/ext-dep-index.html

Ideally, this should happen automagically given the language-specific documentation to ensure consistency.

**Comment by dan-zeman** [comment]
Great, thanks for the draft! I would also suggest that these guidelines adopt the way how treebank-specific diffs are described (issue #116 proposal by @manning).
