### ISSUE TITLE
Double Case in Kurmanji

### ISSUE THREAD

**Issue by MemduhG** [UniversalDependencies/docs#430]
For things like _Pirtuka min a sor_ "my red book", book will take one synthetic and and one analytic case. _Pirtuk_ is "book", and the inflection -a is the construct/genitive case showing it belongs to _min_, "me". When the construct is extended with some other qualifier, the same phoneme is used synthetically (postpositionally? We have not decided on what exactly the POS for this will be either). Would it make sense to call _a_ in this sentence a postposition, and would the case relation it and _pirtuk_ be acceptable, despite the strange situation of having two of the same case?

**Comment by jnivre** [comment]
It sounds fine to me to treat both as case, one morphological one syntactic. It reminds me of the double definite marking in Scandinavian languages. Swedish nouns inflect for definiteness:

bok = book-indef
bok-en = book-def

But when the noun is preceded by an adjectival modifier, the definite marker is also realised as a separate article:

den röda bok-en = the red book-def

We use the "det" relation for "den" and "Definite=Def" for "boken". It sounds to me like you could use the "case" relation for (the analytic) "a" and "Case=Gen" for "pirtuka". Is that what you had in mind?

**Comment by dan-zeman** [comment]
In general, I don't see anything wrong in having morphological case marking + adposition, or 2+ adpositions on one noun. (Two morphological cases would be more difficult to annotate.) Do I understand correctly that the first _-a_ in this example links _pirtuk-_ and _min_, while the second _a_ links _pirtuka min_ and _sor_? Then we cannot express the different scope of the two case markings, but otherwise I think you can use them together. So is it correct to assume that your analysis would look something like this:

    1  Pirtuka  _  NOUN  _  Case=Gen              0  root
    2  min      _  PRON  _  Number=Sing|Person=1  1  nmod
    3  a        _  ADP   _  _                     1  case
    4  sor      _  ADJ   _  _                     1  amod

?
