### ISSUE TITLE
Multi-word tokens with spaces

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#431]
UD v2 guidelines allow "words with spaces" in **exceptional,** approved cases. Currently, "approved" means that the data provider simply provides a regular expression that describes valid cases in their data, and all such cases then pass validation.

While that practice itself seems to me a bit too permissive, there is one special class that in particular does not seem to make any sense: using spaces inside multi-word tokens. Even more so if the multi-word token is actually split _at the space_. If we split it to multiple words anyway, why would we call it a token at the lower level?

Yet such a thing occurs in UD_Kazakh 2.0. Grep for

    \d+-\d+\t\w+ \w+

and you get multiple examples, e.g.

    9-10	дұрыс шығар	_	_	_	_	_	_	_	SpaceAfter=No
    9	дұрыс	дұрыс	ADJ	adj	_	2	parataxis	_	_
    10	шығар	шығар	PART	mod	_	9	discourse	_	_
    11	,	,	PUNCT	cm	_	9	punct	_	_
    12	өзінше	өз	PRON	prn	Number[psor]=Plur,Sing|Person[psor]=3|PronType=Ref	13	advmod	_	_
    13-14	жөн шығар	_	_	_	_	_	_	_	SpaceAfter=No
    13	жөн	жөн	ADJ	adj	_	2	parataxis	_	_
    14	шығар	шығар	PART	mod	_	13	discourse	_	_

Is it a mistake or is there something I am missing?

**Comment by jnivre** [comment]
I agree. This must be a mistake, right? @ftyers

**Comment by ftyers** [comment]
Short answer: Yes, this is probably a sub-optimal conversion and should be fixed in UDv2.1... 

Long answer: the tokenisation in the treebank is based on the tokenisation provided by the Apertium morphological analyser. This groups certain "clitic" items together with the preceding word regardless of if there is a space or not --- we're not big on space-based tokenisation :)

The list (tags from Apertium, in UD these would all get `PART`):

```
+шы<emph>:>ш{I} # ;
+ма<qst>:> {M}{A} # ;
+мекен<qst>: {M}екен # ;
+ау<mod_emo>:-ау # ;
+ай<mod_emo>:-ай # ;
+ғой<mod_ass>: {G}ой # ;
+-ақ<postadv>:-ақ # ; 
+ғана<postadv>: {G}ана # ; 
+да<cnjcoo>: {D}{A} # ;
+да<postadv>: {D}{A} # ;
+шығар<mod>: шығар # ; 
```

These clitics form a natural group, and so for the purposes of processing (on our end) we'd like to treat them the same. Unfortunately they have quite diverse phonology and orthography (some are written with a space, although they assimilate to the previous word, some are written without a space, and some are written with a hyphen). For example:

* {G}ой: гой, ғой, кой, қой, 
* ш{I}: ші, шы
* {D}{A}: да, де, та, те
* {M}{A}: ма, ме, ба, бе, па, пе

However, it shouldn't be hard to modify the conversion scripts to get rid of the "multiword" in the case of _шығар_ if it is required by the guidelines.

@jonorthwash anything to add ?

**Comment by jonorthwash** [comment]
Everything @ftyers said is right (except the word "assimilate", at least in relation to `{M}`).  In principle, it should be trivial to treat the ones with spaces as entirely separate words for UD purposes.

**Comment by dan-zeman** [comment]
It seems that the bug has been fixed, so I am closing the issue.
