### ISSUE TITLE
Annotation of "car" in French

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#432]
I noticed that "car" is consistently treated as a subordinating conjunction (heading an adverbial clause) in French-ParTUT, whereas in the other French treebanks it is (almost) consistently treated as a coordinating conjunction, which I believe is the traditional analysis.

**Comment by msang** [comment]
@jnivre you're right. This is a mistake we must have missed (even in the original ParTUT) just because the Italian counterpart "poiché" is an actual subordinating conjunction. 
I guess it's too late to fix the error for the current release, but it will be definitely fixed for the next one. 
Thank you very much for pointing this out.

**Comment by jnivre** [comment]
No problem. French also has "puisque" and "parce que", which are both subordinating.

**Comment by dan-zeman** [comment]
@msang : Has the bug been fixed and can we close the issue now?

**Comment by msang** [comment]
Yes, definitely. Thank you @dan-zeman for the reminder!
