### ISSUE TITLE
Duplicate paragraphs in UDv2

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/docs#445]
In UD_English train data, 14 sentences are repeated exactly the same three times, IDs:
```
email-enronsent42_01-0022 ... email-enronsent42_01-0035
email-enronsent42_01-0037 ... email-enronsent42_01-0050
email-enronsent42_01-0057 ... email-enronsent42_01-0070
```
In total there are 425 sentences occurring more than once - some of those are OK ("Thanks."), but there are many long sentences.

In UD_German train data, there are 302 sentences occurring more than once, most of them too long to be considered random/natural repetitions.
For example, there are 13 sentences repeated in `train-s4092 ... train-s4104` and `train-s5635 ... train-s5647`.

Such duplication can ruin n-fold cross training/validation and should be avoided in the next release.

**Comment by dan-zeman** [comment]
German fixed in https://github.com/UniversalDependencies/UD_German/commit/97592f4894f342cd0d5bc22de26e1515f6cc4784 (dev branch). I have been thinking that duplicates have already been attended to in German (long ago by @wbwseeker) but it turns out that the first round was only about dev vs. test duplicates, which was arguably much more severe.

**Comment by dan-zeman** [comment]
Overlap test before release 2.4 did not report the English duplicates so I'm assuming it has been fixed.
