### ISSUE TITLE
Complete list of planned languages abaa 

### ISSUE THREAD

**Issue by dehouck** [UniversalDependencies/docs#451]
Dear All,

I am more and more willing to participate in some annotation work the UD project but I am wondering about something.
Do we have an idea of what languages are people actually working on?

Of course there is the home page list, but in a thread someone mentioned examples from the Armenian part of the PROIEL project. Do we know if someone is working on Armenian currently?

More generally, do we know if anyone is working on any language not listed on the main page? (Georgian, Kalaallisut...)

Also, are there any arguments in favour of making smaller datasets for more languages or bigger datasets for fewer languages?

Thank you

Mathieu

**Comment by dan-zeman** [comment]
In general we don't. Sometimes we learn about work on a new language at the moment the data is ready. Sometimes we know for years someone is interested in working, there is a repository for the language (and an entry on the UD title page) but nothing visible happens there.

More specifically, we know there is work going on in Armenian and I suppose we may get some data for the 2.1 release. But because of the more urgent agenda I have not gotten to creating the Armenian repository yet.

**Comment by jnivre** [comment]
Thanks for your willingness to contribute. In general, I would say we want both more languages and more data, but I actually think that the most important concern for the near future will be to improve the quality and consistency of the languages and data we already have, which also implies working out more detailed guidelines both at the universal and at the language-specific level.

However, as Dan hinted, right now we are very busy with the ongoing events, in particular the CoNLL shared task and the upcoming workshop, so it may take a month or two before we can take a real initiative in this direction.

**Comment by dehouck** [comment]
Thanks for those quick answers.

I understand the shared task must be time consuming.

Then I'll get myself more familiar with the annotation scheme and guidelines not to have to refer to them all the time and get in touch with some language specific team to see how I can help.
