### ISSUE TITLE
Vocative as root

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/docs#459]
Often, a complete utterance can consist of a vocative by itself. Currently, validation enforces `root` as the only possible root label, so we cannot label cases like these as vocative:

```
1	Mike	Mike	PROPN	NNP	_	0	root	_	_
2	!	!	PUNCT	.	_	1	punct	_	_
```

Possible solutions to this include:
  * Allow `vocative` as a root label (seems appropriate but breaks the unique root label assumption)
  * Subtype root as `root:vocative` (keeps root label independent, but uses a subtype which is also an independent label in itself)

**Comment by dan-zeman** [comment]
One thing that comes to mind: `vocative` is a label for a dependency relation, not for a node. It is the relation between the NP denoting the addressee, and the (head of the) utterance directed at the addressee. If one of the two members of the relation is omitted (here the utterance is missing), it is not so surprising that the relation disappears, too.

We have it elsewhere in UD: if a node is promoted because its hypothetical parent is elided, the relation between the node and the parent disappears, and the relation between the missing parent and grandparent remains (and holds now between the grandparent and the promoted grandchild).

**Comment by martinpopel** [comment]
If we allow `root:vocative`, it would be logical to allow all other labels for fragmentary answers in dialogues. So e.g. "Mike." could be `root:nsubj` if the question was "Who did it?" and `root:obj` if "Who did you meet?" and `root:obl` if "For whom the bell tolls?" etc. I am not sure if we want to introduce so many labels. UD currently ignores cross-sentence relations and (as noted by @dan-zeman above) most cases of ellipsis except for gapping in enhanced deps. Solving this properly and systematically would be more difficult than just introducing a few labels like `root:vocative`.

**Comment by nschneid** [comment]
Would it at least be worth marking the utterance as fragmentary, rather than a complete sentence? Of course, this raises issues of defining what counts as a complete sentence, but there are clear examples of sentences that are typical of dialogue or similarly concise genres, missing "normal" syntactic elements because they can be recovered from conversational context.

**Comment by amir-zeldes** [comment]
I understand the argument about promotion and the analogy to `root:obj` etc., but I'm not sure it's exactly the same: a vocative is not really the same as the subject of a verb. Vocatives can be used anywhere, in combination with anything - they are not really arguments of any head. If I were to see a fragmentary object like 'Mike' labeled `obj`, I'd ask 'obj of what?'. But for vocative I feel like this question doesn't come up. If I say 'Mike!', it's not really in relation to any predicate.

Even though we conventionally attach vocatives to what is otherwise the root of the clause, they are almost like separate utterances or speech acts. In imperatives it seems tempting to think of them as similar to the null subject, but they can appear next to declaratives like this:

`John, I need a beer!`

But the real issue I have is simply being able to find vocatives in a corpus. Vocatives without an adjacent predication are very common in my data, so searching for the `vocative` label misses a large part of the desired results.

**Comment by dan-zeman** [comment]
I assume `Case=Voc` is not suitable because the vocative is not marked morphologically in Coptic, right?

Then I would just annotate it as extra information in MISC.

**Comment by amir-zeldes** [comment]
That's right, we don't have any other cases, so it would be strange. If this can't be harmonized with one of the initiatives regarding clause types/subtyping of root, then I agree that MISC looks like the only option. 

Because this is an issue that is relevant to essentially any language, it would be good to get input from other people's experiences with vocatives, and then maybe we can make a global recommendation on how to handle this (it would be great to have consistency, since vocative is actually rather comparable across languages).

**Comment by dan-zeman** [comment]
I could report on experience from Czech but it's not going to help you :) vocative is morphologically distinct and we use `Case=Voc`. I have worked with a number of other languages but have not yet faced the need to search for all vocatives. (Arguably, there is a number of other phenomena that one may want to search for and UD annotation will not reveal it. That applies to ellipsis in general - something I and @Kira-D have been trying to search for, and found it very difficult. There will always be something that UD cannot capture.)

Let's see what other people think.

**Comment by dan-zeman** [comment]
Is there anything that needs more discussion in this issue or can we close it?
