### ISSUE TITLE
Subordinating adverbs/particles/conjunctions in Chinese

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#460]
https://github.com/slavpetrov/parallel-treebanks/issues/30 points out issues that should be resolved in UD_Chinese and UD_Chinese-PUD. Certain words, attached to verbs, and tagged either as adverbs or as particles, have actually a subordinating function; following the guidelines proposed by @ermanh and colleagues, these words should be tagged `SCONJ` and attached as `mark`.

**Comment by dan-zeman** [comment]
Fixed in UD_Chinese-GSD and UD_Chinese-GSDSimp.

**Comment by stranak** [comment]
At least some of this looks wrong to me. I see 所 in position where I am relatively sure it is a passive marker (id = 'zh-gsd-dev.s35-5‘) or 也 in places where it really is a regular adverb „also“ ( like id = 'zh-gsd-dev.s1-17‘), or actually all the occurrences of 都 „all“ … I don’t think these should be marked as `SCONJ`.

On the other hand there are words I would consider subordinating conjunctions, but are never `SCONJ`: 因為 „because“, 由於 „due to“, 雖然 „even though“, 如果 „if“, … all are `ADP`

**Comment by AngledLuffa** [comment]
Are you able to put together some analysis of some of these issues, or open a couple more github issues explaining the problems?

**Comment by stranak** [comment]
I looked at the definition https://universaldependencies.org/zh/pos/SCONJ.html and it says: 
> In paired clauses where both clauses are marked by a conjunctive word and the first is subordinate to the second, we treat the conjunctive word in the first clause as SCONJ, whereas the one in the second, main clause as an adverb ([ADV](https://universaldependencies.org/zh/pos/ADV.html)) (e.g., 雖然/SCONJ… 可是/ADV… / suīrán… kěshì… “Although… however…”).

But actually the very first example: 
> 雖然/SCONJ

never happens in GSD, all occurrences are annotated as ADP. All the examples given in that page are: http://hdl.handle.net/11346/PMLTQ-YZRY 

I will do my best to prepare more thorough analysis.
