### ISSUE TITLE
Post-positioned cardinal NUMs acting as ordinal (e.g. “section 3”)

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#466]
In cases like _article 50_ or _Die Hard 3_, the numeral doesn't actually indicate the quantity of a nominal, it rather shows it's order (_the fifth article_, _the third Die Hard movie_).  It feels weird to mix these concepts and use `nummod` here, but many treebanks do.

Can we consider a different (and unified) solution?

**Comment by dan-zeman** [comment]
Agreed that this is not quantity and that we should try to find a better annotation in a future version of the guidelines.

I would not mix it with ordinals either. The ordinal meaning may be there but it is not guaranteed and syntactically it is different, too. Article 50 may turn out to be the fifty-first article if there is article 49A. It is rather something like an entity identifier. I think _article 50_ should receive the same analysis as _Windows 95_ (where there really weren't 94 previous versions).

**Comment by amir-zeldes** [comment]
I think Windows 95 is similar to a left-headed compound (i.e. it's something like the "1995 Windows", a Windows characterized by 95. Maybe similar to Windows Enterprise (the Enterprise kind of Windows).

**Comment by nschneid** [comment]
I guess the ordinal number of version number (*Firefox 54.0*) is more of a modifier than a head, but it seems like a subconstruction of proper names. So I'd be fine with `flat`.

**Comment by sylvainkahane** [comment]
I think that `flat` should be used only when what is the head is unclear. This is the case for _John Smith_, which commutes with both _John_ and _Smith_ (although for many languages it is quite clear what is the head in a construction N N and `flat` could be replaced by another relation).

I suppose that_Firefox 54.0_ can commute with _Firefox_ but not _54.0_, so  _Firefox_ must be the head (at least it will be like that in French). I think `nmod` is quite appropriate here because  _54.0_ acts as a modifier and can be replaced by nouns, as in _Windows Enterprise_ or _Example B_.

**Comment by nschneid** [comment]
In the English corpus there's a sentence mentioning "Adobe Acrobat 3.0" which uses `nummod` and "Adobe Acrobat Reader 4.0" which uses `compound(4.0, Reader)`.

**Comment by sebschu** [comment]
I agree with @sylvainkahane's argument about the headedness, but I'm not so sure about the relation. Most of our uses of `nmod` mark relations between full NPs that can stand on their own and this isn't really true for _Enterprise_ in _Windows Enterprise_ or _B_ in _Example B_. So I'd use `compound` here but with the first noun being the head, i.e., `compound(article, 50)` or `compound(Reader, 4.0)`.
