### ISSUE TITLE
Quoted sentences as modifiers

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#468]
How do we annotate such cases?

_He’s pretty much an “I love American food, good drinks on occasion, laid back” kind of guy._

This can also appear in formal texts when referencing nonnominal titles.

**Comment by sylvainkahane** [comment]
It is a very important question. According to the current guide it should be `parataxis`. But is clear that `parataxis`covers too many different constructions and we have already decided for Spoken French to split this relation into 6 different subrelations (see http://universaldependencies.org/fr/dep/index.html).

The case you mention is even more problematic, even it is quite usual in spoken language (I guess for every languages) and we call this a graft, according to a study of Deulofeu (1990). See how we managed with such constructions in our previous treebank of Spoken French: https://kahanedotfr.files.wordpress.com/2017/06/oral-uppsala2010.pdf.

For the conversion of our treebank in UD, we have not decided what to do because grafts can occupy different positions. One solution would be to give the relation `parataxis:graft` to any graft whatever the syntactic position it occupies. Another solution would be to give it the relation according to the syntactic position it occupies. In your example it coud be `amod:graft` because the graft commutes with an adjectival modifier.

Note also that the direct discourse (= reported speech) can also be considered as a (lexicalized) case of graft. Currently we decided to use the relation `parataxis:obj` but it would also be possible to analyze it with a relation `obj:graft` or `obj:whatever you want`.

**Comment by msklvsk** [comment]
Thanks, Sylvain. We now finally know the proper term for it: a graft. In brat, we mark graft as a property of its head (to avoid multiplying :specific relations), and now wait for better times when there's an official UD inventory for it.
![image](https://user-images.githubusercontent.com/473012/28467327-3e301e52-6e38-11e7-9015-9364e497e347.png)

**Comment by sylvainkahane** [comment]
Thanks Bohdan. I agree with you that the fact to be a graft id a property of the phrase itself and not of the relation between the phrase and its governor. So ok to indicate this in the description of the head of the phrase.

But the question of the relation between the graft and its governor remains. Here I have a general problem with UD. In many cases in UD, the choice of the relation is determined by the nature of the dependent (`nsubj` vs `csubj`, `obj ` vs `ccomp`, `amod` vs `nmod` vs `acl`, etc.). Following the current guide,  I guess that a graft must be `parataxis` because it is a clause/sentence "without any explicit coordination, subordination, or argument relation with the head word". But in your example, the graft is produced in the place of an adjective, so I would like to use the relation `amod`:

> amod(kind,love) and love labeled as graft

 Do we all accept to use `amod` for a graft occupying the position of an adjective?

Another example: _I bought uh I think it is called a dowel_

> obj(bought,think) and think labeled as graft

**Comment by dan-zeman** [comment]
I would not use `parataxis` when the graft occupies the position of an adjective. (In general, I would avoid `parataxis` whenever possible.) I would use either `amod`, or `acl` (because it is a clause; although obviously this is also not the typical case of an `acl`).

As for _I bought uh I think it is called a dowel_: Although one could treat it analogically to the previous example and make "I think it is called a dowel" a graft object (or graft complement) of "bought", this looks to me more like two separate clauses with elided object in the first one. So, actually, even if I just said that I don't like `parataxis`, this example seems to be an example of one.

**Comment by sylvainkahane** [comment]
We even have examples of clear grafts in the subject position in our corpus of Spoken French:

```
vous avez dit que euh disons ma carrière pour simplifier témoigne de ma bonne conduite
'you said that erm let’s say my career to simplify testifies to my good behavior'
```
Note that even if the head of the graft is a verb, the graft works as a nominal phrase and I think that `nsubj`is the best choice: `nsubj(témoigne,disons)` = `nsubj(testifies,say)`

More problematic are examples introduced by a preposition:

```
vous t~ vous suivez la ligne du tram qui passe vers la je crois que c'est une ancienne caserne je crois
'you t~ you follow the tram line which goes toward the I think it used to be barracks I think'
```

Here I propose:

```
obl(passe,pense) = obl(goes,think)
case(pense,vers) = case(think,towards)
```

Of course the link `case(pense,vers)` is a bit strange, but it is the general problem of the treatment of adpositions as dependents.

**Comment by msklvsk** [comment]
I would use `amod`, not `acl` because there's no `ncl`, only `nmod`: _my favorite episode of Better call Saul_. In general, I would use the same relations as if a graft was a single word of a usual POS for its context and export `Graft=Yes` in the MISC field. The only info left out would be that graft's dependents are not “inside” of it, but _it is a general property of dependency trees that phrase modification is structurally indistinguishable from head modification._

**Comment by arademaker** [comment]
In Portuguese, we have cases where one or more sentences are quoted, a discourse being reproduced such as:

> Em seus mais de dez anos de Estadão, afirma ter trabalhado “brutalmente, com uma fecundidade e uma produtividade muito grandes. Só pensava no jornal. Deixei de fazer política, de fazer tudo, para fazer só o jornal”.

As we can see, we have 3 sentences inside the quotes. How to deal with such cases? If we choose to split them into 3 sentences, how to deal with the unbalanced quote symbols?

**Comment by dan-zeman** [comment]
@arademaker : It's not specific to Portuguese, it occurs in other languages too. I think the common approach is to split on sentence boundary inside the quoted string. Each quotation mark stays in its own sentence and is attached to the head of the sentence (if the entire sentence lies between the quotes) or to the head of the quoted part (if there is just one such head) or to the head closest to the quotation mark (in order to prevent non-projective edges).

**Comment by amir-zeldes** [comment]
I agree with @dan-zeman - this is almost exactly what we decided for the GUM corpus which we build at Georgetown, except we somewhat arbitrarily decided to do it only for > 2 reported sentences. If it's just 2 we used parataxis to convey that both were subordinate to the matrix verb, but I have no really good argument to defend the number (it was just fairly common at 2, and rare for 3+).

**Comment by arademaker** [comment]
Thank you for the suggestions. We are thinking about using the misc field to somehow link the open/close quotation marks that end up in different sentences.
