### ISSUE TITLE
POS tagging of "at all"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#472]
I've noticed that in the UD English treebank, both words of "at all" are tagged as `ADV` (and `RB`). This seems counterintuitive, and actually doesn't match the [PTB guidelines](https://catalog.ldc.upenn.edu/docs/LDC99T42/tagguid1.pdf), which have it as `IN` and `DET`. Is this something we should fix?

**Comment by dan-zeman** [comment]
I suppose it should be fixed but the English teams have to negotiate here.
@sebschu @amir-zeldes @manning

**Comment by amir-zeldes** [comment]
I'm happy analyzing this superficially like a PP (so, obl + case, or nmod+case for "anyone at all").

**Comment by nschneid** [comment]
Note that there are other fixed expressions like *at least* where it is similarly unclear (and inconsistent in the data).

**Comment by dan-zeman** [comment]
The main question is whether or not they are nominals. "Yes, they are" means `obl`. "No, they are not" means `advmod`. Both under the assumption that the parent node is a head of a clause, or an adjective, or an adverb.

If they modify a nominal (_at least three liters_), then I'm not so sure. I have been using the subtyped `advmod:emph` for similar cases in other treebanks. But our guidelines actually seem to suggest that `advmod` and its subtypes are out of question when the parent is a nominal (and when the nominal is not a predicate). If that's the case, then we should perhaps use `nmod` instead of `obl`, and `amod` instead of `advmod`. (But `amod` is often perceived as adjectival modifier, and these words are not adjectives. We have been referring to `amod` and `acl` as _adnominal_ modifier/clause, but the [current definition](http://universaldependencies.org/u/dep/index.html) still says _adjectival_.)

Finally, _at all_, _at least_ etc. could be fixed expressions. Then the second word would be attached to the first one via `fixed`, and the UPOS tag of the first word would not count because the fixed expression may represent a different part of speech (here probably `ADV`). So it would be `advmod` (or `amod`, depending on the answer to the question above).

**Comment by amir-zeldes** [comment]
I would be for `nmod` (or `obl` when it modifies a verb in "At least they came") because I think fixed should be a last resort. The basic structure of "at least" is a PP, I think the main reason it's less comfortable for people is that 'least' is somehow adjectival, and nominalized adjectives without "one" are uncommon in present day English. But still, I think the best one could do here while avoiding fixed is nmod. 

Also note it's not quite fixed, e.g. "at the very least", which looks like a PP to me.

**Comment by nschneid** [comment]
> Also note it's not quite fixed, e.g. "at the very least", which looks like a PP to me.

I think the at+superlative construction is more productive with definite marking: _at its busiest_ is another example, but \*_at busiest_.

Without definite marking, I can think of _at least/most/worst/best_.

Different idiomatic prep + adj constructions include *at large*, *of late*, *for sure/real*, *for good*, *in full*. These all seem to be tagged as `case(ADJ, ADP)` rather than `fixed(ADP, ADJ)`. So I suspect that's the most intuitive solution.

Things that are arguably PPs but sometimes tagged as `ADV + ADV` include *at least*, *as well*, *after all*, *of course*.
