### ISSUE TITLE
In English, should a relativizer ever be attached as `mark`?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#475]
English relativizers, including "that", are generally treated as pronouns and attached as subject/object/oblique (see #223). However, I see 14 hits in the English corpus where [the dependent of `acl:relcl` heads a `mark`](http://bionlp-www.utu.fi/dep_search/query?search=_%20%3Cmark%20%28_%20%3Cacl%3Arelcl%20_%29&db=UD_English-v2&case_sensitive=True&hits_per_page=100). Are these correct? Should some of these be `ccomp` or something else?

**Comment by dan-zeman** [comment]
After skimming the query results, I think that `mark` is OK most of the time (in some cases I am not sure whether perhaps `advmod` would be better). So if there is a problem, then it is the `acl` which may not be best described as `acl:relcl`?

In any case, I am pretty sure that the last two examples (no. 9 and 10) are wrong.

9: _show you how to unfreeze_ ... _how_ should be `advmod`, not `obj`; _unfreeze_ is definitely not an `acl:relcl` (did someone mistake _show_ for a noun?) It is a `ccomp`.

10: _plan on what to do_ ... _do_ should not depend on _what_ as `acl:relcl`. Quite the contrary, _what_ is an `obj` of _do_. _On_ should not depend as `case` on _what_, it should depend on _do_. Finally, _do_ should be an `acl` attached to _plan_ (maybe even `acl:relcl` but that depends on the language-specific definition).

**Comment by sylvainkahane** [comment]
It has often been defended since the 1970's that English wh-words are pronouns while _that_ is a pure relativizer. In particular because _that_ does not allow the pied-piping.

> the word on which it depends
> *the word on that it depends

But here we face a general problem for a universal treebank: do we want to favor the internal consistency of the English treebank or do we want we want to favor the consistency of UD?

In any case we have a problem of internal consistency because [the vast majority of _that_ in relative clauses are analyzed as `nsubj` or `obj`](http://bionlp-www.utu.fi/dep_search/query?search=that%20%3Cobj%20%28_%20%3Cacl%3Arelcl%20_%29&db=UD_English-v2&case_sensitive=True&hits_per_page=200).

The same problem will occur in other languages. For instance in French we have pure relativizers (_que_,  _qui_, _dont_) and several relative pronouns (human _qui_, non-human _quoi_, _lequel_, etc.).

My opinion: I think it is better to give an internal function to relativizers in order to indicate which dependent of the verb has been relativized. In other words, I prefer to give the function `nsubj`or `obj`to the relativizer _that_ even if I know that it is a pure relativizer and it should be `mark`. 

@dan-zeman I think that example 10 is well analyzed. _what to do_ is a relative clause without antecedent. [Such constructions are consistently anlalyzed with _what_ as the head.](http://bionlp-www.utu.fi/dep_search/query?search=what%20%3Eacl%3Arelcl%20_&db=UD_English-v2&case_sensitive=True&hits_per_page=50)

**Comment by nschneid** [comment]
In teaching POS annotation today I ran into the problem of relativizer "that" in English, which despite #223 is still [listed under `SCONJ`](https://universaldependencies.org/u/pos/SCONJ.html), though in practice in EWT it is almost always tagged as `PRON`:

- `acl:relcl` + embedded predicate with *that* as `mark`: http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=604a79d4815df&clustering=T.upos
   * 2 ADV, 1 SCONJ
- `acl:relcl` + embedded predicate with *that* as non-`mark` dependent: http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=604a7a86c5898&clustering=T.upos
   * 631 PRON, 18 ADV, 2 DET

**Comment by nschneid** [comment]
I guess #223 was pre-v2 but the consensus seemed to be that we prefer the pronoun analysis because that gives a more informative deprel as a subject or object of the embedded predicate (rather than `mark`). If everyone is OK with that, it is mostly consistent with EWT, and we can just update the guidelines.

**Comment by amir-zeldes** [comment]
I think it's PRON whenever it is substitutable by 'which'. There are cases where "that" stands for some sort of generic complementizer, which may be genuine SCONJ cases IMO. GUM examples:

  * the first time **that** it does the card mode
  * we can't have strangers playing a game **that** their experience is impacted / altered by the fact that there's a proposal going on

But other than these weird cases yeah, I agree PRON is better.

**Comment by nschneid** [comment]
These are complement clauses, not relative clauses, right? Or whatever we call them in UD. :) In any case the "that" is not occupying a core role of the embedded predicate.

**Comment by amir-zeldes** [comment]
Yes, it's not occupying an argument role, but I still think they're `acl:relcl` describing the matrix clause noun. It just means something like "time when" or "game in which", but from a literal perspective we can't call it a relative pronoun IMO, so we tag these `xpos=IN` with deprel `mark`, despite the subordinate head being `acl:relcl`. Not sure if that's optimal, but at least their 'differentness' is somehow annotated.

**Comment by nschneid** [comment]
Then what distinguishes a relative clause from a plain adjectival clause with a finite embedded predicate? The [`acl:relcl`](https://universaldependencies.org/u/dep/acl-relcl.html) description is not very helpful.

**Comment by dan-zeman** [comment]
> is still listed under SCONJ, 

But there it is listed in the sentence _I believe that he will come._ Here it is `SCONJ`. Once it refers to something, it is `PRON` or `DET`.

**Comment by Stormur** [comment]
> Then what distinguishes a relative clause from a plain adjectival clause with a finite embedded predicate? The [`acl:relcl`](https://universaldependencies.org/u/dep/acl-relcl.html) description is not very helpful.

I think an `acl`, to be `relcl`, requires the presence of a relative element, i.e. sporting `PronType=Rel`, "acting" inside the clause, i.e. not as a conjunction. In the end, it is "just" a subrelation. So, in the examples we still have `acl`s, even if not `relcl`s.

> > is still listed under SCONJ,
> 
> But there it is listed in the sentence _I believe that he will come._ Here it is `SCONJ`. Once it refers to something, it is `PRON` or `DET`.

But what in this case, where this element does not show any pronominal trait whatsoever (and etymologically we know it is "frozen")? :thinking:

I am wondering. If we observe that (hope everything is correct)

1. it can be omitted:
    * _The man that I saw_ = _The man I saw_
    * _The boss that I work for_ = _The boss I work for_
2. one cannot say (as far as I know)
    * _The boss for that I work_
2. it can happen something "lopsided" like @amir-zeldes reports:
    * _we can't have strangers playing a game that their experience is impacted_
3. _that_ is used in many (most?) other cases as a mere complementizer...

... is it still coherent to annotate _that_ as a (relative) `PRON` instead as always `SCONJ`?? Then, is it not a distinction made only on semantic grounds?  Whereas other elements like _which_, _who_ (which inflects!) and _where_ seem to be more in line with a relative role.

A very similar phenomenon of "universal complementizer" happens in Italian and Greek, that I know. In Italian I would also strongly argue for a general analysis as `SCONJ`.

**Comment by nschneid** [comment]
[`SCONJ`](https://universaldependencies.org/u/pos/SCONJ.html) says the following:

> We follow [Loos et al. 2003](http://www-01.sil.org/linguistics/GlossaryOfLinguisticTerms/WhatIsASubordinatingConjunctio.htm) in recognizing these three subclasses as subordinating conjunctions:
> 
> * Complementizers, like [en] _that_ or _if_
> * Adverbial clause introducers, like [en] _when_, _since_, or _before_ (when introducing a clause not a nominal)
> * Relativizers, like [he] _še_. (Note that these words, which simply introduce a relative caluse, and normally don't inflect, need to be distinguished from relative or resumptive pronouns, which have a nominal function within the relative clause and which we analyze as [PRON]().)

I interpret the third bullet point as covering relativizer _that_ because, unlike demonstrative pronoun _that_, it doesn't inflect:

* the birds that/*those lives in the park

But Hebrew _še_ (which is not homonymous with a pronoun) is used for nearly all relative clauses, whereas English relative clauses can be marked by clear pronouns, or _that_, or they can be unmarked.

Maybe a way to phrase it would be to say that "some languages, including English, employ a pronominal relative clause marking strategy (`PRON`), while others reserve distinct relativizer words (`SCONJ`)"?

**Comment by amir-zeldes** [comment]
> Maybe a way to phrase it would be to say that "some languages, including English, employ a pronominal relative clause marking strategy (PRON), while others reserve distinct relativizer words (SCONJ)"?

I would agree with the latter, and add that Hebrew še is similar to the quirky "that" in the few examples above, in that it does not replace the role of the matrix noun in the subordinate clause (which is after all the literal meaning of 'pronoun'). In normal uses of relative "that" (i.e. where it is xpos=WDT), it DOES replace the noun in the subordinate clause, and is therefore IMO PRON. In Hebrew this is not the case, since še is just a relative clause marker, whereas the argument role in the subordinate clause is expressed by a resumptive:

  * ha-mis'ada še-axalnu b-a "the restaurant that(=še) we ate in *it*"

**Comment by nschneid** [comment]
Since a lot of us are in favor of keeping the current annotations of relative _that_ as `PRON`, I have updated the guidelines to reflect the status quo:

- `PRON` changes: 23e3bda
- `SCONJ` changes: 1a20f7d
