### ISSUE TITLE
nmod:poss

### ISSUE THREAD

**Issue by sylvainkahane** [UniversalDependencies/docs#477]
In issue #454, @amir-zeldes suggested that `nomod:poss` could be a universal relation. It is true that this relation is currently used in many treebanks for possessive pronouns.

```
Fr. _mon chapeau_ 'my hat'
nmod:poss(chapeau,mon)
```

Is it legitimate?

`nmod:poss`has been initially introduced for English. It "is used for a nominal modifier which occurs before its head in the specifier position used for ‘s possessives."

```
Jonh's hat
nmod:poss(hat, John)
```
English has a particular construction, the so-called Saxon genitive, where an `nmod`can occupy the determiner position. In other words, a phrase such as _John's_ commutes with determiners. It is legitimate to introduce a particular relation for this construction (although the relation `det` could have been used too).

We then face a dilemma for possessive pronouns in English: As determiners they should be `det`, but as pronominalizations of `nmod:poss` phrases, they could be `nmod:poss`. Finally `nmod:poss` has been chosen:

```
his hat
nmod:poss(hat,his)
```

I let the persons in charge of the English treebanks decide if they have taken the right decision. But what it is quite clear for me is that using `nmod:poss` for languages which do not have `nmod`phrases occupying the determiner position cannot be justified from the syntactic point of view. For instance in French, a possessive pronoun such as _mon_ 'my' is a determiner without any doubt and it should be annotated `det`:

```
Fr. _mon chapeau_ 'my hat'
det(chapeau,mon)
```

The fact that this determiner is a pronoun is a feature of the word itself and has nothing to do with its relation towards its syntactic governor.

**Comment by dan-zeman** [comment]
I believe that possessive determiners should be attached jusing `det` or `det:poss` (used e.g. in Portuguese http://universaldependencies.org/pt/dep/det-poss.html or Italian http://universaldependencies.org/it/dep/det-poss.html) but not `nmod:poss`.

The issue is related to the long discussions we had about distinguishing `PRON` and `DET`, where possessives turned out to be a particularly hot topic with varying strategies in different languages (see e.g. https://github.com/UniversalDependencies/docs/issues/159, http://universaldependencies.org/v2/postags.html#revised-guidelines-for-pronominal-words, http://universaldependencies.org/2015-08-23-uppsala/determiners.html).

**Comment by nschneid** [comment]
Is word order the crucial criterion here?

I find `nmod:poss` coherent for English s-genitives because then all case-marked nominals modifying nominals are some type of `nmod`. If we exclude from `nmod` any noun modifiers occurring to the left of the head, that would essentially mean `nmod` is for PP objects but not s-genitives.

I'm not sure how to handle possessive predicate nominals: *That is either mine or John's.* Interestingly, you can say *This is a book of mine* ("double possessive"), but not *\*This book is of mine.*

**Comment by dan-zeman** [comment]
Word order is definitely not something you could apply cross-linguistically in a general definition of `nmod:poss`.

In _That is either mine or John's_, the possessive pronoun is the predicate and there is no room for `nmod:poss`:

nsubj(mine, That)
cop(mine, is)
conj(mine, John)

**Comment by amir-zeldes** [comment]
It occurs to me that making a distinction `det:poss` versus `nmod:poss` might lead to different analyses of these Italian examples

```
Mia nonna "my grandmother" (bare possessive as determiner, possible for close family members etc.)
La mia pizza "my pizza" (additional possessive, not serving as the determiner)
```

That seems undesirable to me, but maybe someone working on Italian can chime in?

**Comment by dan-zeman** [comment]
There is no universal requirement that a nominal has at most one `det` dependent. Italian uses `det` in both _mia nonna_ and _la mia pizza_ but there are different subtypes of `det`, so in _la mia pizza_, you would have

det(pizza, la)
det:poss(pizza, mia)

See http://hdl.handle.net/11346/PMLTQ-TVYF and http://hdl.handle.net/11346/PMLTQ-E04U for examples.

**Comment by amir-zeldes** [comment]
I see, I hadn't realized that was their decision. I think some linguists will probably not like that, but I'm very agnostic about these things - if multiple dets work for what they want to do, that's fine by me. 

I see they also have a predet type though for things like tutti, which in English is mainly motivated by not wanting a flat multi-det analysis.

**Comment by gcelano** [comment]
I would expect to find Italian "mio" tagged as amod, in that it is morphosyntactically different from English "my". It looks like an undue interference of English classification.

**Comment by dan-zeman** [comment]
The difference between `det` and `amod`, as I see it, is that the former is for dependent words POS-tagged `DET` and the latter for `ADJ`.

_Mio_ is a determiner rather than adjective because it expresses a reference (to the first person singular) rather than describes a quality. Otherwise, determiners are supposed to be morphosyntactically very much like adjectives (in the given language).

**Comment by amir-zeldes** [comment]
I don't think that referentiality is generally used as a criterion for such distinctions, at least not in all languages. For example in German there is an adjective 'meinig' (mine-y), which can be used with a very similar possessive meaning to the possessive pronouns:

Das sind die Meinigen / meine  - those are mine (or 'the ones that are mine', the 'mine' ones)

I'm pretty sure these are tagged as adjectives because they exhibit adjectival morphology (e.g. the -n inflection for definite plural). So the criterion in that case is basically morphological - whether or not mio is considered morphologically adjectival is another question, and I'll leave that to the Italian linguists, but I don't think it's inconceivable to have possessive adjectives.

**Comment by dan-zeman** [comment]
Agreed that _Meinigen_ in _die Meinigen_ are not `DET`, although I don't think they are `ADJ` either, I would tag them `NOUN`. But yes, there are possessive adjectives, even nonreferential ones (http://universaldependencies.org/cs/feat/Poss.html).

Morphological resemblance between `ADJ` and `DET` is actually expected.

I cannot quantify whether referentiality is used “generally enough;” languages, grammars and authors differ in criteria they use. But UD has to draw the line somewhere, and preferably use comparable criteria for all languages. Right now it is using referentiality as a criterion (http://universaldependencies.org/u/pos/DET.html), although there are other criteria too, and the picture is not (and cannot be) perfectly sharp across all languages.

**Comment by amir-zeldes** [comment]
Yes, in my example above 'meinige' is nominalized, but that can happen to any German adjective. It's particularly common with 'meinige' because it's usually used contrastively: [your XYZ... as opposed to] den Meinigen. But it's not impossible to find cases modifying a noun, for example:

Jetzt schau mal, ob es mit den meinigen Einstellungen klappt
Now take a look whether it works with my settings (lit. 'the mine-y settings')
http://www.wetterstationen.info/forum/allgemeines-softwareforum/cumulus-software-konfiguration/

For the guidelines, I think it's OK to suggest semantic criteria, as long as they're not binding (and assuming we agree that 'meinige' is not DET, then I guess we also agree on this :)

**Comment by dan-zeman** [comment]
Yes, I guess we do agree on this :)
I would love to have a universally valid definition that, in German, would put _meine_ and _meinige_ on different sides of the line, but I don't think I have one.

**Comment by arademaker** [comment]
@dan-zeman for the 3 cases in the http://universaldependencies.org/pt/dep/det-poss.html  two are very strange:

1. 'Nossa Senhora' is clear a name https://en.wikipedia.org/wiki/Mary,_mother_of_Jesus. 
2. 'dela' (de+ela) is a contraction. 

In the http://github.com/universaldependencies/UD_Portuguese we don't use `det:poss`. We have to investigate ... some cases are annotated as `nmod': 

http://wnpt.brlcloud.com/dep_search_webgui/query?search=de%20%3Ccase%20ela&db=bosque&case_sensitive=True&hits_per_page=10

Maybe @claudiafreitas has something to add.

**Comment by sylvainkahane** [comment]
POSs must be defined in syntactic grounds. What is universal is the fact that natural languages have POSs, that is, classes of words which have more or less the same syntactic properties (distribution, inflection, agreement, etc.).

In some languages nouns cannot easily be dependents of verbs without combining with another class of words:

```
the cat slept
*cat slept
```
Words of this class can have other properties that distinguish them from adjectives:

- they occupy a particular place, e.g. at the very begining of the NP (_the big cat_ vs _*big the cat_)
- they can block variations in number (_each cat_ vs _*each cats_)
- they often have a pronominal counterpart (_each slept_)

This can justify to distinguish this class (DET) from ADJ. The criteria that distinguisg DET from ADJ do not have to be universal. Agian: what is universal is the fact that languages have distributional classes. Semantic criteria are not used to define the POSs, they are used to name them (Croft): if you distinguish two classes of words combining with nouns and one of them contains many words that "express the reference of the noun phrase in context", you will call it DET. But DET can contains words that do not express the reference and words that express the reference (such as _other_) can be not DET. What determine whether you are a DET or not is the fact that you have the properties that characterize DET in you language. And many languages do not have DET because words that express the reference do not have enough specific syntactic properties to be distinguished from ADJ.

For German _mein_ and _meinig_ no doubts are possible: One is DET and the other is ADJ.

Italian _mio_ is problematic because it can behave such as a DET and an ADJ.

French has also a small subclass of words (_quelques_ 'some, few', différents 'different', divers 'various') that behaves like NUM and can act as a determiner or be combine with a determiner (only a definite determiner: _les_ 'the', _ces_ 'these_, or a possessive: _mes quelques amis_ 'my few friends'). Such words are really embarassing and there will be no consensus. Some prefer to introduce [two POSs according to the position](http://bionlp-www.utu.fi/dep_search/query?search=NOUN%20%3E%20quelques&db=UD_French-Sequoia-v2&case_sensitive=True&hits_per_page=10), others prefer to analyze them always as ADJ or always as DET.

**Comment by amir-zeldes** [comment]
Agreed, thanks for those comparisons @sylvainkahane - I also think Italian belongs in the last class, with positionally distinct constructions. Whether or not one chooses two POS for words like mio based on the construction is currently a language specific decision, and I'm not sure if UD should be regulating it or not (this is maybe not a deciding factor, but often people like to be as isomorphic as possible to what their language-specific tagset is doing)

**Comment by gcelano** [comment]
I would argue that "mio" should get ADJ as a POS tag just because of its morphosyntax (although I think this is determined by the way it is conceptualized in Italian): you regularly found it associated with the definite article ("il"): "il mio libro" vs *the my book (and, conversely *mio libro vs my book). I take it as evidence that definiteness is included in "my" but not in "mio", whose morphosyntactic behavior is more similar to that of an adjective (see also "un mio libro" vs *a my book). To be complete, I should add that there are a few uses where "mio" seems to be a DET: with kinship names, one says "mia madre", "mio zio", "mio fratello" without article (*/?la mia madre). However, as far as I can see now, this behavior seems to be limited only to this class of nouns (which is linguistically very interesting). In general, the morphosyntax of "mio" is not that of a DET, and so I would label it as an ADJ. As for syntactic labels, det could be used in cases such as "mia madre", but I would probably use amod when it is preceded by an article.

Using DET/det for Italian "mio" (but this applies to other cases/ languages as well) would wrongly suggest that it morphosyntactically behaves in the same way as "my" does. But this is not true.

**Comment by sylvainkahane** [comment]
We can add that ADJs are possible with proper nouns without DET (_poor John_, _little Bob_). And kinship names can be used without DET (_Father_, _Fratello_). So we could consider that even in _mio fratello_, _mio_ is ADJ.

It is also possible to use _mio_ after the noun: _fratello mio_. In this construction I think that _mio_ can really not be analyzed as a DET.
