### ISSUE TITLE
Clarification on Japanese POS Tag Mapping

### ISSUE THREAD

**Issue by polm** [UniversalDependencies/docs#481]
Hello; I'm looking at adding a mapping from Unidic POS tags to UD tags for [spaCy](https://github.com/explosion/spaCy) (explosion/spaCy#1214). 

The [documentation](http://universaldependencies.org/ja/overview/morphology.html#morphology) describes the UD tags as being a mapping from Unidic tags, with some cases where the same Unidic tag can result in a different UD tag depending on the way the token is used in the sentence. For example, sometimes サ変動詞/suru-verbs are `NOUN` and sometimes they are `VERB`.

Is there any more specific documentation of how the non-direct mappings are intended to be handled, or perhaps some example code that does tag conversion? [This paper](http://www.ar.media.kyoto-u.ac.jp/publications/tanaka-LREC16.pdf) indicates a converter of some kind was used to generate the Japanese UD treebank, but I couldn't seem to find related code in the Japanese UD repos ([1](https://github.com/UniversalDependencies/UD_Japanese), [2](https://github.com/UniversalDependencies/UD_Japanese-KTC)). 

I can guess at a simple rule-based method for determining the appropriate UD tags, and maybe that was what was intended, but it'd be nice to have something more concrete if possible.

**Comment by kanayamah** [comment]
@polm, sorry, the conversion script from UniDic has not been shared yet because current UD_Japanese and UD_Japanese_KTC were generated in different ways even though the definition in the document is based on mapping from UniDic PoS schema.
As you pointed out, the PoS tag ``名詞-普通名詞-サ変可能`` (noun which can be used as a suru-verb) can be mapped to ``NOUN`` or ``VERB`` depending on its context.  Now I'm asking the team converting UniDic system to UD to provide more specific rules.  We'll give you updates soon.

**Comment by masayu-a** [comment]
The understanding of parts-of-speech (PoSs) in Japanese corpora can be split
into two philosophies: lexicon-based (語彙主義) and usage-based (用法主義). The
lexicon-based approach involves extracting all possible categories for one word
as labels. 

BCCWJ(NINJAL word delimitation) standards have two morphological unit
layers.
'Short Unit Word' (SUW) is based on the lexicon-based philosophy.
A morphological analyzer MeCab with UniDic generates the SUW.
Because the ambiguity of the usage is not resolved in this layer,
we introduce a rule for the label `名詞-普通名詞-サ変可能' (Verbal Noun) as a
verb in the SUW layer.

'Long Unit Word' (LUW) is based on the usage-based philosophy.
The unit defines the Japanese syntactic base phrases 'Bunsetsu'.
We can resolve the ambiguity of usage in this layer.
For example, the verbal noun is annotated whether the word is verb or noun in
the syntactic context.
We have a LUW analyzer `Comainu' to analyze compound word, multi-word
expressions and syntactic base phrases.

Now, we are developing a universal dependency compatible annotation for the
`Balanced Corpus of Contemporary Written Japanese' (BCCWJ).
The BCCWJ has the annotations of SUW POS, the usage of SUW, and LUW POS.
The POS conversion table for the layers is still under development.
Please contact me if you need the beta version of conversion table.

Thanks,
  Masayuki

**Comment by polm** [comment]
Thanks for the reply. 

Even if it's not finalized it'd be great to have details on the mapping; I just sent a mail to the email on your profile. If it doesn't arrive for some reason please let me know.
