### ISSUE TITLE
todos/tous as subject or referring to the subject

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#484]
I'm looking at tous/todos, for example: "Salimos todos muy contentos" and "nous savons tous que ces tests ne sont pas encore au point sur le plan scientifique"

It sems to be done in different ways in different treebanks:

* In `UD_Spanish` it is `nsubj` where there is no explicit pronoun, although explicit pronoun is also possible: _**Nosotros salimos todos** con una bolsa para recoger los excrementos de nuestros perros y al lado ves a gente defecando con total naturalidad_
* In `UD_French-Sequioa` it gets `iobj`
* In `UD_French` it gets `obl`
* In `UD_Catalan` it gets `nsubj` where there is no explicit pronoun, although again possible: _Mire, **nosaltres sabem tots** que el president Camps té problemes per a poder amb la gent, i sobretot amb les entitats, perquè així ens ho comuniquen que hi ha ..._

The French documentation for `iobj` seems to suggest "An indirect object is a nominal which corresponds to a dative object." which doesn't apply here. 

Thoughts?

**UD_Spanish:**
```
14      y       y       CCONJ   _       _       15      cc      _       _
15      salimos salir   VERB    _       Mood=Ind|Number=Plur|Person=1|Tense=Past|VerbForm=Fin   7       conj    _       _
16      todos   todo    PRON    _       Gender=Masc|Number=Plur|PronType=Tot    15      nsubj   _       _
17      muy     mucho   ADV     _       _       18      advmod  _       _
18      contentos       contento        ADJ     _       Gender=Masc|Number=Plur 15      xcomp   _       SpaceAfter=No
19      .       .       PUNCT   _       _       7       punct   _       _
```

**UD_French-Sequioa:**
```
3       nous    il      PRON    _       Number=Plur|Person=1    4       nsubj   _       _
4       savons  savoir  VERB    _       Mood=Ind|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin   0       root    _       _
5       tous    tout    PRON    _       Gender=Masc|Number=Plur|PronType=Rel    4       iobj    _       _
6       que     que     SCONJ   _       _       15      mark    _       _
7       ces     ce      DET     _       Number=Plur|PronType=Dem        8       det     _       _
8       tests   test    NOUN    _       Gender=Masc|Number=Plur 15      nsubj   _       _
9       ne      ne      ADV     _       Polarity=Neg    15      advmod  _       _
10      sont    être    AUX     _       Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin   15      cop     _       _
11      pas     pas     ADV     _       Polarity=Neg    15      advmod  _       _
12      encore  encore  ADV     _       _       11      fixed   _       _
13-14   au      _       _       _       _       _       _       _       _
13      à       à       ADP     _       _       15      case    _       _
14      le      le      DET     _       Definite=Def|Gender=Masc|Number=Sing|PronType=Art       15      det     _       _
15      point   point   NOUN    _       Gender=Masc|Number=Sing 4       ccomp   _       _
16      sur     sur     ADP     _       _       18      case    _       _
17      le      le      DET     _       Definite=Def|Gender=Masc|Number=Sing|PronType=Art       18      det     _       _
18      plan    plan    NOUN    _       Gender=Masc|Number=Sing 15      obl     _       _
19      scientifique    scientifique    ADJ     _       Number=Sing     18      amod    _       _
```

**UD_French:**
```
1       Les     le      DET     _       Definite=Def|Gender=Masc|Number=Plur|PronType=Art       2       det     _       _
2       élèves  élève   NOUN    _       Gender=Masc|Number=Plur 3       nsubj   _       _
3       ont     avoir   VERB    _       Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin   0       root    _       _
4       tous    tout    PRON    _       Gender=Masc|Number=Plur 3       obl     _       _
5       une     un      DET     _       Definite=Ind|Gender=Fem|Number=Sing|PronType=Art        6       det     _       _
6       chambre chambre NOUN    _       Gender=Fem|Number=Sing  3       obj     _       _
7       personnelle     personnel       ADJ     _       Gender=Fem|Number=Sing  6       amod    _       SpaceAfter=No
8       ,       ,       PUNCT   _       _       3       punct   _       SpaceAfter=No
9       .       .       PUNCT   _       _       3       punct   _       _
```

**UD_Catalan:**
```
2       La      el      DET     DET     Definite=Def|Gender=Fem|Number=Sing|PronType=Art        3       det     _       _
3       societat        societat        NOUN    NOUN    Gender=Fem|Number=Sing  5       iobj    _       _
4       la      ell     PRON    PRON    Case=Acc|Gender=Fem|Number=Sing|Person=3|PronType=Prs   5       obj     _       _
5       formem  formar  VERB    VERB    Mood=Ind|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin   10      ccomp   _       _
6       tots    tot     PRON    PRON    Gender=Masc|Number=Plur|PronType=Ind    5       nsubj   _       SpaceAfter=No
```

**Comment by sebschu** [comment]
All these examples look like classic cases of quantifier stranding to me, so I actually think all of these analyses are wrong (except maybe the Spanish one). First, I think _tous/todos/tots_ should be tagged as `DET` instead of `PRON`. 

Regarding the attachment and the relation, I'm also not sure. Looking at the English treebank, it seems like we are attaching _all_ to the noun using `det` if it appears after the noun but still before any of the verbs (e.g., in  _"the companies all made a profit"_, _all_ is attached to _companies_ with a `det` relation). If it appears after a verb, e.g., in between an auxiliary and the main verb, then we attach it to the main verb with an `advmod` relation (e.g., in _"the companies could have all made a profit"_, we attach _all_ to _made_ with an `advmod` relation). 

However, as this does not seem to be documented anywhere, I'm not sure whether this is an inconsistency or whether this was actually discussed at some point. I'll ask @manning about it.

**Comment by dseddah** [comment]
Hi Sebastian,

> Le 2 août 2017 à 07:40, Sebastian Schuster <notifications@github.com> a écrit :
> 
> All these examples look like classic cases of quantifier stranding to me, so I actually think all of these analyses are wrong (except maybe the Spanish one). First, I think tous/todos/tots should be tagged as DET instead of PRON.

why should « tous » be tagged the same everytime ? 
 in the UD_FTB

in "Le bistouri semble être pour tous le remède miracle. »  (UD_FTB, sent_id: flmf7ad1co-370) (the bistoury seems to be for all the remedy  miracle/  the bistoury seems to be the miracle remedy for all)
tous is tagged as a PRON and it’s legit.

Here’s the POS  distribution of « tous »  in the UD_FTB (should check also toutes (tous-FEM+PLUR) but no time)


240 tous	ADJ    (in cases like « tous les / all the)
 27 tous	DET  (in structure like  ADP * NOUN,  "en tous genre » (of all kinds)
 46 tous	PRON ( in cases like « Je les aime tous » (I love them all)


And it’s basically the same in the Sequoia corpus as its native POS annotation scheme is the same as the FTB.

Djamé

**Comment by sebschu** [comment]
Sorry, I should have made this clearer. I meant in the quantifier stranding cases, _tout_ should be tagged as `DET`. But you are of course right that there are plenty of cases in which _tout_  should be tagged `PRON` or `ADV`.

**Comment by ftyers** [comment]
I think the POS breakdown that @dseddah gave looks about right, but I'm not sure about the dependency labels, @dseddah do you know motivation for `iobj` ?

**Comment by sylvainkahane** [comment]
This phenomenon is generally referenced as "quantifier floating".

About the POS, it is clear that it concerns PRON and not DET in French. For instance, French as the opposition between _chaque_ 'each_DET' and _chacun_ 'each_PRON' and only _chacun_ is possible:

```
Ils ont tous un chapeau 'They all have a hat'
Ils ont chacun un chapeau 'They each have a hat'
```

About the relation, `iobj` does not make sense. If we do not introduce a special relation for this special construction, the best choice is probably `advmod`.

I think that the same analysis is valid for English and _the companies all made a profit_ should be analyzed with _all_ as a PRON and `advmod(made,all)`.

What about Japanese where this construction is very common?

**Comment by amir-zeldes** [comment]
Just to add this to the mix: These are very common in Coptic and we have them as `advmod` before or after the verb. In fact, placement before the verb mainly occurs for left dislocated subjects, so it really seems like a variant with the same function:

The martyrs all, they did ...
The martyrs did all ...

By convention, we attach it to the NP in the first case, but in the second we attach it to the verb. This also prevents crossing edges, but also seems motivated based on the left dislocation (usually just one phrase) and the general rareness of discontinuities in Coptic (it's nothing like Greek or Latin).

**Comment by dseddah** [comment]
> Le 2 août 2017 à 09:26, Francis Tyers <notifications@github.com> a écrit :
> 
> I think the POS breakdown that @dseddah gave looks about right, but I'm not sure about the dependency labels, @dseddah do you know motivation for iobj ?

Actually I don’t. I suspect it’s an artefact of the automatic conversion from the native dependency format. So in anyway, totally fixable if it turns out wrong.

(5 mn later)

if you want to see where does the error come from, look a these exemple (paste the link to a browser to display the tree)

original phrase-based scheme ("tous" projects a NP-MOD)
http://talc2.loria.fr/OB2ksK5Tgk/?custom=598254ae96a58&corpus=sequoia.const-7.0

native dependency scheme ("tous" is attached to the verb)

http://talc2.loria.fr/OB2ksK5Tgk/?custom=5982547ee9fd4&corpus=sequoia.surf-7.0

UD-scheme  (here comes wrong relation) 
http://talc2.loria.fr/OB2ksK5Tgk/?custom=59825523e7255&corpus=UD_French-Sequoia-2.0


note that in our native deep syntax scheme, the analysis has been enhanced

Deep syntax native scheme (« tous" is attached to the subject as a modifier)
http://talc2.loria.fr/OB2ksK5Tgk/?custom=598254e1a7c7d&corpus=sequoia.deep-7.0



so it’s totally fixable by simply modifying the conversion rules. 


Best

Djamé

**Comment by dseddah** [comment]
> Le 2 août 2017 à 15:47, djame seddah <djame.seddah@gmail.com> a écrit :
> 
> 
>> Le 2 août 2017 à 09:26, Francis Tyers <notifications@github.com> a écrit :
>> 
>> I think the POS breakdown that @dseddah gave looks about right, but I'm not sure about the dependency labels, @dseddah do you know motivation for iobj ?
> 
> Actually I don’t. I suspect it’s an artefact of the automatic conversion from the native dependency format. So in anyway, totally fixable if it turns out wrong.
> 
> (5 mn later)
> 
> if you want to see where does the error come from, look a these exemple (paste the link to a browser to display the tree)
> 
> original phrase-based scheme ("tous" projects a NP-MOD)
> http://talc2.loria.fr/OB2ksK5Tgk/?custom=598254ae96a58&corpus=sequoia.const-7.0
> 
> native dependency scheme ("tous" is attached to the verb)
> 
> http://talc2.loria.fr/OB2ksK5Tgk/?custom=5982547ee9fd4&corpus=sequoia.surf-7.0
> 
> UD-scheme  (here comes wrong relation) 
> http://talc2.loria.fr/OB2ksK5Tgk/?custom=59825523e7255&corpus=UD_French-Sequoia-2.0
> 
> 
> note that in our native deep syntax scheme, the analysis has been enhanced
> 
> Deep syntax native scheme (« tous" is attached to the subject as a modifier)
> http://talc2.loria.fr/OB2ksK5Tgk/?custom=598254e1a7c7d&corpus=sequoia.deep-7.0
> 
> 
> 
> so it’s totally fixable by simply modifying the conversion rules. 


seems like the preferred analysis for a similar construction in english like (we all know)  is  det(all,we)  subj(we,know)
http://talc2.loria.fr/OB2ksK5Tgk/?custom=598256ced4cd6&corpus=UD_English-2.0


Djamé

**Comment by perrier54** [comment]
When « tous » is a modifier of a verb, it is an adjective according to Grevisse. Therefore, the dependency of the adjective “tous” on the verb must be labelled ADVCL, because an adjective that is a verb complement is considered as a predicate in UD. In the following examples, the dependencies of “tous” and “seuls” must be labelled in the same way ADVCL.
Ils viennent tous (they all are coming)
Ils viennent seuls (they are coming alone)
But [sylvainkahane](https://github.com/sylvainkahane) presents two examples, which show that “tous” can also be seen as a pronoun: 
Ils ont tous un chapeau
Ils ont chacun un chapeau
Here, we reach the limits of UD, which mixes the category of the target with its syntactic function in the dependency label. I agree with [sylvainkahane](https://github.com/sylvainkahane) that the least bad label is ADVMOD when a pronoun or an adjective is a modifier of a verb.

**Comment by jnivre** [comment]
In general, I think the use of "advmod" for floating quantifiers is reasonable. The whole idea of floating is that it is something that semantically belongs to a noun phrase but syntactically behaves like an adverb at the clause level. However, if we agree that it is a pronoun, then "obl", rather than "advmod", would strictly speaking be the required relation.

**Comment by dseddah** [comment]
According to the French Treebank guidelines, p.16, morpho-syntax guide, (from which are derived  Sequoia, the FSMB and the FQB), the rule was to tag  all "tout" variants that attach to the verb as PRO. So given the automatic conversion to UD that was applied here, unless I've missed something, I'm expecting the current scheme to follow that pattern.


Tous:PROmp viendront:VF3p
Elles:CL3fp viendront:VF3p toutes:PROfp
Je veux tous:PROmp les:CLO3mp voir:VW
Je les:CLO3mp verrai:VF1s tous:PROmp
J'ai:VP1s tout:PROms lu:VKms
Il:CLS3ms pense:VP3s à:P tout:PROms
Tout:PROms est:VP3s possible:Ams
Tout:PROms ce:PRO3ms qui: PROR3ms évoque la mer

**Comment by CatalinaMaranduc** [comment]
Are there languages in which adverbs have gender and number? In Mr.
Perrier's examples the ”adverb” is plural !
I thought that for such cases there is the xcomp relation.

Cătălina

**Comment by jnivre** [comment]
We are not saying it is an adverb. We are saying that it is used in a syntactic position normally reserved for adverbial modifiers. But since it is nominal (or adjectival) in character, the relation "obl" is more natural than "advmod", as this is used for nominals used as modifiers at the clause level. The "xcomp" relation is reserved for open clausal complements and does not seem to apply. Even if you were to argue that "tous" has an implicit subject controlled by some other element, it does not seem to be a complement of any predicate.

**Comment by CatalinaMaranduc** [comment]
Ah, it was V1 the equivalence predicative element=xcomp !
In V2 xcomp can be only a subordinate clause?

ok, I will annotate the predicative element as member of the large family
of obl.

**Comment by jnivre** [comment]
The definition of "xcomp" has not changed in v2. It is still used for predicative complements like "blue" in "she painted the house blue". The difference compared to the case discussed here is that "blue" is regarded as a complement of "painted", and that "blue" is predicated of "house". By contrast, a floating "all" can be optionally added to any predicate, and it is not clear that there is any predication involved.

**Comment by dan-zeman** [comment]
Newer issue on this topic: #581.
