### ISSUE TITLE
Clausal dependents of adverbs

### ISSUE THREAD

**Issue by LarsAhrenberg** [UniversalDependencies/docs#488]
I have a problem with clausal dependents of adverbs such as

English:  <i> now that I've got your attention I'd like to ... </i>
Swedish:  <i>nu när jag har er uppmärksamhet skulle jag vilja ...</i> lit. <i> now when I've got ... </i>

In UD_English the analysis is `ccomp(now,got)` but this doesn't fit the definition of `ccomp`as a core argument. For Swedish I'd prefer to use `advcl`: `advcl(nu,har)`, but that would contradict the definition of `advcl` as a clause modifying a predicate. And `acl` wouldn't work either as that's for a dependent of a nominal. So, unless a fourth type of dependent clause is called for it seems one of the other three types needs a broader definition.

Lars

**Comment by amir-zeldes** [comment]
I feel like `advcl` is appropriate, otherwise maybe `acl`. Is it very different from: 

_That time when you went to the party_ 

? I think this type of 'that' is more like 'when' than it is like 'which'.

**Comment by dan-zeman** [comment]
This problem is more general. I think we do not have guidelines (or at least have not stated them sufficently clearly and explicitly) for situations when the parent is neither predicate nor nominal. I have been struggling with `obl` vs. `nmod` in similar contexts.

I suspect that people lean towards the nominal vs. non-nominal division, i.e. `advcl` would be OK when the modified word is an adverb, `acl` would not.

**Comment by GPPassos** [comment]
Indeed, `advcl` documentation is restrictive to clauses modifying other clauses:
> An adverbial clause modifier is a clause which modifies a verb or other predicate (adjective, etc.), as a modifier not as a core complement.

However, compare to `advmod`:
> An adverbial modifier of a word is a (non-clausal) adverb or adverbial phrase that serves to modify a predicate or a modifier word.

`advmod` is very permissive, allowing modification of other modifier words*.

Shouldn't the definition for `advcl` be relaxed in order to be more parallel to `advmod`? This would solve the problem, the difference between the two being if the dependent is a clause or a modifier word.


*According to the [function word modifiers section](http://universaldependencies.org/u/overview/syntax.html#function-word-modifiers), it can even modify function words (although this isn't clearly stated in the [advmod page](http://universaldependencies.org/u/dep/advmod.html))

**Comment by amir-zeldes** [comment]
+1

**Comment by jnivre** [comment]
Yes, I think there are many definitions that need to reviewed. Unfortunately, work on the guidelines was stalled because of all the work that went into the CoNLL shared task and the porting of treebanks to v2. Improving the guidelines will be a top priority for the next period. More soon.

**Comment by sylvainkahane** [comment]
Same construction in French  (_Maintenant que vous êtes là, je voudrais vous dire que …_).
For me it's clear that it's a relative clause:

> I've got your attention now -> now that I've got your attention

Adverbs such as _now_ are very close to temporal nouns and can be considered as temporal pronouns (Kahane S. (2010), Entre adverbes, noms et pronoms : le cas des modifieurs temporels, Actes de CMLF, La Nouvelle Orléans.):

> now, today, Monday, the next day, …

Although the construction with _now_ is quite idiomatic, it is also possible (at least in French) with the noun _day_ and the next sentences are attested in French:

> one day that I was in Paris, I …
> the other day that I was coming back from the supermarket, I …

So I vote for `acl:relcl` with my two hands.

**Comment by nschneid** [comment]
I think "now that" + clause is a multiword expression/construction with a syntax similar to subordinator "so that" and meaning similar to subordinator "since". It can't be paraphrased as "currently that", nor is "yesterday that" or "soon that" possible. So I vote for `fixed(now, that)`, mirroring `fixed(so, that)`.

**Comment by jonorthwash** [comment]
I usually call adverbs with dependents adpositions.  Or perhaps [non-attributive and non-core-argument] adpositions are just adverbs that take dependents.

(This comment may seem a bit trollesque, but I'm happy to discuss my reasoning, at least as it relates to certain cases or languages.)

**Comment by sylvainkahane** [comment]
@jonorthwash Yes ,adpositions are transitive adverbs (more or less said in Tesnière 1959 or Mel'cuk 1988). But some adverbs with a complement are not adpositions, if the complement is not direct (e.g. _according (to sth)_).

**Comment by jonorthwash** [comment]
> But some adverbs with a complement are not adpositions, if the complement is not direct (e.g. _according (to sth))_.

I don't totally understand the reasoning here. "according to" seems like more of a canonical adposition than, say, "focussing on" (potentially not the best example).

**Comment by nschneid** [comment]
I don't have access to do a corpus search now, but isn't "according to" a
multiword expression (fixed)?

**Comment by jonorthwash** [comment]
I'm speaking more generally, not necessarily UD-specifically.

**Comment by sylvainkahane** [comment]
@nschneid Two answers:

1) Even if you consider _according to_ as a MWE, you have to give a POS to _according_, which can never be ADP

2) that's really not the topic of this discussion, but I don't think that's a good idea to consider that _to_ is part of MWE. This _to_ is part of the sub-categorization (French _rection_) of _according_, exactly as _to_ is part of the sub-categorization of _talk_ in _I talk to them_. (Because you can say _according to this and **to** that_)

**Comment by amir-zeldes** [comment]
I'm not sure I follow what @jonorthwash is saying - is it the idea that every adverb that takes an argument is an adposition? I would think much like an adjective can take an argument, so can an adverb, and neither is necessarily an adposition as a result. I think it's easiest to look at deadjectival adverbs:

A similar idea to B is ...
amod(idea, similar)
obl(similar, B)

A works similarly to B
advmod(works, similarly)
obl(similarly, B)

In both cases I think it would be strange to claim that similar/similarly is an adposition, and I also think they should be analyzed as having dependents. But I might have misunderstood the issue.

**Comment by amir-zeldes** [comment]
@sylvainkahane about the current topic: I prefer `advcl` to `acl`, since I don't think it specifies a restrictive or non-restrictive relative clause:

"now that we know" != "that now which we know (and not other nows)"
"now that we know" != "a now, which we incidentally know"

I think `advcl` captures this paraphrase, which seems closer to intended reading:

"now, when we know, ..."

Do you feel that in this last example it's also `acl`? If not, is the presence of 'that' as the complementizer the criterion that you would use to choose `acl` over `advcl`, or does the meaning also play a role?

**Comment by nschneid** [comment]
I see @amir-zeldes's point that the ordinary meaning of "now" is somewhat transparent with "now that". OTOH, it seems to me that "now that" has a causal meaning mixed in that is not normally present with "now". Consider:

- I think we should get a cat now that we have a larger apartment.

"When?" does not seem like the most pertinent way to question the "now that..." part of the sentence, but rather, "Why?" (or "Why now?"). I think it is an idiosyncratic fact about "now that" that it can be paraphrased as "because" or "since".

I think this semantic idiosyncrasy supports what I argued earlier:

> It can't be paraphrased as "currently that", nor is "yesterday that" or "soon that" possible. So I vote for `fixed(now, that)`, mirroring `fixed(so, that)`.

["now that" in English treebank](http://bionlp-www.utu.fi/dep_search/query?search=now%20%3E%20%28_%20%3E%20that%29&db=UD_English-v2&case_sensitive=True&hits_per_page=10)

**Comment by sylvainkahane** [comment]
@amir-zeldes Yes the _that_-clause does a selection between all the possible _now_ s. 

_now that you have finished your homework_ = 'many nows were possible and we are in a now in which you have finished your homework'

This is exactly what does a relative clause:

_the day you didn't finished your homework_ = 'many days are possible and I consider the day in which you didn't finished your homework'

What is strange with this relative clause if the use of the relativizer _that_ and the fact that it cannot be ellipsed. I'm far to be a native speaker but I suppose that _now I have finished my homework_ is a bit strange.

In any case, even if the subcategorization frame of this _now_ is unusual, I recommand not to treat _that_ as `fixed`. It is part of the clause dependending on _now_. Cf. the discussion about _to_ in #491. Of course there is here a phenomenon of lexicalization, but this concern the subcategorization of _now_. So it is possible to consider that this `acl` is become a `ccomp`. But it would be a bad idea to analyze the marker of this subcategorized clause as a part of a MWE.

**Comment by amir-zeldes** [comment]
@sylvainkahane yes, I'm also not happy with `mwe`, and I wouldn't think this is `ccomp` for the clause, since you can use now equally without the clause. The 'that' is not mandatory, you can omit it as in:

So now we have an idea about what love is , let 's think about things that we love . (UKWAC)

What I find more curious is that you can't use 'which':

`* Now which you've finished your homework...`

I'm still not sure I see the diagnostic from distinguishing the subordinate clause as `acl` rather than `advcl` - how is it different from "now when you've finished your homework" or 'once' etc. I guess that can also be paraphrased as selecting from alternatives: "that particular now, when ...". In a real adnominal clause expanding 'now', I would expect the following to be possible:

"I experience a now that/which/*when is more vibrant than any other".

In this kind of example it's clear that 'now' is acting as the head of an NP, and a normal acl is possible. For "now that" it feels more adverbial to me.

**Comment by AleksandrsBerdicevskis** [comment]
I found this issue after @harisont and I struggled with a Swedish sentence of the type _Det är därför X är Y_ (This is why X is Y). As in the original question by @LarsAhrenberg, we could not choose between `acl` (_därför_ is not a nominal) and `advcl`. Formally, _därför_ is a predicate here, so it meets the criterion _a verb or other predicate (adjective, etc.)_, but we suspect that's not the intended meaning of the guidelines for `advcl`. 

On a side note: contrasting _nominal_ and _predicate_ seems misleading to me. As I understand those words, _nominal_ refers to POS properties, while _predicate_ to syntactic-semantic properties. This terminology varies across frameworks, of course, but following the UD logic, predicates can be nominal, too. In _I am a linguist who cannot choose between acl and advcl_, _linguist_ is a predicate, but the relative clause would still be `acl`, right?

In practice, the Swedish Talbanken uses `acl:cleft` in contexts similar to ours, and LinES uses `acl`. English-EWT uses `advcl:cleft` (correction: `advcl:relcl`), which would be my personal choice, but Swedish does not have this relation subtype (perhaps add? @jnivre). This issue is closed, but after reading it I am not sure what the consensus is :)

**Comment by nschneid** [comment]
> English-EWT uses `advcl:cleft`

I think you mean `advcl:relcl`, as described here: https://universaldependencies.org/en/dep/acl-relcl.html#it-clefts

**Comment by AleksandrsBerdicevskis** [comment]
Yes, of course. Thank you.

**Comment by Stormur** [comment]
> I found this issue after [@harisont](https://github.com/harisont) and I struggled with a Swedish sentence of the type _Det är därför X är Y_ (This is why X is Y). As in the original question by [@LarsAhrenberg](https://github.com/LarsAhrenberg), we could not choose between `acl` (_därför_ is not a nominal) and `advcl`. Formally, _därför_ is a predicate here, so it meets the criterion _a verb or other predicate (adjective, etc.)_, but we suspect that's not the intended meaning of the guidelines for `advcl`.

If you are thinking of a relative clause, I think it is the usual "trap" of cleft sentences. 

For this I can suggest [`csubj:cleft`](https://universaldependencies.org/la/dep/csubj-cleft.html): _det är därför_ is the extracted part in the predicate, and what remains is the (clausal) subject. 

By the way, a similar construction actually pretty well shows that _därför_ is in the realm of nominals, as a preposition given a kind of pronominal form through a support (_där_), and finally an oblique argument. But anyway, having the copular `root` + `csubj:cleft` does not even pose this issue. 

> In practice, the Swedish Talbanken uses `acl:cleft` in contexts similar to ours, and LinES uses `acl`. English-EWT uses `advcl:cleft` (correction: `advcl:relcl`), which would be my personal choice, but Swedish does not have this relation subtype (perhaps add? [@jnivre](https://github.com/jnivre)). This issue is closed, but after reading it I am not sure what the consensus is :)

I do not see a justification for any of these two relations. Would this anyway mean that the annotation between the two would oscillate according to the extracted element being nominal or not? And when is it not nominal?

**Comment by AleksandrsBerdicevskis** [comment]
> For this I can suggest [csubj:cleft](https://universaldependencies.org/la/dep/csubj-cleft.html): _det är därför_ is the extracted part in the predicate, and what remains is the (clausal) subject.

This is an elegant solution (though why the copular root?), but I am not entirely convinced. Apparently, it is also possible to use _som_ in such sentences in Swedish (an example from LinES: _Ibland undrar jag om det är därför som världen har så svårt att fördra dem_), which suggests a relative clause. The negation placement, AFAIK, would be _det är därför X **inte** är Y_ (let native speakers correct me if I am wrong), indicating a subordinate clause.

**Comment by Stormur** [comment]
> This is an elegant solution (though why the copular root?),

Is it not the same as when you say that "Formally, _därför_ is a predicate here"? That is, the strategy to focus the extracted element is to use it in a kind of existential predicate, which in the languages discussed here happens through a copula.  

> Apparently, it is also possible to use _som_ in such sentences in Swedish (an example from LinES: _Ibland undrar jag om det är därför som världen har så svårt att fördra dem_), which suggests a relative clause.

For sure, and what I referred to as a "trap" is that the remaining part often assumes the form of a relative clause, which is a strategy to make a clause fit into a prototypically nominal slot, and come natural when this clause has a "gap" which you might want to coreference to the extracted element. 

For this Swedish uses _som_, which is actually a `SCONJ`, so I think it is not even warranted anymore to speak of a relative clause rather than generic subordination, and this is shown by the disappearance of _som_ in your examples. The same goes for Italian with _che_, but is slightly different with Latin where the pronoun _qui_ inflects as the original argument would.  

Other strategies are possible and I can think of an Italian one as in 

* _Gianni ha fatto questa cosa_ 'Johnny did this thing'
* a) _È stato Gianni / che ha fatto questa cosa_ 'It was Johnny / who did this thing'
* b) _È stato Gianni / a fare questa cosa_ lit. 'It was Johnny / at doing this thing'

Using the infinitive (_fare_), a verb noun, and a preposition (_a_) as a subordination marker is another way to "nominalise" the clause. My point is that a relative structure comes in very handy and natural, but it is just one strategy.

On the other hand, I do not think that an analysis of the remaining part as _acl_ is motivated, as there is no modification of the extracted element, just coreference at most.
