### ISSUE TITLE
Nominal predicates together with modality.

### ISSUE THREAD

**Issue by lauma** [UniversalDependencies/docs#490]
Hi!
Due to working with Latvian, we got a general question about UD - how it is ment to annotate sentences where predicate consists of a verb describing some kind of modality, a copula and a noun?
E.g., _es gribu būt skolotājs_ "I want to be a teacher".

If I understand correctly, in sentence _es esmu skolotājs_ "I am a teacher", the word "teacher" should be the root, but in the sentence _es gribu peldēt_ "I want to swim",  the word "gribu" is the root. It seems good enough to assume that _es gribu būt skolotājs_ is some kind of composition of the both constructions, but which sould be the top level?

Is the correct way one of the below or something different?
~~~ sdparse
es gribu būt skolotājs
cop(skolotājs, būt)
xcomp(gribu, skolotājs)
nsubj(gribu, es)
~~~

~~~ sdparse
es gribu būt skolotājs
cop(skolotājs, būt)
dep(skolotājs, gribu)
nsubj(gribu, es)
~~~

And if the second one is correct, what label should be used for _gribu_?

**Comment by ftyers** [comment]
If you are treating _gribu_ as a modal auxiliary, then it should probably be:

```
es gribu būt skolotājs
cop(skolotājs, būt)
aux(skolotājs, gribu)
nsubj(skolotājs, es)
```

Otherwise, if you want to treat _gribu_ as a main verb with a non-verbal predicate complement:

```
es gribu būt skolotājs
cop(skolotājs, būt)
xcomp(gribu, skolotājs)
nsubj(gribu, es)
```

**Comment by dan-zeman** [comment]
@lauma : Since you say that _gribu_ is the root in _es gribu peldēt_ (I.e. it is not considered auxiliary in Latvian), the first solution is correct.

**Comment by jnivre** [comment]
If "want" takes an xcomp in "I want to swim", then it also takes an xcomp in "I want to be a teacher", so the only difference is that the second xcomp has a noun as its head. However, it is important not to rely on translation to English, because languages may differ in this respect. So, for example, while English "want" takes an xcomp, the closest equivalent to "want" in Swedish behaves syntactically like an auxiliary. Hence:

En: I want to swim
nsubj(want, I)
xcomp(want, swim)
mark(swim, to)

Sv: Jag (I) will (want) simma (swim)
nsubj(simma, Jag)
aux(simma, vill)

En: I want to be a teacher
nsubj(want, I)
xcomp(want, teacher)
det(teacher, a) 
cop(teacher, be)
mark(teacher, to)

Sv: Jag (I) vill (want) vara (be) en (a) lärare (teacher)
nsubj(lärare, Jag)
det(lärare, en)
cop(lärare, vara)
aux(lärare, vill)

So, you need to decide if Latvian is more like English or more like Swedish.

**Comment by lauma** [comment]
So, basically everything boils down to how we consider "gribēt" in Latvian. Currently it seems that modality for this verb in Latvian is mostly semantical feature, so we will stick to the solution with `xcomp`. Thanks for explaining this!
