### ISSUE TITLE
"according to"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#491]
The English UD treebank is [not completely consistent](http://bionlp-www.utu.fi/dep_search/query?search=according&db=UD_English-v2&case_sensitive=True&hits_per_page=50).

- POS: It looks like the analysis is `VERB` for "according" and `ADP` for "to". Even though "according" is not exactly acting as a verb in this expression (it cannot have a subject, for example), `VERB` seems to be the best tag available given that this seems to be a multiword expression derived historically from a verb + preposition combination.

- Relations: Most trees have `fixed(according, to)` and attach "according" as `case`. I.e., it is treated as a multiword preposition. I agree with this approach because "according" cannot function as an adposition except when followed by "to". There are a few annotations which have both words attaching as `case`—I think these should be changed.

In #488, @sylvainkahane points out that the "to"-PP can be coordinated: "according to John and to Mary". While this shows that the MWE is not as completely fixed as some other MWEs, I still think `fixed` may be the best route available to us.

*The Cambridge Grammar of the English Language* (CGEL) does not recognize syntactically compound prepositions in general, and in general takes an expansive view of the category preposition, so this use of "according" is deemed a preposition. But I think UD treats morphology as a more important consideration for the POS, hence `VERB`.

**Comment by sylvainkahane** [comment]
_according_ is originally a gerundive form of a verb, which lexified as an adverb/preposition as other gerundive forms. When the verb is transitive,the gerundive becomes a preposition (_following_, _concerning_, etc.), when the complement is oblique, it becomes an adverb (_concerning_ (to)).

I think it doesn't really matter if _according_ is tagged `VERB`+VerbForm:Ger or `ADV`, because both have the same distribution.

The only important point here is the analysis of _to_. Of course _according_ is a frozen form of the verb _accord_, but this concerns semantics only. From the syntactic point of view, it still behaves like any word subcategorizing a PP _to_ + `NOUN`. In many UD treebanks, subcategorized words are analyzed as part of their governor with a `fixed` relation. It's very bad from the theoretical/linguistic point of view. And it is very bad from the practical point of view (parsing, etc.), because PP subcategorized by adverbs (or any other POSs) behave more or less as PP subcategorized by verbs.

**Comment by nschneid** [comment]
Also: UniversalDependencies/UD_English-EWT#179
