### ISSUE TITLE
A treebank POS missing in the conversion table

### ISSUE THREAD

**Issue by nesor** [UniversalDependencies/docs#492]
Hi,

There is DET in the Polish treebank, but I didn't find it in the pl::ipipan conversion table. There is also AUX in the Czech PDT treebank, but I didn't find it in the cs::pdt table. Is it because the tables are based on UD v1? 

Thanks!

Alexandr

**Comment by dan-zeman** [comment]
No. While the conversion tables at http://universaldependencies.org/tagset-conversion/index.html are indeed v1 and need to be updated, this is rather related to the disclaimer at the top of that page. Neither `DET` in Polish nor `AUX` in Czech can be derived directly from the source tagset. The conversion procedure has to look at lists of lemmas and (in the latter case) at the tree structure to find out that a particular word should be `DET` instead of `PRON`, and `AUX` instead of `VERB`. Hence these tags will probably not appear in the v2 tables either.

**Comment by nesor** [comment]
Thanks, Dan! Are the conversion procedures available? Perhaps people could contribute and improve them.

**Comment by dan-zeman** [comment]
Yes. They are implemented in Treex (http://ufal.mff.cuni.cz/treex), which is versioned on Github. Specifically, the PRON-DET decision for Polish is currently done here: https://github.com/ufal/treex/blob/master/lib/Treex/Block/HamleDT/PL/Harmonize.pm#L101-L193 and the VERB-AUX decision for Czech can be changed at multiple places, depending on whether it is an auxiliary verb in periphrastic verb forms (https://github.com/ufal/treex/blob/master/lib/Treex/Block/HamleDT/Udep.pm#L409), or a copula (https://github.com/ufal/treex/blob/master/lib/Treex/Block/HamleDT/Udep.pm#L577-L595).

Note: The above URLs point to the current revision of the source code on Github. They will become invalid when the sources are edited.
