### ISSUE TITLE
Multiword preposition "next to"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#496]
Structurally, both words are attached to the noun object as `case`. But the POS tag of "next" is inconsistent: sometimes `ADV`, sometimes `ADP`.

(Related to #491)

**Comment by kimgerdes** [comment]
This is an important question because the problem of complex prepositions causes inconsistencies inside many treebanks and across languages. One of the recently projected tasks is to come up with functional and consistent annotation guidelines for these cases.

The first question is the distinction of function and content words. You say that "Structurally, both words are attached to the noun" and thus that both _next_ and _to_ are function words. In that case next should be a dependent of either the noun or of _to_. This gives two possible analyses: 
1a. _N -> next_. Here the link _N -> next_ should be marked as a special `case:xxx` because it attaches to the whole phrase _to N_. 
1b. An alternative sub-solution could be to preserve the internal syntactic structure and have _N -> to -> next_.

However, syntactically, a preposition is just an adverb that takes a direct object. And _next_ is an adverb that takes an indirect object with the preposition _to_ (just like _according to_ that is discussed in the link you provide). And _next_ can be used without this indirect object: _She runs next_ (Note however that in case of _next_ the meaning differs between spatial and temporal interpretation in presence and absence of the indirect object: _She runs next to Peter_) So a second analysis which is also found in the current English treebank would consider _next_ as the head of _next to N_. This would be consistent with the currently most frequent analysis of cases like _on top of N_, where _top_ is commonly analyzed as the head.

A third analysis would see _next to_ as a complex preposition analyzed by `fixed`. But this is probably the worst choice because the structure is internally transparent and `fixed` should be reserved to irregular structures. 

The situation is similar for French _près de_ or _au dessus de_ or German _mitten in_. Compare also to Chinese 在 山腰 间 zài shānyāo jiān _on/be mountainside between_ 'on the mountainside' where the two "prepositions" _zài_ and _jiān_ attach to the noun from different sides.

We will try to find a way of collecting examples for these cases from different languages in order to come up with a consistent annotation. One way could be a designated wiki page...

**Comment by jnivre** [comment]
I created a page for this: http://universaldependencies.org/workgroups/. The idea is that different working groups can create their own subpage (there are currently two, one for MWEs and one for enhanced dependencies). Feel free to create new subpages (unless you think this belongs under MWEs).

**Comment by nschneid** [comment]
Listed under http://universaldependencies.org/workgroups/mwe.html

**Comment by nschneid** [comment]
I think annotators would be tempted to treat "next to" as `fixed` because the plain adjective "next" has a rather different meaning—contrast "near to":

- The house is near to the post office. (slightly antiquated to include "to"? but grammatical for me)  
   ⇒ The post office is down the road, and the house is near.
- The house is next to the post office.
   ⇏ The post office is down the road, and the house is next. — This would have to mean that one encounters the house immediately *after* the post office, not merely that they are side by side.

Syntactically, we see conflicting evidence:

- Two to-PPs can be coordinated after "next", though the repeated "to" sounds a bit old-fashioned to my ears: Is the house next to the post office or to the library?
- "to" cannot be separated from "next" by fronting:
   * What is the house near (to)? What is near the house?  
   ?To what is the house near?
   * What is the house next to?  
   *To what is the house next?

**Comment by amir-zeldes** [comment]
I'm not particularly opposed to making it `fixed`, though I'd like to keep pos consistent with PTB/ON & co. (RB+IN, so upos ADV+ADP). In GUM it's consistently an adverb 'next' dominating an `obl` argument with 'to' as `case`, which seems reasonable enough if we don't want `fixed`. TBH I'm not very bothered about how it is right now either, so we could also save the work and just leave it. But if you feel strongly about it it's not hard to change to fixed.
