### ISSUE TITLE
Ideophones in Erzya and English, what is the deprel

### ISSUE THREAD

**Issue by rueter** [UniversalDependencies/docs#511]
Ideophones are often classified as Interjections for part-of-speech. Instead of describing a subjective emotion expressed by the speaker as a result of an event (e.g. Ouch! he said. Wow! she said.), ideophones are vocalizations that illustrate events, such as Poof! the fairy disappeared.
Since the words can be reordered: He said "wow". She said "ouch", the first two (ouch; wow) might be seen as displaced. But displaced What? 
discourse(said, Wow)
displaced(said, Wow)
parataxis(Wow, said)

The word "poof", however, is more of a vocalization followed by an elaborating appositive predication.
appos(poof, disappeared)
Bang! the gun went off.
appos(bang, went)
The gun went bang.
obj(went, bang)

I am not satisfied with my own solutions. Perhaps those working with Japanese, Korean, Hausa, Ewe etc. will have some suggestions

**Comment by jnivre** [comment]
I think parataxis is the least evil here. The dislocated relation is for displaced arguments or argument-like phrases and should not be used, and I don't think there is a clear discourse function either. In fact, in the fairy example, there seem to be two independent clause-like entities, which could have been written as two separate sentences:

Poof! The witch disappeared.

This suggests to me that parataxis is the right relation, with the relation going from "Poof", the head of the first clause-like entity to "disappeared", the head of the second clause.

**Comment by lauma** [comment]
Inside the Latvian UD part we recently also had some discussion about idiophones and interjections. We concluded that at least in Latvian interjections tend to creep in the roles usually fulfilled by nouns, e.g., one can say not only _viņš pateica paldies_ (he said a "thank you") or _viņš teica au_ (he said ouch), but also _man nevajag tavu paldies_ (I don't need your "thank you"), where possessive takes accusative case (_tavu_) similarly as it would with a noun object - _man nevajag tavu māju_ (I don't need your house). We also noted some examples, where interjections act similarly to attributive modifier or even subject - _tējkanna saplīsa ar brākš troksni_ (teapot broke with a grakh noise) and _skaļš bum bija dzirdams no otras istabas_ (a loud boom was heard from other room). Also, due to Latvian morphology we are rather sure that these are interjections, not nouns, because (a) words I used in samples don't have characteristic Latvian noun endings and are indeclensible, and (b) Latvian has actual declensible nouns for describing most of these sounds (_blīkšķis_ for _blīkš_, _brākšķis_ for _brākš_, _krakšķis_ for _krakš_, _zlankšķis_ for _zlankš_, etc., except there is no direct noun coresponding to interhection _paldies_).

Meanwhile the argument about the word order turned out not be particulary helpfull in our case, as for the sake of emphasis Latvian allows a lot of word order change anyway.

Thus, at least for now we allow to annotate at least some ideophones as core roles even, especially when predicate is related to someone speaking or something making noise. However, I don't know, if it is a good idea for less inflective languages.

**Comment by jnivre** [comment]
It is clear that any word or phrase can be used as a noun when quoted or forming part of a title, etc., and I wouldn't expect interjections to be any different. When they are, they should be given the proper syntactic relation, but there is no need to change the part-of-speech tag. This is discussed under "Using a word vs. mentioning it" in the guidelines on Morphology: http://universaldependencies.org/u/overview/morphology.html

**Comment by lauma** [comment]
What I am suggesting is: maybe "wow" in "He said "wow"" is just an object, not parataxis?

**Comment by jnivre** [comment]
That seems perfectly fine to me. The parataxis relation should only be used for speech verbs when they are parenthetical or post-posed.
