### ISSUE TITLE
Shared dependents and governors in coordination

### ISSUE THREAD

**Issue by perrier54** [UniversalDependencies/docs#524]
1)	Basic dependencies. 
According to the annotation guide, shared dependents and governors are attached to the head of the first conjunct.
This principle cannot apply when a dependent is not shared by the heads of the two conjuncts but by words more or less deeply embedded in the conjuncts. Consider the following example:
_Il pense obtenir et obtiendra sûrement son diplôme_ (word for word : _he thinks to get and will surely get his degree_)
The word _"diplôme"_ is an object shared by the verbs _"obtenir"_ and _"obtiendra"_. The problem is that _"obtenir"_ is not the head of the first conjunct. I propose to attach the shared depend to the closest governor, _"obtiendra"_ in this example. This proposal is consistent with the idea of surface dependencies.
In the previous example, the closest governor is in the second conjunct, but if the shared dependent precedes the coordination, the closest governor is in the first conjunct, as in the following example:
_Le livre qu'il doit présenter mais connaît mal (the book he has to present but knows badly)_
In this example, the relative pronoun _"qu'"_ is an object shared by the verbs _"présenter"_ and _"connaît"_. According to our principle, it will be attached to _"présenter"_.
I propose to apply this principle, even if the governors of the shared dependents are the heads of the conjuncts. Consider the following example:
_I read and liked this book_
I propose to attach the shared object _"book"_ to _"liked"_.

2)	Enhanced dependencies
For shared governors, I propose to change nothing with respect to basic dependencies, that is, to attach them to the head of coordination. In this way, sentences _"John and Mary met yesterday"_ and _"the students met yesterday"_ are annotated similarly.
For shared dependents, I propose to distribute them on the conjuncts, even if it is not justified semantically.
Consider the example: _John and Mary, who met yesterday_
At the enhanced level, I propose to distribute the ACL:REL dependency on _"John"_ and _"Mary"_ as its source.

**Comment by martinpopel** [comment]
Good point. I agree that "diplôme" should be attached to "obtiendra" (head of the second conjunct) in basic dependencies (and that there will be no clue in the basic dependencies that the object is shared also with "obtenir").

I like your suggestion for changing the guidelines to attached shared dependents to the head of the **nearest** conjunct instead of the **first** conjunct. I know it will be controversial because it means backward non-compatible changes and re-annotating many sentences, which cannot be done fully automatically because in basic dependencies we cannot be sure whether a given dependent is shared or not. The reason why I like your suggestion is that the nearest conjunct is usually the **sure** one, while sometimes it is unclear whether it is actually shared dependent of the non-nearest conjunct (e.g. "big apples and oranges" - Are onranges big?).

I expect someone will suggest an alternative solution - keep clear cases as in UD 2.0 and use this rule only for the cases as you described (when the shared dependent is not attached to *all* heads of the conjuncts).

We should be also aware of the cases when the shared dependent is **between the conjuncts**, so it is not easy to say which one is the nearest one, e.g. *There comes a **man** and goes away.*

**Comment by perrier54** [comment]
If my suggestion is adopted in the guidelines, the re-annotation of corpora will not be a difficult task because it can be done automatically: when a dependent that follows a coordination is attached to the head of the first conjunct, it will be attached to the head of the last conjunct.
In some cases, the transformation will not be correct, when the dependent must be attached deeply in the second conjunct, for example :
_Il aime bien et souhaite rencontrer cet écrivain (he likes and hopes to meet this writer)_
Automatic re-annotating will attach _" écrivain "_ to _" souhaite "_, whereas it must be attached to _" rencontrer "_. Nevertheless such cases are very rare.


@martinpopel   raises the problem of shared dependent between the two conjuncts, giving the following example:
_There comes a man and goes away._
In my opinion, this is not a problem : the dependent is before the conjunction of coordination and the rule applies, it must be attached as closely as possible, that is, in the first conjunct to _"comes"_.

**Comment by martinpopel** [comment]
> it must be attached as closely as possible

I don't say it is a problem, we just need to define clearly what does "closely as possible" mean. Imagine e.g.
*There comes very quickly a man and goes away.*
Here according to the word-order distance *man* is closer to *goes* than to *comes*, but it seems counter-intuitive to change the attachment of *man* just because *very quickly* was added.

> re-annotation of corpora will not be a difficult task ... In some cases, the transformation will not be correct.

Yes, this is what I meant by "cannot be done fully automatically". The basic re-annotation rule is simple: if a node depends on a conjunct, but it is not the closest conjunct, re-attach it to the closest one. The problem is with the definition of closest (as noted above) and with possible non-shared dependents which are now (for whatever reason) attached to non-closest conjunct. In general, the problem is that in the basic dependencies, there is no reliable distinction between shared and private dependents. There is just a heuristics: if it depends on non-closest conjunct then it is most probably shared.

If the re-annotation takes place, it would be wise to add enhanced dependencies automatically at the same time, so no information is lost. (After the re-annotation, we cannot use the above-mentioned heuristics.)

**Comment by dan-zeman** [comment]
Changing the guidelines would be a long-term goal; at present there is no schedule for UD v3. And I do not think the benefit is so great to justify re-annotation of 100+ treebanks.

On the other hand, examples like _Il pense obtenir et obtiendra sûrement son diplôme_ (however marginal they are) need a solution and this solution will be just a more detailed specification of the current guidelines, rather than changing the guidelines. Attaching the object to the second conjunct in this case looks like one of the acceptable options.

**Comment by sylvainkahane** [comment]
I just want to add some linguistic data to the debate. Data are from French but I’m sure that similar constraints occur in other languages if not all.

First, agreement. French adjectives agree with the noun they depend on and in case of coordination, the masculine wins (this was imposed by male grammarians in the 17th century and the rule is under debate now). So we have:

> une assiette et un plat blancs
> a-FEM plate and a-MASC dish white-MASC.PL

It is very difficult to produce and to accept:

> ??un plat et une assiette blancs

It seems that the last conjunct must be masculine because the adjective is at the masculine form. I remember that some studies show that before the application of the 17th century rule, the agreement was with the last conjunct and the correct form would have been:

> un plat et une assiettes blanches
> a-FEM plate and a-MASC dish white-FEM.PL

Second, subcategorization.

> Faut-il arrêter ou continuer à rembourser la dette ?
> Must we stop or continue to repay the debt?

This is perfectly acceptable even if the subcategorisation of _arrêter_ is _de_ + Infinitive and not _à_ + infinitive.
But the reverse order is unacceptable:

> *Faut-il continuer ou arrêter à rembourser la dette ?

So again it seems that the last conjunct constrain the shared dependent much more than the first conjunct.

It does not mean that we must change 100+ treebanks but it is likely that the initial choice was not linguistically relevant.

**Comment by dan-zeman** [comment]
@sylvainkahane I see your point and it is valid of course, but UD is a compromise that tries to satisfy various conflicting goals. This sort of linguistic relevance is one of the goals but we cannot always satisfy it – for example, we do not make auxiliary verbs heads although they are the verbs that morphologically mark features of subjects.

I think the main claim from the UD point of view here is that there is a constituent C, modified by a constituent M; the consitutent C is coordination _(une assiette et un plat)_; and M _(blancs)_ modifies the entire coordination, which here also happens to be supported linguistically, namely by the plural suffix.

The edge between _assiette_ and _blancs_ is then just a technical consequence of an (also technical) decision that coordination is always represented by the head node of the first conjunct. If UD had a mechanism of distinguishing modifiers of a phrase from private modifiers of the head of the phrase, it would be clear that one must first take _assiette et plat_ as the combined head, and only then study the agreement with _blancs_.

**Comment by sylvainkahane** [comment]
@dan-zeman  Our answer is interesting because it touches the foundations of dependency and constituency.
We are analyzing a configuration X & Y M, where M is a so-called shared dependent of X and Y. So we are tempted to consider that X & Y form a constituent C and M depends on C. In fact, it is not possible to encode this analysis in DG: we cannot attach M to C, we have to decide to what word in C M is attached. Even if you attach M to the head X of C it means that M depends on X, not C.

The second problem (which is even more problematic I think) is that it is not absolutely clear that C is the only interesting "constituent" of the configuration X & Y M. If we look at the combination XM and YM, it appears that YM is quite motivated (and more than XM). That was my point concerning agreement and subcategorization. So we could be interested in considering YM also as a constituent. And that's exactly where constituency syntax and dependency syntax mainly differ. Constituency forces you to chose between the two possible decompositions (X&Y + M) or (X + &YM) (Gleason 1955/1961) and it is reasonable to consider that the first decomposition is the most important, at least at the semantic level. But dependency does not force you to make this choice: you can both say that X and Y combine and that Y and M combine.

To conclude, the analysis of this construction we defend is that M first combines with Y and then the link between X and M is inherited (cf. Gerdes & Kahane at Depling 2015). Of course, such an analysis cannot be formalized with a tree, but if we impose to only keep a tree, we think that the link between Y and M must be favored towards the link between X and M.

(The discussion about the foundation of dependency and constituency is developed in two papers: Gerdes & Kahane at Depling 2011, and Kahane & Mazziotta at MOL 2015.)

**Comment by dan-zeman** [comment]
Well, _blancs_ is `Gender=Masc` AND `Number=Plur`. The masculine gender supports your claim that it first combines with Y (_plat_). The plural number suggests that it combines with the entire C.

Is there a reason to say that the gender feature is more important than number?

**Comment by gossebouma** [comment]
You can use agreement in/of relative clauses to find similar puzzles in the Dutch:

[De grote publiekstrekkers van Oudenaarde zijn echter het stadhuis en de kerk van Sint-Walburga , die beide aan de markt liggen ](http://haytabo.let.rug.nl:8067/tree?db=lassysmall&names=true&mwu=false&arch=/net/corpora/paqu/lassysmallmeta.dact&file=wiki-7543.p.13.s.1.xml&global=true&marknodes=20)
(the big attractions of Oudenaarde are however the city-hall and the church of S.W., which both are located on the market)

The pronoun _die_, the verbal form _liggen_, and the adverb _beide_ (_both_) all suggest a plural antecedent. I should admit that in the annotation from which we generate the UD (in the link), the relative is also annotated as being a dependent of both nouns, not of the conjunction as a whole.

**Comment by jnivre** [comment]
We had a discussion about proximal agreement and related phenomena at one of our first meetings (http://universaldependencies.org/2015-08-23-uppsala/coordination.html). We concluded that there was not sufficient evidence for abandoning the general principle that, in the interest of cross-lingual consistency, all coordination should be annotated by attaching other conjuncts and shared dependents to the first conjunct. So this is what we have for v1 and v2.

**Comment by dseddah** [comment]
@dan-zeman " Is there a reason to say that the gender feature is more important than number?"
at least in French and (some) romance languages, gender is not marked in the verb flexion (except for past participles of course but that's a another story). 
(he/she eat)

il/CL-MS mange-V-S
elle/CL-FS mange-V-S

(they eat)
ils/CL-MP mangent-V-P
elles/CL-FP mange-V-P

so I wouldn't say gender is more important that number.

**Comment by sylvainkahane** [comment]
@dseddah If you consider spoken French (and spoken language is the true language, the one you speak at five when you are already a speaker), it is clear that gender is much more marked in French than number.

@dan-zeman But I don't understand this question about number and gender, because you don't have the number agreement with one of the conjunct. It is difficult in a dependency-based representation to consider that X is equivalent to the partial projection X&Y.

@jnivre I don't understand why attaching shared dependents to the first conjunct is better for cross-lingual consistency. And it doesn't seem that shared dependents are discussed in the link you give.

**Comment by dseddah** [comment]
> Le 25 janv. 2018 à 15:41, sylvainkahane <notifications@github.com> a écrit :
> 
> @dseddah If you consider spoken French (and spoken language is the true language, the one you speak at five when you are already a speaker), it is clear that gender is much more marked in French than number.

You’re probably right for spoken Fr, would be interesting to see evidences  though (I’m sure it already exists).  Anyway, that’s not the case with other romance languages, where spoken is much closer to written forms.


Djamé

**Comment by perrier54** [comment]
I agree with @sylvainkahane  on his last statement : the examples given in [http://universaldependencies.org/2015-08-23-uppsala/coordination.html)](http://universaldependencies.org/2015-08-23-uppsala/coordination.html) concern shared governors and no shared dependents. For shared governors, I agree with the proposal of attaching the dependency from the shared governor to the head of the coordination regardless of the agreement.

For shared dependents, I didn't see any good arguments to attach them to the head of the coordination but I gave good arguments to attach them in the nearest conjunct.  I give a new example to illustrate my proposal:
_Je vais acheter et je rapporterai tout de suite le médicament_ _(I am going to buy and I will immediately report the drug)_
If we attach the object _"médicament"_ to the head _"vais"_ of the coordination, we obtain a dependency which has no sense in French because the verb _"aller (go)"_ in French cannot admit a nominal object. 
With my proposal, _"médicament"_ is attached to _"rapporterai"_, which makes sense in French.

**Comment by jnivre** [comment]
It is true that shared dependents are not discussed on the page I pointed too, but I think they were discussed at the meeting. Sorry for not being clear about this.

As for cross-linguistic consistency, my point was not that one of the analyses is per se better than the other, only that we want some analysis to be applied consistently. And since attachment to the first conjunct (of both governors and dependents) is what we currently have as the standard, it would be a major effort to change this in all treebanks. Therefore, we need to be convinced that a change would constitute a major improvement with respect to several of the desiderata of UD before we undertake it. This falls under Ginter's Razor ("Do not multiple changes beyond necessity!"), an important complement to Manning's Law.

**Comment by dseddah** [comment]
@perrier54, there's an extensive discussions about right-node rising here
https://github.com/UniversalDependencies/UD_v2/issues/16
and shared arguments here too
http://universaldependencies.org/v2/enhanced.html
and here as well   
http://universaldependencies.org/v2/ellipsis.html

@all 
While I'm here I'm not sure I understand the rationale behind the ghost token naming scheme..
1 John
2 loves 
3 Mary
4 and
5 Paul
5.1 (e)   #the ghost tokens
6 Virginie

in that case, the elided predicated will be coordinated with loves and so we can retrieve it but in a more complicated case  as in the exemple from the doc:
Mary wants to buy a book and Marie (e)_8.1 (e)_8.2  a CD
I'm wondering why the reference token id was not kept instead of a counter. 
as in Mary wants_2 to buy_4 a book and Marie (e)_8.2 (e)_8.4  a CD   

This could enable a more direct learning of such structures without potentially resorting to a more or less complex retrieval process. 
  

Djamé
