### ISSUE TITLE
Spanish translation for the entire documentation

### ISSUE THREAD

**Issue by michaelizer** [UniversalDependencies/docs#529]
Greetings,

I would love to contribute to the project with the Spanish translation, primarily to help Spanish speakers understand and get involved into it. Spanish is my native language so don't panic. I work for the Utopian.io community. Say it and I'll start immediately.

Thanks in advance for your time.

**Comment by dan-zeman** [comment]
It would be obviously useful to have but I'm afraid it would get out of sync sooner or later. "The entire UD documentation" is not a fixed body of text, it is constantly evolving and it will never be finished. If the Spanish translation shall help the users rather than confuse them, then all translated pages should contain a disclaimer pointing to the source text, indicating the exact revision that was used as source, and warning that a newer English version may exist.

**Comment by michaelizer** [comment]
>then all translated pages should contain a disclaimer pointing to the source text, indicating the exact revision that was used as source, and warning that a newer English version may exist.

sounds good fo me
