### ISSUE TITLE
Elided non-predicates in enhanced dependencies

### ISSUE THREAD

**Issue by lauma** [UniversalDependencies/docs#533]
Enhanced dependency description suggests to use null node for elided predicates. Treebank we convert Latvian UD from does the same not only for predicates but also for other parts of sentence if such part has dependants.

For example, _Es dzeru baltu kafiju, tev patīk melna_ "I drink white coffee, you like black [coffee]" would feature elided node for coffee in original data, because this missing _kafija_ "coffee" has a dependant _melna_ "black". In example _Es dzeru baltu kafiju, bet tu melnu_ "I drink white coffe, but you [drink] black [coffee]" original data would have two elided nodes - one for elided predicate and one for elided object.

Is it okay to have elided object/subject/etc. in such cases (they have their own dependants, e.g., `amod`, `nmod`, `nummod`) in enhanced graphs?

**Comment by jnivre** [comment]
UD is very restrictive null nodes, so they should only be used for predicates in gapping constructions. For noun phrases we simply promote the adjective or similar to be the head of the phrase. Please see the guidelines.

**Comment by lauma** [comment]
Thanks. We corrected our data for v2.2.

**Comment by msklvsk** [comment]
…but why? What is the reason to reject such valuable info? We can explicitly mark the elision type in `MISC` if it can’t be derived. Having the same issue as Lauma.

**Comment by jnivre** [comment]
In order to fulfil its practical purposes, UD needs to be suitable for rapid consistent annotation as well as computer parsing with high accuracy. It also needs to be understandable to people without deep knowledge in linguistics. If we try to capture too many details in the annotation, it will become unusable in these respects. Exactly where to draw the line can of course be discussed, but regarding ellipsis this is where it is currently drawn. Please check the "Introduction to UD" section of the documentation to learn more about the "compromise philosophy" behind UD, also referred to as "Manning's Law".

**Comment by msklvsk** [comment]
I’m familiar with the law. To me it’s just a weird place to draw the line. There already is an infrastructure for null nodes: the format, annotation and visualization tools, but now we refuse to use it for nominal ellipsis, which shouldn’t be more complex than predicates. Not sure where it contradicts the law.

**upd**
I can easily imagine arguments you provide in [Sentences with Gapping: […]](https://nlp.stanford.edu/pubs/schuster2018gapping.pdf) applied to other types of ellipsis.

**Comment by jnivre** [comment]
The current policy is to keep the use of the orphan relation (and null nodes in enhanced) to an absolute minimum. Therefore, we limit their use to structures involving predicates and core arguments. This is admittedly somewhat arbitrary, but we think it is a good place to draw the line in order to promote consistency across languages and treebanks.

**Comment by msklvsk** [comment]
(Just leaving it here.)

_The-export of-goods from Northern region increased by 125%, from-Western — by 83%, …_

Both the predicate _(increased)_ and the subject _(the-export)_ are elided. If we allow to reconstruct only predicates, we have `nsubj`(_[increased]_, _Western_) — bad for NLU, which was the main point for reconstruction.
