### ISSUE TITLE
mark versus case deprels

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/docs#537]
The deprel `mark` introduces clauses:

http://universaldependencies.org/u/dep/mark.html
> A marker is the word introducing a finite clause subordinate to another clause. 

But the `case` deprel description can also be used for clauses? See the  'noun or clause' in the last sentence in the fragment below:

http://universaldependencies.org/u/dep/case.html
> The case relation is used for any case-marking element which is treated as a separate syntactic word (including prepositions, postpositions, and clitic case markers). Case-marking elements are treated as dependents of the noun or clause they attach to or introduce.

**Comment by nschneid** [comment]
Good point—guessing that "clause" shouldn't be there. For example, in the UD_English-EWT corpus *of* in *thinking of waiting* is treated as a subordinator with `mark`.

**Comment by jnivre** [comment]
Yes, this is a mistake. I actually fought for allowing "case" also with clauses, because I think there are cases in Swedish where you lose a generalisation otherwise (and my colleague @LarsAhrenberg agrees), but I lost this battle and have changed the annotation for Swedish in order to be consistent with other languages. See #257.

I will update the documentation.

**Comment by gossebouma** [comment]
So does this mean that in general, whenever a finite clause is introduced by a preposition, the preposition should be assigned the rel mark instead of case? In Dutch there are verbs selecting for a obl PP that can contain either an NP or a clause:

hij overtuigd hem van zijn gelijk 
he convinces him of his point-of-view

hij overtuigd hem er van dat Arnhem kan worden veroverd
het convinces him EXPL of that Arnhem can be conquered

So, depending on whether the dependent is clausal or nominal, the preposition is mark or case. That sounds ok to me, as the idea of having case as dependent of a verbal head is not very intuitive either. 

In the English data, it seems the preposition is usually assigned pos-tag SCONJ, but could it also just be ADP? In the Dutch examples, the prepositions that show up in this construction are clearly the same as the prepositions heading nominal obliques, so no reason to distinguish them I think.

**Comment by jnivre** [comment]
Yes, this is what the current guidelines say. The examples in Dutch are parallel to the ones in Swedish that I originally thought motivated a "case" analysis. Maybe we are suffering from "anglocentricity" here, as it seems that English is peculiar among Germanic languages in not readily allowing prepositions with nominal clauses. :)

The question of whether "mark" implies "SCONJ", or whether it is okay to use the postag "ADP" is an issue that I don't think has been fully resolved. It is parallel to other similar issues, such as the DET-PRON distinction. The Swedish-Talbanken treebank uses ADP, which I think is a reasonable way of capturing the distinction between this phenomenon and regular subordinating conjunctions.

**Comment by sylvainkahane** [comment]
In French (as well as in many other languages), a NOUN, an infinitive VERB and a finite verb introduced by a SCONJ can commute in many syntactic positions (see the transfer theory of Tesnière about infinitive and SCONJ). It is true in subject positions, in object positions and after a preposition. It would be very problematic considering that an ADP cannot introduce an infinitive verb or a finite clause.
 
In particular it is possible to have a first transfer of a finite verb by a SCONJ and a second transfer of the resulting phrase by an ADP (see third ex) : 

> pour ça
> for that
> 
> pour manger
> for to_eat
> 
> pour que Bob mange
> for that Bob eats
> ADP SCONJ PNOUN VERB

In the last example, the best analysis is certainly to consider that the SCONJ _que_ is `mark` and that the ADP _pour_ is `case`. Currently, such constructions are analysed with _pour que_ as a fixed expression, but I consider it's an artefact of the current guidelines and not a linguistically motivated analysis.

**Comment by jnivre** [comment]
It is precisely because of the third type of example that we keep ADP in Swedish, to distinguish it from the first transfer, which is SCONJ. However, the syntactic relation is mark in both cases.
