### ISSUE TITLE
The preposition between iobj and obl

### ISSUE THREAD

**Issue by Stormur** [UniversalDependencies/docs#542]
Reading [the tutorial](http://universaldependencies.org/eacl17tutorial/intro.pdf), at page 5 I found this example:

`Valencia da la bienvenida a los participantes de EACL`
`Valencia welcomes the participants to EACL (= "... gives the welcome to the participants ...")`

Now, we find here the deprel `iobj(da,participantes)`. However, in the [documentation](http://universaldependencies.org/u/dep/iobj.html) we read explicitly that such a case has to be treated as `obl`. Is this just an error or simply coming from the interlinguistical counterintuitiveness of this rule (see "the dative alternation")?

In fact, an `obl` deprel should be "a non-core (oblique) argument or adjunct. This means that it functionally corresponds to an adverbial attaching to a verb, adjective or other adverb." However, we might argue that `a los participantes` is very much core to the verb `dar`, "give". Also, staying with Spanish, sometimes the direct object is expressed with an a:

`Veo a Marìa`
`I see Mary`

Here `a Maria` is clearly the "second most core argument of a verb after the subject", but it should be labeled `obl`.

Would it be thinkable to admit prepositional phrases as `obj`s and `iobj`s?

**Comment by jnivre** [comment]
The tutorial example (embarrassingly enough) is an error. It should have been obl. Thanks for catching this.

The Spanish obj with prepositions is a special case, because Spanish regularly (for all verbs) use a preposition in case the direct object is (a) animate and (b) specific. Hence, it has minimal pairs like:

busco una secretaria = I am looking for a secretary (non-specific)
busco a una secretaria = I am looking for a (certain) secretary (specific)

Since this is completely regular and applies to all transitive verbs, it is reasonable to say that we have an object in both cases.

In general, therefore, whether an obj can be marked with a preposition has to be decided on a language by language basis. There are even languages (I understand) where all core arguments are marked by adpositions. For a language like English, however, the second argument of a primary transitive verb is never marked by a preposition, so in that case a prepositional phrase should always be regarded as oblique, regardless of whether it is an argument or an adjunct.

The key issue here is that the core-oblique distinction is not the same as the argument-adjunct distinction. Some theories make a thee way distinction between core arguments (essentially subjects and objects), oblique arguments, and adjuncts. UD only distinguishes between core and non-core, and hence lumps oblique arguments together with adjuncts. This is because, by and large, the distinction between core and non-core is based on overt morphosyntactic encoding and can therefore be applied more consistently in annotation than the more subtle argument-adjunct distinction.

**Comment by Stormur** [comment]
OK, so probably my confusion lies in thinking more semantic-orientedly than morphosyntactic-orientedly, and I can understand the different take on cores and adjuncts. 
However, don't you think that "dative phrases" in some languages, e.g. in Italian, are regularly enough introduced by an adposition to warrant them the status of `iobj`, using the same point as for a-direct objects in Spanish? For example:

`Do il libro al mio amico`
`I give the book to my friend`

The dative case will always be expressed by means of `a`=`to`, and only pronouns have a dative form (in this case `gli`=`to him`); there is no other possible construction like `I give my friend the book` in English.    

In any case, I might suggest to rephrase future versions of the documentation regarding `obj`, `iobj` and `obl`, particularly with regard to the coreness of an argument. Besides, the treatment of "double object constructions" looks a little bit Anglocentric.

**Comment by amir-zeldes** [comment]
+1 for allowing obj with an adposition (this is normal e.g. in Japanese, and many languages alternate by construction, e.g. Hebrew, Coptic)

**Comment by bulbulistan** [comment]
We’re talking about differential object marking here, aren’t we? So it’s a
question of, well, differences in marking of the object based on various
semantic criteria, but the primary criterion is still the coreness of the
argument and, by extension, the valency of the verb. Take Spanish “amar” in
“Amo a Lucía”: the “a” does not change the valency frame of the verb,
 “Lucía” is still an obj.


El dv, 13 abr 2018 a les 15:20 Flavio <notifications@github.com> va
escriure:

**Comment by jnivre** [comment]
Yes, that is precisely the point. There is no general rule in UD that says that a core argument can never be accompanied by an adposition. It all depends on how core arguments are encoded in the given language. But it has to apply to all (or the majority) of core arguments and shouldn't depend on lexical properties of the verb. 

I agree that "dative objects" in Romance (and other) languages are borderline. One possible analysis is to say that they have a non-core encoding with full noun phrases but a core encoding with pronouns. And the dative case is problematic in many languages, since it seems to behave like core in some respects and non-core in others.
