### ISSUE TITLE
fixed having dependents

### ISSUE THREAD

**Issue by tzshi** [UniversalDependencies/docs#543]
Although not explicitly mentioned in the documentation (or I didn't find it), it seems that for `fixed` (and maybe applies to `flat` as well) MWEs, the current analysis assumes a rather flat structure that the first word is treated as the head, and all other words are dependents to the first word. Out of this "local" structure, the entire MWE will behave as a single unit. 

There are some current annotations, however, having a node with `fixed` relation (meaning that it is not the first word of the MWE) with its own dependents. 

Queries with Grew is here: http://match.grew.fr/?custom=5ad0e89d131b1&corpus=UD_English
These cases can be found in multiple languages. I'm wondering whether this should be added into the automatic check as well?

In my current query, I excluded the case of `fixed` having `punct` child, as in the Czech example:
než-li
where "-" is currently attached to "li". One might argue that punctuation should be attached to the head word as well.

**Comment by martinpopel** [comment]
I agree, the guidelines should say whether a non-first word of a `fixed` or `flat`structure may have any dependents or not (in which case it is easy to automatically re-attach them to the first word). Currently, I don't see any reasons for such dependents.

As for the Czech "než-li" example: usually upos=PUNCT implies deprel=punct and in that case, there is [a rule](http://universaldependencies.org/u/dep/punct.html) for attaching punctuation to the *dependent* unit (which is "li", not "než"). There is an exception which allows upos=PUNCT and deprel=fixed, but it is a question whether to exploit this exception also for hyphens (and commas), which are clear cases of punctuation.

**Comment by sylvainkahane** [comment]
I agree that the dependent of a `fixed` construction can only be on the first node.
But not for `flat`. `flat` is for headless constructions, not for frozen constructions: AB is `flat` if you cannot decide which of A and B is the head. But A and B can be complex phrases.

**Comment by jnivre** [comment]
@sylvainkahane  is right. There is a clear difference between `fixed` and `flat`in this respect.

**Comment by martinpopel** [comment]
OK, so
- the documentation of `flat` needs an example where non-first word has (non-`flat`) dependents
- the documentation of `fixed` needs a rule that non-first words cannot have (non-`punct`?) dependents.

What about the punctuation in fixed expressions?
Should we make an exception that `punct` can be attached to `flat`? Or should we make (explicit) an exception that PUNCT can be `fixed` (instead of `punct`)?
Should all punctuation within a `fixed` phrase be automatically annotated as `fixed` (and attached to the first word)?

**Comment by dan-zeman** [comment]
I think that punctuation should be always attached as `punct` and never as `fixed`. I would also support the rule that punctuation is exception and can be attached (if it accords with the other rules for punctuation) to a word whose deprel is `fixed`.

**Comment by dseddah** [comment]
never as "fixed" ? idk, how about  dashes in cities name (Pont-à-Mousson) or in some multi word expression such as "peut-être" (maybe), "c'est-à-dire" (meaning, that is,..)  those punctuations are part of the mwe and so should labeled as fixed.

**Comment by mcdm** [comment]
The words you give as examples should probably not be split, I think.

**Comment by jnivre** [comment]
I agree. Why go to the trouble of splitting them only to connect them by "fixed"?

**Comment by martinpopel** [comment]
There are no clear universal guidelines when to
* keep as one token and one word
* keep as one token, but multiple words (using multi-word token)
* split into multiple tokens with SpaceAfter=No.

According to @dan-zeman there should be language-specific guidelines for this. My suggestion is: it should be consistent within the language (and related languages) and for a given punctuation symbol. We probably always want to split (and use SpaceAfter=No) commas, question marks, sentence-final period etc. But apostrophes and hyphens are language specific. E.g. in language X they always imply a token boundary (so the tokenization is simple and deterministic and the difficulties are only in distinguishing multi-word tokens from single-word tokens), but in language Y we may decide that these punctuation symbols can be inside a token, or even inside a word. Depending on the answer to this question for French, there may be a reason for splitting on dashes and connecting with `fixed` (because of consistency with other French examples). However, it seems that UD_French (v2.0) is consistent in keeping hyphens inside words, but inconsistent in apostrophes: e.g. *c'est* is tokenized into two tokens (and two words), but *c'est-à-dire* is kept as one word.

French *éditeur-en-chef* is kept as one word, but English *editor-in-chief* is tokenized into five words (with SpaceAfter=No and deprels `case` for "in", `punct` for "-" and `nmod` for "chief", i.e. without using `fixed`). I am not saying this is necessarily wrong. I know this cross-lingual inconsistency may be a result of intra-language consistency (English uses hyphens in so-called "compound adjectives" like *user-generated*, which we clearly want to split).

**Comment by dan-zeman** [comment]
Even if the hyphen is a separate token and part of a fixed expression, it does not necessarily mean that it must have the `fixed` deprel. It can still be `punct` if the special rule for punctuation gets higher priority than the special rule for fixed expressions. Elsewhere, punctuation is part of coordination and we also attach it as `punct`, not as `cc`.

**Comment by nschneid** [comment]
What do people think of the proposed language in #770? (Addresses `flat` only, not `fixed`.)

**Comment by dan-zeman** [comment]
Sounds good to me.

**Comment by nschneid** [comment]
The `flat` guidelines are now updated.

I do see coordination of `fixed` dependents in Irish: http://match.grew.fr/?corpus=UD_Irish-IDT@dev&custom=6044e7d28cee8 @tlynn747 @kscanne Is this intentional? If so, should it be allowed as an exception?

**Comment by kscanne** [comment]
I'd prefer seeing "mar sin" annotated as a standard PP and not `fixed` since it certainly has that internal structure. Doing so would clean up these examples — no exception to the guidelines should be necessary.

**Comment by nschneid** [comment]
Updated https://universaldependencies.org/u/dep/fixed.html. I assume `goeswith` and `reparandum` dependents are also allowed (as well as `punct`).

**Comment by nschneid** [comment]
I think the guidelines updates have resolved this issue
