### ISSUE TITLE
Adverbish phrases with nominative nouns e.g. cheek to cheek

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#557]
How do you annotate _“We’re out together swinging **cheek to cheek**.”_?

**Comment by dan-zeman** [comment]
Noun phrases that function as adverbial modifiers are attached as `obl`, no?

**Comment by msklvsk** [comment]
Just checking if `Case=Nom` won’t be a problem for `obl`. Also it feels like cheeks are modifying some elided verb in parallel, therefore I’m not sure if it’s `nmod`(_cheek_, _cheek_).

I should have asked about _“The children tease **one**.Nom **another**.Acc”_ first. Each TB does it differently.

**Comment by nschneid** [comment]
At first I thought "cheek to cheek" might be a secondary depictive, and thus `acl`. But I suspect it's more of a manner adverbial. As noted on the `advmod` page: "We differentiate adverbials realized as adverbs (`advmod`) and adverbials realized by noun phrases or adpositional phrases (`obl`)." Is it a noun phrase, though? Feels more like a compound adjective or adverb to me.

For "each other" and "one another" EWT uses `det`, which seems reasonable enough. "other" is tagged as `ADJ` and "another" as `DET`. I would say that holistically "each other" and "one another" act as accusative reciprocal pronouns, but I guess there's no way to encode that in dependencies if the individual words are treated as syntactic tokens.

**Comment by jnivre** [comment]
I agree it is adverbial. Historically, I think it is a clausal absolutive construction. Compare "dancing cheek to cheek" to "entering cap in hand", for example. Synchronically, however, I think the best solution is to simply use "obl", even though "cheek to cheek" is not a prototypical noun phrase.

**Comment by msklvsk** [comment]
Still have some doubts about reciprocal example. Let’s take Russian for clarity, where it’s represented by nouns and you can’t analyze in EWT way.
_They love each other_ 
would be 
_They love **friend**.Nom **friend**.Acc_.
Still `obl`(_love_, _friend.Nom_), `nmod`(_friend_, _friend.Acc_)?

**Comment by dan-zeman** [comment]
I think the accusative _friend_ should be `obj` of _love_. It is an analogy of other expressions of reciprocality, such as with reflexives in some languages (_They love themselves_). I am unsure about the nominative _friend_. Using `det` as with the English _each other_ would be inappropriate. Besides, the nominative friend is not really modifying the accusative friend. It is closer to the actor role of _love_, but that role is already filled by the pronoun _they_, which is the real subject (agrees in number with the verb). The nominative _friend_ might be an `expl` but we usually have pronouns as expletives.

Or you could say that _drug druga / friend.Nom friend.Acc_ is a fixed expression. You would do `fixed`(_friend.Nom, friend.Acc_) and `obj`(_love, friend.Nom_). It would be no longer important that the head of the object subtree is in the nominative (instead of the expected accusative) because the _friend friend_ expression must be judged as a single syntactic unit.

**Comment by sylvainkahane** [comment]
I think that the second noun must be the head in all these constructions (cheek to cheek, cap in hand, drug druga) because the first noun functions as a kind of "subject" of the second noun. In some example it is possible to gloss the construction with a clause by adding 'being'  (_cap in hand_ = 'her cap being in her hand'). It could even be conceivable to use the relation `nsubj`between them, even if it is another construction. Unless we introduce a special relation for that, I don't really see a better choice.

**Comment by dan-zeman** [comment]
@sylvainkahane : The first noun is not a subject of the second noun and the second noun is not a predicate, unless it is a copula-like clause (imagine a "=" sign), which it isn't. We would have to imagine an elided verb, as @msklvsk initially suggested. But then the nominative noun would be the head and the accusative noun (in case of _drug druga_) would be attached to it as `orphan`.

**Comment by amir-zeldes** [comment]
I'm not saying this is a good analysis of "drug druga" (which is highly lexicalized and functional), but for the 'cheek to cheek' case I do see @sylvainkahane 's point: if it's `obl` headed by the first, then that makes it sound like there is an NP "cheek to cheek". From a literal/etymological point of view, that is not the case IMO. 

Essentially I agree it is a secondary, verbless predication: (one) cheek (being close/at/near) to (another) cheek. In that sense, it is `advcl` headed by the second cheek, and `nsubj` from second to first. The fact that there isn't a verb doesn't need to bother us in dependencies, since we accept verbless predication anyway, no? So I guess I see it like @dan-zeman 's suggestion of a 'copula-like' clause, since at least we avoid a 'cheek type' NP called "cheek to cheek", which seems weird to me.

**Comment by jnivre** [comment]
This is what I meant by saying that it is a clausal absolutive construction. These used to be called "ablativus absolutus" in Latin, because they take ablative case there.
