### ISSUE TITLE
Encoding predication for ADV predicates with dropped subject

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#558]
Consider Ukrainian “_Там добре._” or Polish “_Tam jest dobrze._” — ”_It’s good there._“
```
ADV    ADV
Там    добре .
there  good
```

Is it `nsubj`(_dobre_, _tam_)?

**Comment by ftyers** [comment]
How about:
```
root(добре)
advmod(добре, там)
```

Can you do something like "там все добро" ? Would you consider that the same structure ?

**Comment by dan-zeman** [comment]
I tend to agree with @ftyers. It is nonverbal predication (even including a copula in the past tense or in related languages). Out of the two adverbs, _добре_ “well” seems to be the predicate here. But the other adverb is not the subject. To me it looks like an impersonal, subjectless clause (with the default 3rd person neuter singular agreement, if the copula is used). Therefore, _там_ “there” should be `advmod`.

It is also possible to interpret it as the existence of the well-state. Then _добре_ would be the state whose existence is asserted, rather than a predicate; but in the UD tree it would end up as `root` anyways.

**Comment by msklvsk** [comment]
Agreed, I’m just struggling to encode the predication. Now I realize it’s OK to give up trying to do that in the basic representation and the only way is to add null nodes, correct? We can do _там все добре_ or use a “dative subject” (#248) _там всім.Dat добре_.

**Comment by dan-zeman** [comment]
What do you mean by “encoding the predication”? The predicate is there, and it is the root node, as predicates often are. It has no arguments. The current enhanced guidelines introduce null nodes only in contexts different from this one, but even if it was possible to add a null node, what purpose would it serve?

**Comment by msklvsk** [comment]
I mean where is the distinction between _“there good”_ and _“very good”_? There’s no predication in _“very good”_, it’s just an adverbial phrase like _“a blue sky”_ is a noun phrase, while _“there good”_ is a complete sentence. Are you saying there should be no explicit encoding of that at UD level?

**Comment by dan-zeman** [comment]
It is distinguished by the attachment of _добре / dobre_ “well”. If its deprel is `root`, `ccomp`, `csubj` etc., we can assume that it is a predicate because it heads a clause. If its deprel is `advmod`, we know that it is just an adverbial phrase.

We have the same thing with adjectives: in _добре скоординований механізм / dobre skoordynovanyj mechanizm_ “well coordinated mechanism”, we will have

`amod`(_механізм_, _скоординований_)
`advmod`(_скоординований_, _добре_)

In contrast, I assume that (apologies if I'm messing up Ukrainian) in _механізм добре скоординований / mechanizm dobre skoordynovanyj_ “mechanism [is] well coordinated”, we have

`root`(_скоординований_)
`nsubj`(_скоординований_, _механізм_)
`advmod`(_скоординований_, _добре_)

**Comment by msklvsk** [comment]
I wish it was the same thing as adjectives. You have `amod`(`NOUN`, `ADJ`) vs `nsubj`(`ADJ`, `NOUN`) — the exact encoding of a phrase vs predication. No such thing for _там добре_.

Relying on the attachment is a hack and doesn’t always work e.g. not all `root`s are predicated and `ccomp` can be buried by `conj`. If phantom _it_ is not an option, maybe a lang-specific morpho feature is, saying “there is a dropped _it_ subject hanging of this word.”

**Comment by Stormur** [comment]
If `there` just means _in that place_ and is not modifying good as in _very good_, and you are translating it as "It's good there", then couldn't it be:

`obl(добре, там)` ?

The predicate is missing, but that's no problem.

Update: I see that according to the guidelines `obl` is reserved to nominals, my fault. Still, it is true that here `advmod` looks ambiguous. Probably a subfeature like `advmod:obl` could solve that!
