### ISSUE TITLE
A ready to jump cat — nsubj:xsubj(jump, cat)?

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#567]
If we have an `nsubj:xsubj` in
<img width="288" alt="image" src="https://user-images.githubusercontent.com/473012/45266376-f8dfa080-b462-11e8-8de9-e362f70651e1.png">
[`to < (VERB <xcomp ADJ)`](http://bionlp-www.utu.fi/dep_search/query?search=to%20%3C%20%28VERB%20%3Cxcomp%20ADJ%29&db=UD_English-EWT-dev&case_sensitive=True&hits_per_page=10)

…should we have `nsubj:xsubj`(_hit_, _agents_) here?
<img width="470" alt="image" src="https://user-images.githubusercontent.com/473012/45266364-c766d500-b462-11e8-82bb-667ce872688f.png">
[`to < (VERB <xcomp (ADJ <amod _))`](http://bionlp-www.utu.fi/dep_search/query?search=to%20%3C%20%28VERB%20%3Cxcomp%20%28ADJ%20%3Camod%20_%29%29&db=UD_English-EWT-dev&case_sensitive=True&hits_per_page=50)

**Comment by dan-zeman** [comment]
I think that reaching to modified nouns goes beyond the current guidelines and beyond what @sebschu and @manning proposed in their Enhanced UD paper. That is, nouns modified by a deverbative adjective as `amod` (because we also have other similar enhancement type where we look at nouns modified by `acl:relcl`).

On the other hand, I agree that adding an enhanced nsubj(hit, agents), as well as nsubj(willing, agents), would be as useful as the enhancements we already have in the guidelines. But strictly speaking, it does not seem to be allowed at present.
