### ISSUE TITLE
How far should we reach for controlled subjects?

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#568]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/473012/45263845-37149a00-b43a-11e8-997d-e5c13a245c94.png">

Everything is nice in a _Mary wants to buy a book_ example, which is more often the case in the wild. 
However, sometimes the subject may reside in a higher-level clause. (Examples are translations from Slavic.):

`advcl`, converb phrase
_**They** yelled, trying **to-shout** down the-voice from the-screen._

`ccomp`
_**He** said, that he-can **to-tell** truth from fiction._

`acl:relcl` without a relativizer (assume _that_ is a pure conjunction)
_[an] old **cat** that/SCONJ is-unable **to-catch** mice_

And sometimes the subject is embedded into a verb’s person.
_**I**-decided **to-sleep**_.

(See also #567.)

What should be the policy regarding such cases?

**Comment by dan-zeman** [comment]
I think it would be useful to revisit the enhanced guidelines in the near future and take all these experiences into account. Right now, traversing a `ccomp` or `advcl` does not seem to comply with the guidelines. But if I were annotating enhanced UD manually, I would at least keep these cases so that the more enhanced annotation is ready if it is allowed in the future.

As for the “subject embedded into the verb's person”, enhanced UD does not reconstruct dropped arguments in pro-drop languages, hence nothing happens for the controlled verb.

I cannot imagine what may have been the original source for
_[an] old cat that/SCONJ is-unable to-catch mice_
but I do not think that it is a problem if there is no relative pronoun. You can still connect the modified noun as an argument of the subordinate verb if you know what argument (subject/object) it is. It may be a problem for automatic enhancing but probably not for manual annotation.
