### ISSUE TITLE
Korean particles vs. Japanese particles annotations

### ISSUE THREAD

**Issue by GuestMaru** [UniversalDependencies/docs#579]
Dear all,

first of all, thank you for your time and attention.

We are attempting to label a small Korean language corpus with POS tags.

We were looking into the Kaist database to have a standard reference, but we discovered that particles aren't getting directly tokenized. In the example below, the direct object particle (를) appears attached to the adjacent noun, and the resulting label is thus NOUN.

종소리를           종소리+를	   NOUN

Anyway, when comparing this with Japanese (GSD), the same phenomenon gets treated differently, and the direct object particle is being separated and has a tag on its own (see below).

を      ADP

The question is: to which standard of annotation for an agglutinative language should we refer to?
The first one, being the most widespread, still looks a bit too broad to effectively grasp all the syntactic phenomena of the Korean language.

Thank you again. Any suggestion will be really helpful.

Marco

**Comment by dan-zeman** [comment]
I think the question boils down to word segmentation because if it is a separate word, it is natural to tag it `ADP` in UD, and if it is kept together with the noun, then the overall tag is of course `NOUN` but the particle is taken as a case suffix and contributes the morphological feature `Case=Acc`.

Whether or not to cut it off is a different (and difficult) question. Japanese is different because there are no spaces, so some have to be introduced somewhere. Korean texts have spaces so the question is whether we need to complicate the annotation by adding an artificial space here. I am not sure the benefit is so significant (but I do not speak any of these languages). We do not necessarily make case morphemes separate words in other agglutinating languages, such as Turkish.

**Comment by kanayamah** [comment]
@GuestMaru, We made a lot of discussion about the Japanese word units, and concluded that we should adopt the Japanese traditional word units because the _bunsetsu_ (correspond to Korean _eojeol_) is too big as a unit of word and it may suffer other tasks (_e.g._ dependency parsing and word embeddings).  As @dan-zeman pointed out, we do that because we don't rely on white space.  I know it is difficult for Korean to detach _josa_ and _eomi_ because they can break character boundaries (_e.g._ ``나+ㄴ``, ``가+ㅆ어``).
It is unfortunate that the word unit cannot be aligned in similar languages, but thanks to the UD's content-head strategy, it is possible to convert the word units by attaching or detaching functional words with minimal confusions.

**Comment by amir-zeldes** [comment]
Disregarding the issue of spaces in the orthography, I think it's important that in Japanese the object marker can often be dropped (esp. in informal language), whereas the prototypical idea of case marking languages is that case is a mandatory inflection which must be marked on e.g. all accusative nouns (notwithstanding syncretism). For me this is another argument supporting the traditional smaller unit guideline for Japanese, instead of bunsetsu.

**Comment by murawaki** [comment]
I did survey the definition of word. I submitted a review paper to UDW18 but it was rejected.

I don't fully support the current word segmentation criteria of UD Japanese, but as for Japanese particles like を (accusative), they are right. を is a clitic and thus should be treated as a word. Japanese particles are characterized by a high degree of interruptibility and non-selectivity. Take
男 を
man =ACC
as an example. We can insert だけ (only) between the two morphemes:
男 だけ を
man =only =ACC
For this reason, the sequence 男 を is not a single word but two.

Two more things to note. 1) The definition of word is essentially about distinguishing clitics (~= words) from affixes and it is an unresolved problem. A thorough review by Martin Haspelmath is a must-read. http://www.academia.edu/download/31578541/WordSegmentationFL.pdf 2) Although Japanese is often said to be a language of the Altaic type, it is atypical in many ways. The high degree of autonomy of particles is one example. In my opinion, the Turkish accusative marker -i4 is different from the Japanese counterpart in that it is an affix, or attached to another morpheme to form a word. Unfortunately, my knowledge of Korean is too limited to determine whether 을/를 is an affix or clitic.
