### ISSUE TITLE
Absolute construction

### ISSUE THREAD

**Issue by rafael75012** [UniversalDependencies/docs#580]
I wondered which relation to choose for the annotation of absolute construction.

I guess when it refers to the general situation in which the action takes place we could use `obl`
_The referee having finally arrived, the game began._

And when it refers to one of the argument of the verb, we could use `acl`?
_Hands in his pockets, he roams his city._

**Comment by dan-zeman** [comment]
> I guess when it refers to the general situation in which the action takes place we could use obl
> The referee having finally arrived, the game began.

So what words would be connected by the `obl` relation? Isn't _arrived_ the head of the dependent phrase? Then I think it is an adverbial clause and the relation is

advcl(began, arrived)

**Comment by rafael75012** [comment]
The head would be "referee", governing "having" with acl relation?

**Comment by sylvainkahane** [comment]
The most efficient test to identify the head of a unit U = AB is to look whether A or B has the same distribution than U. Here you want to decide whether A = _the referee_ or B = _having finally arrived_ is the head. What do you prefer?

```
(1) The referee, the game began.
(2) Having finally arrived, the game began.
 ```

Even if (2) is semantically strange, it is much better. With another verb, it is perfect:

`Having finally be prepared, the game began.
`

So no doubt that the head is in B.

**Comment by rafael75012** [comment]
I think that it is the nominal part of the construction that is the head

**Syntactic criterion**
The absolute phrase have the distribution of a NP
It can be complement of a verb (a) and complement of a preposition (b)

"The referee having finally arrived, the game began."
(a)
> We saw the referee (having finally arrived)
> *We saw having finally arrived

(b)
> We look at the referee (having finally arrived)
> *We look at having finally arrived

**Morphologic criterion**
The noun is the morphological contact point, it agrees with external element

 "The referee having finally arrived, the game began."
> The referees having finally arrived were seen. [edited]
> *The referee having finally arrived were seen. [edited]

 "Hands in the pockets, he roams his city."
> With them (*they) in the pockets

**Semantic criterion**
The sentences above reveal quite clearly that the absolute construction phrase as a whole refers to the entity (in a specific state), i.e. the NP, more than to the state in itself, i.e. the PP/V(-ed/-ing)/AP



Absolute construction internal analysis
 _The referee having finally arrived, the game began_ ==> acl(_referee_, _having_)
 _Hands in the pockets, he roams his city_ ==> nmod(_hands_, _pockets_)

Absolute construction external analysis
 _The referee having finally arrived, the game began_ ==> obl(began, referee)
 _Hands in the pockets, he roams his city_ ==> obl(hands, roams)

**Comment by nschneid** [comment]
I would say:

The referee having finally arrived, the game began.

advcl(began, arrived)
nsubj(arrived, referee)
aux(arrived, having)

"The referee having finally arrived" cannot stand alone, and is optional. "The game began" is the main clause. The absolute clause could be replaced with a more standard subordinate clause, e.g. "Because the referee had finally arrived", but cannot be simplified to a noun phrase—it needs a predicate:

*The referee, the game began.
*The referee's arrival, the game began.

"We saw the referee (having finally arrived)" probably means that *we* have finally arrived, not the referee. "See" prefers to be transitive, but "We saw, having finally arrived" works as long as there something established in context that is available for us to see.

> Morphologic criterion
> The noun is the morphological contact point, it agrees with external element
>
> "The referee having finally arrived, the game began."
>    The referees having finally arrived were saw.
>    *The referee having finally arrived were saw.

I don't understand this. The last 2 sentences are both ungrammatical.

The "hands in the pockets" examples (actually, it would be "hands in his pockets") might be depictives, which pertain semantically to one of the arguments of the matrix verb. Cf. "He entered the room **drunk**." Those are acl, I believe.

**Comment by sylvainkahane** [comment]
@rafael75012 You said: "Semantic criterion. The sentences above reveal quite clearly that the absolute construction phrase as a whole refers to the entity (in a specific state), i.e. the NP, more than to the state in itself, i.e. the PP/V(-ed/-ing)/AP", but I don't see any argument supporting this affirmation.
As @nschneid said, the absolute construction can be paraphrased by "Because the referee had finally arrived". It refers to a fact and can also be paraphrased by something like "Due to the fact that the referee had finally arrived".
It is also why it cannot commute with an NP, as in "We saw the referee (having finally arrived)". In this case it is no longer the absolute construction.

**Comment by rafael75012** [comment]
So "The referee having finally arrived, the game began" and  "Hands in the pockets, he roams his city" are two distinct constructions? 

Following @nschneid  suggestion : 
"The referee having finally arrived, the game began" : `advcl`(began, arrived)
 "Hands in his pockets, he roams his city" : `acl`(he, hands) [edited]

**Comment by sylvainkahane** [comment]
"Hands in his pockets, he roams his city" : `acl`(roams, pockets).

**Comment by rafael75012** [comment]
@sylvainkahane, why "pockets" would be the head of "hands in his pockets"?
"in" is head of the PP "in his pockets", which is part of the NP "hands in his pockets"

And why `acl` linked to "roams"? `acl` is for modifiers of nouns, I guess you meant `advcl`.
But if we consider it's a depictive then we should link it to the argument of the verb directly, with `acl`

**Comment by sylvainkahane** [comment]
Oh yes sorry, it must be `advcl`(roams, pockets), as it was _hands being in his pockets._ In UD the noun is the head of the PP.

**Comment by rafael75012** [comment]
So the complete annotation you propose is
`nsubj`(_pockets_, _hands_)
`case`(_pockets_, _in_)
`det`(_pockets_, _his_)
`advcl`(_roams_, _pockets_)

**Comment by sylvainkahane** [comment]
Yes, even if the `nsubj` relation is a little problematic here. It is a different construction from the subject-verb construction and it is why it deserves a special name (absolute construction). Introducing a new relation for that would be costly, but I would be in favor of having something like `nsubj:absolute`.

**Comment by rafael75012** [comment]
Ok, thanks !

**Comment by rafael75012** [comment]
As @nschneid  suggested 

> The "hands in his pockets" examples might be depictives, which pertain semantically to one of the arguments of the matrix verb. Cf. "He entered the room drunk." Those are `acl`, I believe.

So the annotation should rather be :  

"Hands in his pockets, he roams his city"
> `nsubj`(_pockets_, _hands_)
> `case`(_pockets_, _in_)
> `det`(_pockets_, _his_)
> `acl`(_he_, _pockets_)

Below, the complete annotation for non-depictive absolute construction : 

"The referee having finally arrived, the game began"
> `det` (_referee_, _the_)
> `nsubj` (_arrived_, _referee_)
> `aux` (_arrived_, _having_)
> `advmod` (_arrived_, _finally_)
> `advcl` (_began_, _arrived_)
