### ISSUE TITLE
Appos and Parataxis - guidelines vs annotated golden corpus (EWT)

### ISSUE THREAD

**Issue by claudiafreitas** [UniversalDependencies/docs#591]
1. Although guidelines on `appos` ([http://universaldependencies.org/u/dep/appos.html](http://universaldependencies.org/u/dep/appos.html)) state that
`
> state senator Paul Mnuchin

should not be tagged as `appos`, the following cases are tagged as `appos` in the EWT corpus:

> my _friend_ Nick Keck 

> Her _mother_ Ismat

> The _hijacker_ Ahmed Alhaznawi

> _bacteriologist_ Dr. Abdul Qadoos Khan

> our youngest _daughter_ Elizabeth

We (in portuguese) are fine considering restrictive appositives as appos, but we thought we were diverging from the guidelines.. maybe not?

2. The following cases are tagged as `appos` as well - we were not sure if, according to guidelines, they should be` appos `or `parataxis`: 

> ...and author of "Sacred Space and Holy War" (I.B. Tauris, 2002). 

3. The example below, taken from the `parataxis` guidelines ([http://universaldependencies.org/u/dep/parataxis.html](http://universaldependencies.org/u/dep/parataxis.html))  is tagged as` list`, and not as `parataxis`

> WASHINGTON (CNN) 

I think we could benefit if both cases were treated as if they were the same...

> WASHINGTON (CNN)
> ... and author of "Sacred Space and Holy War" (I.B. Tauris, 2002)

**Comment by sebschu** [comment]
Re 1: This distinction is a bit tricky since we only use `appos` if the descriptive noun phrase can stand on its own and be switched with the name but not in cases of "titles" such as senator which have to precede the name.

So I think all of the examples you provide should be tagged as `appos`, except perhaps _bacteriologist Dr. Abdul Qadoos Khan_ (unless there is a determiner in front of _bacteriologist_).

Note that for all the other ones, we can invert the order:

> Nick Keck, my friend 

> Ismat, Her mother

> Ahmed Alhaznawi, The hijacker 

> Elizabeth, our youngest daughter

**Comment by Stormur** [comment]
1. I think that the first group of examples should all be tagged `flat`, as per the guidelines. A construction like _Ismat, her mother_ seems to have another structure and nuance to me. In one case we have a title which "binds" with the noun, in the second case we have a specifying phrase. 

However, the `appos` relation has indeed shown to be somewhat controversial (I'd say too restrictive and too English-oriented in its definition) and its use in the different treebanks varies wildly. A change should be discussed, and at least consider the use of apposition-introducing elements.    

2. I don't understand what is tagged as `appos` here, since to me it all looks just like `conj`s and `nmod`s:

```
conj(...,author)
cc(author,and)
nmod(author,Space)
case(Space,of)
...
conj(Space,War)
...
```

**Comment by amir-zeldes** [comment]
@Stormur I think the idea is that I.B. Tauris is the author, but this case actually doesn't obey the reversibility guidelines, due to the presence of the year:

`* (I.B. Tauris, 2002) author of "Sacred Space and Holy War"`

For this reason we use `dep` to attach author citations to names of works in UD_English-GUM. 

As for "Ismat, Her mother", I think this is a perfectly normal apposition - we don't have separate labels for restrictive and non-restrictive `amod` or `acl`, so I don't think we need to make this distinction on `appos` (though it could certainly be a sublabel or MISC annotation, if some corpora have that information)

**Comment by Stormur** [comment]
> @Stormur I think the idea is that I.B. Tauris is the author, but this case actually doesn't obey the reversibility guidelines, due to the presence of the year:
> 
> `* (I.B. Tauris, 2002) author of "Sacred Space and Holy War"`

My fault, I did not notice the name in parentheses! Well, it looks like a loose relation to me rather than an `appos`, with an internal `flat` structure, as typical for names. We need to see the entire sentence for clarity, though, to understand the reference and what should be the head of that element. If however _(I. B. Tauris, 2002)_ refers to the publishing house and not to the author, I see a  `parataxis`, but not with _author_ as head (guidelines: "[...] placed side by side without any explicit coordination, subordination, or argument relation with the head word"). In any case I think that either loose-relation deprel or `appos` is preferable to an agnostic `dep`.

> As for "Ismat, Her mother", I think this is a perfectly normal apposition - we don't have separate labels for restrictive and non-restrictive `amod` or `acl`, so I don't think we need to make this distinction on `appos` (though it could certainly be a sublabel or MISC annotation, if some corpora have that information)

_Ismat, her mother_ is an apposition, sure; but _her mother Ismat_ is a flat construction. The comma here is a sign that we have two different constructions (see also the guidelines: `flat` would not be appropriate most of the time if punctutation sets the two elements apart, exactly because punctuation is trying to convey a different relation). I would also treat _her mother, Ismat_ as a case of apposition, for the same reasons. Please correct me, but I don't think that the sentence 

_Ismat her mother scolded me yesterday_

is grammatical, compared to 

_Her mother Ismat scolded me yesterday_. 

 We have to rephrase it as 

_Ismat, her mother, scolded me yesterday_. 

So I argue that we can not really reverse the phrase without altering its structure (and the nuance of meaning, too), and that all the examples in point 1 are not `appos`.

**Comment by dan-zeman** [comment]
I agree that the examples _my friend Nick_ to _our youngest daughter Elizabeth_ are not `appos`. Also note that the [current guidelines](http://universaldependencies.org/u/dep/appos.html) define `appos` as a left-to-right relation.

**Comment by amir-zeldes** [comment]
I think even if there is a slight nuance to not using the comma, it's risky to rely on this, as many languages do not have reliable comma usage rules (English is not very strict either), and for some languages (especially in historical treebanks) we don't have commas at all.

Incidentally I think "her mother Ismat" is actually grammatical, and maybe only slightly odd because a mother is usually unique, so it has to be non-restrictive. If it said "her sister Sarah" (as opposed to her sister Isabel), that would be 100% unmarked for me.

**Comment by Stormur** [comment]
The comma is of course a useful convention to detect such structures, but can not be the only criterion.

> Incidentally I think "her mother Ismat" is actually grammatical, and maybe only slightly odd because a mother is usually unique, so it has to be non-restrictive. If it said "her sister Sarah" (as opposed to her sister Isabel), that would be 100% unmarked for me.

I considered only a form like _Ismat her mother scolded me_ as ungrammatical. 

>     2. The following cases are tagged as `appos` as well - we were not sure if, according to guidelines, they should be`appos`or `parataxis`:
> 
> > ...and author of "Sacred Space and Holy War" (I.B. Tauris, 2002).

I searched for the whole sentence, which is: 

_Juan Cole ( www.juancole.com ) is a professor of modern Middle East history at the University of Michigan and author of " Sacred Space and Holy War " ( I.B. Tauris , 2002 ) ._

I, too, am not convinced by both choices of `appos`, as they appear in the treebank:

```
appos(Juan,www.juancole.com)
...
appos(Space,I.B.)
```

Namely, I see both rather as loose relations, so either as `list` or `parataxis`; I would say, in the first case 

`list(Juan,www.juancole.com)`,

following the examples of lists constituted by names, e-mail addresses, and so on. And for the second one I agree with the interpretation as 

`parataxis(Space,I.B.)`.

I do not consider it an apposition, because it does not truly "define, modify, name, or describe" the title of the book. It's just extra information about the book itself "without any explicit [...] argument relation with the head word", in this case omitting something on the lines of _edited by I.B. Tauris in 2002_. 

So, @claudiafreitas, answering point 3, yes, I totally agree with you: both cases should be treated as `parataxis`. 

I admit though that the border between `list` and `parataxis` is quite slippery... Maybe we could think of a unique deprel for loose relations? Would it be too coarse?

**Comment by nschneid** [comment]
The examples at http://universaldependencies.org/u/dep/list.html seem to be outside of a (grammatical) sentence.

For citations and other extra metadata injected in sentences in writing, which would not normally be uttered as such in speech, `parataxis` seems better to me. Though there's probably room for clarifying or refining parataxis.

**Comment by amir-zeldes** [comment]
I like parataxis for these last two cases better than list - you could consider it to be a parenthetical, similar to:

Juan Cole -- you can find more info about him at www.xyz.com -- is author of ...
parataxis(Juan,find)

This is what PTB brackets would group under a PRN node, and I understand parataxis to cover these cases as well.

**Comment by sylvainkahane** [comment]
For UD_French_Spoken, we decided to split `appos` in two relations: `appos:conj` for _my sister, Mary_ or _Mary, my sister_ and `appos:nmod` for _my sister Mary_ or _le journal Le Monde_. See http://universaldependencies.org/fr/dep/index.html for details.
For written corpora the distinction can be recovered using the punctuation, but for a spoken corpus it needed to be explicitely encoded.
The distinction is based on the fact that in `appos:conj` we have two (prosodic) phrases, while in `appos:nmod` there is only one. In some sense, `appos:conj` is a particular case of paradigmatic list as the coordination. Two phrases X and Y forms a paradigmatic list if Y piles up on X and occupies the same syntactic position. On the other side, `appos:nmod` is just a case of nominal modification of X by Y, even if by chance Y can commute with X. These two relations could be better named `conj:appos` and `nmod:appos`, as we do in our SUD version of the corpus.

Note that we also consider a bunch of different parataxis relations, due to the variety of such relations in spoken French. Again, details on http://universaldependencies.org/fr/dep/index.html  and in our paper [Trois schémas d’annotation syntaxique en dépendance pour un même corpus de français oral : le cas de la macrosyntaxe](https://kahanedotfr.files.wordpress.com/2017/06/treebanks-macro-taln2017.pdf).

**Comment by arademaker** [comment]
Why can we take a more semantic definition of appos? Like two NP can be linked by appos whenever they reference the same entity. In the case, `my friend Alexandre...` would be fine to have `appos` between 'friend' and 'Alexandre'.

**Comment by amir-zeldes** [comment]
Some other constructions for which appos is frequently used are non-coreferential, such as the city-state construction:

Boston, MA
appos(Boston,MA)

I'm not saying this is the best/correct solution for these phrases, but if coreference were a requirement for appos, we'd need to do something different with these. There are also cases involving set-member relations, such as:

They have many problems, droughts for example.
She knows everyone, Beth, Bobby, Jane... 
(everyone is not necessarily strictly the same as these three people)
