### ISSUE TITLE
Noun classes in Wolof

### ISSUE THREAD

**Issue by chedio** [UniversalDependencies/docs#592]
Like Bantu languages, Wolof has noun classes. 8 singular classes, 2 plural classes, 1 locative class and 1 manner class. The classes are identified by their index (_b, g, j, k, l, m, s, w_) for singular and (_y, ñ_) for plural, _f_ for locative and _n_ for manner. The class index functions as a stem to which an affix is added to form determiners and pronouns. For instance, dog is in the _b_ class and sheep is in _m_ class. Typically _k_ and _ñ_ are singular and plural classes for humans, respectively. 

To form definite articles, the vowels _i_ and _a_ are added as suffix to the noun class stem. Each suffix conveys a different deixis information (i.e. proximity and distance in space, time, or conversation). The vowel _i_ indicates proximity and _a_ indicates distance. Here some examples:

xaj b-i
dog class-DEF.PROX
the dog (proximal)

xaj b-a
dog class-DEF.DIST
the dog (distal)

xar m-i
sheep class-DEF.PROX
the sheep (proximal)

Besides articles and demonstratives, deixis is also encoded in the various types of pronouns. First, I would like to ask whether it would potentially be possible to introduce _Deixis_ as a new feature. 

Now, my main question is about the existing feature _NounClass_. For Wolof, it may sound logical to use a mapping between the Bantu classes and the ones found in Wolof. However, I face a non-trivial issue here of incompatibility between the two systems.
For instance, the Swahili noun classes that are given as illustration in the UD guidelindes have in most cases clear semantics. In contrast, the Wolof noun class system lacks a semantic coherence. On reason for this is that in Wolof noun classification is sometimes based on other factors than semantics, including phonology and morphology. And still these are just some tendencies, but in most cases there is no clear semantics, phonology or morphology that can explain the classification in Wolof. In fact, there are more exceptions than the rules. 
This makes a mapping between the two systems hardly possible, if not impossible. 
At the current state, I just keep the index as the value of the noun class in Wolof. Any suggestion on how to deal with this issue?

**Comment by dan-zeman** [comment]
You cannot have a feature value that starts with a lowercase letter and you cannot have a non-ASCII letter (ñ) anywhere in the feature value.

The NounClass feature is described in UD because it is described in Unimorph, but at present I think it is not used in any UD treebank. We don't have Swahili (or any other Bantu language) yet.

The idea in UniMorph was that you can define one set of classes per language group or family. But it has to be decided where the boundary of the group is (Wolof sharing with Bantu languages the Niger-Congo family, but not being Bantu). If the Bantu classes were extensible to Wolof, then it would not seem appropriate to call them Bantu1 - Bantu23. But since they apparently don't (or don't extend easily), we can say that Wolof has its own set of classes (or maybe shared with some other related non-Bantu Niger-Congo languages?) Then it could be, following the same schema, Wolof1 - Wolof12. You can still try to order them in a way that would be comparable to the Bantu classes where possible, but you would not be restricted by the names because they would not refer to Bantu.

The Deixis feature is a good idea. It already exists in Unimorph, so we should adopt their values if possible (reformatting them to our Upper-Lowercase convention): `Deixis=Prox`, `Deixis=Remt`. (They have more values but it seems that we only need these two for Wolof, right?)

**Comment by chedio** [comment]
@dan-zeman: Thank you. Sorry that I was not clear in the previous message. For the class indexes, I actually meant that they are all in uppercase letters. The same applies for the _Deixis_ feature values. I was not aware of the fact that values cannot have a non-ASCII. Thanks for the clarification. 

Your suggestion about creating an own set of classes for Wolof sounds good. As you suggested, I can try to work out a schema for Wolof (e.g. Wolof1 - Wolof13) in an order similar to the Bantu classes. 

Concerning `Deixis`, it would be great to have such a feature. The values `Prox` vs. `Remt` would in fact cover most of the information needed for articles and pronouns. The only category that may require other values concerns demonstratives.

Wolof  has  a  rich  system  of  demonstratives (ca. 11 paradigms). These combine indications  of  the  distance vis-à-vis  the  speaker with  considerations  on  the  addressee  (-oo- morpheme) and also emphasis. For instance, for the _b_ noun class, I can give the four most commonly used forms (_bii_, _bale_, _boobale_, and _boobu_) as exemplified below with the noun _xaj_ "dog".

1. _xaj bii_ 'this dog (close to me, wherever you may be)'
2. _xaj bale_ 'that dog (far away from me, wherever you may be)'
3. _xaj boobale_ 'that dog (far away from both of us, but closer to you than to me)'
4. _xaj boobu_ 'that dog (close to you and far away from me); the dog in question’

**Comment by dan-zeman** [comment]
The Unimorph specification is [here](https://unimorph.github.io/doc/unimorph-schema.pdf), deixis starts on page 22. Mapping from them may not be always straightforward because they allow to combine various subdimensions orthogonally. We need subdimensions called "Distance" and "Reference Point". Maybe we could model them as two features, `Deixis` and `DeixisRef`.

1. close to me, wherever you may be ... Unimorph PROX.REF1 ... `Deixis=Prox|DeixisRef=1`
2. far from me, wherever you may be ... Unimorph REMT.REF1 ... `Deixis=Remt|DeixisRef=1`
3. far from both, closer to you ... Unimorph MED.REF2 ... `Deixis=Med|DeixisRef=2`
4. close to you, far from me ... Unimorph PROX.REF2 ... `Deixis=Prox|DeixisRef=2`

This approach does not allow to encode distance from both referents at the same time (neither does Unimorph). We can get the four distinctions without it; but I cannot predict whether it will be needed in another language. Alternatively one could model the situation using [layered features](http://universaldependencies.org/u/overview/feat-layers.html). Then the referent could be the layer (perhaps with REF1 being default): far from both, closer to you = `Deixis=Remt|Deixis[2]=Med`; close to you, far from me = `Deixis=Remt|Deixis[2]=Prox`.

**Comment by chedio** [comment]
Thanks. I will try with the two features `Deixis` and `DeixisRef`. For Wolof, I think this may be enough (because within the 11 paradigms, there are many allomorphs).
