### ISSUE TITLE
UD_Hebrew-HTB analysis of מה"גרין (mh"grin) contains itself

### ISSUE THREAD

**Issue by bhkjersten** [UniversalDependencies/docs#598]
he_htb-ud-train.conllu version 2.0 or later contains a self-contradictory annotation that crashes our in-house CONLLU parser.

he_htb-ud-train.conllu analyzes מה"גרין (mh"grin) as מ+ה+"+מה"גרין (m+h+"+mh"grin) instead of מ+ה+"+גרין (m+h+"+grin). This means that the token is described as containing itself, and it is impossible to reconcile the length of the full token with the lengths of its constituent parts.

I don't know if this is the only token with this problem.

**Comment by dan-zeman** [comment]
Seems fixed now:

<pre>
17-20	מה"גרין	_	_	_	_	_	_	_	_
17	מ	מ	ADP	ADP	_	18	case	_	_
18	ה	ה	DET	DET	PronType=Art	16	obl	_	_
19	"	"	PUNCT	PUNCT	HebSource=ConvUncertainHead	18	dep	_	_
20	גרין	גרין	PROPN	PROPN	HebSource=ConvUncertainHead	18	dep	_	_
</pre>

**Comment by shovalsa** [comment]
This problem occurs whenever a PROPN is quoted immediately after a preposition. For example,
 מה"גרין קארד" שלו
from his "green card"
By chance this only occurs in the train set because this construction did not appear elsewhere.
I just fixed it by replacing the LEMMA to be identical to the FORM (which was ok).
The revised version can be found in the dev branch:
https://github.com/UniversalDependencies/UD_Hebrew-HTB/tree/dev

**Comment by dan-zeman** [comment]
(BTW in general it is not guaranteed that the number of characters of a multiword token must be the sum of the characters of the individual words.)
