### ISSUE TITLE
Change filename to identify corpus for which content (words) have to be donwloaded separately

### ISSUE THREAD

**Issue by gw17** [UniversalDependencies/docs#599]
There are several corpora for which only annotations are provided (e.g. French-FTB).

Dataset of these treebanks should have a special names (e.g. their extension can be `.conllu.without_words` to prevent them from being included when doing experiments on the whole UD Project.

**Comment by dan-zeman** [comment]
There are many other respects in which the treebanks differ (although this is arguably one of the more important differences). Then we could also have .conllu.without_lemmas, .conllu.without_features_and_lemmas etc. Instead of putting metadata information into filenames, we put it in the [README files](http://universaldependencies.org/release_checklist.html#treebank-metadata). You can grep the README file for a line that says

<pre>
Includes text: yes
</pre>

If you find it, the treebank has word forms.
