### ISSUE TITLE
Question about English UPOS verison 1.2 vs 1.3

### ISSUE THREAD

**Issue by gnepul-ace** [UniversalDependencies/docs#607]
Hi,

I am using the UPOS 1.3, and I find some papers using version 1.2,
Could you give me a description of what is the difference between them(1.2 vs 1.3), as I want to cite the result directly?
Can you give a history track to version 1.2 of POS.

Peng

**Comment by manning** [comment]
Hi Peng,

At the level of specifications, there is no difference between UPOS v1.2 and v1.3. They both had the same set of UPOS with the same definitions (modulo minor clarifications which may have been added to the documentation). The only changes in the set and their definitions occurred between UD v1 and UD v2.

If the question is in practice how the corpora differed, then for UD_English-EWT, it appears that the changes in UPOS between v1.2 and v1.3 are limited to correcting a bunch of cases of _which_ and _that_ which had been POS-tagged as DET to PRON. In general, you should be able to figure out diffs either by downloading different official releases from the CLARIN site and doing your own diff, or doing diffs between versions on GitHub.

It's a little difficult to get at the diff from v1.2 to v1.3 because of the directory renaming, but I think this shows you what you want:

https://github.com/UniversalDependencies/UD_English-EWT/commit/2fed950ace6f86d3f929eba14a023c033e08bc71#diff-b72b18822ded969c66da61d212164739
