### ISSUE TITLE
DEPREL: spelling out by syllables

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/docs#609]
I am wondering what is the right way to label relations in cases such as:
(a) AF-RI-KA, 
(b) AF -- RI -- KA, 
(c) AF -- RI -- (say) -- KA 'Africa'
In the texts of poetry and fiction, the syllables can be written separately intentionally, so it is probably not correct to tokenize them as one word (cf. also (c)).
The relation is not `goeswith` since it is only whitespace that can divide segments according the current guidelines,
and it seems not to be `reparandum` and `dislocated`, just by their definition, in my opinion.

**Comment by dan-zeman** [comment]
Yes I think it's not `goeswith` because it's done on purpose and it's not a spelling error. Although I am wondering whether someone thought about such cases and rejected them when defining `goeswith`. Maybe the definition could be extended (and then we would have to allow `punct` nodes between two nodes connected by `goeswith`).

Other than that, perhaps we can simply use `dep`.

**Comment by sylvainkahane** [comment]
I also think that `goeswith` should not be used in this case. Maybe `list` is a solution. At least from the prosodic point of view, such constructions work as lists. An extension could be used such as `list:syllable`.

**Comment by dseddah** [comment]
Hi Sylvain and all,

I see the argument about list but in that case how about constructions such as 

in-f.cking-deed ?
as in
https://twitter.com/spacebunth/status/1092207999408582657
or
https://twitter.com/jsmoothis2cooll/status/1090430122287599616

(easily searchable in Twitter’s seach field)


Djamé

**Comment by jnivre** [comment]
Hi all,

Also keep in mind that UD does not segment words into morphemes. In some of these cases (especially the ones without spaces), the best approach is probably to just treat them as separate words. If needed, additional annotation can be used to capture what is special about them. The morphosyntactic UD annotation can never capture everything.

**Comment by dseddah** [comment]
(Hi Jioakim)

I was wondering 1) how one could coordinate prefixes as in (1) and 2) if it is something we really want to do :)
1° les pros et anticommunistes se sont affrontés hier 
    (Pros and anticommunists fought yesterday)

I found these two discussions, the last link on part suggests that part/prefix should be analyzed at the tokenization stage but I’m not sure it was actually done.

a) https://github.com/UniversalDependencies/docs/issues/133
b) https://universaldependencies.org/pt/pos/PART.html

on a similar vein, I was wondering how to treat cases like
1)  il a perdu entre 300 et 400 000 euros 
     he lost between 300 and 400,000 euros
2) il a perdu entre 300 et 400k€
    he lost between 300 and 400k€ euros

where I think something should be done, at least at the enhanced level to  share  the « thousands » marker between 300 and 400.

Best,
Djamé

**Comment by jnivre** [comment]
Hi Djamé, 

The first case occurs all the time in Swedish, which has very productive compounding. Currently, we just fudge and treat it as ordinary coordination:

conj(pro, anticommunistes)
cc(anticommunistes, et)

This can be motivated by an analysis where the first conjunct is treated as a kind of ellipsis (where the prefix is promoted):

pro(communistes) et anticommunistes

In Swedish, this is supported by a regular orthographic convention, since the first element usually has a hyphen at the end. For example,

tränings- och tävlingsdräkter (= training and competition outfits)

Joakim
