### ISSUE TITLE
French Causative FAIRE

### ISSUE THREAD

**Issue by rafael75012** [UniversalDependencies/docs#610]
The causative FAIRE is actually treated as an auxiliary in French treebanks, I wonder if this solution could be ameliorated.

It would maybe be more accurate to treat it as a full verb, with the infinitive linked to it with `xcomp`

> Paul fait —`xcomp`→parler Pierre de sa jeunesse.

With all complements generated by the causative construction depending on the causative, and all complement belonging to the valency of the predicative verb depending on it.

This strategy would avoid problems, like the presence of two `obj` if we follow the FAIRE = `AUX` strategy like in : 

> Paul le fait rembourser les pertes

> `nsubj` (rembourser, Paul)
> `obj` (rembourser, le)
> `aux` (rembourser, fait)
> `obj` (rembourser, pertes)
> `det` (pertes, les)

Additionnally, the causative FAIRE is not an `AUX` according to UD : "An auxiliary is a function word that accompanies the lexical verb of a verb phrase and expresses grammatical distinctions not carried by the lexical verb, such as person, number, tense, mood, aspect, voice or evidentiality" https://universaldependencies.org/u/pos/AUX_.html

And I think that if we start to go beyond the traditional auxiliaries ÊTRE and AVOIR, and open this category to other verbs, then the limit become very unclear

See more in depth discussion in https://gitlab.inria.fr/sequoia/deep-sequoia/issues/153

**Comment by dan-zeman** [comment]
I agree. It would also be parallel to the English constructions with _make_ + `VERB` (see this query: [http://hdl.handle.net/11346/PMLTQ-PPQP](http://hdl.handle.net/11346/PMLTQ-PPQP)).

**Comment by sylvainkahane** [comment]
Each POS correspond to a distributional class. In English, AUX contains the traditional auxiliaries "have" and "be" but also modal verbs "must", "can" etc, because they share distributional properties with  "have" and "be": the initial position in questions.
In French, modal verbs do not share any interesting property with the auxiliaries "avoir" 'have' and "être" 'be' and they are not in AUX. On the contrary, "faire" 'make' in the causative construction is the only verb sharing a distriutional property with the auxiliaries: the raising of the clitics:

> Marie le voit. 'Mary sees it'
> Marie l'a vu. 'Mary has seen it'
> Marie peut le voir. 'Mary can see it' 
> Marie me le fait voir. 'Mary makes me see it'.

The causative "faire" is the only verb like this.

**Comment by sylvainkahane** [comment]
About the definition of AUX : : "An auxiliary is a function word that accompanies the lexical verb of a verb phrase and expresses grammatical distinctions not carried by the lexical verb, such as person, number, tense, mood, aspect, voice or evidentiality"
https://universaldependencies.org/u/pos/AUX_.html

This is clearly a semantic definition, which I think is not convenient. It is not even clear that it apply for English "must". And more generally, the definition of POSs should be syntactic and distributional.

**Comment by rafael75012** [comment]
> Each POS correspond to a distributional class

Is it the case in UD?

> The causative FAIRE is the only verb like this.

That's why it is often seen as a semi-auxiliary I guess
So one would have to choose on which side it should fall in, whether verb or auxiliary.

**Comment by dan-zeman** [comment]
>> Each POS correspond to a distributional class

>Is it the case in UD?

Not necessarily. Distributional criteria are important but it is not just about them.

>> The causative FAIRE is the only verb like this.

Such a test sounds reasonable to me, so maybe it can be auxiliary after all. But I cannot be the judge on this.

**Comment by rafael75012** [comment]
The placement of clitics juste before FAIRE is not systematic 

> Pierre a fait téléphoner Marie **à Paul**
> *Pierre **lui** a fait téléphoner Marie

> Il a fait se **les** laver aux enfants

The causee can not be the exclusive object of an eventual complex predicate, because it reacts posivitely to subjecthood test

> Ce qui est arrivé a fait partir **sans rien dire** la tante de Jean

The adverbial clause **sans rien dire** is controlled by the causee. 

So we have at least two clauses in causative sentences, one around the verb FAIRE, which takes the causee as object, and one around an embedded lexical verb, which subject is controlled by the causee.

Cf. https://www.diu.edu/documents/gialens/Vol3-2/Lovestrand--French-Causatives.pdf

**Comment by sylvainkahane** [comment]
I agree with you that we could have considered causative FAIRE as a plain verb (even if I’m not convinced by your examples, which looks too much as coined examples).
There is a continuum between pure functional verbs and plain verbs and it is difficult to decide where to cut between AUX and VERB.
Moreover in UD, functional heads are treated as dependents of lexical heads, which accentuate the limit between AUX and VERB.
Here our choice were based on clitic raising: treating AUX as dependent has an advantage, it reduces the non-projectivity, because AUX is between the lexical VERB and its complement.
Note that there are other constructions with clitic raising in French:

> J’ai entendu chanter la Marseillaise ‘I heard (someone) singing the Marseillaise'
> Je l’ai entendue chanter, litt. I it hear singing
> 
But we decided not to include them and not to consider ENTENDRE ‘hear’ as an AUX here.

**Comment by rafael75012** [comment]
In which case do you have non-projectivity?
If you make the arguments generated by the causative construction depending on FAIRE and not on the plain verb, I guess you don't have non-projectivity

Treating FAIRE as a full verb has also the advantage to mark which arguments belong to the causative-construction, and which ones belong entirely to the plain verb

>  There is a continuum between pure functional verbs and plain verbs and it is difficult to decide where to cut between AUX and VERB.

That is an argument of not treating FAIRE as an auxiliary I gave earlier, because once you go beyond the limit of AVOIR and ÊTRE, it is hard to know where to stop

Your point on ENTENDRE tends to show that the clitics placement argument is not sufficiently strong to treat FAIRE as an auxiliary, as some lexical verbs like ENTENDRE also show this behaviour

**Comment by rafael75012** [comment]
In which case do you have non-projectivity?
If you make the arguments generated by the causative construction depending on FAIRE and not on the plain verb, I guess you don't have non-projectivity

Treating FAIRE as a full verb has also the advantage to mark which arguments belong to the causative-construction, and which ones belong entirely on the plain verb

>  There is a continuum between pure functional verbs and plain verbs and it is difficult to decide where to cut between AUX and VERB.

That is an argument of not treating FAIRE as an auxiliary I gave earlier

Your point on ENTENDRE tends to show that the clitics argument is not sufficiently strong to treat FAIRE as an auxiliary, as some lexical verb like ENTENDRE also show this behaviour

**Comment by sylvainkahane** [comment]
"In which case do you have non-projectivity?"

> Marie lit le livre.
> Le professeur fait lire le livre à Marie.
> Le professeur le fait lire à Marie
> 

_le_ depends on _lire_. If the subject _le professeur_ is linked to _fait_, the tree is non projective.

"That is an argument of not treating FAIRE as an auxiliary I gave earlier, because once you go beyond the limit of AVOIR and ÊTRE, it is hard to know where to stop"
We have to decide where to stop, before or after FAIRE. We decided to use the clitic climbing as defining property for AUX. The case of ENTENDRE is very marginal.

I don't think that it is a very important point that needs to be discussed further. The only interesting point here for me is: which kind of criteria do we use to define POS and relations? I really think that we must have clear distributional criteria and that these criteria must be stated in the guidelines for each language. These criteria cannot be universal, but every language is likely to have a subclass of functional verbs with particular properties (and specific to this language).

**Comment by sylvainkahane** [comment]
I forgot to mention one important property of the demoted subject in French causative constructions: the realization of the demoted subject depends on the subcategorisation of the lexical verb. If the verb is intransitive, it becomes a direct object (1); if the verb is transitive, it becomes an indirect object (2); and if the verb is ditransitive, it becomes an oblique complement (3).

> (1) Marie dort -> Pierre fait dormir **Marie** 'Peter makes Mary sleep'
> (2) Marie lit le livre -> Pierre fait lire le livre **à Marie** 'Peter makes Mary read the book'
> (3) Marie donne un livre à Jean -> Pierre fait donner un livre à Jean **par Marie** 'Peter makes Mary give a book to John'

For this reason, we cannot just say that the demoted subject depends on FAIRE. There is a clear interaction between FAIRE and the lexical verb and it is another reason why we consider that FAIRE + the lexical verb form a compound form and FAIRE is an auxiliary.

**Comment by amir-zeldes** [comment]
Not sure that this should make a difference for French, but for FWIW for Coptic we made the causative marker be a VERB in UPOS and made it the head, since it takes its own tense and subject agreement (she causes, he had caused, etc.), so it seemed reasonable to treat it as a full verb which can govern its own auxiliaries. 

I do remember briefly debating it in the project and eventually deciding based on how, language internally, it behaves like other main predicates governing xcomp, even though it is completely grammaticalized (e.g. it cannot appear without a caused predicate, can't take just a nominal object like 'cause a disaster' or 'faire quelque chose', etc.)
