### ISSUE TITLE
advmod but not UPOS=ADV

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/docs#617]
In UD_Coptic-Scriptorium we have a number of exceptions to the advmod=ADV convention, which the validation script flags. However I'm not sure I want to change these cases to ADV, so I'd appreciate input on these situations:

1. `NUM` can be `advmod` - for example, Coptic often uses repeated numbers adverbially to indicate distributive quantities. For example: joou-se snau snau, lit. "send them two two" (=send them two by two, in groups of two). I think this is NUM, but also adverbial (how were they sent? two two)
2. `PRON` as `advmod` - we often get adverbial reflexives (this should happen in English too): ame:in nto:tn "go yourselves" (i.e. by yourselves) - shouldn't this be `advmod`?
3. `NOUN` as `advmod` - there are various constructions, maybe the easiest to explain is the same as 1.: sor-f ebol meros meros "tear it out limb limb" (limb by limb, one limb at a time)

There are many constructions in which items are used adverbially which are morphologically clearly not adverbs. Is the UD standard recommending to tag them as ADV based on the function? Or should they be given a different function? 

Personally I would just like to keep their morphological POS and still label them advmod, since that is the most informative option IMO.

**Comment by nschneid** [comment]
I like to think of `advmod` as short for *adverb* modifier, not *adverbial* modifier. PPs used adverbially, for example, are `obl`. (This may well be different from what "advmod" means in other dependency schemes.)

**Comment by amir-zeldes** [comment]
Right, I see, this is actually the same for English now that I think of it, where we have `obl:npmod` (formerly `npadvmod`). I have no problem with `obl` for adverbially used PPs, these just have no prepositions. I guess we'll need to decide whether we prefer to allow `obl` without a preposition in Coptic (currently not done in the treebank) or add a subtype to keep them distinct, maybe leading to some sparseness.

**Comment by msklvsk** [comment]
For Ukrainian, the validator generates 43 _'advmod' should be 'ADV'_ errors for a special case which we separated into special relation [`advmod:det`](http://universaldependencies.org/uk/dep/advmod-det.html). These are pronominal adjectives that modify a degree of an adjective. They agree as an adjective but are always translated as an adverb into English and West Slavics.
<img width="366" alt="image" src="https://user-images.githubusercontent.com/473012/57015254-83f0ef00-6c1c-11e9-9824-23bd21c30dda.png">

How would we please the validator without compromising the truth?

**Comment by dan-zeman** [comment]
Would `det:advmod` be a problem, instead of `advmod:det`?

(BTW I found one occurrence of this in Czech, and it got `det`: http://hdl.handle.net/11346/PMLTQ-ZX2X)

**Comment by msklvsk** [comment]
It would be a problem since it goes against [`det`](http://universaldependencies.org/u/dep/det.html)’s definition:

> `det` holds between a nominal head and its determiner

We thought `advmod` would be a better base relation because it can be considered adverbial (and translations show that). But I see no justification for `det`.

Also, you can always replace `DET` with an `ADV` synonym in this cases, like _настільки_ (this-much).

Interesting that Czech has this construction. SynTagRus has an [abundance](http://bionlp-www.utu.fi/dep_search/query?search=L%3Dтакой%20%3C%20ADJ&db=UD_Russian-SynTagRus-dev&case_sensitive=True&hits_per_page=50) of such cases too, all `det`, but I think it only sweeps the problem under the carpet. It stays hidden until you implement a validation rule that allows `det` from nominals only, as the definition says.

**Comment by dan-zeman** [comment]
I see your point. So the question is whether we want to admit that determiners can act as `advmod` for adjectives, or whether the definition of `DET` should be extended to allow adjectival heads.

In any case I think you can rest assured that I cannot implement a validation rule that requires `NOUN` as the head of a `det`. Since the noun can be elided, and UD solves such elipsis with promotion, it is always possible that an adjective will be promoted to the head of the nominal. Then a `det` relation going out of the adjective is legal regardless whether the definition of `det` explicitly mentions it or not.

**Comment by KoichiYasuoka** [comment]
In Classical Chinese, we observe some adverbial use of `VERB` (single word), so we introduced `VerbForm=Conv` with `advmod`:
```
# sent_id = KR1h0004_001_par5_12-16
# text = 節用而愛人
1	節	節	VERB	v,動詞,描写,態度	Degree=Pos|VerbForm=Conv	2	advmod	_	Gloss=moderate|SpaceAfter=No
2	用	用	VERB	v,動詞,行為,動作	_	0	root	_	Gloss=use|SpaceAfter=No
3	而	而	CCONJ	p,助詞,接続,並列	_	4	cc	_	Gloss=and|SpaceAfter=No
4	愛	愛	VERB	v,動詞,行為,交流	_	2	conj	_	Gloss=love|SpaceAfter=No
5	人	人	NOUN	n,名詞,人,人	_	4	obj	_	Gloss=person|SpaceAfter=No
```
In the particular example above "moderately use and love person", we observe `VERB` 節 is used as a [verbal adverb](https://universaldependencies.org/u/feat/VerbForm.html#conv-converb-transgressive-adverbial-participle-verbal-adverb) to modify another `VERB` 用.

**Comment by dan-zeman** [comment]
@KoichiYasuoka Words that are tagged `VERB VerbForm=Conv` are attached via `advcl` in other languages. It is not a problem that the clause consists of a single word. Single-word clauses are not so rare, especially nonfinite clauses.

Alternatively, it is possible to tag the word `ADV VerbForm=Conv` and attach it via `advmod`. So it depends on your priorities and judgment what is more acceptable: to assume a conversion (zero-derivation) of an adverb from a verb, or to keep treating the word as a verb and admit that it forms a minimalistic clause.
