### ISSUE TITLE
Gaps in fixed expression: "because of" and similar

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/docs#623]
We have a case in the Coptic TB where a fixed expression, roughly 'because of', is interrupted by some Wackernagel clitics, which appear in the second position in the sentence while ignoring syntactic structure:

```
ebol de on je ...
out but also that ...
"But also because..."
```

The words 'ebol' and 'je' appear separately often, meaning 'out' and 'that', but the combination is consistently annotated as a fixed expression, similarly to English "because of" (also `fixed`). The words 'on' and 'de' are enclitic and will appear in second position no matter what else is happening in the sentence. 

The only problem I have is that the validator is complaining about this with "Gaps in fixed expression". 

Any ideas on how to handle this are appreciated!

**Comment by dan-zeman** [comment]
Joakim is right that the UD guidelines do not explicitly forbid discontiguous fixed expressions. [The guidelines](http://universaldependencies.org/u/dep/fixed.html) refer to [Sag et al. 2001](http://lingo.stanford.edu/pubs/WP-2001-03.pdf), section 2.1. When writing the validation rules, I deduced this rule from the Sag et al.'s work, specifically from the statement that a fixed expression could be represented as a simple word-with-spaces.

In fact, I had to remove the fixed analysis in a number of occurrences in Czech, where an expression which is normally fixed was interrupted. One possibility is similar to what Amir reports: a conjunction or grammaticalized adverb intrudes into a multi-word preposition because of Wackernagel-like rules:

* _nehledě na X_ "regardless of X"
* _nehledě tedy na X_ "regardless thus of X"

This is rare but in theory it can happen with any multi-word preposition; if discontiguous fixed expressions are allowed, I will revert this change and make them fixed again. The second pattern is slightly more suspicious because it directly affects the subtree of the fixed expression:

* _na základě X(genitive)_ "on the basis of X"
* _na jejichž základě_ "on whose basis"

Here, _na základě_ is normally treated as a fixed multi-word preposition and it is attached as `case` to the noun representing the thing whose basis is referred to. However, historically it was just the noun _základě_ "basis" modified by another noun in the genitive. And here is where the second example comes from: the genitive nominal is replaced by a possessive relative pronoun. This is semantically parallel to a genitive nominal but it is not a genitive noun phrase. So not only it appears in the middle of the "fixed" expression, it is also quite strange if we make it the head and attach the fixed expression as its `case`. I am not sure whether _na základě_ "on the basis of" deserves to be analyzed as `fixed` in these constructions, even if we allow discontiguous fixed expressions. And if it does not, is it a good idea to analyze the normal cases as fixed, when they are in fact parallel to this? Shouldn't we get rid of noun-involving multi-word prepositions completely?

**Comment by dan-zeman** [comment]
As for the validator, I have tentatively switched this test off in https://github.com/UniversalDependencies/tools/commit/3c84a16f3f746058247217d0352e39967d4a40ed.

**Comment by sylvainkahane** [comment]
I don't understand why _because of_ and your other examples should be analyzed as fixed expressions. For me it's clearly a confusion between syntax and semantics. There are a lot of adverbs in English which have complements: _regardless of N, independently of N, apart from N_, etc. I don't see any reason not to use the relation `obl` here. Cf. our paper [Multi-word annotation in syntactic treebanks - Propositions for Universal Dependencies](https://aclweb.org/anthology/papers/W/W17/W17-7622/).

**Comment by ceramisch** [comment]
I agree with @sylvainkahane for _because of_

I'm not 100% familiar with the current state of the guidelines concerning `fixed' expressions, but I've been studying similar constructions in French. I tend to believe that a construction that seems syntactically regular should get a regular analysis using standard dependencies. A stand-off semantic/MWE layer would then group such "fixed" expressions for further (semantic) processing.

Moreover, this introduces differences that are hard to explain: some _of_ are `case` dependents of the nouns they introduce, others are `fixed` dependents of some (arbitrary) previous word. The argument to distinguish both is semantic (e.g. it ignores the distribution of _because_, which can occur without _of_). Without more advanced guidelines or lists per language, this kind of distinction is likely to yield annotation inconsistencies.

As for the coptic example, it seems more complex because of the positon of clitics. The `fixed` dependent seems to be a complementiser, so I guess it could be a `mark` of what comes next, probably like for the clitics (?)

**Comment by bulbulistan** [comment]
'because' is not an adverb, is it?
We'll do it regardless.
They have arrived at this conclusion independently.
Why do these two always sit apart?
*I came here because.
Or am I missing something?

**Comment by amir-zeldes** [comment]
The semantic part of the argument is that ebol does not mean because: it only means "out" by itself. The preposition for "because" would be etbe.

The argument for treating them as one unit is also syntactic though: ebol je alternates with single token marks, such as jekaas in Coptic, so we are just saying, taken together this idiomatic expression functions as one `mark`. 

Finally there are perhaps cognitive and morphophonological reasons to assume items such as because of ('cus-a), out of (outta) etc., which are probably stored and have idiosyncratic properties. 

I do agree though with @ceramisch that it seems likely some language specific decisions do not match neatly across corpora. But if we consider them to be complex lemmas, maybe this is just a difference in lexicon.

**Comment by amir-zeldes** [comment]
@dan-zeman @jnivre ud-cop-scriptorium now validates, thanks! On to eng-gum...

**Comment by sylvainkahane** [comment]
@amir-zeldes You say: "The semantic part of the argument is that ebol does not mean because: it only means "out" by itself." That's a purely semantic argument. It does not prove that the construction is syntactically irregular. 
Your other argument, _out of_ = _outta_, is morphonological, as you said, and similar to _want to_ = _wanna_, which do not trigger off a `fixed`.
@bulbulistan The fact that the complement "_of_ N" is obligatory does not imply that _because of_ is `fixed`. A verb also can have an obligatory complement.

**Comment by nschneid** [comment]
@sylvainkahane is your objection to using `fixed` for combinations like *because of* and *out of* in general, or just if some other external process can create a gap between the words, as is the case with Coptic?

[The current guidelines for `fixed`](http://universaldependencies.org/u/dep/fixed.html) clearly include *because of* and the connective *as well as*, at least for English. If you are proposing a change to the guidelines perhaps that should be a separate issue.

**Comment by amir-zeldes** [comment]
@sylvainkahane I agree that semantics and morphophonology alone are not criteria for making syntactic decisions, but in my opinion they can be relevant when deciding between two plausible analyses, especially in ongoing or recent grammaticalization. The syntactic motivation, as I mentioned, is substitutability, which is not a semantic test: ebol je is in a pradigmatic relationship with words like jekaas 'since'. Specifically for subordinating conjunctions, UD treebanks largely have a single item with the function `mark`, and this holds for other Coptic adverbial clauses as well, so that allowing us to have the equivalent of a single `mark` here increases consistency.

The relevance of the morphophonological and semantic evidence is that it demonstrates a plausible case  why we think speakers of the language might also view these as single items at the syntactic level. Adding a productive syntactic analysis within such recently grammaticalized 'words' may be possible, but runs the risk of putting apples and oranges in the same basket: we can also decide that 'during' is a living participle of an extinct verb 'dure' and annotate it `advcl` (historically correct), but synchronically I think it is best to place it in the paradigm of prepositions. The case of 'because of' seems less obvious, and I agree it's a judgment call, but I don't think it obscures the syntax of adverbs that take prepositional arguments (those seem like a different class than 'because of' to me).

**Comment by sylvainkahane** [comment]
@nschneid If it is possible to insert words between two words A and B that are linked, it means that AB has an internal syntactic structure. It is why @dan-zeman forbid gaps between fixed expressions at first.

I also think that _because of_ should be analyzed syntactically. Such a choice is particularly problematic for UD, because we know that these two words form a unit together and, due to the particular choices of UD where function words such as _of_ are dependents, the only way to link _because_ and _of_ in UD is to have a `fixed` link between them. With a more common surface-syntactic annotation, this problem disappears and we can say both that there is a regular syntactic relation between these two words and that, due to semantic freezing, this link becomes particularly cohesive (and can even be subject to morphophonological reductions such as _out of_ -> _outta_).
We have to accept that _because_ and _of_ won't be linked in UD or that they will be linked by a `fixed` link although it's a regular syntactic link.

**Comment by amir-zeldes** [comment]
I think you could link because + of in UD and retain the case analysis in several ways, maybe most directly by treating because as an adverb that takes a PP (like 'outside'):

```
I did it because of the rain
advmod(did,because)
obl(because,rain)
case(rain,of)

I did it outside of the house
advmod(did,outside)
obl(outside,house)
case(house,of)
```

But I don't think this is a better analysis: for outside you can easily remove the PP, and it's clear it has an adverbial function ("I did it outside", *"I did it because"). I think for me synchronically it's strange to think of 'because' in 'because of' as an adverb, so by picking a `fixed` analysis we're saying "because of" is more like a complex preposition, rather than an adverb with a complement. But I recognize this is probably a matter of preference, I don't have a clear cut syntactic reason why it's not like "outside of" (anyone?)

BTW historically I suspect the reason for this analysis in EWT goes back to PTB, where "because of" is tagged IN, IN and both tokens just stand at the left of a PP phrase, so at least this is consistent with other treebanks based on PTB.
