### ISSUE TITLE
Too strict constraint "Punctuation must not cause non-projectivity of nodes"?

### ISSUE THREAD

**Issue by LarsAhrenberg** [UniversalDependencies/docs#624]
Generally I find the validation very helpful in identifying errors as regards punctuation, but I have hit upon a problem with paired punctuation marks such as citation marks. The following is a (simplified) example from English_LinES:

`The Americans wanted the new regime to educate the population and create "a stable middle-class, so that real democratic institutions could develop".`

My reading is that the citation marks includes two unrelated parts both of which have their heads before the first citation mark:

```
obj(create,middle-class)
advcl(create,develop) alt. advcl(educate,develop)
```
Also, I assume that the two citation marks should have the same head, say middle-class, within the stretch marked by the citation marks. This annotation will cause the validation script to signal an error, however. So it seems I must assign the two citation marks different heads, or treat the two parts as syntactically or paratactically related. Does anyone have a suggestion?

**Comment by dan-zeman** [comment]
This issue overlaps with https://github.com/UniversalDependencies/docs/issues/440. (I thought there was another more recent issue about this but it turns out that it was just an e-mail exchange with a few people @perrier54 @bguil @jnivre .) Long story short: preserving projectivity has higher priority than attaching paired punctuation to the same head; the priority follows from the v2 [guidelines](http://universaldependencies.org/u/dep/punct.html).

If the text enclosed in the paired marks does not have a single head, then I think it does not make much sense to attach both marks to the same node; attaching each mark to the highest node of the closest component inside the brackets would seem sensible to me. Nevertheless, if we strictly follow the guidelines, we can actually (sometimes) find the common ancestor outside the bracketed/quoted segment. In the example given by @LarsAhrenberg , the word _create_ could play this role if both components within the quotes were attached to it. However, I suspect that the first component should be attached to _create_ and the second to _educate_. Then it is not possible to attach both quotation marks to the same node without breaking projectivity.

**Comment by amir-zeldes** [comment]
Honestly I don't care too much about how the punctuation is attached, the problem for me is more that udapi is producing punctuation attachments that trigger validation errors. Whatever is decided for these cases, it would be great if there were a deterministic procedure to attach punctuation to an otherwise gold tree which passes validation - and even better if this can be implemented in udapi :)

**Comment by martinpopel** [comment]
@amir-zeldes: If you know about any cases where [Udapi](http://udapi.github.io/) (I expect you mean the [ud.FixPunct](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/fixpunct.py) block) produces a non-valid output, please let me know. Ideally, attach a sample (single-sentence) conllu input, actual output and expected output and report it via [Udapi issues](https://github.com/udapi/udapi-python/issues). Make sure it is a Udapi issue, not a [UDPipe](http://ufal.mff.cuni.cz/udpipe) one (UDPipe parser produces similar structures to what it has seen in the training data).

**Comment by LarsAhrenberg** [comment]
Thanks @dan-zeman for your answer and pointer. I think your solution makes sense, given that citation marks mostly have other motivations than syntax,

**Comment by amir-zeldes** [comment]
@martinpopel - Yes, thanks, I meant FixPunct - here's an example that stays non-projective after process_document(): (tested with udapi 0.2.2 under Python 3.6)

```
1	Most	most	ADJ	JJS	_	2	amod	_	_
2	fields	field	NOUN	NNS	_	13	nsubj	_	SpaceAfter=No
3	,	,	PUNCT	,	_	2	punct	_	_
4	on	on	ADP	IN	_	7	case	_	_
5	the	the	DET	DT	_	7	det	_	_
6	other	other	ADJ	JJ	_	7	amod	_	_
7	hand	hand	NOUN	NN	_	13	obl	_	SpaceAfter=No
8	,	,	PUNCT	,	_	7	punct	_	_
9	including	include	VERB	VBG	_	11	case	_	_
10	computer	computer	NOUN	NN	_	11	compound	_	_
11	science	science	NOUN	NN	_	2	nmod	_	SpaceAfter=No
12	,	,	PUNCT	,	_	2	punct	_	_
13	lack	lack	VERB	VBP	_	0	root	_	_
14	a	a	DET	DT	_	17	det	_	_
15	single	single	ADJ	JJ	_	17	amod	_	_
16	all-encompassing	all-encompassing	ADJ	JJ	_	17	amod	_	_
17	organization	organization	NOUN	NN	_	13	obj	_	_
18	and	and	CCONJ	CC	_	23	cc	_	_
19	membership	membership	NOUN	NN	_	20	compound	_	_
20	information	information	NOUN	NN	_	23	nsubj	_	_
21	is	be	AUX	VBZ	_	23	aux:pass	_	_
22	instead	instead	ADV	RB	_	23	advmod	_	_
23	distributed	distribute	VERB	VBN	_	13	conj	_	_
24	across	across	ADP	IN	_	27	case	_	_
25	many	many	ADJ	JJ	_	27	amod	_	_
26	disjoint	disjoint	ADJ	JJ	_	27	amod	_	_
27	lists	list	NOUN	NNS	_	23	obl	_	SpaceAfter=No
28	,	,	PUNCT	,	_	33	punct	_	_
29	such	such	ADJ	JJ	_	33	case	_	_
30	as	as	ADP	IN	_	29	fixed	_	_
31	web-based	web-based	ADJ	JJ	_	33	amod	_	_
32	faculty	faculty	NOUN	NN	_	33	compound	_	_
33	directories	directory	NOUN	NNS	_	27	nmod	_	_
34	for	for	ADP	IN	_	36	case	_	_
35	individual	individual	ADJ	JJ	_	36	amod	_	_
36	departments	department	NOUN	NNS	_	33	nmod	_	SpaceAfter=No
37	.	.	PUNCT	.	_	13	punct	_	_
```

**Comment by amir-zeldes** [comment]
Oh wait, you wanted a udapi issue, I will open one!

**Comment by msklvsk** [comment]
This rule is being triggered in Ukrainian for:

_She-said: «All [of] this happened before those big struggles» (that-is before [the] October Revolution)_

There is an `appos`(_struggles_, _Revolution_) that crosses the closing quote. Do you suggest I should connect the closing quote to _Revolution_? What is so important about projective punctuation that justifies such a butchering of a truthful analysis? Yes, it’s non-projective, which signifies it’s about something inside the quotes. 

There are currently 4 similar cases in our TB.

**Comment by dan-zeman** [comment]
I suggest that you should connect the closing quote to _struggles_.

**Comment by msklvsk** [comment]
@dan-zeman What is the reasoning behind the projectivity rule, why is it so important? “Fixing” natural non-projective occurrences seems like breaking logic and intuition, losing info.

**Comment by dan-zeman** [comment]
If I recall it correctly, the reasoning was that punctuation, strictly speaking, is not part of the syntactic structure, but we have to attach it somewhere. So we would not lose information regardless of where we attach it, but obviously we want some rules rather than random attachment. Non-projective dependencies are generally considered difficult to parse, so it was decided that the projectivity requirement would have the highest priority among those more-or-less arbitrary rules.

Personally I agree that it would be aesthetically more appealing if paired symbols could always have the same parent (which they sometimes cannot anyway, for reasons other than projectivity), but I am not sure it would have been worth it to define such cases at the time v2 guidelines were being designed; and I do not think that it would be useful to redesign the guideline now (which would also mean finding and re-attaching such cases in more than 200 treebanks).

**Comment by sylvainkahane** [comment]
@dan-zeman Parsing is one reason to develop treebanks, and at the beginning of UD it was certainly the main reason if not the only reason. But more and more treebanks in UD are developed by linguists with different goals. For these linguists, it is important that particularly tricky constructions are well annotated. These cases where double punctuation cannot be annotated projectively can interest some linguists and they don't want to crush them.
As you said, punctuation is not very important and I don't think that people will reannotate double punctuations in existing treebanks, but if some people want to have a clean annotation of double punctuations, I don't see why it is a problem for others. The validation rule could be as follows: a `punc` link must be projective, except when it is attached to the same governor as a projective `punc`. A more precise validator could ask the list of double punctuations.

**Comment by perrier54** [comment]
I checked for expressions in quotation marks or parentheses with a [Grew-match query](http://universal.grew.fr/?custom=62a0a7f760a51). The query aims to find opening parentheses or quotation marks without punctuation marks depending on the same head.
I found 257 occurrences, among which 237 correspond to expressions between quotation marks or between parentheses, where one of the two punctuation marks is missing. This is due to a questionable splitting of the corpus into sentences. 
20 occurrences correspond to dependencies between a token inside the bracketed expression, which is not the head of the expression, and a token outside the expression.
In these cases, if we attach the two punctuation marks to the head of the bracketed expression, the sentences check the validation rule given by @sylvainkahane .
These 20 cases are linguistically interesting and it would be a pity not to show them by relaxing the validation rule.

**Comment by dan-zeman** [comment]
> relaxing the validation rule

The validation rule is not my arbitrary whim, it directly follows from the guidelines. If the guidelines are changed, the validation rule will be changed, too.

**Comment by msklvsk** [comment]
> If the guidelines are changed, the validation rule will be changed, too

Is there a ‘box’ where we can put suggestions for guideline (breaking) changes?

**Comment by dan-zeman** [comment]
Now with the new policy that allows amendments to the v2 guidelines it is conceivable that such a change will be approved by the core group as an amendment. There is no dedicated ‘box’ though. The amendments introduced with UD 2.10 were linked to one or more open issues here in the issue tracker, so I guess that could be the way. Perhaps with a new label "amendment wanted" (or with the existing label "enhancement").
