### ISSUE TITLE
AUX vs PART for TAME markers

### ISSUE THREAD

**Issue by prokopidis** [UniversalDependencies/docs#625]
Hi,

The `AUX` guidelines [mention](https://universaldependencies.org/u/pos/AUX.html) that "[an auxiliary] is often a verb (which may have non-auxiliary uses as well) but many languages have nonverbal TAME markers and these should also be tagged AUX." But the `PART` guidelines [mention](https://universaldependencies.org/u/pos/PART.html) "Indeclinable aspectual or tense particles: [zh] 了 / le" as examples of words to be tagged as PART. 

I am not familiar with the languages and the context of the `PART` examples. Are these particles not attached to verbs? If they are, isn't there a conflict here and shouldn't these words also be tagged `AUX`?  Also, should the `AUX` page perhaps state more explicitly that nonverbal TAME markers to be tagged as `AUX` (and `aux`) include indeclinable TAME particles, if this is the guideline?

Thanks.

**Comment by jnivre** [comment]
Thanks for reporting this, Prokopis. I suspect the reason for this apparent inconsistency is that the PART page has not been updated for v2. In v1, the AUX tag had a more narrow definition and was limited to auxiliary verbs, I think. We should make sure that these are made consistent.

**Comment by dan-zeman** [comment]
Agreed with Joakim. I have removed the Chinese example from `PART` because I think it should indeed be `AUX` in UD v2 (although I'm not a Chinese speaker and I can be missing something; but the example, as it stood there now, was misleading).

**Comment by sylvainkahane** [comment]
Auxiliary verbs in Indo-European languages are verbs that subcatogorize the lexical verbs and change its form. For this reason they cannot be erased and they are the distributional head, even if UD choose to analyze them as dependents.
```
Peter comes
Peter is coming
*Peter coming
```
Aspectual particules in Chinese are quite different because they are optional and they don't change the form of the verb. I think that this difference must be kept somewhere. It is nice that they both have the function `aux` and that some are AUX and others PART.

**Comment by amir-zeldes** [comment]
Auxiliaries in some IE languages can be erased (especially in some historical varieties, such as earlier Slavic, leading to Russian preterit without auxiliary, or early new high German), and some particles can't be erased if you want to get a past tense reading. 

Personally I don't think AUX is really a part of speech cross-linguistically, it's more of a functional category than a morphological one. But if we're tagging verbs as AUX, I think we may as well tag particles the same. In Coptic we have a number of auxiliaries with deprel `aux`, some of which were historically verbs in Ancient Egyptian, and some of which were other indeclinable elements. Synchronically they all occupy the same slot, so it's convenient to just call all of them AUX, regardless of etymology.

**Comment by dan-zeman** [comment]
In UD v1 it was assumed that `AUX` would be verbal. For v2 it was originally suggested that the `AUX` category be removed because it is simply a `VERB` attached via an `aux` relation. But the final decision was to keep the category in v2 and extend it to indeclinable particles that have a similar function as auxiliary verbs in other languages, such as the future tense particles in Bulgarian and Greek, or the conditional particles in some Slavic languages. `PART` was kept for particles that don't fit in `AUX` for whatever reason, with the note that it should be used sparingly (language-specific documentation should list all particles in the language and make a case for each of them, why it cannot be tagged with any other category).
