### ISSUE TITLE
flat:foreign in German

### ISSUE THREAD

**Issue by EmanuelUHH** [UniversalDependencies/docs#632]
We are not quite sure how to deal with the relation subtype `flat:foreign`. The validation tool does not accept the use of flat:foreign for German. Is that intended or should we still use it if applicable? 

And if we should use it (and assuming it is for some reason not possible to annotate according to the foreign language): can `flat:foreign` be used for loanwords and foreign names when they are included in a foreign phrase?

**Comment by dan-zeman** [comment]
As with all relation subtypes, it has to be declared specifically for each language in which it is to be used. The reason why it was not accepted by the validator is that this relation has not been used in any other German treebank and was not (until now) declared in [deprel.de](https://github.com/UniversalDependencies/tools/blob/master/data/deprel.de).

It is now allowed and you can use it. Ideally the German treebanks should be harmonized in the future, i.e., `flat:foreign` should be used instead of `flat` at appropriate places in the other treebanks as well.

**Comment by EmanuelUHH** [comment]
Thanks. :)

**Comment by dan-zeman** [comment]
As for your second question: If you declare a segment of your data as a foreign phrase, then I think it is up to you whether you include the foreign words (and names) that could also appear directly in German as loanwords.

You could also share a word with the foreign language although it is not a loanword (e.g. German vs. English _so_) and I think you would still treat it as foreign if it appears in the middle of a foreign phrase.
