### ISSUE TITLE
Hyphens/other symbols as case markers

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#649]
EWT specifies the hyphen as a case marker of the following number in e.g. "September 16 - 18". However, unlike case markers spelled as proper words, punctuation/symbol case markers are not reflected in the enhanced nmod dependency (presumably `nmod:-` would be problematic).

Should `nmod:to` be used in these cases as that is how it would be pronounced? Should the hyphen be tagged as `ADP` with "to" as the lemma? Currently it is tagged as `SYM`.

A few other symbols also serve as case markers: "/", "@", "x".

There are 6 tokens tagged as `PUNCT` serving as case markers, but these should probably be `SYM`.

**Comment by sebschu** [comment]
I'm not sure about the POS tag, but yes, I think the lemmas should be "to", "at", "by", etc. in these cases (and the enhanced relation `nmod:to`). IIRC, we do the same for uses of "2" instead of "to" and "4" instead of "for".

**Comment by nschneid** [comment]
> IIRC, we do the same for uses of "2" instead of "to" and "4" instead of "for".

Correct.

One wrinkle: "/" can be ambiguous between "and" and "or", even to human readers. We could go with "slash" as the lemma in such cases.

(I could see an argument that "-", "/", "x" are actually coordinating conjunctions rather than adpositions—and Geoff Pullum was sympathetic to this analysis when I discussed it with him following #645—but this is not a hill I'm willing to die on.)

**Comment by sebschu** [comment]
> "/" can be ambiguous between "and" and "or", even to human readers. We could go with "slash" as the lemma in such cases.

I don't have a strong opinion about this, but I'm not totally convinced that using "slash" instead of "/" as the lemma would be a better solution than keeping "/". In the other cases, using the preposition highlights the equivalence of "-" and "to", but that doesn't apply if we use "slash". And further, is it really always pronounced as "slash" when read aloud? i think in some cases, people just use prosody to convey the non-specific conjunction.

**Comment by nschneid** [comment]
Then is there a good alternative to `nmod:/`?

**Comment by sebschu** [comment]
Probably not, but I think we have to convince @dan-zeman of that, because last time I checked, the validator did not accept treebanks with special characters in the relation name :)

**Comment by dan-zeman** [comment]
POS tag: If it is pronounced aloud and it has a syntactic function, it is not `PUNCT`. But if, at the same time, it resembles punctuation because it consists of special characters, the `SYM` tag is used.

Enhanced deprel: it's not just the validator, we have also specified in the guidelines the characters that can appear in a deprel. I'd really like to avoid non-alpha characters here. Using `nmod:slash` seems more acceptable to me (although I never really bought the idea that case-extended deprels are good).

**Comment by amir-zeldes** [comment]
RE pos and lemma in GUM: 
  * `-` meaning 'to': xpos="TO", upos="ADP", deprel="case", lemma="-"  (there are different types of dashes and we give them all themselves as the lemma)
  * `/` meaning 'or': xpos="SYM", upos="SYM", deprel="cc", lemma="/"

For me '/' etc. is its own word, and indeed it can be pronounced 'slash', or 'or', so it can be a distinct lemma, but syntactically it's a `cc`. The POS decision is based on the PTB guidelines for '/'. For "TO" we wanted to avoid PUNCT for a `case`, so we treated it like the word 'to' (but still gave a distinct lemma).

I feel like this, and a lot of other issues should probably be standardized across the English TBs, since at the moment it's really impossible to concatenate and train on all of them.

**Comment by nschneid** [comment]
Regarding putting the lemma in the enhanced dependency, see #566
