### ISSUE TITLE
Chinese validator doesn't recognize copula "为/為"

### ISSUE THREAD

**Issue by qipeng** [UniversalDependencies/docs#653]
"为/為" is a pretty common copula in Chinese, aside from its other uses.

For instance (part of `sent_id = dev-s498` in the dev set of Chinese-GSDSimp)
```
61  五  五  NUM CD  NumType=Card    62  nummod  _   SpaceAfter=No
62  楼  楼  NOUN    NN  _   65  nsubj   _   SpaceAfter=No
63  为  为  AUX VC  _   65  cop _   SpaceAfter=No
64  演艺    演艺    NOUN    NN  _   65  case:suff   _   SpaceAfter=No
65  厅  厅  PART    SFN _   10  parataxis   _   SpaceAfter=No
66  。  。  PUNCT   .   _   10  punct   _   SpaceAfter=No
```

**Comment by dan-zeman** [comment]
This issue seems to be a Chinese variant of the issues #622 and #627. (For the record: there was also #497 directly about the Chinese copula, although it was not about the possibility to have more than one copula in Chinese.)

So I have essentially the same question: If you look at [the copula documentation](http://universaldependencies.org/u/dep/cop.html), does this seem to be a legitimate exception to the one-copula-per-language rule? The validator currently knows 是 as the Chinese copula. If 为/為 is a legitimate second copula even in the UD sense, I will be happy to add it.

**Comment by qipeng** [comment]
Thanks for the context, @dan-zeman ! 

为/為(wei2) does not convey more semantic information than 是(shi4) when acting like a copula, and I think in most cases they are interchangeable. The sentence in my original post reads just fine with 是:

```五楼是演艺厅。```

I think the main difference is that 是 is used both in spoken and written Mandarin, whereas 为/為 (probably also 系/係 too) is more formal and mostly used in formal speech and (formal) written text. Same thing probably holds for Cantonese 係 (informal) vs 為 (formal, maybe 是 also?), although I'm not L1 in Cantonese so can't be 100% sure.

Feel free to loop in more L1 experts on this one to discuss this matter!

**Comment by dan-zeman** [comment]
@wongtaksum Should we add 為 as a second possible copula in Cantonese?

**Comment by dan-zeman** [comment]
I have added 为/為 (wei2) to the Chinese list.

**Comment by qipeng** [comment]
Thanks, @dan-zeman !

**Comment by wongtaksum** [comment]
Oh sorry for not replying you earlier...
為 is not used in colloquial Cantonese but only in high variety, like when reporting news.  Nevertheless, I think it is still reasonable to add this verb to the copula list in Cantonese.
