### ISSUE TITLE
Need Help in including repositories to my account UniversalDependencies/UD_Sindhi-MazharDootio

### ISSUE THREAD

**Issue by mazharaliabro** [UniversalDependencies/docs#656]
I am new one and want to add repositories to GitHub account UniversalDependencies/UD_Sindhi-MazharDootio 
What I have to do to include Sindhi language in up coming process of universal dependency in November 2019?
Please help me in defining the steps for inclusion Sindhi language.

**Comment by dan-zeman** [comment]
Hi @mazharaliabro, your Github user account already has write access to the repository UD_Sindhi-MazharDootio. You can use the git tool to clone the repository to your computer, add files to your local copy of the repository, then use the commands "git commit" and "git push" to push the changes back to Github. All this is documented in our [Release Checklist](https://universaldependencies.org/release_checklist.html) page. (In particular, working with git is described [here](https://universaldependencies.org/release_checklist.html#repository-branches).) If anything remains unclear, feel free to ask me directly.

The deadline for the upcoming release is November 1. Your data should be present in the repository on Github, and reported as VALID by the [automatic validation page](http://quest.ms.mff.cuni.cz/cgi-bin/zeman/unidep/validation-report.pl). After November 1, the data freeze period begins. In that period people are not supposed to modify the contents of the repositories unless specifically asked for it; that is because I will be working on preparing the release packages and sudden changes might break the process. After the release, it will be possible to modify the data again if anything has to be improved for the future releases.

**Comment by dan-zeman** [comment]
The next data freeze deadline will be May 1, 2020. I am closing this issue now.
