### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/docs#669]
In the current workflow, only @dan-zeman promote data to the `master` branch of the repositories, right? We all prepare the data in the `dev` branch. The problem is that git insights are restricted to the master branch and people can't get a real idea of the contributors and their efforts. How to deal with that?  See PT case

https://github.com/UniversalDependencies/UD_Portuguese-Bosque/graphs/contributors

**Comment by martinpopel** [comment]
When @dan-zeman **merges** the dev branch to the master branch, all the commits from the dev branch (since the last merge, i.e. since the last release) are included in the master and reflected in GitHub insights. So the GitHub insights reflect the number of commits of each contributor until the last release, which is quite OK, I think. (It would be different if Dan had squashed all the commits from dev and copied just the content of the conllu files into the master omitting the commit history.)

Another issue is that the number of commits and even the number of lines changed/deleted/added by each contributor do not reflect accurately their efforts. Many of Dan's commits are just "updated statistics" or "Updated CONTRIBUTING.md", which he probably does semi-automatically in all the UD repositories. (That said, I know there is a lot of "invisible" work Dan does for UD.) Note that the merge commits themselves are not included in the GitHub Insights statistics. I think there is nothing we can do with this issue - number of commits/lines can never accurately reflect the effort. My suggestion: if you want, you can update the [Acknowledgments section of README.md](https://github.com/UniversalDependencies/UD_Portuguese-Bosque/blob/master/README.md#acknowledgments) and add some details about the contributors' efforts (in each UD release).

**Comment by arademaker** [comment]
Hi @martinpopel, thank you for clarifying. I was misguided by the current statistics in our repo.
