### ISSUE TITLE
Sufficiency/excess constructions: enough/too/so X that/to Y

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#672]
E.g.:

- The apples are ripe ENOUGH to pick.
- The apples are TOO ripe to pick.
- I have ENOUGH apples to cook 10 pies.
- I have SO many applies that I can cook 10 pies.

Arguably the scalar modifier (TOO/SO/ENOUGH) licenses an optional embedded consequence clause. **Should it be the head, even if this would make the tree nonprojective?**

The apples are TOO ripe to pick.
  * advmod(ripe, too), advcl(too, pick)?
  * advmod(ripe, too), advcl(ripe, pick)? Note that this is a bit awkward because "too" cannot be dropped without dropping the embedded clause (*The apples are ripe to pick).

I have ENOUGH apples to cook 10 pies.
  * amod(apples, enough), advcl(enough, cook)?
  * amod(apples, enough), acl(apples, cook)?

There is [discussion](https://universaldependencies.org/workgroups/comparatives.html) and [documentation](https://universaldependencies.org/u/overview/specific-syntax.html#comparatives) of comparatives, but I don't see "enough" and "too" addressed there (also known as the [Degree-Consequence Construction](http://www.lrec-conf.org/proceedings/lrec2018/pdf/856.pdf) or [Attributive Degree Modification Construction](http://www1.icsi.berkeley.edu/~hsato/cxn00/helpF/helpF/Attributive_degree_modification.html)).

English_GUM consistently attaches the embedded clause to the head of AdjP/NP, not ENOUGH/TOO/SO (unless ENOUGH is not modifying anything: "four days is enough to see the major sights").

English_EWT seems to be inconsistent.

**Comment by Stormur** [comment]
I think it is not a problem of _too_ being able to be dropped in such a construction. The head still is the nominal; when doing research on these constructions, one will be able to verify that (if) an element like _enough_ or _too_ is always present as a modifier of the nominal or not. Probably we have again a case where a notation for nesting would be useful, as it is _to pick_ that can be taken to modify the whole block _too ripe_., where in any case _ripe_ is the head. As it stands now, I'd say that

`amod(ripe,enough) , acl(ripe,pick)` ( `advmod(ripe,enough)`? )
`amod(apples,enough), acl(apples,cook)` ( or better `det(apples,enough)`? )


are correct interpretations and perfectly symmetrical (but doesn't _enough_ acts as an adverb in the first case?). `acl` because it is the nominal, and not the predicate, that is modified, i.e. [The apples] [are [enough ripe to pick]] vs. [The apples] [are ripe enough [to pick]]. Non-projectivity shouldn't be a concern: to me (although I'm not a native speaker) that _enough_ looks indeed non-projective, and, for how meaningful it might be, as a language-learner I would be in fact surprised that you can't say _enough ripe to pick_ (as in Italian, for instance)! :-)

**Comment by amir-zeldes** [comment]
I also agree that the nesting makes this trickier than it might be, and I don't think non-projectivity should stop us, but often the construction works without the 'enough', suggesting that it is not the head. For ripe we also have 'ripe for the picking' (suggesting that 'ripe' licenses 'ripe in what respect'), and for the pie I could say:

I have apples to cook 10 pies

Without 'enough'. In GUM you'll find cases like "wise enough not to sell..." which is similar to "you are wise not to sell it", where enough looks like an optional expansion. I think it should take strong evidence to want 'enough' to be the head, and even then we should consider whether it's really enough by itself or the adjectival phrase (in which case UD suggests the phrasal head should be the dependency head)

**Comment by nschneid** [comment]
> often the construction works without the 'enough', suggesting that it is not the head

I think these are different constructions—see below.

> For ripe we also have 'ripe for the picking'

This is a weird construction that I do not fully understand and that native speakers have varying opinions about the productivity of: https://twitter.com/complingy/status/1191012756025159681

A Facebook discussion showed that "for the taking" and "for the picking" were widely accepted, but generalizing the -ING form to other verbs was controversial.

> In GUM you'll find cases like "wise enough not to sell..." which is similar to "you are wise not to sell it"

Some adjectives license infinitival complements: "You are ready/eager/afraid/... to sell it." Then there is a construction which provides an evaluation of somebody who does something: "You were wise/an idiot to sell it", meaning that the sale reveals you to be wise or an idiot. So yes, it is possible for some of these uses of the degree modifier to be dropped. But not always: "*You are tall to sell it." This requires a degree modifier: "You are tall ENOUGH to sell it". I think it's fair to say ENOUGH licenses the embedded clause in at least these cases.

> I have apples to cook 10 pies

To get the 'enough' semantics I'd use a definite article: "I have the apples to cook 10 pies". I think this is yet another interesting construction (cf. have the guts to do something risky). It may be limited to verbs of possession: "?I saw the apples to cook 10 pies." (intended reading: 'I saw enough apples to cook 10 pies.').

Without the definite article, the reading that I get is that the purpose clause is modifying "have", meaning 'I have some apples, and the reason that I have apples is to cook 10 pies'. Not specifically asserting that the amount of apples is sufficient.

**Comment by nschneid** [comment]
"so many tell lies that none have credibility": I assume this should be advcl(many, have), a nonprojective dependency?

**Comment by dan-zeman** [comment]
> "so many tell lies that none have credibility": I assume this should be advcl(many, have), a nonprojective dependency?

Yes, probably.

**Comment by sylvainkahane** [comment]
I think it should be advcl(so, have), because it it _so_ that licenses the advcl:

> #many tell lies that none have credibility

I also suppose that the following dialogue is possible (it would be possible in French):

> Many tell lies. - Yes, so that none have credibility.

**Comment by nschneid** [comment]
> I think it should be advcl(so, have), because it it _so_ that licenses the advcl:

We discussed the possibility of making *so* the head of the subordinate clause, but decided that to be consistent with our treatment of comparatives, the head should be the degree-qualified adjective/adverb. (One way to look at it is that degree-modifier *so* is a functional element, and UD prefers content heads.) This is now clarified at https://universaldependencies.org/u/overview/specific-syntax.html#sufficiency-and-excess

> I also suppose that the following dialogue is possible (it would be possible in French):
> 
> > Many tell lies. - Yes, so that none have credibility.

This is possible in English but it is a different construction—this is "so that" as a connective expressing a consequence (which we treat as [a fixed expression](https://universaldependencies.org/en/dep/fixed.html#causal-connectives)). I can't get the reading that *so* is modifying *many* here.

**Comment by leky40** [comment]
Just out of curiosity 

how do we know that “so” in the clause above is either a subordinate conjunction, a modifier towards “many”, or a discourse marker?

what could hint us what “so” should be in this clause?

**Comment by nschneid** [comment]
@leky40 in "Many tell lies. - Yes, so that none have credibility."?

This can be paraphrased as "Many tell lies. - Yes, **with the result that** none have credibility."

According to https://universaldependencies.org/en/dep/fixed.html#causal-connectives, expressions like "so that" and "so as to" are treated as complex subordinators. (Note that these are idiosyncratic: you cannot paraphrase with "so to" or "so as that". I presume that is why `fixed` is used.)

**Comment by leky40** [comment]
@nschneid Thank you. At first, I could not read the clause "so many tell lies that none have credibility"  with "so that". Just one clause is not enough for me (a non-native speaker) to be able to read it. And I was often curious if "so" at the beginning should be either a conjunction, modifier, or discourse marker.

Now I can read it from your explanation that "so" is not just "so", but "so that". 

I am not sure if this would be relevant. I was wondering how "that" and "this" which are used as a modifier to express intenseness or degree would be annotated.

For example,

He is so used to that much attention.

I am this relaxed. 

Would "this" and "that" be adv in this structure? And advmod would be assigned: advmod(that, much) and advmod(this, relaxed)?

**Comment by nschneid** [comment]
Yes, ADV: https://universal.grew.fr/?custom=650f991b5241d
