### ISSUE TITLE
Should the appos dependency be left and right? 

### ISSUE THREAD

**Issue by rueter** [UniversalDependencies/docs#693]
I am looking for a solution to the dilemma _appos_ vs _nmod_ in relations, such as: 
Est _sõna "kommunist"_ 'en: the word "Communist"/fi: kommunisti-sana'
Eng _the word "terrorist"_ 'fi: terroristi-sana'
Swe _ordet schizofreni_ 'en: the word schizophrenia/jakomielitauti-sana'
Erzya _"kov?" kevkst'emas'_ 'en: the question "where?"/fi: kysymys "minne?"'

In the instances of Estonian and English, given below, the dependency _appos_ is used for: 
et: appos(sõna, kommunist), 
en: appos(word, terrorist)

In Swedish, on the contrary, the relation _nmod_ is applied: nmod(schizofreni, ordet).

It would seem that the dependencies _nmod_ and _appos_ are used to express the same dependency. 
(Finnish translations were provided due to the absence of Finnish examples where a hyphenated word "-sana" 'word' would be post-posed. There are instances in Finnish where such defining words are preposed; separate preposition is more common in Finnish than postposing.)

No examples were brought from the Finnish Parsebank, because the dependencies show too much inconsistency, e.g., _amod_, _nsubj_, _compound:nn_, _nmod_, etc., and the example contexts scarcely reflect Finnish original texts.

I first was fascinated by the use of the _appos_ dependency
[https://universaldependencies.org/u/dep/all.html#al-u-dep/appos]
hmm, nmod(dependency, _appos_), is this correct?

But examination of the TalBanken material _Ordet schizofreni_, in which nmod(schizofreni, Ordet) was given, I stopped again.
Hmm, perhaps nmod(Ordet, schizofreni) would be more to the point, as we are talking about a particular word.

Once again, however, we are referring to a dependency on the basis of ```use``` and not ```mention```.  
Problems in the Finnish Parsebank are seen in combination with the Finnish word ```ääntäminen``` `pronunciation': ```the pronunciation of "does"``` 
Do we want nsubj(does, pronunciation)?  I am perplexed.

Three contexts: Estonian, English and Swedish

Estonian solution:
```sõna "kommunist"```
[https://raw.githubusercontent.com/UniversalDependencies/UD_Estonian-EDT/master/et_edt-ud-test.conllu]
```
# sent_id = ilu_sauter_425
# text = Võibolla tuli see pähe sellepärast, et sõna "kommunist" sisu on muutunud minu jaoks väga segaseks.
1	Võibolla	võib_olla	ADV	D	_	2	advmod	_	_
2	tuli	tulema	VERB	V	Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin|Voice=Act	0	root	_	_
3	see	see	PRON	P	Case=Nom|Number=Sing|PronType=Dem	2	nsubj	_	_
4	pähe	pea	NOUN	S	Case=Add|Number=Sing	2	obl	_	_
5	sellepärast	selle_pärast	ADV	D	_	2	advmod	_	SpaceAfter=No
6	,	,	PUNCT	Z	_	14	punct	_	_
7	et	et	SCONJ	J	_	14	mark	_	_
8	sõna	sõna	NOUN	S	Case=Gen|Number=Sing	12	nmod	_	_
9	"	"	PUNCT	Z	_	10	punct	_	SpaceAfter=No
10	kommunist	kommunist	NOUN	S	Case=Nom|Number=Sing	8	appos	_	SpaceAfter=No
11	"	"	PUNCT	Z	_	10	punct	_	_
12	sisu	sisu	NOUN	S	Case=Nom|Number=Sing	14	nsubj	_	_
13	on	olema	AUX	V	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	14	aux	_	_
14	muutunud	muutuma	VERB	V	Tense=Past|VerbForm=Part|Voice=Act	2	advcl	_	_
15	minu	mina	PRON	P	Case=Gen|Number=Sing|Person=1|PronType=Prs	14	obl	_	_
16	jaoks	jaoks	ADP	K	AdpType=Post	15	case	_	_
17	väga	väga	ADV	D	_	18	advmod	_	_
18	segaseks	segane	ADJ	A	Case=Tra|Degree=Pos|Number=Sing	14	xcomp	_	SpaceAfter=No
19	.	.	PUNCT	Z	_	2	punct	_	_

```

An English solution
[https://raw.githubusercontent.com/UniversalDependencies/UD_English-EWT/master/en_ewt-ud-test.conllu]
```the word terrorist```

```
# sent_id = weblog-blogspot.com_floppingaces_20050313182621_ENG_20050313_182621-0007
# text = Over three years after 9-11, the United Nations, despite their attempts to project strength in fighting terrorism , still cannot properly define the word "terrorist" , waffling over the issue of whether the murder of innocent civilians are terrorist acts.
...
22	can	can	AUX	MD	VerbForm=Fin	25	aux	25:aux	SpaceAfter=No
23	not	not	PART	RB	_	25	advmod	25:advmod	_
24	properly	properly	ADV	RB	_	25	advmod	25:advmod	_
25	define	define	VERB	VB	VerbForm=Inf	0	root	0:root	_
26	the	the	DET	DT	Definite=Def|PronType=Art	27	det	27:det	_
27	word	word	NOUN	NN	Number=Sing	25	obj	25:obj	_
28	"	"	PUNCT	``	_	29	punct	29:punct	SpaceAfter=No
29	terrorist	terrorist	NOUN	NN	Number=Sing	27	appos	27:appos	SpaceAfter=No
30	"	"	PUNCT	''	_	29	punct	29:punct	_
31	,	,	PUNCT	,	_	25	punct	25:punct	_
...
```

The Swedish Talbanken solution is nmod

```ordet schizofreni```
[https://raw.githubusercontent.com/UniversalDependencies/UD_Swedish-Talbanken/master/sv_talbanken-ud-test.conllu]
```
# newpar id = P301.13
# sent_id = sv-ud-test-672
# text = Ordet schizofreni betyder ungefär kluven själ.
1	Ordet	ord	NOUN	NN|NEU|SIN|DEF|NOM	Case=Nom|Definite=Def|Gender=Neut|Number=Sing	2	nmod	2:nmod	_
2	schizofreni	schizofreni	NOUN	NN|UTR|SIN|IND|NOM	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	3	nsubj	3:nsubj	_
3	betyder	betyda	VERB	VB|PRS|AKT	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	0	root	0:root	_
4	ungefär	ungefär	ADV	AB	_	3	advmod	3:advmod	_
5	kluven	klyva	ADJ	PC|PRF|UTR|SIN|IND|NOM	Case=Nom|Definite=Ind|Gender=Com|Number=Sing|Tense=Past|VerbForm=Part	6	amod	6:amod	_
6	själ	själ	NOUN	NN|UTR|SIN|IND|NOM	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	3	obj	3:obj	SpaceAfter=No
7	.	.	PUNCT	MAD	_	3	punct	3:punct	_

```

In Erzya the convention is much the same as what is familiar from Finnish, where "-sana" 'the word' is post-posed. In Erzya, however, the orthographic convention is to write the words separately, and therefore there needs to be some sort of dependency.

I see that this is related to previous discussions of matters addressing: ```the number _five_```, ```the letter _A_```, ```the word _bluish_```, ```the word _does_```

The quoted item might be seen as a fuzzy symbol we have to classify. Calling our fuzzy symbol by class or category is familiar when dealing with word written in unfamiliar orthographies. We might even refer to them in UPOS as SYM, but there still seems to be inconsistency in connecting SYM to classifier in our documentation of various languages in the UD project.

The _appos_ dependency cannot be used for Erzya, because left appos is invalid.

Any solutions? Thoughts and analogies, of course, are always welcome.

**Comment by jnivre** [comment]
The appos relation has turned out to be problematic in a number of ways. My own view (nowadays) is that appos is a subtype of nmod although it is not treated as such in the UD taxonomy. However, in the examples discussed, the main point of disagreement seems to be whether "word" or "terrorist" is the head of the phrase "the word terrorist". In Talbanken, we treat "terrorist" as the head (mainly by heritage from the original annotation), and therefore "appos" is definitely out because an apposition (given the narrowly defined UD version of this concept) has to follow its head.

**Comment by Stormur** [comment]
The annotation of `nmod`, `appos` and `flat` is very inconsistent throughout the different UD treebanks, to the point that it makes cross-linguistic comparisons, such as e.g. investigation around the 23rd Greenberg's universal, unviable.

Here, given the difficulties in identifying a true head, mentioned by @jnivre , I think that the most appropriate relation would be `flat`, so that we treat in the same fashion _the word terrorist_ = _president Obama_ = _the number five_ and so on. This by the way solves the issue of leftward or rightward dependencies, and perhaps it might be used for Erzya, too.

I am not so sure as to whether `appos` is truly a subtype of `nmod`. I think that the main feature distinguishing the two relations is co-referentiality: `appos` bears it, while `nmod` does not. `Appos` is thus in a sense more similar to an (asyndetic) co-ordinated conjunction. Of course, this should probably be independent from left-right orientation, just as it is discussed for co-ordination.

So: _sõna "kommunist"_ is not a case of `appos` because _sõna_ and _kommunist_ are not co-referential, as it is _kommunist_ that is a _sõna_, but not viceversa; and there is no `nmod` relation, which would imply some sort of subordination like a _sõna_ for/to/with/against... a _kommunist_, and of the kind we see  in _the pronunciation of "does"_.

**Comment by LarsAhrenberg** [comment]
There are actually good arguments to analyse _'ordet'_ as head in a phrase such as Swedish _'ordet terrorist'_ (the word terrorist) or 'the word schizofreni'. Predicative adjectives agree with singular NP:s in grammatical gender. Thus, you would say _'Ordet terrorist är numera vanligt'_, where the neuter gender, the final -t in _vanligt_ is the gender for _Ordet_, while _terrorist_ is non-neuter.

**Comment by amir-zeldes** [comment]
Another substantial difference between appos and nmod in languages that distinguish case is that appos takes the same case as its head, which depends on the role of the whole phrase, whereas non-appositional modifiers typically take an oblique case, which can be distinct from and not determined by the function of the phrase headed by the head nominal.

**Comment by sylvainkahane** [comment]
`appos` covers two different relations, at least in languages such as English. Compare:

```
(1) My sister Mary is coming (I have two sisters and the one who is coming is Mary)
(2) My sister, Mary, is coming (i have one sister and I recall you that she is called Mary)
```
(1) is a particular case of `nmod`, while (2) is a particular case of paradigmatic relation, a double formulation (we propose two denotations of the same referent, _my sister_ and _Mary_). The relations in (1) and (2) should be distinguished. (1) could be annotated `nmod:appos`. I think that _the word terrorist_ or _the number five_ belong to this case.

**Comment by amir-zeldes** [comment]
@sylvainkahane I agree that (1) and (2) above can be distinct and carry different intonation. I'm not sure the distinction is properly semantic though, because I think I can use (2) in a situation where I do have two sisters, but I don't treat the existence of the second sister as relevant (i.e. further siblings not under discussion).

Either way though, I wouldn't say (1) is the same as a regular nmod, for the case reason outlined above: in both cases, the sister and Mary would agree in the case marking languages I now, rather than show case government (which is what nmods usually do). Even in English, the possibility of nominative pronouns is restricted to the apposition construction:

```
My brother Conan (appos1)
My brother, Conan (appos2)
I Conan (appos1)
I, Conan (appos2)
A brother of John's (nmod, with case)
* A brother of I (nmod + non-nom. case not possible)
```

**Comment by arademaker** [comment]
Somehow related to this discussion, what is `full nominal` on the page https://universaldependencies.org/u/dep/appos.html? I didn't find a definition for full nominal nor any explanation of why titles are `less than a full nominal`

**Comment by arademaker** [comment]
Still related to this issue and my last comment. In the same appos page, we read

> appos is intended to be used between two nominals. In general, modulo punctuation, the two halves of an apposition can be switched.

Can we make more precise this test? What changes are admitted during the switch? The English example suggests that the switch can't change anything else in the sentence. But in Portuguese, we have one example such as 

> ... filho dos imigrantes poloneses Julio Zymler e Chaja. (son of the Polish immigrants Julio Zymler and Chaja.)

In Portuguese, we have the contraction `de+os` making the switching impossible without also substituting the contraction `de+os` to only `de`:

> filho de Julio Zymler e Chaja, imigrantes poloneses. 

So the question is if this case pass on the test of `appos` or not!

**Comment by amir-zeldes** [comment]
I think 'fusion' should not count as a criterion preventing the substitutability. The fact that we 'sub-tokenize' "dos" into "de+os" means that as far as we are concerned, those are separate syntactic units. The reordering works with those units separated, and the way I see it, the fusion is just an automatic realization of 'de' next to 'os' in this case.

**Comment by dan-zeman** [comment]
[A related page that arose after the discussion in another issue thread.](https://universaldependencies.org/workgroups/newdoc/two_nominals.html)
