### ISSUE TITLE
PT doc update

### ISSUE THREAD

**Issue by alvelvis** [UniversalDependencies/docs#694]
Hi, my team has been working within UD and would like to update the Portuguese specific documentation according to UD v2 guidelines. How has the workflow been? Once you accept a pull requests it is already live in the website?

Thank you

**Comment by arademaker** [comment]
@alvelvis , @dan-zeman can help on the details, but we need first to agree on the instructions since they will be, after published, considered the Portuguese guidelines used in the Portuguese treebanks. 

As far as I know, the files on `_u-dep` are the ones that automatically update the website. What we need to understand is how the files under `_pt` are used. Are they the Portuguese specific documentation or the expected translation of the general UD instructions?

**Comment by alvelvis** [comment]
Sure, @arademaker. Thanks.

**Comment by dan-zeman** [comment]
See [https://universaldependencies.org/release_checklist.html#language-specific-guidelines](https://universaldependencies.org/release_checklist.html#language-specific-guidelines) and [https://universaldependencies.org/contributing_language_specific.html](https://universaldependencies.org/contributing_language_specific.html).

In short: there should be a one-file summary of Portuguese in UD, and this is the most needed part. There can be more files (as it is now for some languages), mirroring the universal instructions for individual labels and providing Portuguese examples, but these are optional. If they exist, you can provide links to them from the summary page. There is a template for the Portuguese summary page [here](https://github.com/UniversalDependencies/docs/blob/pages-source/_pt/template-index.md). When its contents is ready, rename it to `index.md` (or ask me to do so).

**Comment by arademaker** [comment]
See https://github.com/UniversalDependencies/docs/issues/696#issuecomment-608035208

**Comment by dan-zeman** [comment]
There is now a [Portuguese documentation page](https://universaldependencies.org/pt/index.html). It is incomplete, but the question how to create it has been answered, so I am closing this issue now.
