### ISSUE TITLE
Plural marker as DET? What feature values to assign?

### ISSUE THREAD

**Issue by AngelAquino** [UniversalDependencies/docs#711]
Languages such as Tagalog and Vietnamese can code plurality with an independent word instead of an affix:
[tl/vi/en] 
_baka_ / _con bò_ / cow
_**mga** baka_ / _**các/những** con bò_ / cow**s**

Upon inspection of [WALS](https://wals.info/feature/33A#2/26.1/152.8), it seems that no other languages currently in UD use words to code plurality.

Would it be correct to tag these words as `DET` (as is currently the case in UD_Vietnamese-VTB and UD_Tagalog-Ugnayan)? And if so, what feature values would they take? None of the values in `PronType` or `NumType` seem appropriate, while `Number=Plur` is used to denote inflection in nominals, not an indicator of a word actually being a plural morpheme.

**Comment by sylvainkahane** [comment]
Naija, the Nigerian creole of English, use _dem_ (a form of the pronoun _them_) as a plural marker: [examples](http://match.grew.fr/?corpus=UD_Naija-NSC@2.6&custom=5ece8624c672f). We didn't tag _dem_ as DET because it is postnominal and `det` are prenominal in Naija, as in English.

**Comment by AngelAquino** [comment]
I agree with the use of `PART` for _dem_ in the Naija examples, but it seems as if the nouns modified by _dem_ already have plurality encoded in them.

For Tagalog, the lexical item for the noun remains the same regardless of number, and plurality is encoded in the plural morpheme _mga_ as an independent word (unless a `nummod` is attached to the noun, in which case _mga_ is not used). For example:
[tl/en] _bibe_/duck; _mga bibe_/ducks; _dalawang bibe_/two ducks

**Comment by Stormur** [comment]
Does it not look exactly like a `PART`? As for its features, it could probably stay without, but "give" the plurality to the noun it is attached to. In the corpus, this would mean that all nouns with `Number=Plur` are accompanied by this element.

Does _mga_ occur in any other construction?

**Comment by AngelAquino** [comment]
I would have thought to label _mga_ as a `PART` too, were it not for the Vietnamese-VTB precedent for _các_ and _những_ (as described in [this](https://vn-translate.livejournal.com/15023.html) forum post; unfortunately, I don't have a Vietnamese reference grammar on hand), as well as the definition of `DET` including pronominal quantifiers.

When other quantifiers are present, the word _mga_ is typically dropped, but it always precedes a plural noun if there are no other quantifiers:
[tl/en]
_oras_ / hour
_mga oras_ / hours
_ilang oras_ / a few hours
_maraming oras_ / many hours
_sampung oras_ / ten hours

One thing which does distinguishes _mga_ from the other quantifiers is that it isn't accompanied by the linker suffix _-ng_ which marks the word to which it is attached as a modifier of the succeeding noun. In this case, _ilan_ "few", _marami_ "many", and _sampu_ "ten" can all stand independently, while _mga_ only occurs as a pluralizer.

**Comment by sylvainkahane** [comment]
If _mga_ and other DETs are mutually exclusive, then _mga_ is a DET.

In Naija, _dem_ is not a DET because it can co-occur with a DET.

**Comment by dan-zeman** [comment]
I think that [DET](https://universaldependencies.org/u/pos/DET.html) is appropriate in its wider UD sense as a word that lends additional features to a nominal. Regardless of whether or not it is mutually exclusive with other determiners, this is not a requirement in UD.

[Number](https://universaldependencies.org/u/feat/Number.html)=`Plur` seems also quite appropriate, although we should extend the documentation to explicitly state this. Note that this is analogous to `Definite=Def`: in English, it is used with the determiner _the_ which contributes the feature to its nominal; but in Swedish, it is used with the head noun which becomes definite through inflection.

BTW, in UD we also have this in Yoruba where the pluralizer _àwọn_ is attached as [det](https://universaldependencies.org/u/dep/det.html). And according to WALS, Guaraní also employs plural words, but I cannot comment on that.

**Comment by Stormur** [comment]
In the light of this discussion, @dan-zeman , I have a question regarding Latin.

There, some pronouns accept a clitical particle _met_ which is attached to the inflected form:

_nobis_ 'to us' -> _nobismet_ 'to us (emphatic)'

It can also combine with the determiner _ipse_ '~ self': _nosmetipsi_, _nobismetipsis_ 'we/to us ourselves (emphatic)' .

So, would you rate this element _met_, which really has no other function, is only clitic, bears no inflection at all (contrary to _ipse_ and actually nearly everything else in Latin) and whose sole function is to give emphasis, as `DET` rather than a `PART` (as we are doing at the moment)? Anyway, I think that it would be sensible to assign it something like `PronType=Emp`, as for _ipse_, and in the same vein as _mga_ could have `Number=Plur`. But would this make it a determiner?

**Comment by dan-zeman** [comment]
@Stormur : I think I'd be inclined to tag _met_ `PART`, possibly with `PartType=Emp` (this feature is already used in Erzya, though undocumented @rueter ). But it is difficult to base it on criteria more exact than feelings :-) Perhaps plural is more important and expected in a nominal than emphasis (although this may be European bias). Also, from what you say it looks like _met_ is used only with certain pronouns and not with nouns. Another question is what relation you use to attach _met_ to the emphasized pronoun. I think I would use `advmod:emph`.

**Comment by Stormur** [comment]
The relation is unmistakeably `advmod:emph`, this is certain! :-) 

(I wasn't aware of `PartType`, but this brings me to a collateral issue: could `PronType` & company be renamed to just `Type`, or in any other neutral way? In the specific case of _met_ and _ipse_, they may be `DET`, `PART` or something else, but still they share the feature `Emp` independently from that. The name `PronType` also becomes confusing when it can be assigned to non-pronouns...) 

With regard to _-met_ and _mga_, if the former is deemed to be a particle, I would be then inclined to consider the latter actually more entitled to be one... I would get this basically from the following passages in the guide lines: 

* `DET`: express the reference of the noun phrase in context
* `PART`: function words that must be associated with another word or phrase to impart meaning

One might argue that definitess (as for _the_ in English or _-en/-et_ in Swedish) indeed expresses a reference, while number does not. Further, this:

> One thing which does distinguishes mga from the other quantifiers is that it isn't accompanied by the linker suffix -ng which marks the word to which it is attached as a modifier of the succeeding noun.

So it seems to act in quite a different way than other determiners, more as if it were just a "morphological marker".

All in all, I am quite confused as to where to draw a line between `PART` and `DET` in cases like this. Could it make sense to claim that in UD we require an element to have at least one feature from among the current `PronType`s, `Poss`, `Definite` (the latter with an in-between lexical/inflectional status) to be considered `DET`? With this definition, probably Latin _-met_ would be `DET`, as it bears `PronType=Emp` (maybe correcting the _European bias_ you mentioned) and _mga_ `PART`.

**Comment by dan-zeman** [comment]
> could PronType & company be renamed to just Type, or in any other neutral way?

No. Definitely not while UD v2 guidelines are in effect. And even if a new version of the guidelines is discussed, I would argue that `PronType` and `NumType` may occur together at one word, specifying its type along two different axes (similarly you could have `AdvType` orthogonal, but that one is not defined at the universal level). Rather than "type of pronoun", I prefer to read `PronType` as pronominal type, which also applies to pronominal adverbs, and to DET, which I read as "adjectivally behaving pronominal words".

> All in all, I am quite confused as to where to draw a line between PART and DET in cases like this.

The definitions in the documentation were written in times when UD covered much fewer languages and the Indo-European bias was much stronger, so the documentation may need better specification (at least once discussions like this one reach something resembling a concensus). For example, Tagalog also has very frequent noun phrase markers like _ang_ and _ng_, which you may think of as prepositions (even though they mark core arguments), but other authors actually call them determiners. These markers seem to conflate various things such as topic-focus, definiteness and case, so they are not very close to Indo-European determiners, but given the repertory we have in UD, `DET` seems plausible to me. And if these are `DET`, then I don't see a problem with classifying _mga_ as `DET` as well. (Note: I just checked the two Tagalog treebanks we have in UD 2.6. The older one, TRG, sides with the authors who categorize _ang_ as determiner, while the new one, Ugnayan, tags _ang_ as adposition.)

**Comment by dan-zeman** [comment]
> Could it make sense to claim that in UD we require an element to have at least one feature from among the current PronTypes, Poss, Definite (the latter with an in-between lexical/inflectional status) to be considered DET?

In fact I think that if the treebank has features (which are optional in UD), then each `PRON` and `DET` must have a non-empty `PronType`, and some `ADV` may have a non-empty `PronType`. It is probably not stated that strictly in the guidelines, but it seems logical because `PronType` is supposed to be a finer-grained partitioning of the POS space. It is not tested by the current validator and I am confident that there are many treebanks that leave some pronouns and/or determiners without this feature. It used to be part of the [optional content validation](https://universaldependencies.org/svalidation.html#pron-or-det-lacks-the-prontype-feature) (now discontinued). As for `Poss` and `Definite`, these features can accompany `PronType` but they don't replace it.

**Comment by Stormur** [comment]
> No. Definitely not while UD v2 guidelines are in effect. And even if a new version of the guidelines is discussed, I would argue that `PronType` and `NumType` may occur together at one word

I forgot about NumType, but I wasn't thinking of "neutralising" it too. I understand the issue.

> The definitions in the documentation were written in times when UD covered much fewer languages and the Indo-European bias was much stronger, so the documentation may need better specification

One thing that maybe needs to be clarified, from my point of view, is when exactly we have a _pronominal adverb_ that can receive `PronType` as opposed to `AdvType`. 

Just my two cents: probably particles would deserve `PartType` to be more visible; this maybe could help clarify the distinction between the roles of the two classes (I was thinking of the Latin interrogative clitic _-ne_, which I would be tempted to assign an `Int` value, or the other discussion about the Chukchi emphatic particle).

----

Trying to summarize the points of this discussion and to see if a consensus can be reached about these points:
* _mga_: as it _determines_ the feature of a nominal, in particular it makes it plural in a language which otherwise has little nominal inflection (from what I have understood), it may well be treated as a `DET` bearing `Number=Plur`. Now, as we have to choose a `PronType` for it, we could probably pick `Art`; this would be by the way totally comparable to the English article which exclusively bears definiteness (in contrast e.g. to the Italian one which also has number and gender, and so on).
* _-met_: as it is uninflected in a language which basically inflects everything for overlapping categories, as it appears to be only clitic (and actually it seems often to be perceived as part of the word it attaches to, and it occurs before any other clitics) and restricted to a particular subset of words (so it has no wider applicability as _ipse_ or _mga_), as it does not truly express a contextual reference of that word but just gives a small emphasis, it seems appropriate to treat it as a `PART` with feature `PartType=Emp` to distinguish it from other clitics (like interrogative _-ne_).

**Comment by dan-zeman** [comment]
> One thing that maybe needs to be clarified, from my point of view, is when exactly we have a pronominal adverb that can receive PronType as opposed to AdvType.

The most clearly defined category seems to be interrogative/relative adverbs such as English _where, when, how, why_ (in languages other than English, relative adverbs may be different from interrogatives). Then we can define corresponding sets with various answers to the interrogatives – _somewhere, sometimes, somehow_ (indefinite); _here, there, now, then, so_ (demonstrative); _everywhere, always_ (total); _nowhere, never_ (negative). If you see a parallel to a category of pronouns (especially if the words use similar prefixes etc.), you add the same `PronType` to the adverb. There will inevitably be some border cases, but I believe the core words will repeat across many languages. [AdvType](https://universaldependencies.org/u/feat/AdvType.html) is more a semantic category. For example, from the above words, `AdvType=Loc` would cover _where, somewhere, here, there, everywhere, nowhere._

**Comment by ftyers** [comment]
@dan-zeman Guarani has a plural suffix/word *kuéra* (or *nguéra*) that can be written either apart from the word or joined to it. 

There are two words in K'iche', *taq* and *e* which mark plurality in nouns. They can appear with or without plural suffixes on nouns (which are only grammatical for a reduced set of lexemes).
