### ISSUE TITLE
Passive Voice: the case of Latin deponent verbs

### ISSUE THREAD

**Issue by Stormur** [UniversalDependencies/docs#713]
As of lately, I was wondering if I have been doing right something which I thought to be trivial and to which I did not pay so much attention, namely the annotation of the `Voice` feature. I would summarize the question as: is this feature understood as really _morphological_ or rather _syntactical_?

Latin presents the following. There are two series of suffixes for the finite conjugation of verbs, one usually labeled the **active conjugation** and the other the (medio)**passive conjugation**. An example with _amo_ '[to] love':
* active: amo, amas, amat, amamus, amatis, amant; amabam, amabas...
* passive: amor, amaris, amatur, amamur, amamini, amantur; amabar, amabaris...

One translates _amat_ as '(he/she/it) loves' and _amatur_ as '(he/she/it) is loved': the first one would easily receive `Voice=Act`, while the second as easily `Voice=Pass`.

Now, there are so-called **deponent** verbs (i.e., which have "deposed" their active forms) which are said to "use only the passive conjugation, but to have active meaning". Some of them can be transitive. For example: 
* Canis sequi**tur** cattum 'the dog follows the cat' (`obj` relation)
* Re**or** canem celerem esse 'I am of the meaning that the dog is fast' (`ccomp` relation)

Such sentences allow no passive construction, since _morphologically_ they are already "passive". Further, perfective tenses use a periphrastic construction parallel to a "normal passive":
* _Canis secu**tus est** cattum_ 'The dog has chased the cat'
* _Ra**tus sum** canem celerem esse_ 'I have been of the meaning...'
* Non deponent, regular  "passive": _Puer amatus est (a puella)_ 'The boy has been loved (by the girl)', from active _Puella amavit puerum_

The relation `aux:pass` should be used for "Auxiliares used to construct the passive voice", but the first cases are "passive" only in a morphological, not in a syntactic sense: they are transitive clauses! So, if one should just use `aux` here, should one also use `Voice=Act` for the verbs? Further, there are some verbal nominal forms which are inherently always active, also for deponent verbs, such as the present participle:
* _sequens_ 'following'
* _rens_ 'being of the meaning' (admittedly very rare, but possible)
* _amans_ 'loving'

There exists no passive present participle in Latin. 

Last but not least, just another case of "morphological but not syntactical" passive: the impersonal construction.
* _Romam eo/is/it/..._ 'I/you/he/she/it/... go(es) to Rome'  -> _Romam itur_ 'It is gone to Rome', in the sense that there is a non-specified person performing this action
    * _Romam eundum est_ '"It has to be gone" to Rome' -> 'There is the necessity to go to Rome'

Notice that _Romam_ is left untouched by this transformation, which can be done for any _intransitive_ verb.

---

To sum it up: should one verb and/or one deprel be labeled as passive (`Voice=Pass` / `:pass`) 
1. **pure morphological criterion:** just because a given construction has a morphology which is _usually associated_ to the passive voice (in Latin, this is applicable only to active, transitive verbs), even if some verb uses it in active constructions;
2. **syntactic criterion:** assign passivity based on the syntactic construction/behavior of the verb (but then, the label _morphological feature_ is somewhat misleading)?

Outline of a proposal: should we decouple a truly morphological feature of "conjugation class" from the now existing `Voice`? This could mean that, in latin, we might have the following combinations: 
* `ConjClass=Act|Voice=Act`: _amat_; _amans_, _sequens_
* `ConjClass=Pass|Voice=Pass`: _amatur_; _amatus_ 
* `ConjClass=Pass|Voice=Act`: _sequitur_; _secutus_
* `ConjClass=Act|Voice=Pass`: _fio_ 'to become, to be done' (I had previously forgotten this _unicum_)

**Comment by sylvainkahane** [comment]
Thanks @Stormur for this very clear presentation of these interesting data.

The annotation has several goals. Of course it must be theoretically acceptable, but it must also allow you and others to easily find that something special arise here. And for computational linguist the annotation must be as coherent as possible. I add this last point because I suppose that a parser discovering a deponent construction for the first time should analyse it as a passive with a direct object.

As you showed us, the deponent has a passive construction at the surface and I think I would like to annotate it as a passive form with `Voice=Pass` and `aux:pass`. And I will add another feature on the verb indicating that it is a deponent verb, that is a verb that has no active form and a transitive passive construction. This feature could be only in the lexicon but it is ok of it is also in the treebank. It would help to find these construction in the treebank.

- `Voice=Act`: _amat; amans, sequens_
- `Voice=Pass`: _amatur; amatus_
- `Voice=Pass`, `VerbType=Deponent`; _sequitur; secutus_

**Comment by dan-zeman** [comment]
Like @sylvainkahane, I think I prefer to use `Voice=Pass` with deponent verbs, since their morphological form is passive. Possibly with a language-specific feature `VerbType=Deponent` to make the identification of these verbs easier.

The relation `aux:pass` attaches a function word, which, from the UD perspective, is a process parallel to (or accompanying) morphology, so it makes sense to use it here too.

I am less sure about the relation `nsubj:pass` which is normally used for subjects of passive verbs. The motivation of this relation subtype is to signal downstream applications that there is something non-standard about the mapping between grammatical functions and semantic roles, namely that the subject is not the most active participant. However, that is not the case in the examples given by @Stormur for Latin deponent verbs. Also, there would be no `obl:agent`, and in the transitive examples, there would be a direct object and we hardly would want to mark it `obj:pass`. So the core arguments of deponent verbs should probably be attached using the normal relations `nsubj` and `obj`, without subtypes.

In any case this is an interesting and important issue and we should probably document it in the universal guidelines (after all, there are other languages that have deponent verbs). There are some important implications for interpretation of the annotation. So far I have assumed that it would be an error to have `Voice=Pass` or `aux:pass` in a clause and not to mark the subject of that clause as `nsubj:pass` (it is a "weak error", since relation subtypes are optional, but still). Sometimes it is even impossible to identify a passive clause by `nsubj:pass` if the subject pronoun is dropped, but `aux:pass` still signals that the subject, if present, would be `nsubj:pass`. Now, with deponent verbs, this does not hold any more.

**Comment by Stormur** [comment]
Thanks! I think in the end I also prefer a "purely morphological" approach for `Voice` and a syntactical one for `:pass` as you suggested me, and probably most of the time the transitivity of the clause would indeed be signalled by some given dependency relations, but the particular case highlighted by @dan-zeman is an issue. All considered, the mark `VerbType=Deponent` might be needed, and we will investigate about its addition, suspending it for the moment. 

As for the issue of determining what is an _active_ conjugation and what a _passive_ one, correct me if I am rambling, but could this be traced back to the _syntax of primary transitive_ verbs, as it is the case for core arguments? This means that, if _occido_ '[to] kill' is one, and then _ego te occido_ 'I kill you' is a transitive clause and _ego (a te) occidor_ 'I am killed (by you)' an intransitive, passive one, then the series _-o, -is, ..._ is labelled active and the series _-or, -ris, ..._ passive?

---

For the sake of completeness, Latin has also an intermediate phenomenon: **semideponent** verbs! They come in two flavours:
* _fido_ '[to] trust': present _fido_ (`Voice=Act`), perfect _fisus sum_ (`Pass`), infinitive _fidere_ (`Act`)
* _revertor_ '[to] go back': present _revertor_ (`Pass`), perfect _reverti_ (`Act`), infinitive _reverti_ (`Pass`) 

They can be transitive or intransitive. So, for such verbs we would have some tenses marked with `VerbForm=Deponent` and some others not, in accordance to their mixed nature.

Another controversial case are **gerundive** forms. They are used in some very peculiar constructions which are embedded clauses, and it has been argued for their being active, passive, or not having any voice at all (I think they would deserve a separate issue). With what has been said here in mind, I think it is reasonable to treat them as morphologically **passive** (as this appears to be their basic, regular syntactic behaviour), and let any deviance in usage come through by means of appropriate non-passive deprels (this would boil down to `obj`), but still, they would not be `VerbType=Deponent`s.

**Comment by Stormur** [comment]
Just an addendum: Latin indeed has a verb which, albeit morphologically _active_, can have passive syntax. It is the case of _fio_ 'to be done; to become' (added in the first post).

**Comment by dan-zeman** [comment]
Sorry, I'm not sure where you are headed with the reference to the primary transitives. Transitive vs. intransitive is a different dichotomy than active vs. passive, although they are related and the prototypical Indo-European passivization will convert a transitive verb into intransitive (but there are also intransitive verbs that are not in the passive form).

Gerundives can be recognized by the `VerbForm` feature and you could also consider saying that certain verb forms do not distinguish voice (the `Voice` feature would not be present). On the other hand, `VerbForm=Deponent` would probably clash with the universally defined verb forms, as the form would still need `VerbForm=Fin` or `Part` etc.

What does it mean if you say that _fio_ has "passive syntax"? I can imagine there is something passive-like in the syntax-semantics interface, i.e., the subject is a patient rather than actor, but such verbs could probably be found in various languages and their syntax might still be that of intransitive verbs, no?

**Comment by Stormur** [comment]
> Sorry, I'm not sure where you are headed with the reference to the primary transitives. Transitive vs. intransitive is a different dichotomy than active vs. passive, although they are related and the prototypical Indo-European passivization will convert a transitive verb into intransitive (but there are also intransitive verbs that are not in the passive form).
> 

Yes, my bad, it was just a vague thought. I intended to express a (probably obvious) criterion by which I am entitled to assign the feature of _active voice_ to a given set of verbal affixes and of _passive voice_ to another one, rather than using different or variable labels, exactly because of the fact that the dichotomy is different (as shown here with the example of deponent verbs). Therefore I referred to primary transitives, since for (at least) this class of verbs the relation active voice - active conjugation and  passive voice - passive conjugation holds. It is probably just a formal issue.

> Gerundives can be recognized by the `VerbForm` feature and you could also consider saying that certain verb forms do not distinguish voice (the `Voice` feature would not be present). On the other hand, `VerbForm=Deponent` would probably clash with the universally defined verb forms, as the form would still need `VerbForm=Fin` or `Part` etc.
> 

After this discussion I am oriented towards not using a specific label for deponent verbs (the suggestion was `VerbType`), because it seems to be a characteristic that arises from the combination of Voice and the deprels, and when it does not, the configuration is indistinguishable from that of other non-deponent verbs...
In the same vein as the `Voice` feature refers to the morphology and not to the transitivity of a clause, I think there are many reasons to argue that the gerundivum/gerundium is indeed still _morphologically_ passive, and that its possible active use or reanalysis can be detected from its accompanying deprels. I am hesitant not to assign a `Voice` when it is otherwise always present in Latin... 

> What does it mean if you say that _fio_ has "passive syntax"? I can imagine there is something passive-like in the syntax-semantics interface, i.e., the subject is a patient rather than actor, but such verbs could probably be found in various languages and their syntax might still be that of intransitive verbs, no?
>

You may be right, and I am still not so conclusive about it. I'll try to explain  what I mean: the fact is that, traditionally, _fio_ 'to become; to be done' 'is assimilated in the passive conjugation of _facio_ 'to do', and its perfect forms are supplied by those of facio, so, for example, we have _factus sum_ 'I have been done' instead of an unattested *_fivi_, or something along those lines (although, viceversa, you might still say _facitur_ instead of _fit_). But from a morphological point of view, it is a perfectly fine active verb and, moreover, its meaning 'to become' perfectly fits the behaviour of other active verbs. So yes, we could see the traditional passive voice of _fio_ mostly as a "translation bias". But still, sometimes there is e.g. an agent that normally only appears for passive constructions: _quae fiunt ab ipsis_ 'what is done by them' (Vulgate). And by now, it is hard to assess how much _fio_ was truly seen as the passive counterpart of _facio_ in the conscience of native speakers, and how much of it is a formal systematization of grammarians. In any case yes, apart from some "syntactical passive elements", most of the time it is true that syntactically and morphologically a _fio_ clause is not distinguishable from that of any other intransitive active verb.
