### ISSUE TITLE
Substantive Adjectives and Participles

### ISSUE THREAD

**Issue by jamalainm** [UniversalDependencies/docs#715]
Hi all!

Apologies if this has been addressed using different terminology, I'm still getting the hang of the vernacular for UD.

I'm marking up Terence's Andria (a Latin comedy), and I'm wondering what guidelines I should follow for words that have a sort of fluid assignment.

The phrase that brought me here is "quo pacto" (in what way / by what agreement)

"pacto" is an oblique form of a participle used as a noun.

This is a fairly common phrase, more or less meaning "how?"

Latin also very regularly employs other participles and adjectives as nouns (called "substantives" in the field)

Are there guidelines within UD for labeling the UPOS in these cases?

**Comment by Stormur** [comment]
Hi! This is a much debated issue. It has been last discussed in #620 . 

In the specific case of _quo pacto_, it might be treated in the same way as an ablativus absolutus, i.e. by means of `advcl`, in which _quo_ (probably from _quis_) is the (passive) subject of _pango_, literally: 'having agreed about what / having fixed what' (in the Andria I found an _eo pacto_, which looks more "standard" for an abl. abs.). Another, maybe less complicated, way is simply to acknowledge that _pactum_ is a noun in itself (as reported by many dictionaries), so that you simply have the `obl` _quo pacto_ from _quod pactum_. The context might be decisive!

Anyway, this seems to be an open issue in UD, but it is true that verbs and nouns often still show distinguishable patterns, at least in Latin, even if there are truly difficult cases.

PS: Since I am part of a group that works (also) on Latin syntax, feel free to contact me if you want to discuss about annotation for Latin! :smile:

**Comment by jamalainm** [comment]
Oops! You're right, it was "eo pacto."

Thanks also for pointing me to the debate and offering to advise! I have lots of questions, but I'll try not to make you regret the offer ;)
