### ISSUE TITLE
Partly foreign words

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/docs#719]
I see in the specification for the feature `Foreign` that there used to be values other than `Yes`. I'm running into this situation now since we have complete annotations for foreign word status for UD_Coptic, but quite a lot of the words are only 'partly' foreign. Compare:

monaxos 'monk' (from Greek)
mntmonaxos 'monk-hood' (monk from Greek, '-hood' using a Coptic derivational affix 'mnt-')

We have information in the original annotations to distinguish the two, and there are currently 86 cases of such 'partially foreign' words in the TB. Could we use something like `Foreign=Partial` or maybe `Derived`?

**Comment by bulbulistan** [comment]
But if the word can take native affixes (whether derivational or inflectional), doesn't it ipso facto become nativized and there is no more need for the `Foreign` label? In Maltese, we have tons of this stuff, from  _timijiet_ 'team-PL' through _ċċekkjatur_ 'checker' to _il-bottom line hi..._ 'DEF bottom line is...'. The decision tree I use is that if the foreign word takes native affixes, it is no longer foreign, UNLESS it is a part a syntactically analyzable foreign unit. So in this case, only the third example would get the `Foreign` label.

**Comment by dan-zeman** [comment]
It is generally possible to define a language-specific extra value of an otherwise universally defined feature. As always, the extra values should be documented in the language-specific documentation. The unusual thing here would be that the universal version of the feature is boolean, having either the `Yes` value or being omitted. When a feature may have the `Yes` value, it is generally not expected that other values are possible but I don't think it's forbidden. The alternative is to define a separate language-specific feature for the "partiality", and keeping `Foreign` as it is.

The three values in language-specific predecessors of the v2 [Foreign](https://universaldependencies.org/u/feat/Foreign.html) feature distinguished foreign words in a foreign script, foreign words in the same script as the one of the host language, and foreign words transcribed from a foreign script.

I'm also not sure whether _monaxos_ is really alien in Coptic text in the sense of the [specification of Foreign](https://universaldependencies.org/u/feat/Foreign.html), or it is just a loanword (which is not tagged with `Foreign=Yes` in UD). If it serves as a base for Coptic derivations, then I'm inclined to view it as a loanword.

**Comment by Stormur** [comment]
I am in line with the others.

If I can just add something that may be connected, in Latin we sometimes encounter a Latinised Greek word that uses Greek declination instead of Latin one, e.g. _metamorphoseos_, genitive plural of _metamorphosis_, instead of a possible _metamorphos(i)um_. In that case we do not use `Foreign`, but consider to use a feature like `Variant=Greek` to signal this "systematic morphological exception".

**Comment by amir-zeldes** [comment]
Thanks everyone - yes, words like 'monaxos' are generally loanwords, so it sounds like `Foreign` is not intended for these cases. We do occasionally have genuine Greek with Greek syntax interpolated into a sentence (basically code-switching), so maybe I'll just use Foreign for those (they can be identified by an xpos tag, `FM` for Foreign Material). If anyone has a suggestion for a different existing feature name that could be used to designate these loanwords, please let me know, since I'd like to represent as much information as possible from the underlying corpus in the conllu format as well.
