### ISSUE TITLE
Null surface forms of attitude verbs in Laz

### ISSUE THREAD

**Issue by utkuturk** [UniversalDependencies/docs#734]
In the annotation process of Laz, we have encountered a set of sentences which puzzled us. These sentences have zero forms as their verbs. They are mostly attitude or report verbs. 

```
Tanura-k    Şana      noseri   on     ya
Tanura-Erg  Şana.Nom  smart    be.Prs Comp
"Tanura thinks that Şana is smart"
```
When we talked with the native speakers of Laz, they reported that this structure rarely means "Tanura says". Instead it means As for Tanura, Tanura believes, Tanura thinks. So, what we did is we annotated is as the following:

```
noseri > 0 > root
on > 3 > cop
ya > 3 > mark
Şana > 3 nsubj
Tanurak > 3 > obl
```

The problem is in certain context, this structure with "ya" definitely means "say".  And the sentence may have adverbs that modify the verb "say". The following sentence may not mean "Arte thinks that he swam silently yesterday".

```
Arte-k    ğoma      uneneli  uneneli  vinçirare   ya.
Arte-Erg  yesterday silent   silent   I.will.swim Comp
"Yesterday, Arte silently said that he would swim."
```

I am pretty much stuck and do not where to go from here. should I just put an empty node for the report verbs or should these adverbs modify the proposed obl Arte-k?

**Comment by Stormur** [comment]
Do you think it cannot be treated as a regular ellipsis? This would mean to use some `orphan` relations here and there, e.g. between _Artek_ and the adverb. And just a question: why are you tagging the ergatives as `obl`s? Shouldn't they be `nsubj`s?

**Comment by ftyers** [comment]
So the problem is that in UD this *ya* should be attached to *vinçirare* as `mark` and then our choice of the `root` is problematic. 

I think one approach would be to make *ya* the `root` and then make *vinçirare* `ccomp`:

```
nsubj(ya, Artek)
advmod(vinçirare, ğoma)
ccomp(ya, vinçirare)
advmod(vinçirare, uneneli)
advmod(vinçirare, uneneli)
root(ya)
```

Then you could certainly restore the predicate in the enhanced representation:

```
nsubj(*THINK*, Artek)
advmod(vinçirare, ğoma)
ccomp(*THINK*, vinçirare)
advmod(vinçirare, uneneli)
advmod(vinçirare, uneneli)
mark(vinçirare, ya)
root(*THINK*)
```
![Captura de 2020-10-06 15-32-08](https://user-images.githubusercontent.com/449545/95215759-3c936880-07e9-11eb-99b3-1f83e106a0e5.png)

But also, looking at it, is there a reason to assume that *Artek* is not the subject of the embedded clause? Would that change the meaning?

However, if as you said, the sentence means "Yesterday, Arte silently said that he would swim.", then you could do something like:

```
root(ya)
nsubj(ya, Artek)
advmod(ya, uneneli)
advmod(ya, uneneli)
ccomp(ya, vinçirare)
advmod(ya, ğoma)
```
![Captura de 2020-10-06 15-27-40](https://user-images.githubusercontent.com/449545/95215155-93e50900-07e8-11eb-8e46-7e4dab47463b.png)

**Comment by utkuturk** [comment]
@Stormur *normally* They are definitely nsubj! However, for the given structure, they act almost as a "As for Tanura". And in a sentence like As for Tanura, Şana is smart, Tanura is not a subject. In Laz, there is no 100% match between the morphological case marking and the syntactic role. Like in Turkish, you can have Nominative subjects, but you can also have nominative arguments of postpositions. 

As for the ellipsis, I thought we must have an already existing verb as in I like tea and you coffee. In Laz examples, there is no instance of any elision.

@ftyers Thank you for the root ya suggestion. However, like I said adverbial modifiers are not modifying the swim. Instead they are modifying the event of saying. So, we can do something like this: 

```
nsubj(ya, Artek)
advmod(ya, ğoma)
ccomp(ya, vinçirare)
advmod(ya, uneneli)
advmod:redup(uneneli, uneneli)
root(ya)
```
And then, I rescue the structure as you and @Stormur suggested with ellipsis and enhanced deps. 

As for your last question, I need to ask my informant. I checked my notes, and I noted it "not a reported speech". But I do not think I did enough tests to be 100% sure. However, Artek as the subject of the embedded clause in the second sentence is definitely one of the readings, if not the only one.

**Comment by ftyers** [comment]
@utkuturk if they are modifying the event of saying then they can be attached to *ya* as the promoted item, as in my second tree/graph. (sorry about the confusion with the examples, this was so interesting I responded before having coffee and only processed half of it and then realised that I missed out the second part) :) I thought I'd leave both examples as a contrast anyway.

In any case I think that the most important thing here is how to do the *ya* part. It seems like it won't be necessary to use `orphan` here because there is a function word that can be promoted.[1](https://universaldependencies.org/u/overview/syntax.html#promotion-by-head-elision)

Incidentally here the ergative is used like *-CA* suffix in Turkish? e.g. *bence* "in my opinion, as for me" ?

**Comment by utkuturk** [comment]
I am glad that it is interesting. Indeed, the ergative here is like _-CA_ in Turkish, but not always.  In those cases, I will promote the _ya_ as you suggest. Thanks a lot!
