### ISSUE TITLE
Causative verbal forms

### ISSUE THREAD

**Issue by jheinecke** [UniversalDependencies/docs#740]
I've been working for a while on Chechen (an ergative language). Chechen has conjugated causative forms for verbs:
e.g. охьадожо "to drop [something]" --> охьадожадайта "make [somebody] drop [something].
The enforcer (Causer) of the action is marked by the Ergative case, the Causee in a Locative case, all depend from the verb

```
Ӏумара   Аслане    куьзга     охьадожадайтира.
Omar-ERG Aslan-LOC mirror-ABS make-drop-PAST
"Omar made Aslan drop the mirror"
```

I wonder which dependency relation is appropriate for the causee, Aslan: `obl` does not seem appropriate

```
1	Ӏумара		Ӏумар		PROPN	_	Case=Erg	4	nsubj	_	Gloss=Omar.erg.sg
2	Аслане		Аслан		PROPN	_	Case=All	4	obl	_	Gloss=Islam.all.sg
3	куьзга		куьзга		NOUN	_	Case=Abs|Number=Sing	4	obj	_	Gloss=mirror.abs.sg
4	охьадожадайтира	охьадожо	VERB	_	Tense=Past	0	root	_	Gloss=pverb.fall.caus.rpst
```

Another idea is to use ` obj:agent` for the causee, and keeping `obj` for the object of the caused action

```
1	Ӏумара		Ӏумар		PROPN	_	Case=Erg	4	nsubj	
2	Аслане		Аслан		PROPN	_	Case=All	4	obj:agent	
3	куьзга		куьзга		NOUN	_	Case=Abs|Number=Sing	4	obj
4	охьадожадайтира	охьадожо	VERB	_	Tense=Past	0	root	
```

I couldn't find many examples from other languages (a part from the French _faire faire quelqu'un quelque chose_). What is your opinion?

**Comment by Stormur** [comment]
If it's in the locative, I think _Aslan_ well deserves an `obl` relation... why do you think that it is not appropriate? Of course, if the locative is not used for clear direct objects elsewhere in the language, or if _Aslane_ does not behave as a true secondary object (then `iobj`). What happens with passivization?

You could always specifiy this particular argument with a subrelation like `obl:cau`. At the moment it is registered for Telugu, but there's no documentation.

**Comment by jheinecke** [comment]
The reason why I'd prefer not to use `obl` is that I think this argument (Aslan) is more "core" than not. In French-GSD (even htouhg French uses a _faire_ + infintive for the cuasative) the Causee is annotated as obj:agent (cf: `UD_French-GSD/fr-gsd-train.conllu`, sentence `fr-ud-dev_01246`)
There is passivization (at least not as found in Indo-Eurpoean languages)

**Comment by ftyers** [comment]
This also exists in Turkic, but in Turkic the causee is usually in Dative, see discussion [here](https://universaldependencies.org/u/overview/simple-syntax.html) regarding `iobj:caus` and `obj:caus`. But I think that `obl:caus` would also work fine too.

**Comment by Stormur** [comment]
> The reason why I'd prefer not to use `obl` is that I think this argument (Aslan) is more "core" than not. In French-GSD (even htouhg French uses a _faire_ + infintive for the cuasative) the Causee is annotated as obj:agent (cf: `UD_French-GSD/fr-gsd-train.conllu`, sentence `fr-ud-dev_01246`)
> There is passivization (at least not as found in Indo-Eurpoean languages)

The impression that I get from this example is that this argument is actually ousted from the core, if it ever was there, in virtue of the fact that it is made assume an oblique case different from ergative, absolutive, nominative or accusative. This of course may depend on the base verb.

Honestly, I don't at all agree with the `obj:agent` interpretation you mention, if the situation in French is vaguely reminding of that in Italian (the causative is expressed through the verb _fare_ 'to do/make') : generally speaking, if the base verb is intransitive, than the causee appears as an object (i.e. no preposition), and indeed it can be passivized:
* _cadere_ 'to fall (intr.)': 
    * _cado_ 'he/she/it falls'
    * _faccio cadere Aslan_ 'I make/let Aslan fall'
    * _Aslan viene fatto cadere (da me)_ literally 'Aslan is made fall (by me)'

But with a transitive verb, the causee becomes oblique, the verb keeps its object, and no passivization of the causee is possible:

* _scrivere_ 'to write':
    * _scrivo una lettera_ 'I wrote a letter'
    * _faccio scrivere una lettera **ad** Aslan_ 'I make/let Aslan write a letter', literally 'I make write a letter **to** Aslan'
    * *_Aslan viene fatto scrivere una lettera (da me)_ 'Aslan is made write a letter (by me)' is impossible

Italian does not admit double objects. So, a subrelation like `obj:agent` cannot be generalized to all causative constructions, because indeed, the causee is not always an object. The situation might be analogous in Chechen, and as @ftyers point out, in Turkish too, where the dative is oblique. However, I think that `iobj` is extremely controversial as it is described now and should be really motivated, so if `obl` is possible, it should be favoured.

**Comment by jheinecke** [comment]
I agree, `iobj` is out of question here (by the way Chechen as a dative case, with similar semantics in other languages, so here we could use ` iobj`. I'll go for  `obl`  or `obl:caus` then. Thanks for your input!

**Comment by Stormur** [comment]
Ah, of course there is also the more general and more widespread `obl:arg`, which might be as good as `obl:caus`, if this is deemed to be too specific!

**Comment by dan-zeman** [comment]
+1 for attaching the causee as `obl` if it is in the allative case. BTW if the causative form is analyzed as an inflection of the basic (active) form, as your CoNLL-U excerpt suggest, you should annotate the verb with [Voice=Cau](https://universaldependencies.org/u/feat/Voice.html#Cau).
