### ISSUE TITLE
Person=Auto in Breton

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#746]
I was wondering what `Person=Auto` is supposed to mean? It [occurs 31times](http://hdl.handle.net/11346/PMLTQ-CEGM) with [Breton verbs](https://universaldependencies.org/treebanks/br_keb/br_keb-feat-Person.html) but it is not documented and it does not appear in any other Celtic treebank (or, in fact, in any other treebank).

**Comment by ftyers** [comment]
This is the autonomous/impersonal form. 

> “Another shared trait in the verbs is the presence in the paradigm of the ‘impersonal’ or
‘autonomous’ verb form. Basically, all Celtic languages possess an impersonal form for
each tense which is neutral as to the person and number features of the subject. So Welsh
*dysg* + *ais* ‘I taught’ in fi rst- person singular contrasts with the impersonal form *dysg* + 
*wyd* ‘one taught’. While this form can often be translated as a passive (‘is taught’), the ending also occurs with intransitive verbs, as with Irish *táthar* ‘they/people are’. The impersonal paradigm is an important inherited feature from Indo- European, since it partakes of the *- r ending which also appears in Italic, Tocharian and Hittite. The actual usage of these forms has diverged significantly over time (in Welsh these have become rather literary constructions, but they are everyday forms in Irish), but the presence of a special verbal inflection for an unspecified subject is another particular feature of Celtic.” (Fife, 1993)

It appears in:

* Irish as `Voice=Auto`
* Welsh has `Person=0`
* Manx has no features as of yet.
* ~Scottish Gaelic probably has the same thing, but I haven't found it in the feature set.~
  * As @kscanne mentions below, it is `Person=0` in Scottish Gaelic.

Calling all Celtic UD contributors: @tlynn747 @colinbatchelor @jheinecke @kscanne :) 

I think that there are some similar constructions in Finnish too (see e.g. [description of passive and zeroth person](https://en.wikipedia.org/wiki/Finnish_grammar#Voices)).

---

* Fife, James. 1993. Historical aspects: introduction. *The Celtic Languages*, ed. by Martin J. Ball and James Fife, 3-25. London and New York: Routledge.

**Comment by amir-zeldes** [comment]
Polish also has `Person=0` for a similar purpose, e.g.:

http://match.grew.fr/?corpus=UD_Polish-PDB@2.7&custom=5fda2950b3c04

**Comment by Stormur** [comment]
Question for my understanding: if such impersonal forms coincide with personal endings, as it happens in Latin (with the 3rd person, often passive), shouldn't one just use the same morphological label as for that form? This somehow reminds me of the recent discussion about deponent verbs (#713).

**Comment by kscanne** [comment]
It's `Person=0` in Scottish Gaelic also.  This construction doesn't exist in the Manx corpus; usually some kind of circumlocution is used to convey this meaning.

**Comment by kscanne** [comment]
> Question for my understanding: if such impersonal forms coincide with personal endings, as it happens in Latin (with the 3rd person, often passive), shouldn't one just use the same morphological label as for that form? This somehow reminds me of the recent discussion about deponent verbs (#713).

In Irish at least, the impersonal forms usually do not coincide with any personal form.

**Comment by amir-zeldes** [comment]
> Question for my understanding: if such impersonal forms coincide with personal endings, as it happens in Latin (with the 3rd person, often passive), shouldn't one just use the same morphological label as for that form? This somehow reminds me of the recent discussion about deponent verbs (#713).

In Coptic we have impersonal 'passives' that look exactly like 3rd person plural active, so as you suggest, we tag them like 3rd person plural, even though they can have a by-agent phrase:

  * a-u-hotb-f (ebol hitn-tef-ma'u) "they killed him (by his mother)" (=he was killed by his mother)

If there's no agent, you can't distinguish "they killed him" from "he was killed". 

But the Polish forms in the link above are different - they use a special morphological form dedicated to having an impersonal agent (in fact you cannot specify the agent argument with that form). I think if the form is non-identical with other morphological forms, it deserves its own person value. Ancient Egyptian also has such forms, though they did not survive into Coptic, and Hausa is the same:

  * sun yi biki "they celebrated" (active 3rd person plural)
  * an yi biki "it was celebrated" (active impersonal - note "it" does not stand for some festival; this just means celebrating happened, like German 'es wurde gefeiert')

+1 for standardizing the value for this. Anything is fine IMO, I suppose `Person=0` has the advantage of keeping all values numeric?

**Comment by jheinecke** [comment]
Similarly for Welsh. It is different from the 3rd Singular and a verb in the impersonal form does not trigger soft mutation on a indefinite direct object. And there is no pronoun, so these .. From a semantic point of view it is rather close to French  "on + Verb" or German "man + Verb", with the difference, that in French or German in this case the verb is in 3rd Singular

**Comment by ftyers** [comment]
I've updated the Breton to be `Person=0` (from `Person=Auto`) in https://github.com/UniversalDependencies/UD_Breton-KEB/commit/dd7ec81e3b962e3ab78977e95feaf5384ed9e34f. But before closing this issue would like to get feedback regarding the Irish treebank.

**Comment by dan-zeman** [comment]
Thanks! It sounds to me like `Person=0` is the right solution here (we added it in v2 UD guidelines, inspired by Unimorph, although their specification did not mention Polish, Ukraininan or Celtic). Let's see what @tlynn747 thinks about it.

**Comment by dan-zeman** [comment]
I have checked `Person=0` as valid with `VERB` and `AUX` for [Breton here](https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/langspec/specify_feature.pl?lcode=br), so the validator no longer reports the feature as an error. (But it still reports some langauge-specific relation subtypes.)

**Comment by rueter** [comment]
> I've updated the Breton to be `Person=0` (from `Person=Auto`) in [UniversalDependencies/UD_Breton-KEB@dd7ec81](https://github.com/UniversalDependencies/UD_Breton-KEB/commit/dd7ec81e3b962e3ab78977e95feaf5384ed9e34f). But before closing this issue would like to get feedback regarding the Irish treebank.

It is interesting to note that the Finnish and Estonian treebanks use the feature ```Voice=Pass``` when dealing with what the traditional grammars call ```passive```, but whose meaning would, indeed, be a near if not perfect match for the impersonal ```Person=0``` addressed here. 

The Finnish and Estonian forms are distinct from the 1–3 personal forms. The structure does not work with an agent, except in the spoken language, where it is regularly used to indicate the first person plural in Finnish.

**Comment by dan-zeman** [comment]
@rueter : But 3 Finnish treebanks (out of 4) do [use Person=0](https://universaldependencies.org/treebanks/fi_tdt/fi_tdt-feat-Person.html). Estonian does not use it, though.

**Comment by tlynn747** [comment]
Apologies all - I'm late to the conversation on this one. I missed the notifications, probably as it was just before Christmas :)

Thanks @kscanne for flagging it again.   I'm happy enough to go with Person=0 instead of Voice=Auto in the Irish data. Obviously the other Celtic treebanks didn't exist when these decisions were made... nor did I know much about Polish verbs!

Just to point out, based on experiments I carried out, Voice=Auto served the intended purposes (ie to help the parser know that the first NP after the verb was an object and not a subject. But as these verbs are the only cases where we used the Voice feature, I think using the Person value makes sense - especially to keep it in line with other treebanks.
