### ISSUE TITLE
Right-to-left apposition with pronoun due to fronting?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#751]
Currently the validator enforces a restriction that `appos` must go from left to right, with the justification that the apposition construction is about elaboration, hence the elaborating information must go second in the sentence (#510).

But occasionally there is an example like the following (from English-EWT):

* The former leader of the Egyptian Al-Gamaa al-Islamiya ("Islamic Group"), he was also a spiritual leader of Al Qaeda.

This looks to me like a fronted appositive. It means the same thing as "He, the former leader..., was also a spiritual leader of Al Qaeda", and it is odd to say that "he" is an elaboration of "the former leader". "He" functions to connect the subject of the sentence with old information (a previous mention) and "the former leader..." is the new information.

Should this be considered a legitimate case of right-to-left-apposition, i.e. `appos(he, leader-1)`?

**Comment by amir-zeldes** [comment]
I don't think it's the same construction as an apposition. At least for me, I feel like there is an added predication here, i.e. that this is an elliptical version of:

"Being the former leader ..., he was also..."

So I would choose `advcl` here, so advcl(leader2,leader1). I wouldn't want to allow RTL apposition because:

  * apposition is supposed to be reversible, so if we really wanted appos we should pick appos(leader, he)
  * if its not reversible, and unusually postponing a pronoun suggests that this is the case, it would be nice to pick a different relation for this construction
  * RTL appos is in 99% of cases I've seen just a clear error that the validator catches for us, so I am happy if it gets flagged.

We have a couple of these in GUM as well, and have gone with this advcl analysis in the past.

**Comment by nschneid** [comment]
Hmm, it doesn't feel to me like `advcl` because it applies specifically to "he".

A depictive adjective is the closest non-appositive construction I can think of: "Eager to leave, he forgot his umbrella". That would be `acl`, not `advcl`. But it feels very wrong to have a nominal expression attach as `acl`. And I think it's reversible like other uses of `appos`, it's just clear that the first part is the new information rather than the elaboration.

**Comment by nschneid** [comment]
What about [`dislocated`](https://universaldependencies.org/u/dep/dislocated.html)?

**Comment by sebschu** [comment]
+1 for `dislocated` which is also used for attaching _general_ in this example:

```Bush, in answering the question about the leader of Pakistan, also said: "The new Pakistani general, he's just been elected -- not elected, this guy took over office.```

But then it should also be attached to the root of the main clause, i.e., `dislocated(leader2, leader1)`.

**Comment by nschneid** [comment]
There's a clear stylistic difference: the Pakistani general one sounds like the conversational/spoken language introduction of a topic before starting a complete sentence, whereas the Egyptian leader one is leading with a new descriptor of the previously mentioned entity, more like an appositive or predicative NP.

When the subject of the sentence has the same referent as the topic it may be hard to distinguish these. But consider

* The bicycle, my mom found it in the shed.

That's clearly the conversational-topic one. We presume the bicycle wasn't already topical in the discourse (if it were the speaker would not have needed the preface). But it was probably mentioned earlier, hence the definite reference.

So at some level these feel like different constructions. But using `dislocated` for both may be the best option.

**Comment by sebschu** [comment]
Oh, I hadn't realized that this was an example of this newspaper practice of introducing new information about an entity by changing the referring expression before I looked at the context. 

But I think syntactically, it is still a topic phrase (because of the additional _he_ as the subject), so I think `dislocated` is appropriate here.

**Comment by amir-zeldes** [comment]
I also think they're syntactically different, and notice the dislocated Pakistani General can't be made indefinite; if you do it, it becomes the 'added information' construction. Compare:

  * The new Pakistani general, he's a great guy (dislocated)
  * ??A new Pakistani general, he's a great guy (infelicitous IMO)
 
But:

  * A new Pakistani general, Ashraf was the best hope for all sides (=being a new Pakistani general, because he was a new general, etc.)
  * The new Parkistani general, Asharf was the best hope for all sides (IMO ambiguous between appos and the added information construction; in speech I think these two options would be pronounced differently)

**Comment by amir-zeldes** [comment]
> Oh, I hadn't realized that this was an example of this newspaper practice of introducing new information about an entity by changing the referring expression before I looked at the context.
> 
> But I think syntactically, it is still a topic phrase (because of the additional _he_ as the subject), so I think `dislocated` is appropriate here.

The reason I prefer `advcl` to `dislocated` here is that in the latter, the hanging topic should serve the same function as the second mention, usually a pronoun, so things like:

  * My neighbor, I like her (object dislocation)
  * My neighbor, she's great (subject dislocation)

In both these cases, the dislocation matches the pronoun in definiteness, and doesn't add any adverbial flavor (e.g. causal). This is not true of the 'added information' construction, which can be interpreted e.g. as cause, and does not need to match in definiteness:

  * A great fan of dogs, Kim could not be expected to let the puppies down

This seems very close to an elliptical version of:

  * **Being** a great fan of dogs, Kim could not be expected to let the puppies down

**Comment by nschneid** [comment]
But it's also true of the standard appositive, right?

* Kim, a great fan of the dogs, could not be expected to let the puppies down
* Kim (a great fan of the dogs) could not be expected to let the puppies down

I take it those would be `appos`. "Being" could be inserted to make it `advcl`.

**Comment by amir-zeldes** [comment]
@nschneid yes, I agree appos also fulfills that, so I think it's better than dislocated. It seems the main reason I picked advcl is just an intuition that it feels different from appos, but that's not a serious argument. I guess the only way to really prove a difference between this construction and normal apposition is if it is separable, so if you could say:

  * A great fan of dogs, the guards couldn't dissuade Kim from rescuing the puppies

If this is grammatical, I would say it's not appos, since appos should not be separable by an argument (but for advcl this would be fine)

**Comment by amir-zeldes** [comment]
OK, I looked around a little and it may be possible to find non-adjacent cases. For example I think this one can't be appos:

  * “Maybe she really does just need a little space ...,” **Amy** said, **ever the optimist**. (The Body in the Casket: A Faith Fairchild Mystery/Katherine Hall Page, 2017)

I think in a case like this, `appos` doesn't work due to non-adjacency, but a reading of "ever (being) the optimist" allows a fairly standard use of `advcl`. It also helps explain what an adverb like 'ever' is doing there. But for adjacent cases, maybe appos is still simpler?

**Comment by sylvainkahane** [comment]
It must be noted that it is a construction specific to English, or at least with specific constraints in each language. For instance the first example of @nschneid could not be translated in French with a definite article:

```
The former leader of the Egyptian Al-Gamaa al-Islamiya ("Islamic Group"), he was also a spiritual leader of Al Qaeda.
*L'ancien chef du groupe égyptien Al-Gamaa al-Islamiya ("groupe islamique"), il était également un chef spirituel d'Al-Qaida.
Ancien chef du groupe égyptien Al-Gamaa al-Islamiya ("groupe islamique"), il était également un chef spirituel d'Al-Qaida.

```
And these constraints are not the constraints we observe neither for apposition, nor for dislocation.

**Comment by nschneid** [comment]
>  * “Maybe she really does just need a little space ...,” **Amy** said, **ever the optimist**. (The Body in the Casket: A Faith Fairchild Mystery/Katherine Hall Page, 2017)
> 
> 
> I think in a case like this, `appos` doesn't work due to non-adjacency, but a reading of "ever (being) the optimist" allows a fairly standard use of `advcl`. It also helps explain what an adverb like 'ever' is doing there.

I suspect many appositives/parentheticals bear resemblance to predicates and can be modified by adverbs:

(a) John, (recently) a widower, said... 
(b) (Recently) a widower, John said... [clause-initial preferatory construction as in the Pakistani general example]
(c) I told John, (recently) a widower.
(d) I told a widower, John. (different pragmatics? cf. I told a widower, namely John.)
(e) *I told [recently a widower], John.

My guess is that annotators would be very tempted to call all of these `appos`. @amir-zeldes, do you want adverb-insertability to be a test for `advcl`?

**Comment by amir-zeldes** [comment]
I see your point, I guess the adverb is not really a good argument then. I do agree with the annotators as you said though, I think `appos` is probably the best we can do here. The "ever the optimist" example was mainly meant to show that some cases are separable, and for those cases I think `advcl` (assuming an elliptical predicating "being") is the most elegant thing we can do with the current set of labels. 

Since I don't think it's worth adding a label for these very rare cases, I would prefer `appos` for adjacent cases not involving a pronoun (which is usually not reorderable), `dislocated` for the lex NP in pronominal ones, and `advcl` for non-adjacent:

  * A former Pakistani general/dislocated, he gave the order immediately
  * John, a widower/appos, said...
  * I told a widower, John/appos...
  * Amy said, ever the optimist/advcl, that ...

The pronominal cases with prefixed lexical subject are BTW very common in some languages (Coptic) and obligatory in some tenses in some languages, e.g. Hausa, where we must specify a pronominal person-aspect complex, even if a lex NP subject is also specified.

**Comment by nschneid** [comment]
> * Amy said, ever the optimist/advcl, that ...

That's ungrammatical for me, or at least exceedingly odd. I think if "ever the optimist" comes after "said" it has to be at the end of the sentence.

For 

* "Blah blah blah," Amy said, ever the optimist.

I can see `advcl` as a hacky workaround to compensate for the fact that English appositions don't actually respect the contiguity constraint 100% of the time.

Personally, I'd rather change the contiguity constraint to a preference instead of doing gymnastics to work around it.

Maybe @dan-zeman wants to weigh in?

**Comment by nschneid** [comment]
For completeness, we should also consider whether "ever the optimist" should be `dislocated` on the right, if we treat the Pakistani general example as dislocation on the left.

I will note that Wikipedia classifies these as [appositions](https://en.wikipedia.org/wiki/Apposition); these are NOT the same as left dislocation and right dislocation as defined [here](https://en.wikipedia.org/wiki/Dislocation_(syntax)), which are like "My neighbor, he's great" discussed above—"my neighbor" is not adding information about "he", but rather, bringing up a discourse-new entity that can then be referred to with "he".

It occurs to me that the contraction with the copula shows that "he" is directly the subject, not a modifier of "neighbor": you wouldn't say "Amy, ever the optimist's, hopeful for the future"—to use the contracted copula on the subject you'd have to say "Ever the optimist, Amy's hopeful for the future".

**Comment by dan-zeman** [comment]
_"Blah blah blah," Amy said, ever the optimist._

To me, `advcl` looks much more natural here than `appos`. That is,
`advcl(said, optimist)`
instead of
`appos(Amy, optimist)`

What Wikipedia says about apposition is probably irrelevant because if anything is clear, then it is the fact that various authors have much broader notion of apposition than the one used in UD :-)

**Comment by nschneid** [comment]
@dan-zeman In that case would you say "Ever the optimist, Amy said...." should be `advcl`, `dislocated`, or `appos`?

**Comment by dan-zeman** [comment]
It would be the same for me, i.e., `advcl`.

However, it now occurs to me that it also resembles secondary predication (optional depictive), in which case the UD guidelines say it is `acl(Amy, optimist)`. Even here, I don't think the word order matters.

**Comment by nschneid** [comment]
Ah yes, it does resemble a depictive. I'm starting to wonder whether the notion of apposition is somewhat orthogonal to the kinds of relationships expressed by the core UD relations (`nmod`, `acl`, `advcl`, `conj`, etc.). _Canonical_ cases of apposition seem to involve (1) elaboration of a nominal with a modifier that is (2) parenthetical and (3) nominal. (3) is in common with depictive `acl`. Maybe we need a definition for "parenthetical" to separate that from the criteria for apposition. Is it relevant that two of these seems odd:

- "Blah blah blah," said Amy (ever the optimist).
- ?"Blah blah blah," Amy said (ever the optimist).
- Amy (ever the optimist) said "Blah blah blah".
- ?(Ever the optimist) Amy said "Blah blah blah".

I.e. maybe one interpretation of comma-separated "ever the optimist" is parenthetical and another isn't? I admit I don't know much about the syntax/information structure of parentheticals. :)

BTW apparently nonrestrictive relative clauses in English are also called "appositive relatives". This matches the parenthetical aspect (2) but not (3).

**Comment by nschneid** [comment]
Come to think of it: do any languages code morphologically for appositives? If not I can't help but wonder if something like `nmod:pred` (predicative nominal modifier) wouldn't be a better solution, also for nominal depictives. (And then `amod:pred` for adjectival depictives. The use of `acl` for depictives has always seemed stained to me.)

**Comment by dan-zeman** [comment]
I guess the idea behind `acl` is that secondary predication, as any other predication, means a clause.

**Comment by nschneid** [comment]
OK I finally looked up what CGEL has to say about appositives, and unfortunately, it is not simple.

First, the general definition of appositive with examples of "integrated dependents in NP structure" such as _the opera 'Carmen'_ (p. 447):
![image](https://user-images.githubusercontent.com/985263/104966456-e8368200-59ae-11eb-81a3-86f53cc0ce97.png)


They use the term __supplementation__ for a parenthetical-like interruption, which includes but is not limited to NPs and appositives. Starting on p. 1356:

![image](https://user-images.githubusercontent.com/985263/104966304-89710880-59ae-11eb-9f70-f5dbb29e6ba5.png)
![image](https://user-images.githubusercontent.com/985263/104966316-95f56100-59ae-11eb-9d8b-5ce8fbf62376.png)
![image](https://user-images.githubusercontent.com/985263/104966329-a1e12300-59ae-11eb-9151-727ce4fed254.png)

**Comment by nschneid** [comment]
### Summary of the CGEL taxonomy

- Appositive: dependent NP that, when substituted for the main NP in a clause, systematically yields an entailment of the original sentence. (_I saw the opera Carmen_ ⇒ _I saw Carmen_.) Two kinds: 
   * Appositive supplements
   * Integrated in NP structure
- Supplement: a phrase that serves as an aside/interruption rather than directly participating in ordinary dependency structure: can be a relative clause, specifying (appositive) NP, ascriptive (non-appositive) NP, etc.
   * the NP elaborated on is the **anchor**—not really a head, not necessarily adjacent
   * supplement can have an _ascriptive_ function (characterizing an entity: _Kim Jones, quite an outstanding student, ..._) or a _specifying_ function (further identifying an entity: _the first contestant, Lulu, ..._)
     - Specifying NP supplements qualify as appositives
        * Test: _that is_, _namely_, etc. can be inserted before the NP
   * "In supplementations with one NP as anchor and another as supplement, the relation between the two is comparable to that between subject and predicative complement in a _be_ clause. In particular, the distinction between specifying and ascriptive complements applies also to supplements." However, not every supplement readily paraphrases as a predicative complement: #_A university lecturer was Dr. Brown_.

|                   |  Supplement    |   Non-supplement  |
|-----------|----------------|---------------------
**Appositive**  | The first *contestant*, __Lulu__, was ushered on stage.<br> A university *lecturer*, __Dr. Brown__, was arrested.<br> I met a *friend* of yours at the party last night - __Emma Carlisle__.  | the *opera* __Carmen__ |
**Non-appositive** |  [ascriptive NP after anchor] Her *father*, __a die-hard conservative__, refused.<br> [ascriptive NP before anchor] __A die-hard conservative__, her *father* refused.<br> [ascriptive RC, verbal anchor] We *stopped* on the way, __which made us late__.<br> [ascriptive NP, verbal anchor] United will be *playing* at home, __a not inconsiderable advantage__.   |  |

Above I have bolded the appositive or supplement and italicized the head of the NP it refers to.

### How does this relate to current criteria for `appos`?

It seems we are using `appos` for adjacent, postnominal NP supplements, whether they are properly appositives in CGEL terminology or not. The difficulties raised by this thread involve prenominal or non-adjacent NP supplements.

It is also not entirely clear where CGEL's non-supplement appositives fall under current guidelines, as discussed in #591 for example.

**Comment by dan-zeman** [comment]
> It is also not entirely clear where CGEL's non-supplement appositives fall under current guidelines

For me, these were always doubtlessly `nmod`. But I have observed that some people expect prepositions or genitives when `nmod` is involved.

**Comment by amir-zeldes** [comment]
Thanks @nschneid for putting together this overview!

I just want to say two things:
  * A lot of the distinction between non-appositive/supplementary and true/integrated apposition seems to be signaled by articles (or the rare non-contiguous case). If we want cross-linguistically valid criteria, this will be problematic to use, since not all languages have articles/they may be distributed differently
  * Even just for English, the comma is problematic to rely on due to spoken data, which we are now getting a bunch of in GUM for example

**Comment by Stormur** [comment]
> It would be the same for me, i.e., `advcl`.
> 
> However, it now occurs to me that it also resembles secondary predication (optional depictive), in which case the UD guidelines say it is `acl(Amy, optimist)`. Even here, I don't think the word order matters.

In #476 it was already argued to change the annotation of "depictives" from `acl` to `advcl`, and all this discussion seems to bring new evidence! Namely, the main fact is that, even though it might not be obvious in English, where the subject is expressed obligatorily, such depictives, or secondary predications, appear independently from it: for example, as noted, they can be separated by what they refer to. So `acl` is not tenable, as from what I understand it requires an explicit element, else it depends on the predicate and it becomes `advcl` anyway. In Latin we are planning to use `advcl:pred` to point it out from other adverbial clauses (they use markedly different strategies, mostly coming from the fact that secondary predications seem to refer only to core arguments).  

Besides, I am in agreement with the interesting differences between `appos`, `dislocated` and `advcl` highlighted in this discussion. Very interesting points have been made.
