### ISSUE TITLE
Adding Universal Dependencies introduction to the repository README.md file. 

### ISSUE THREAD

**Issue by TawfikYasser** [UniversalDependencies/docs#755]
Hi, I want to add the introduction from the Universal Dependencies Website to the repository README.md file to make it easier for readers to know about this repository.

###### Thanks

**Comment by dan-zeman** [comment]
The [README file](https://github.com/UniversalDependencies/docs/blob/pages-source/README.md) already contains a link to the [UD website](https://universaldependencies.org/). I think it is better than copying any information from the website to the README file because then any updates would have to be manually synchronized at the two places.

**Comment by TawfikYasser** [comment]
Okay, I thought it would be better for the reader to see some little information about the site, in addition to having a link that takes him to the web site to get more information. I think that a repository without a description is not good, what do you think?

and Thanks for your reply :)
