### ISSUE TITLE
Segmentation, extremely difficult cases

### ISSUE THREAD

**Issue by robvanderg** [UniversalDependencies/docs#778]
When comparing to the raw txt files, it became clear to me that for some cases it is extremely difficult to get the segmentation right, and in some of these cases this seemed to be due to a mistake made while creating the txt files (from the conllu files?). Three examples:

In Slovenian-SSJ, there is for example: 
svetovljansko mesto ZDAVetrova pot ni vetrovna, ampak tista, na kateri se
Where the second sentence starts with "Vetrova"

In Belarusian-HSE there is:
ІНФАГРАФІКАУ Віцебску за наркотыкі затрымалі шклоўскага міліцыянта? Коля
Where the second sentence starts with "У Віцебску"

In UD_Italian-TWITTIRO there is:
http://t.co/mmToHn5Mzola buona scuola di renzi ha avuto la sua apoteosi in
Where the second sentence starts with "la buone"

Would it make sense for me to try and find all of them, and push corrections?, or would we like to keep the .txt files as they are, and not correct them based on the annotation?

**Comment by dan-zeman** [comment]
The text files in the released data are generated automatically from the CoNLL-U files using [conllu_to_text.pl](https://github.com/UniversalDependencies/tools/blob/master/conllu_to_text.pl). Fixing directly the text files thus does not make sense. If there is a bug in the conversion from CoNLL-U to text, I can fix the script. If the “error” is in the CoNLL-U file, I assume that it reflects the original source text, which was wrongly edited. In such cases the default UD approach is to keep the error while indicating in the analysis that it should actually be two words or even sentences. But maintainers of individual treebanks may decide that it is an error in corpus processing rather than a mistake by the original speaker/writer, and that they want to fix it.

I located the first of your three examples (sentences ssj234.1554.5620 and ssj234.1555.5621 in sl_ssj-ud-train.conllu) and it does indicate that there is no space between the two sentences: The last token of the first sentence, _ZDA_ “USA”, has `SpaceAfter=No` in the MISC column.

**Comment by robvanderg** [comment]
Thanks for the explanation!, I will start issues in the corresponding treebank repositories then, and whether SpaceAfter=No should be removed can then be decided on a per-case basis by someone that actually knows the data.
