### ISSUE TITLE
Suspicious cc attachments

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#785]
http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=6044ecacc2749 reveals 58 occurrences where `cc` attaches to a head that is not a `conj`, `root`, or `parataxis` dependent. Many of these are errors (e.g. `cc` within "and also" or "and not" whereas "and" should attach to the predicate). There are also some tricky constructions:

## Measurement-related
- *a notch or two*: currently nummod(notch, two); arguably ellipsis which would mean conj(notch, two), right?
- *week and a half*: same as above
- *445 or so*: currently nummod(445, so); conj would be better?

## Other
- *and so on*, *or vice versa*
- *Lo and behold*: fixed?
- *orange or "high"* ('a.k.a.'): currently appos(orange, high), but this seems overly semantic—perhaps conj is better
- coordinated auxes attach as `aux` sisters to the predicate: *would or could*, *may or may not*. IIRC this is the correct analysis because we want to minimize internal structure under `aux`

**Comment by dan-zeman** [comment]
I agree with the proposed fix for all three examples under "Measurement-related".

_and so on_ is also `conj` IMHO. (Headed by _so_.)

_lo and behold_ is new to me but what I see on the web looks like `fixed` is the right choice.

On the other hand, coordinated auxiliaries should be annotated as coordination. This is the correct analysis and a legitimate exception to the rule that an `aux` is leaf. Attaching them as siblings would be misleading because you could not collect a verb with all its auxiliary children and take it as one periphrastic verb form. Thus:
aux(VERB, may-1)
conj(may-1, may-3)
cc(may-3, or)

**Comment by amir-zeldes** [comment]
Agreed on "and so on" and the auxiliary coordination. For "lo and behold", we also have a case in GUM (with a typo), and we went with compositional cc+conj:

https://corpling.uis.georgetown.edu/annis/#_q=IkxvdyIgLiAiYW5kIiAuICJiZWhvbGQi&_c=R1VN&cl=0&cr=15&s=0&l=10

It's true that it's idiomatic, but the syntax seems quite transparent, I dislike extending the shopping list of fixed expressions, and you can actually use them separately as well:

  * When I did look up , **lo** ! straight before me lay Grovetown
  * these missives , almost every one of which contains amazing exact detail about recovered alien flying machines and **lo** , their alien crews no less
  * The chemical mixture was applied , and **lo** ! what should appear but a most ancient and valuable copy of Holy Scriptures of handwriting not later than the fifth century !
  * So they die die die every day . And **lo** after three weeks how many are left ? Dam few and most are dead

**Comment by Stormur** [comment]
As @amir-zeldes pointed out, _lo and behold_ just looks like a normal and transparent co-ordination with a word of very restricted use/style, but it does not show the characteristics of an "amalgamation" of words. Is _lo_ maybe treated as a special imperative form of _look_? This analysis would make it on par with _behold_.

I also agree with @dan-zeman about the treatment of _and so on_. We are dealing the same way in Latin with the otherwise problematic, from a part-of-speech point of view, _etcetera_ (lit. 'and other such [things]'; the internal head would be _cetera_), often just _etc._, making it always depend as `conj` on the relevant element.

**Comment by manning** [comment]
I also agree. Always lots of things to fix! (I am fixing a few....) I agree that a transparent syntax analysis of "lo and behold" seems better. I agree with @amir-zeldes that it usually seems best to do that unless clearly unviable.
