### ISSUE TITLE
Issue with u links in AUX pages

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#792]
On https://universaldependencies.org/en/pos/AUX_.html, the "u" link points to https://universaldependencies.org/u/pos/AUX.html, which for some reason redirects to https://universaldependencies.org/kpv/pos/AUX_.html rather than https://universaldependencies.org/u/pos/AUX_.html.

**Comment by dan-zeman** [comment]
There is some hidden magic that picks a description of a tag / feature / relation, if it exists, either from the universal guidelines or from one of the language-specific guideline sets. I bet that it stumbles upon the redirection mechanism, which we don't use very often but which is needed for `AUX` and `aux` (because the filename `AUX.*` is not portable across operating systems).

Maybe @spyysalo would know what's going on here?

**Comment by nschneid** [comment]
The issue was that the `redirect_from` field in https://github.com/UniversalDependencies/docs/blob/pages-source/_kpv/pos/AUX_.md, and equivalent pages in several other languages, had "u/pos/AUX.html" by default. So multiple pages specified the same source URL and one of them was arbitrarily picked.

I went through all the languages with AUX documentation pages to make sure they specify the correct alias.
