### ISSUE TITLE
Including raw data in repo

### ISSUE THREAD

**Issue by BramVanroy** [UniversalDependencies/docs#797]
Hello

I am wondering why the raw data (TXT) is not included in the UD repositories (not just in this one). To get the raw data it seems required to download the whole release [here](https://lindat.mff.cuni.cz/repository/xmlui/handle/11234/1-3424#show-files). This has the disadvantage that you need to download the whole UD treebank and can't pick a specific language let alone a specific treebank. Furthermore you can only dynamically get that dataset with curl which may not be easy to maintain compared to git.

I would like to have access to the raw files through git for development and evaluation reasons. During development of new UD parsers, it is useful to benchmark the parser's performance against the gold .conllu test set with an [evaluation script](https://universaldependencies.org/conll18/evaluation.html). To generate output with the parser, however, you need access to the raw data. As said, the power of git exceeds that of curl and, especially, it is cumbersome to have to download the whole treebank.

Is it possible to add the raw data to the repositories as well? Or, if not, is their a particular reason that they are not added?

Thank you

**Comment by dan-zeman** [comment]
The “raw” data is not the source text before the annotators came. Quite the opposite: It is a reconstruction from the annotated data. It is based entirely on the information that is already present in the CoNLL-U files ([document and paragraph breaks](https://universaldependencies.org/format.html#paragraph-and-document-boundaries) are optional, so the text files have them only if they were annotated in the CoNLL-U files).

The text files are automatically generated from the CoNLL-U files during the release process, using the [conllu_to_text.pl](https://github.com/UniversalDependencies/tools/blob/master/conllu_to_text.pl) script from the tools repository:

<pre>
perl conllu_to_text.pl --lang zh < file.conllu > file.txt
</pre>

Adding the text files directly to the treebank repo on Github seems redundant, although it would be possible to modify the infrastructure so that the files are available there. A side note: We actually should encourage people to download the official Universal Dependencies package from Lindat rather than from Github, because then the download statistics will be more accurate.

**Comment by BramVanroy** [comment]
Hi, Thanks for the reply. I was not aware of the conllu to text script. This is useful indeed. I can also understand the desire to increase traffic to Lindat, though statistics for individual repositories can also be tracked with [Insights](https://docs.github.com/en/github/visualizing-repository-data-with-graphs/accessing-basic-repository-data/viewing-a-summary-of-repository-activity).

That being said I still stand by the points that I made in the OP. Having the txt files as part of the repository would be quite useful from the perspective of the end user.
