### ISSUE TITLE
Looking for a list of German determiners and pronouns (needed for the UD tag set for Yiddish) 

### ISSUE THREAD

**Issue by ttasovac** [UniversalDependencies/docs#804]
Hi.

my colleagues and I are working on the UD tag set for Yiddish, as part of a project to build a training corpus for spaCy —  https://newnlp.princeton.edu. So far, the German tag set has been very useful because Yiddish is a Germanic language and the grammatical structures (tenses, cases etc.) are very similar. 

One thing that we're  wondering about is drawing the line between determiners and pronouns. The UD documentation reads:

> The pronoun (PRON) vs. determiner (DET) distinction is based on word lists because the traditional grammar does not define determiners.

Does anybody have an authoritative list of pronouns and determiners in German? Many thanks in advance.

All best,
Toma

**Comment by dan-zeman** [comment]
I am afraid that the actual annotation in (at least some of) the UD treebanks for German is based on context and not just word lists. This may be an artefact of the influential Stuttgart-Tübingen tagset, which distinguishes “substantive” and “attributive” pronouns depending on how they are used in the given sentence. My rule of thumb would be that if it can inflect for gender, it is a `DET`, otherwise a `PRON`. But that does not seem to be the approach currently taken in the German treebanks.

There are comparative statistics of the last official UD release for languages that have more than one treebank. [Follow this link for German](https://universaldependencies.org/treebanks/de-comparison.html), then search for _tagged as pronouns_, _tagged as determiners_, and for _sometimes as PRON and sometimes as DET_.

**Comment by ttasovac** [comment]
Thanks a lot @dan-zeman! I wasn't aware of the comparative statistics —  this is extremely useful in general and will help us a lot as we discuss how to approach the tagging of determiners and pronouns in Yiddish.
