### ISSUE TITLE
Serial verb constructions in Indo-Aryan languages

### ISSUE THREAD

**Issue by aryamanarora** [UniversalDependencies/docs#819]
I have been looking through the Hindi Dependency Treebank (HDTB) with the goal of eventually cleaning up the annotations, and have also been tinkering with trial dependency annotation for some treebank-less Indo-Aryan languages (Middle Indo-Aryan dialects, Punjabi, some Dardic languages, perhaps Sinhala).

One serious inconsistency between existing treebanks is the handling of **serial verb constructions**, V + V compounds that describe a single event. #386 discussed the issue a bit: in pretty much Indo-Aryan languages, there are a closed class of verbs (which in IA linguistics are called "light" or "vector" verbs) which have grammaticalised to be able to modify Aktionsart when compounded with other verbs. The issue is that while the light verb is semantically bleached, it does syntactically "take over" the main verb, having full TAM marking while the main verb is made non-finite (usually some converb construction or the stem form).

(A note about very annoying terminology: this is not to be confused with UD `compound:lvc`, also called a light verb construction in some works on Indo-Aryan, which is for N/Adj + V compounds. #401 attempted to deal with those but there are still issues there too...)

An example from Hindi:
| Sent | Translit | Gloss | Translation |
| :-- | :-- | :-- | :-- |
| मैंने किया। | *maiⁿ nē kiyā* | 1sg erg do-pfv | "I did it" |
| मैंने कर **डाला**। | *maiⁿ nē kar **ḍālā*** | 1sg erg do put-pfv | "I did it (straightaway/without a second thought/determinedly)" |
| मैंने कर **दिया**। | *maiⁿ nē kar **diyā*** | 1sg erg do give-pfv | "I did it (for someone)" |
| मैंने कर **लिया**। | *maiⁿ nē kar **liyā*** | 1sg erg do take-pfv | "I did it (for myself)" |

In Hindi the main verb in all of these is कर *kar* "do" which is in stem form, and is the obvious semantic head since it describes what the event actually is. Other languages use a converbial suffix for the main verb, e.g. Gujarati would use _-ī_, Marathi _-ūn_, etc.

Now, there are a couple issues with annotating these:
1. **Which verb is the head?** In the Marathi treebank the light verb is the head, and I can see some syntactic features that favour that analysis, since light verbs affect argument case marking, take full TAM marking like the main verb with a converbial `advcl`. In Marathi, main V + light V is also syntactically identical to converb + main V. But UD generally favours content heads. One thing is that these light verbs can become grammaticalised into auxiliaries: Hindi रह _rah_ is an auxiliary marking the progressive aspect that was analysed more like a light verb as recently as in 19th-century grammars.[^slade]
2. **What deprel?** The Armenian treebank uses `compound:svc` on the light verb dependent to the main verb, which is one option; Marathi treebank flips the dependency direction but uses the same label. HDTB uses `aux` which I don't think should be used since it confuses these and actual auxiliaries together.
3. **How do auxiliary verbs attach to this construction?** IA languages have normal auxiliary verbs which can also be used with these constructions, e.g. Hindi कर दिया था _kar diyā tʰā_ "**had** done it (for someone)". Does the auxiliary था attach to the light verb (which is the one with TAM marking!) or to the main verb (which has all the semantic content)? I honestly have no idea on this.

There are even more really deep issues relating to this (e.g. where does the negation attach?) but those are dependent (pun intended) on these basic ones being figured out.

[^slade]: Slade, Benjamin (2020). "[Development of verb-verb complexes in Indo-Aryan](https://lambda-y.net/publication/slade-2021-vv-devel-ia/)" in *Verb-Verb complexes in Asian languages* (eds. Prashant Pardeshi, Taro Kageyama, Peter Hook). Oxford: Oxford University Press

**Comment by amir-zeldes** [comment]
I think this issue has been discussed in the past numerous times, so it's worth going back through the issues and seeing where the discussion ended up. That said (and disclaimer: I am no expert on IA languages at all), for me the question is whether the combinatorics are more or less automatic, or rather limited, and what the syntactic of the rest of the language does. I think having a special label is nice if it's feasible to do so (e.g. `compound:svc`), but compound as a term in Linguistics is more often associated with combining multiple lexical items to form a new lexical item.

For the direction as well, if the list of verbs that can do this is closed AND they can be combined with the vast majority of verbs in the language in this way with a consistent, transparent meaning, then they are good candidates for being dependents (like auxiliaries) rather than heads, favoring content as UD generally does. But if it is a more limited phenomenon, with unpredictable combinations, then that is less warranted IMO. I feel these distinctions more or less mirror the difference between inflection and derivation in morphology: inflection is automatically available and creates paradigms; so do auxiliaries, on the syntactic level.

Finally the 'overall syntax' consideration is, I suppose, why English words like "want" are not classified as auxiliaries, while "can" is - in English, there is a small closed system of modals (can, would) which take a bare infinitive, and an open class of verbs taking xcomp "to" infinitives. Even though "want" is often quite low content and close to the modals in meaning, it is syntactically interchangeable with other infinitive governing predicates, and we draw the line based on form factors (otherwise we would have a slippery slope - if "want" were an auxiliary, could we argue that "plan" should be one too?)

But that's just by way of comparison, I hope we'll now hear from some UD people who know more about the languages in question!

**Comment by aryamanarora** [comment]
These are fair points--there are a small set of light verbs forming a pretty closed class which have pretty predictable modification to TAM. Linguistic works like Slade (2020) which I ref'd in the original issue can easily list them out for specific languages. And like English *can* in Hindi they can take a bare stem-form verb, which is pretty unique to this class (but similar diagnostics I don't think exist for other Indo-Aryan languages, but the closed-classed-ness still holds).

Something like `aux:svc(main verb, light verb)` sounds sensible, since I think we'd want to be able to query light verb combinations easily and not wholesale merge them with `aux`. I'm not sure who else active in UD with Indo-Aryan language knowledge would be qualified to discuss this, maybe @shashwatup9k?

**Comment by dan-zeman** [comment]
I would stay with using `compound:svc` and keep off `aux` (I know it is now used in the Hindi/Urdu treebanks for things that should not be `aux`). Making the more contentful verb the head sounds UD-ish enough to me :-) Also, I would attach auxiliaries to the head of the complex (unless there is evidence in particular cases that the opposite should be done; it is not forbidden for `compound` dependents to have children.
