### ISSUE TITLE
ADJ + ਹੋਣਾ compounds in Punjabi

### ISSUE THREAD

**Issue by aryamanarora** [UniversalDependencies/docs#821]
Generally ਹੋਣਾ *hōṇā* is the copula so it is not the head of a VP. But when it is a part of a compound verb (i.e. had a child `compound:lvc` with upos `ADJ`) it's not clear what to do with it.

E.g.
* [ਸਰਪੰਚੀ ਲਈ] ਖੜ੍ਹਾ ਹੋਣਾ "to run [in the Sarpanch election]"

We could analyse it as a copula and have the adjective be the head (so it is `AUX`), or treat it as a complex predicate and a normal `VERB`. The issue comes especially with simple conjugations:

* ਮੈਂ ਚੋਣਾਂ ਵਿੱਚ ਖੜ੍ਹਾ ਸੀ "I stood for the election"

This problem applies to other South Asian languages too.

**Comment by dan-zeman** [comment]
I would analyze ਹੋਣਾ _hoṇā_ as a light verb in construction where it alternates with the light verb ਕਰਨਾ _karanā_.

`compound:lvc(ਹੋਣਾ, ਖੜ੍ਹਾ)`
`compound:lvc(ਕਰਨਾ, ਖੜ੍ਹਾ)`

ਹੋਣਾ _hoṇā_ should probably be tagged `VERB` rather than `AUX` in these cases.

But is it possible to consistently draw the line between this usage of _hoṇā_ and the copular usage?

**Comment by dan-zeman** [comment]
> I would analyze ਹੋਣਾ _hoṇā_ as a light verb in construction where it alternates with the light verb ਕਰਨਾ _karanā_.

A similar analysis is taken in the Hindi PUD treebank:

तेज हवा चलनी शुरू होती है।
teja havā calanī śurū hotī hai.
Strong wind starts blowing. [starts=beginning is]

`compound:lvc(होती, शुरू)`
`compound:lvc(hotī, śurū)`

एक यजीदी महिला ने रोना शुरू किया।
eka yajīdī mahilā ne ronā śurū kiyā.
A Yazidi woman began to cry. [began=beginning did]

`compound:lvc(किया, शुरू)`
`compound:lvc(kiyā, śurū)`

The large Hindi HDTB treebank does not use the `compound:lvc` subtype yet. However, it seems to use just `compound` and otherwise analyze it the same way. Same [for the Urdu UDTB treebank](http://hdl.handle.net/11346/PMLTQ-NWHS):

آندھی اور طوفان کی اےک حولناک لہر امریکہ کی جنوبی ریاستوں مےں شروع ہو گئی ہے۔
Āndhī aor ţofan kī aek holnak lhr amrīkh kī jnobī rīastoñ meñ shroʿ ho gī he.
A terrible wave of wind and storm has started in the southern states of the United States.

`compound(ho, shroʿ)`

پولیس بس ڈرائیور کو حراست مےں لے لیا اور پوچھ تاچھ شروع کر دی ہے۔
polīs bs ḍraīor ko hrast meñ le līa aor pochh tachh shroʿ kr dī he.
Police have arrested the bus driver and started questioning him.

`compound(kr, shroʿ)`

**Comment by aryamanarora** [comment]
> But is it possible to consistently draw the line between this usage of *hoṇā* and the copular usage?

That is the exact problem. ਖੜ੍ਹਾ ਹੋਣਾ "to stand [for an election]" can probably be reasonably analysed as a `compound:lvc` construction since it's non-compositional. But in certain parts of the paradigm of ਹੋਣਾ it's really hard to claim a syntactic difference from attributive `ADJ`:

- ਉਹ ਚੋਣਾਂ ਵਿੱਚ ਖੜ੍ਹੇ ਹਨ *uh coṇā̃ vicc kʰaṛʰe han* "he is running in the election"
- ਉਹ ਚੌਰਾਹੇ ਵਿੱਚ ਖੜ੍ਹੇ ਹਨ *uh caurāhe vicc kʰaṛʰe han* "he is standing in the street"

One could say both of these are `nsubj(ਖੜ੍ਹੇ, ਉਹ)` and `cop(ਖੜ੍ਹੇ, ਹਨ)`.

There is a lot of debate about `ADJ` + `VERB` constructions in Indo-Aryan languages and I'm not sure if there's a consensus among linguists about how to analyse it. It is akin to the issue of analysing `NOUN` + `VERB` as `compound:lvc` or `obj`/`ccomp` and the fuzzy boundary between.

**Comment by dan-zeman** [comment]
> It is akin to the issue of analysing `NOUN` + `VERB` as `compound:lvc` or `obj`/`ccomp` and the fuzzy boundary between.

OK, but that analogy could at least provide some lead. Since there seems to be consensus within the UD community that light verb constructions are so pervasive in Indo-Iranian languages that they deserve a special treatment (as opposed to treating the non-verbal component as an object of the verb), we could say that there is a group of verb-noun/adjective compounds that deserve the `compound:lvc` treatment. The group perhaps does not have sharp boundaries (I suppose it's not a closed class that we could enumerate?) but one could hopefully list the most prominent examples and then say something like "if you are in doubt, prefer the compositional analysis over `compound:lvc`".

Now if that group contains ਕਰਨਾ _karanā_ with a particular `NOUN` or `ADJ`, then ਹੋਣਾ _hoṇā_ with the same nominal counterpart will be also analyzed as `compound:lvc`; in other cases, ਹੋਣਾ _hoṇā_ will be analyzed as a copula.

I admit that there is the catastrophe effect you demonstrate above, superficially similar sentences will get different analyses. But if we instead say that ਹੋਣਾ _hoṇā_ is always copula, we will have the catastrophe between the ਹੋਣਾ _hoṇā_ "compounds" and corresponding ਕਰਨਾ _karanā_ compounds. And if we decide that there should be no `compound:lvc` whatsoever, then we first should persuade the maintainers of Hindi, Urdu, Persian and other treebanks to abandon it, and then we would have issues with cases where the ਕਰਨਾ _karanā_ compound takes another nominal as a direct object. So each of the three options has a downside.

**Comment by aryamanarora** [comment]
Tara Mohanan (1994), *Argument structure in Hindi* says:
- the primary way to diagnose whether an N+V sequence is a light verb construction is if the N modifies the argument structure of the clause
- despite scrambling in Hindi, N+V light verb constructions generally resist separation in the clause (they behave as one unit), however the V can be topicalised and fronted
- the N cannot take determiners or other modifiers if it is in a light verb construction (if it does, it's just an `obj` to the verb)
- genitive arguments to the N should be treated as children of the V (currently, I am not doing this for Punjabi and have been labelling them `nmod`)

I think these criteria can be applied to Adj+V compounds without modification.
