### ISSUE TITLE
Word Segmentation and CoNLL-U conflict in examples for multiword tokens

### ISSUE THREAD

**Issue by rhdunn** [UniversalDependencies/docs#833]
In the [Word Segmentation](https://universaldependencies.org/workgroups/newdoc/word_segmentation.html) documentation, it states:
> Unlike in some non-UD approaches, tokenization does not involve any normalization of the word forms, that is, the FORM column contains exact substrings of the input text, and the original surface string can be reconstructed by concatenation. (If normalization is desired, it can be done in the LEMMA column and possibly with additional attributes in MISC.)

However, the example of multiword tokens in [CoNLL-U Format](https://universaldependencies.org/format.html#words-tokens-and-empty-nodes) contradict this:
```
1-2    vámonos   _
1      vamos     ir
2      nos       nosotros
3-4    al        _
3      a         a
4      el        el
5      mar       mar
```

To conform with the word segmentation guidelines, this should be:
```
1-2    vámonos   _
1      vámo     ir
2      nos       nosotros
3-4    al        _
3      a         a
4      l        el
5      mar       mar
```

i.e. the word form normalization is present in the lemma and the original text is reconstructed from concatenation of the FORM field, following space rules from token ranges, SpaceAfter, and CorrectSpaceAfter.

It may also be better in this case to have the full 10 columns to make it a valid CoNLL-U example. There should then be `SpaceAfter=No` in the word sequence output with a note that these have been added for all but the last token in the token range, with the last token taking the SpaceAfter MISC feature if present from the token range word line. If the /vamos/ is to be preserved, it should be in a CorrectForm MISC feature.

**Comment by rhdunn** [comment]
The German example in Word Segmentation ("am" => "an dem") also contradicts the tokenization rules for FORM.

Specifically -- when using only the non token ranges, it is impossible to get the correct source text (and is thus then impossible to work out where the token starts and ends in the source text).

**Comment by nschneid** [comment]
It is important to note that multiword tokens only have to match the surface string at the supertoken level: "The form of the surface token does not have to be a simple concatenation of the forms of the syntactic words." This is followed by examples like *am* as a contraction of *an* + *dem* (similar to *al* in Spanish).

So I don't see a problem with the examples in the guidelines.

**Comment by rhdunn** [comment]
As written, that sentence keeps the guidelines consistent, but:
1. it goes against the general note of UD not normalizing the FORM field -- specifically, I read that guideline as it making it easy to determine where a token begins and ends in the `text = ` metadata, or the reconstructed text;
2. it means that a tokenizer (or any other analysis) cannot depend on the non-MWT information to tokenize compound words/word forms [1];
3. The "This is useful for various contractions where the uncontracted form of the word can be shown." guideline can equally be handled by CorrectForm or other features, just like is done with Abbr=Yes or Typo=Yes features.

[1] This is especially the case where that tokenization is needed to yield valid part of speech analysis of the compound word (gon|na, do|n't, 't|was, etc.).

NOTE: I would be happy with a feature (e.g. `TokenPart=`) that can be used in conjunction with the MWT annotations to denote where in the source text the non-MWT word line occurs in the source text.

In that case, the convention that each word line that is a part of a MWT is a complete word should be enforced (e.g. "1-2/don't" => "1/do 2/not").

**Comment by nschneid** [comment]
These guidelines for the FORM column have been widely implemented so I think they are unlikely to change. Conventions for tokenization (in the sense of merely inserting spaces into the input string) are a largely language-specific issue when it comes to syntactically complex surface words, and UD leaves it up to individual languages how they want to interpret the FORM column for words within a multiword token.

If the goal is to map every subtoken word to a part of the input string (if this is even possible in all cases), I suppose this could be done with a MISC feature like `TokenPart`, but I'm not sure all treebanks will want to implement this.

**Comment by amir-zeldes** [comment]
Yes, as @nschneid said, this is absolutely an intended usage of MWTs: they do not have to be the sum of the token FORM fields. I can add that in some cases token-wise alignment to the source text is indeed not possible, since you can have things like mergers of two tokens into a single MWT character, or have MWT strings which are totally distinct from the token substrings. For example in Portuguese from Bosque:

  * O atacante, que deveria ter se apresentado anteontem à noite...
  * "The attacker, who should have performed the night before last..." (à noite = "a + a + noite" 'in the night')

```CoNLL-U
1	O	o	DET	_	Definite=Def|Gender=Masc|Number=Sing|PronType=Art	2	det	_	_
2	atacante	atacante	NOUN	_	Gender=Masc|Number=Sing	14	nsubj	_	SpaceAfter=No
3	,	,	PUNCT	_	_	2	punct	_	_
4	que	que	PRON	_	Gender=Masc|Number=Sing|PronType=Rel	5	nsubj	_	_
5	deveria	dever	VERB	_	Mood=Cnd|Number=Sing|Person=3|VerbForm=Fin	2	acl:relcl	_	_
6	ter	ter	AUX	_	VerbForm=Inf	8	aux	_	_
7	se	se	PRON	_	Case=Acc|Gender=Masc|Number=Sing|Person=3|PronType=Prs	8	expl	_	_
8	apresentado	apresentar	VERB	_	VerbForm=Part	5	xcomp	_	_
9	anteontem	anteontem	ADV	_	_	8	advmod	_	_
10-11	à	_	_	_	_	_	_	_	_
10	a	a	ADP	_	_	12	case	_	_
11	a	o	DET	_	Definite=Def|Gender=Fem|Number=Sing|PronType=Art	12	det	_	_
12	noite	noite	NOUN	_	Gender=Fem|Number=Sing	9	obl	_	SpaceAfter=No
...
```

There is no way to align this uniquely and character-wise, except to say that both tokens 10 and 11 align to the same character, which is basically what MWTs do: 10-11 corresponds to the surface character "à".

**Comment by dan-zeman** [comment]
Thanks for pointing out potential confusion. I tried to fix it in https://github.com/UniversalDependencies/docs/commit/018dabb5e891e5833815f9ab8971f92a6cf5587c. I confirm that the correspondence of FORM to a substring of the input only holds for surface tokens but not for parts of multi-word tokens. It is thus possible to reconstruct the input sentence by collecting forms from surface token lines, and inserting spaces unless `SpaceAfter=No` is present.

This has been the interpretation of multi-word tokens since UD 1.0. `CorrectForm` in MISC is a much later development and it is just an optional extension.
