### ISSUE TITLE
How to annotate enhanced dependencies

### ISSUE THREAD

**Issue by adripag** [UniversalDependencies/docs#843]
Hello! We are planning to annotate enhanced dependencies for a corpus in Brazilian Portuguese. We have gone through open and closed issues, but could not find updated information on best practices - particularly if manual editing is generally performed and which tools are best to annotate.
Webanno / Inception seem to support both basic and enhanced dependencies. Any other tool(s)?
Suggestions are most welcome!

**Comment by jheinecke** [comment]
Hi, try https://github.com/Orange-OpenSource/conllueditor (and tell me whether it works for you needs). I would pre-annotate the ehnanced dependencies by copying the basic dependencies except those which are never enhanced (line `orphan`)

**Comment by dan-zeman** [comment]
The [UD validator](http://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl) already has some tests for the enhanced graphs, and other tests will probably be introduced in the future, so make sure to use the validator early (or simply upload the data to the dev branch and see the report at the page linked above).

As for creating the annotation: some enhancements can be created automatically or almost automatically (parent propagation across coordination, case-enhanced relation labels, to some extent also relative clauses and even control verb structures), so it will be beneficial to prepare the data using a script and then edit it. People have been using the Stanford Enhancer (the version I have played with sometimes choked on certain trees, but maybe it was fixed in the meantime, I haven't checked). However, some of the enhancements can be probably implemented relatively easily in tree-rewriting tools such as [Udapi](https://ufal.mff.cuni.cz/~zeman/vyuka/deptreebanks/NPFL075-working-with-UD.pdf).

**Comment by amir-zeldes** [comment]
I can add that there is a basic enhancement script for English using the Python library depedit:

https://github.com/amir-zeldes/DepEdit/blob/master/examples/eng_enhance.ini

Just download or install depedit and run:

`> python depedit.py -c eng_enhance.ini INFILE.conllu`

The script has a little bit of English hardwired into it (e.g. lemmas for verbs with subject control), but can be adapted fairly easily to other languages. It is not quite, but almost the complete script for creating the initial enhanced dependencies in UD_English-GUM (that corpus has some additional annotation layers that allow a few improvements).

**Comment by adripag** [comment]
Many thanks for all replies!
I am "ashamed" to say that I could not get Orange installed in my mac... (All suggestions are most welcome).
Was happy to learn there will be a talk on enhanced dependencies at SyntaxFest this year.

**Comment by jheinecke** [comment]
@adripag, create an issue at https://github.com/Orange-OpenSource/conllueditor and describe what is the problem (java, the shellscript starting the server?). I'll see what I can do to get it running
