### ISSUE TITLE
Anonymous places and people

### ISSUE THREAD

**Issue by colinbatchelor** [UniversalDependencies/docs#848]
Among the most common `PROPN`s in the Scottish Gaelic corpus are [Name] and [Placename], which indicate people and places which have been anonymised. It goes without saying that these aren't real Gaelic and I'd like to annotate them as such but I'm a bit stumped as to how and I haven't found anything in the documentation so far.

Maybe `Anonymised=Yes` in the FEATS column? Or `Anonymized=Yes`?

They might even be `SYM`, I suppose.

**Comment by nschneid** [comment]
These placeholders are a difficult case. *Maybe* a case of what https://arxiv.org/abs/2011.02063 calls Disguise, except the point with anonymization is that it is impossible to reconstruct the original name, whereas Disguise just makes it more effortful.

`PROPN` reflects its distribution but not its spelling. `SYM` may be the best option, or `X`.

I like the idea of `Anonymized=Yes` or `Placeholder=Yes` to reflect that it is not a real word but stands for one. Blanks that represent a place to fill in a word or phrase might also be considered placeholders when syntactically part of a sentence. Presumably the feature should go in MISC for now as it is nonstandard.

@amir-zeldes have you encountered this in user-generated content?

**Comment by amir-zeldes** [comment]
Yes and no - since UGC is generally not open license, we distribute the data as underscores anyway, and the source data is openly posted un-anonymously anyway. But in a spoken scenario, anonymity must be preserved if those were the terms of data collection. GUM contains SBC data which I believe has pseudonyms, which I think is maybe the optimal solution (aside from that, the data looks like people are using normal names)

In terms of POS, I think SYM is worse than PROPN - the grammar of the sentence is as if the name really is there, so I think that's how it should be tagged. I would also support something like `Anonymized=Yes` if it's truly necessary, but if it's all people's and place names, and they are indexed for identity (name1, name2), I would recommend introducing a random name generator to replace them (if necessary, maybe it could be a random Scottish personal and place name generator :) Not sure if the maintainers can provide that, but it would be nicer IMO.
