### ISSUE TITLE
Treebanks with manually annotated enhanced dependencies

### ISSUE THREAD

**Issue by ALeczkowski** [UniversalDependencies/docs#851]
Hello,

I am looking for information about enhanced dependencies in UD corpora v2.9. I have already extracted the list of corpora that have enhanced dependencies (32 corpora); that was an easy task.

However, I was wondering whether there is a list somewhere with information if those enhanced dependencies were annotated manually or automatically. I was trying to find that information in the ReadMe files of each treebank; however, that information is in most cases not provided. In most cases an information as in the exmaple below is given (English EWT):

`
2021-03-10
   Added enhanced dependencies
  `

If you where I could find a good source of that information please let me know!

Regards,
Aleksander Leczkowski

**Comment by amir-zeldes** [comment]
Hi Aleksander - sadly I am guessing you may have to piece that together corpus by corpus from the individual maintainers... But I can start by answering that question for UD_English-GUM: most of the enhanced dependencies there are re-computed automatically at each release using a variety of other annotations, so that each version is hopefully a little better, as we improve the algorithms for adding the enhanced dependencies.

That said, there is a subset of cases which are manually annotated, primarily (but not only) in cases where the primary dependencies have the `orphan` relation or virtual empty nodes (ellipsis tokens with IDs like `7.1`). You can see exactly which tokens are manually annotated for edeps in the upstream (non UD) repo - here is an example document:

https://github.com/amir-zeldes/gum/blob/dev/_build/src/dep/GUM_bio_moreau.conllu#L140

Notice how this row, and others like it, have the DEPS field populated - these are manually annotated enhanced dependencies, and the field can contain multiple edges as is normal for edeps. I think in total these annotations are quite rare, perhaps about 500 edges or so; but the algorithm for automatically adding edeps given the other layers is fairly reliable, so we only manually add edges in cases where an ellipsis token is needed or where we notice an unusual configuration which the automatic rules can't cover reliably.

**Comment by martinpopel** [comment]
I would consider a semi-automatic approach similar to the one described by @amir-zeldes above as the most reliable one. Based on my experience it is much more reliable than a fully manual annotation (without automatic checks). Most of the rules for enhanced dependencies are quite deterministic.

**Comment by dan-zeman** [comment]
In the Czech, Slovak, Lithuanian, Arabic and Tamil treebanks, edeps are derived automatically from the basic annotation using various heuristic rules. One of the enhancements that cannot be derived deterministically – the shared dependents of conjuncts in coordination – draws upon annotation in the original non-UD scheme, where the necessary information was annotated manually; so you could say that this piece is based on manual annotation. The exception is UD_Czech-PUD, which was annotated natively in UD, hence the information about shared dependents is not available.

**Comment by ALeczkowski** [comment]
Thanks for all of your comments!

**Comment by lauma** [comment]
Latvian is manually annotated different, more complex, format and then converted to UD / enhanced UD with rule-based methods. Thus, I would like to think that most of the enhanced UD Latvian has is correct, but it lacks couple aspects of enchancedness entirely.
