### ISSUE TITLE
Reconstructed Lemma

### ISSUE THREAD

**Issue by MathieuDehouck** [UniversalDependencies/docs#865]
Dear All,

I have a basic question regarding Lemmatisation.

I am working on the IKUVINA treebank, for Umbrian.
Since the amount of text we have is limited, we do not have all the forms for many open class words.
Thus it is virtually impossible to have a unique source for open class words' lemma (infinitive; nom. sing...).
But since it is an Italic language that is decently understood a number of forms can be confidently reconstructed even though we might never be sure they actually existed.

The question is then, in such a case where we do not know the prototypical form chosen for lemma, should we:
0. not put any lemma?
1. pick another existing form?
2. pick the reconstructed form?
2.5. pick the reconstructed and write as such (*fakiom)?

Thank you for you insights.

**Comment by dan-zeman** [comment]
Not providing any lemma is a bad idea. We still want to be able to group together forms that belong to the same lexeme, and lemma can help with this.

If the desired form can be reconstructed, I would use it even if it is not attested in the preserved texts.

**Comment by MathieuDehouck** [comment]
Thank you for the reply.

But then, would you make it clear that it is a reconstructed form, like with an asterisk or rather not?

**Comment by sylvainkahane** [comment]
I think having a special mark is a good idea, maybe as well as a specific feature.
For instance, in the treebanks we are developping starting from IGTs (interlinear glossed texts), we keep the "=" in the form and the lemma of clitics, and we add a special feature TokenType=Clit.

**Comment by dan-zeman** [comment]
I am not fond of adding special characters to the lemma, and a feature in the FEATS column also does not seem a good fit, as these features are meant to describe the form rather than the lemma (although some of them are lexical, so they will have the same value for all forms of the lemma). Technically you will be able to define a language-specific feature if you choose to do so, but I would probably encode the information as an attribute in the MISC column.

**Comment by MathieuDehouck** [comment]
Then, I'll add a "Lemma=Reconstructed" in the Misc column when necessary.
We can always decide to change this later on if a formal decision is eventually taken, in the unexpected case of more languages with a similar problem popping up.

**Comment by sylvainkahane** [comment]
`lemma` is already used. I think that a feature such as `Reconstructed=Yes` or `ReconstructedLemma=Yes` is more desirable.

**Comment by MathieuDehouck** [comment]
I see.
I was not sure there was already fixed ```misc``` features beside ```SpaceAfter=No``` or something like that.
Then I'll use something like ```ReconstructedLemma```.
Thank you.

**Comment by dan-zeman** [comment]
> I was not sure there was already fixed `misc` features beside `SpaceAfter=No` or something like that.

Nothing besides `SpaceAfter` is really fixed in MISC but it is desirable that similar things are encoded similar way across treebanks even in that column, so there is a [documentation page on MISC attributes](https://universaldependencies.org/misc.html) and people are encouraged to consult it before defining new attributes (and to document them there after defining them). `Lemma` is not there, so I don't know what exactly @sylvainkahane means by it being used; nevertheless, if an attribute were labeled simply `Lemma`, I would expect the actual lemma string as the value (rather than some property of the lemma), so I agree that `ReconstructedLemma=Yes` is better.
