### ISSUE TITLE
Presentational constructions

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#870]
The English guidelines for [`cop`](https://universaldependencies.org/en/dep/cop.html) mention that presentational constructions should not be considered copula clauses. The *be* verb is treated as the root, not `cop`. (And presumably, then, it should be tagged VERB not AUX like with existentials.)

But English corpora seem to be inconsistent for "Here is/are..." annotations. ([EWT](http://universal.grew.fr/?custom=62793754e6d3a), [GUM](http://universal.grew.fr/?custom=6279377c50888))

What is the right policy here? Notably, [this section](https://universaldependencies.org/u/overview/simple-syntax.html#nonverbal-clauses) of the main universal guidelines does not mention presentationals.

**Comment by dan-zeman** [comment]
https://universaldependencies.org/workgroups/newdoc/location.html

**Comment by nschneid** [comment]
Thanks! Should that be linked from https://universaldependencies.org/u/overview/simple-syntax.html?

I don't immediately see an answer for how to treat "Here is/are" sentences. Is "here" an advmod or expl or predicate? [These `cop` guidelines](https://universaldependencies.org/en/dep/cop.html) example 12 say advmod, but it's not obvious to me why "there" should be expl but "here" should be advmod.

**Comment by dan-zeman** [comment]
> Should that be linked from https://universaldependencies.org/u/overview/simple-syntax.html?

Maybe. But it resides in an incubator for "new" documentation (started in 2018). If this is ever completed, it will be moved to a different place.

As for English _here_ vs. _there_, I would want to hear the opinion of the English data maintainers and then we can reflect the concensus also in the global guidelines. I am not the best person to give advice here because I think I would prefer to extend the copular analysis to presentational constructions in English; but that option was rejected by other people (@sebschu? @manning?) when UD v2 guidelines were discussed.

**Comment by amir-zeldes** [comment]
It's sort of piggy-backing on the PTB xpos EX guidelines IMO. I mean, there are plenty of other adverbial options that allow inversion in English, and even PPs allow it. GUM examples:

1. Thus commenced his unprecedented and whimsical 21 - year " reign " over America
2. So reasoned Erasmus .
3. And here comes Melvin Dobson arriving at the scene
4. Slower and slower went the circling hands
5. In that northeast quadrant was Debbie 's smoking chair

I think what makes "there" special is that is allows duplication, indicating that it's truly an expletive:

6. There 's not enough lemon there to bother me

This would be very unusual to do with "here" (though probably not impossible, just not attested in a corpus the size of GUM!). So it's a bit special that way, but in any case limiting it to there/EX makes it a bit more decidable/consistent. If "here" were expl some of the time, it would be harder to decide than for "there" IMO.

**Comment by nschneid** [comment]
OK, I don't feel the need to argue for an expanded EX category.

Was the logic for "be" being the predicate in existentials that expletives should not be predicates, and the nominal after "be" should be the nsubj, so "be" is the only thing left to serve as predicate? Trying to figure out how that maps on to "here" cases.

"Here is a book" and "A book is here" are valid paraphrases in some but not all contexts.

With the first sentence, negation—"Here isn't a book"—would be quite bizarre.

If you handed me a mysterious object and said "Here it is", it would be odd to respond "What is here?" Better: "What is this?"

**Comment by amir-zeldes** [comment]
> Was the logic for "be" being the predicate in existentials that expletives should not be predicates, and the nominal after "be" should be the nsubj, so "be" is the only thing left to serve as predicate? Trying to figure out how that maps on to "here" cases.

Those all sound right, but there are also other reasons: the construction implies pure existence, which is headed by existential predicates for verbs like "exist". Since "there" doesn't mean anything in this scenario, it's hard to see it as a (locative?) predicate. I fully agree that from a syntactic perspective there is a lot of similarity to cases with "here" in the same position, but that "emptiness" is a lot less straightforward there. Compare:

  * There is a book there (the initial there is clearly meaningless, allowing another there)
  * There is a book here (even allows the seemingly contradictory "here")

But with "here" these are quite odd if we add the other one:

  * Here is a book
  * ?Here is a book here
  * ?Here is a book there

Again, not saying it can never happen, but "there" has gone one step further in being a totally empty expletive which does not saturate the locative predicate slot. The effects around interrogation definitely suggest that "here it is" is a construction in the CxG sense IMO, but don't necessarily mean that it's identical to there/EX, or that it should be headed by "is" as UD analyzes things.

**Comment by nschneid** [comment]
I think I agree with you that "here" can't be as semantically vacuous as "there". But if I am showing somebody a book, "Here is a good example in the appendix" sounds perfectly fine as an expression of location (and possibly existence). "Here" is presumably highlighting a pointing-out speech act rather than describing a location per se. I think that's a counterexample to the view that "here" saturates a location slot.

**Comment by amir-zeldes** [comment]
Oh yeah, I definitely agree the "here" construction can be a grammaticalized presentational construction and can have further locatives, but it's not quite the same one as expletive "there", and I think there's reason enough to analyze them differently (esp. in the interest of high agreement/consistency, and the presence of other fronted locatives postponing the subject in the mix)
