### ISSUE TITLE
Annotation of intervals - linking two PPs

### ISSUE THREAD

**Issue by MagaliDuran** [UniversalDependencies/docs#871]
How should we annotate the relationship between two prepositional phrases that are part of the same interval (one is the beginning and the other is the end of the interval)? Examples:

from January to December
from now until the end of the year
from Monday to Friday
from zero to ten
from A to Z
from the beginning of the year to the end

De Marneffe et all (2021) suggests conj to link both parts of a numerical range in Czech (example 50, p. 286). 

Is this extendable to English and other languages or is it specific to Czech?

**Comment by nschneid** [comment]
Good question. In English EWT it is [sometimes `nmod` headed by the first nominal](http://universal.grew.fr/?custom=627b0f57aef5a), but more often they are [treated as sister PPs](http://universal.grew.fr/?custom=627b103c22039). GUM is similar.

**Comment by dan-zeman** [comment]
> De Marneffe et all (2021) suggests conj to link both parts of a numerical range in Czech (example 50, p. 286).
> 
> Is this extendable to English and other languages or is it specific to Czech?

That example can be extended to other (some, not all) languages. But it is different from your examples here. The Czech word _až_ is a coordinating conjunction, not a preposition, so it is not a _from-to_ example, although its English translation would have to use the preposition _to_.

For two prepositional phrases I lean towards treating them as siblings, that is, separate oblique modifiers of the predicate:

_Storms can be expected from November to February._
`obl(expected, November)`
`obl(expected, February)`

Treating one as `nmod` of the other would be wrong because _to February_ does not modify _November_ in any sense (and either of them can be omitted, and there could be two _to_ modifiers, one of them rendered with different preposition in other languages, etc.)

However, things get a bit rough when only the second nominal has a preposition in English _(Storms can be expected November to February)._ You could still say they are two sister obliques, but the first one does not have a preposition and it could not occur alone this way _(*Storms can be expected November.)_ I still believe that _February_ does not modify _November_ and should not be its `nmod` here but I can imagine that people do this because they don't see a better solution. I would be tempted to say that in these constructions, English _to_ is no longer a preposition and it has become something like a coordinating conjunction. Then we could treat _November to February_ as coordination, i.e., `conj(November, February)`.

**Comment by gossebouma** [comment]
Note, however, that in verb second languages, such as Dutch, the 'from ... to ...' part can precede the finite verb, which is a test for constituency. So that suggests they are a single constituent:

Van 1 januari 1950 tot 1 januari 1982 was ik huisarts .    (From jan 1 1950 until jan 1 1982 was I GP)

If treating the second PP as nmod of the first noun is to be avoided, than the conj solution seems more appropriate than the 2 independent obl's solution.

**Comment by amir-zeldes** [comment]
I'm uncomfortable with the conj solution in this construction, it doesn't really exhibit coordination properties like plural agreement:

  * May until June is/*are a long time

I also agree with @dan-zeman that sister obls to the verb is the optimal solution in situations like:

  * The storms are expected from November/obl until December/obl

since both of these modify when the storms are expected: 1. expected from November and 2. expected until December. We can also specify only one of those, and it would mean the same constraint: after November (if 1. is specified), until December (if 2. is specified). The fact that we can specify only "until December" also makes a conj analysis suspicious:

  * The storms are expected until/*and December

Regarding situations in which there is no verb to attach to, I also agree we have to attach time2 to time1, but I think the correct deprel is still `obl`, not `nmod`:

  * When? From November until December/obl

If it were `nmod`, I would understand that "November until December" is a nominal constituent, taking the case modifier "from", but actually, "from" only applies to November. In other words, I think "December" is the modifier of something like an unexpressed predicate, so by promotion it replaces that predicate and we should still use the `obl` deprel, not `nmod`.

**Comment by dan-zeman** [comment]
> coordination properties like plural agreement

I doubt that this is a "coordination property". It may hold in some languages for some coordinating conjunctions, such as _and_, but would it apply to other coordinating conjunctions, such as English _or_ or _but_?

**Comment by MagaliDuran** [comment]
In Portuguese none of these PPs ("de" X "a" Y) can occur alone. Some
synonymous prepositions that mark the beginning and the end of the range
allow the PP to occur alone: "desde" (from), "até" (to),. But this is not
the case for the prepositions "de/a" and "de/para". Therefore, the solution
of two separate obliques does not seem adequate to me either.

**Comment by nschneid** [comment]
@amir-zeldes The example was

- Storms can be expected November to February

"Until" is different I think. It would be more marginal to use "until" there without "from".

I think that "to" is somewhere in the gray area between coordinating conjunction and preposition. Semantically we have a range or juxtaposition of two values, neither of which is modifying the other. I have argued in other issues that maybe we should consider the hyphen ("1918-1973", "a 3-0 score") and "vs." as CCONJ.

In a recent discussion about ["plus" vs. "minus"](https://twitter.com/brettrey3/status/1519854560466153474), Brett Reynolds pointed out that core coordinating conjunctions cannot be preceded by "just"/"only". I think this is in common with "to" here:

- ??Storms can be expected November only to February

As distinct from "to" in the from...to correlative construction:

- Storms can be expected from November only to/until February

Also, it is easy to form a compound modifier with "November to February"—this really looks like a constituent, not two separate modifiers of the head noun:

- the November to February storm season
- *the to February storm season
- *the from November to February storm season

**Comment by nschneid** [comment]
In terms of correlative from...to in English, I think it would not be wrong to conclude that there's a special construction: the juxtaposition of a source-PP followed by a goal-PP being used to convey a range. Perhaps motivated by iconicity: if it is a temporal range, earlier things are said in the sentence before later things (I wonder if there are languages where the endpoint of a range conventionally occurs first?).

If it is important to convey this construction in UD, it seems to me like a headless combination of PPs, so I think connecting the nominals with `flat` might be most appropriate. For example:

- We worked from 8am to 10pm.  
obl(worked, 8am), flat(8am, 10pm), case(8am, from), case(10pm, to)

That said, we clearly have the range construction piggybacking off of two standard PPs (that get reanalyzed as a single constituent). Either of them can be omitted or modified with "only". It just would be odd to invert the order:

- ??We worked to 10pm from 8am.

UD largely avoids encoding ordering constraints in the structure anyway. So I guess not much lost structurally in analyzing those PPs independently, i.e.

- We worked from 8am to 10pm.  
obl(worked, 8am), obl(worked, 10pm)

And the advantage is that we don't have to worry about deciding exactly what counts as an instance of this construction when there's ambiguity (does it also apply to from...to combinations expressing motion, change of state, etc.).

If the range construction is more idiosyncratic in other languages, and it is not leveraging coordination, then perhaps the flat analysis should be used.

**Comment by MagaliDuran** [comment]
I believe that flat is not a good option, because it would "sacrifice" the whole syntax of these ranges, which may be more complex than what we are exemplifying. For example:

6 o'clock the day before to 6 o'clock the day after
18 to 25 years old 
800 to 900 calories
from 80 cm to 2 m

conj sounds better to me, even though we have prepositions and not conjunctions.

**Comment by nschneid** [comment]
TBC I was just suggesting `flat` might be an option if there are 2 PPs. If there's no "from" ("18 to 25 years old"), I think "to" might actually be analyzed as CCONJ.

**Comment by amir-zeldes** [comment]
> "Until" is different I think. It would be more marginal to use "until" there without "from".

Are you saying that the following two sentences should have different trees?

  * The storms are expected from November until December
  * The storms are expected from November to December

**Comment by nschneid** [comment]
No. I was referring to the construction without "from".

**Comment by amir-zeldes** [comment]
So these two are definitely obl + obl from the verb, right?

And what about these two, do they have the same tree?

  * The storms are expected November until December
  * The storms are expected November to December

**Comment by MagaliDuran** [comment]
In Portuguese we have always 2 PPs in these cases (I have only presented
the translations). Even though, they can not occur isolated as independent
obl.

Em qui, 12 de mai de 2022 12:15, Nathan Schneider ***@***.***>
escreveu:

**Comment by nschneid** [comment]
> So these two are definitely obl + obl from the verb, right?

I could live with flat for these but I think obl + obl is probably more practical.

> And what about these two, do they have the same tree?
> 
>   * The storms are expected November until December
>   * The storms are expected November to December

"Until" sounds odd to me here. Do people say that?

**Comment by amir-zeldes** [comment]
It's not hard to find examples with "until" but without "from", here are some:

  * If you visit Oktoberfest in Munich ( **middle of September until beginning of October** )
  * Both of these Rhytisma species form black spots on maple leaves late in the season ( **September and October until leaf fall** is a good time to observe tar spot in the northern latitudes ) .
  * Campsite Date : **29th June until 1st July 2012** ( weekend ) Units : Tents , caravans , ...

I think the problem is it's a slippery slope. I agree "from+to" is the most common, but I think in the wild you will get all sorts of pairs, and I don't think they stop being prepositions just because a range is being expressed (at least I think linguists searching for the preposition 'to' would expect to find these).

**Comment by nschneid** [comment]
Any examples outside of parentheticals/fragments? Maybe in that context people find the preposition unnecessary. (There could also be dialect variation.)

**Comment by amir-zeldes** [comment]
Sure, for example:

  * This really leaves October until December as the best time for a visit 

Although I don't think it really matters, since we need to be able to annotate parentheticals as well.

**Comment by nschneid** [comment]
Twitter has spoken: https://twitter.com/complingy/status/1524851954400346119

**Comment by amir-zeldes** [comment]
OK, good to know I'm in the majority, although I'm not a fan of asking for grammaticality judgments like this - often just by being asked, people get suspicious and claim they would never say such things, while if we look in a corpus, many people do, and perhaps the same people would not notice it if you gave them a 100 sentence text and asked them to flag ungrammatical sentences. There is also a substantial bias in the type of people who volunteer to answer these surveys (often people with Linguistics education), which, especially if they are trained linguists, leads to answers that are [quantitatively very different](https://www.degruyter.com/document/doi/10.1515/tlir.2010.001/html?lang=en) from randomly selected test subjects.

**Comment by msklvsk** [comment]
We invented [`flat:range`](https://universaldependencies.org/uk/dep/flat-range.html) for this. Fits perfectly.

`obl`s don’t work when e.g. the range is an `obj` and you can only have one `obj`.
