### ISSUE TITLE
Flexibility of numeric expression tokenization across treebanks?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#885]
In adding numeric features we have discovered inconsistencies of tokenization involving numeric expressions:

- The percent sign in "10%" is split in some corpora but not others (UniversalDependencies/UD_English-EWT#337)
- Fractions with "/" are tokenized differently even within Penn English treebanks: separated in EWT (`1 / 2`) but not in most parts of OntoNotes (`1/2`) (UniversalDependencies/UD_English-EWT#337)
- Fully numeric dates like "9/11/2001" are split often but not uniformly (https://github.com/UniversalDependencies/UD_English-EWT/pull/342#issuecomment-1194111122)

This has ramifications for, e.g., the meaning of `NumType=Frac` vs. `NumType=Card` (#884). Right now the [guidelines](https://universaldependencies.org/en/feat/NumType.html#frac-fractional-numbers) mention that the "/" will be tokenized in fractions and probably assume (without mentioning) that "%" will be tokenized in percentages.

Decisions about how to define `NumType=Frac` and so on should take place in other threads, but I want to ask the more general question of how flexible UD should be about tokenization for things like numeric expressions, which feature orthographic conventions more stable across languages than typical linguistic information, but where tokenization conventions in source treebanks differ.

Should UD specify some numeric tokenization rules to favor uniformity?

Or should UD cope with alternate tokenizations and define, for example, that `NumType=Frac` may apply either to a full fraction, or the denominator of a tokenized fraction, or a percentage if the "%" symbol is included? (And of course additional deprels will be needed for the tokenized ones, and queries/downstream uses of multiple treebanks will have to cope with the discrepancies.)

**Comment by dan-zeman** [comment]
So far UD has been quite flexible about tokenization: some recommendations or common practices may have been mentioned, but no real rules as far as I remember. The reason is that large UD treebanks were converted from pre-UD frameworks (some of which are further maintained alongside UD), inherited their tokenization, and keeping the tokenization compatible with existing tokenizers and/or non-UD versions of the corpora is considered practical and important.

That said, I would actually like to see a more uniform approach to phenomena that exist in most languages and where the differences are technical rather than linguistic (dates, times, percent signs etc.) There could at least be a set of guidelines that would be understood as strong recommendations but would not necessarily be enforced by the validator.

But it won't be an easy endeavor. There are many such phenomena, and I'm sure we'll encounter peculiar details in some languages for each of them. For example, just focusing on the _%_ symbol as it is (or should be, officially) used in Czech: When you say _three percent of students_, you write a space between _3_ and _%_, so there is no tokenization dilemma: _3 % studentů_. But you could also omit the space and then you are actually encoding an adjective: _3% menšina_ = _tříprocentní menšina_ = _a three percent minority_. I don't think that _3%_ should be split to two tokens in Czech in this case, although I do think that _3%_ should be two tokens in English when it corresponds to the _3 %_ case in Czech :-)

**Comment by amir-zeldes** [comment]
I agree with @dan-zeman - it's probably not practical to impose uniform tokenization at this point (i.e. at the validation level), but I also think it would be nice to have recommendations for people building new TBs, or if they are in a position to go either way on some decision, or if they are revising tokenization for a corpus anyway.

**Comment by nschneid** [comment]
@dan-zeman Would you advocate `NumType=Frac` for "3%" where the percent sign is included in the token, but something else where they are split?

**Comment by dan-zeman** [comment]
> @dan-zeman Would you advocate `NumType=Frac` for "3%" where the percent sign is included in the token, but something else where they are split?

Yeah, I guess I would. (Also I think I'm responsible for the current usage of `NumType=Frac` for _3%_ in Spanish and Catalan – if I recall it correctly, they had a specific tag in the original annotation of AnCora, and I wanted to convert it to something different than normal numbers.)

**Comment by nschneid** [comment]
@manning also agrees that it would be good to whip up some recommendations. (But enforcing anything as mandatory is not on the table.)

**Comment by dan-zeman** [comment]
> > @dan-zeman Would you advocate `NumType=Frac` for "3%" where the percent sign is included in the token, but something else where they are split?
> 
> Yeah, I guess I would.

Seeing https://github.com/UniversalDependencies/UD_English-EWT/issues/337#issuecomment-1198665931, it now occurs to me that you may have been asking (also) about the Czech adjective, not just about languages where it meens "three percent" (quantity) and is written as one token. For the Czech adjective, I'm not sure whether I would use a `NumType` at all. This is not because it is `ADJ` – we do have `ADJ`s with `NumType`, for ordinals. But I would not use any `NumType` for the equivalent spelled-out adjective _tříprocentní_, like I would not use it for other adjectival compounds containing numbers (_tříletý_ "three-year", _třípatrový_ "three(four)-storey" etc.).

**Comment by nschneid** [comment]
OK, then as I understand it `NumType` is meant to reflect the morphological inflection of a number, full stop. If a number is part of an untokenized compound, it doesn't apply (and tokenization of compounds is not meant to be addressed here; we defer to individual languages). If a number represents a non-integer such as 3.14, but doesn't bear (and wouldn't be pronounced with) a special inflection indicating fractionality, it can be considered `NumType=Card`. (Mathematically the name "cardinal" is confusing, but I suppose it can be justified because pronouncing "3.14" involves reading a series of digits in their cardinal number form.)

I'm persuaded by @amir-zeldes that fractions written as the ratio of two integers and pronounced with a fraction construction ("2/3" pronounced "two thirds") would be better as a single `NumType=Frac` token. This is morphological in that the denominator is read with a special inflection, at least in English. By contrast, the division operator as such (necessarily pronounced on its own—"over" or "divided by" or "(out) of" or "in", as in "x/y" or "8.5/10") would be tokenized. There could be some ambiguity between these, e.g. "2/3" as part of a larger mathematical formula, but heuristics should work pretty well.

When a fraction is spelled out, only the morphologically inflected words are `NumType=Frac`: thus in "three fourths" or "three quarters", "three" is `NumType=Card`.

It seems like the guideline for "%" would have to be something like "if it would be spelled as a separate word, then treat it as a separate token". As a separate token it would not bear `NumType=Frac`, and would not trigger `NumType=Frac` on the number unless the number would bear a fractional inflection.

I suppose fully numeric dates like "9/11/2011" should remain single tokens with `NumType=Card` assuming they could be read with their components as cardinal numbers ("nine - eleven - two thousand eleven").

What are some other questions that might arise in the tokenization of numbers?

**Comment by nschneid** [comment]
Is there a language where ordinals are expressed analytically?

**Comment by amir-zeldes** [comment]
Japanese and Chinese, arguably, depending on how you tokenize dai/di.

**Comment by nschneid** [comment]
Supposing "3 dai" was tokenized separately, are we OK with not marking that as ordinal, because the ordinal meaning is expressed analytically?

**Comment by dan-zeman** [comment]
In Chinese and Cantonese _di_+number is one token. Chinese HK (http://hdl.handle.net/11346/PMLTQ-AMTX) and Cantonese HK (http://hdl.handle.net/11346/PMLTQ-KHMQ) tag it `ADJ` and attach it as `amod`. They don't seem to use the `NumType` feature though (in general, features are used very sparsely in these languages). Chinese GSDSimp uses the same tokenization (http://hdl.handle.net/11346/PMLTQ-WRPF) but tags it as `NUM` and attaches it as `nummod`, which is probably wrong. Japanese GSD has 第 and the number as two separate tokens, typically both involved in a larger `compound` sequence (http://hdl.handle.net/11346/PMLTQ-UAQV); 第 is tagged `NOUN`. Japanese GSDLUW (= long unit word) (http://hdl.handle.net/11346/PMLTQ-W4J4) has tokens that comprise 第, the number, and apparently also the noun whose rank is being specified: 第1作 _dai 1 saku_, according to Google Translate, shall mean "1st work". Classical Chinese (http://hdl.handle.net/11346/PMLTQ-QCQ7) has 第 as a separate token, tagged `NOUN`, and the number attached to it as `nummod`.

**Comment by dan-zeman** [comment]
> Supposing "3 dai" was tokenized separately, are we OK with not marking that as ordinal, because the ordinal meaning is expressed analytically?

I don't object to that but note that expressing something analytically does not exclude using the corresponding features. For example, `Definite=Def` is used in Bulgarian and Swedish on nouns to say that it is the definite form of the noun, but in English it is used with the definite article _the_, which provides the definiteness to the noun analytically.

Nevertheless, neither Japanese GSD nor Classical Chinese (the two corpora from the above post that do tokenize 第3 separately) use `NumType=Ord` for any of the parts. (Note that Classical Chinese does use `NumType=Ord`, but for other words than these; I cannot comment on why it's so.)

**Comment by nschneid** [comment]
> expressing something analytically does not exclude using the corresponding features

In that case why not say that in "3 % of the revenues", "%" contributes `NumType=Frac`? This usage of "%" is specific to, or at least canonically associated with, fractional numbers, right?

**Comment by dan-zeman** [comment]
> > expressing something analytically does not exclude using the corresponding features
> 
> In that case why not say that in "3 % of the revenues", "%" contributes `NumType=Frac`? This usage of "%" is specific to, or at least canonically associated with, fractional numbers, right?

You could do it but I don't feel the urge to make it a UD-wide recommendation. It looks like a semantic tag; I wouldn't say that _%_ is a grammatical function word.

**Comment by amir-zeldes** [comment]
To add to the confusion in Japanese, the alternative ordinals like "ni-ban (me)" and "futatsu me" are also not consistent in GSD - usually "ichiban" 'first' is tagged ADV as a single token, but I also find the number tokenized apart as NUM with nummod...
