### ISSUE TITLE
Full list of universal features?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#895]
There are a number of features listed in https://github.com/UniversalDependencies/docs/tree/pages-source/_u-feat than are  not documented at https://universaldependencies.org/u/feat/index.html, including AdpType, AdvType, ConjType, NameType, NounType, PunctSide, PunctType, VerbType. Is this on purpose?

**Comment by dan-zeman** [comment]
Yes, it is on purpose. These are not universal features. They were never listed as such, neither in v1 nor in v2 guidelines. Until recently, their documentation was also not present in this folder and it only existed in an old documentation of Interset. However, some treebanks use them as language-specific (or treebank-specific) additions, although most of them are actually not very language-specific. Now that the validator requires each feature and value to be documented somewhere, it was easier to make the existing documentation globally visible to the validator (despite the fact that the features are not first-class citizens) rather than chasing data providers in individual languages and forcing them to create a language-specific version of the doc files.

From the infrastructure's point of view, we now have the following classes of features in a given language (these *can* be enabled in the language, but if they are not enabled, the validator will still flag them as errors):

* Universal features with (only) universal/global documentation
* Universal features with language-specific documentation (overrrides the global one)
* Non-universal features with globally available documentation
* Language-specific features with local documentation

**Comment by nschneid** [comment]
OK. Maybe it is worth mentioning this somewhere in the docs.

**Comment by dan-zeman** [comment]
It was already briefly mentioned [here](https://universaldependencies.org/contributing_language_specific.html#language-specific-features). [Now](https://github.com/UniversalDependencies/docs/commit/7c87f0a3a284d47b30bb65b5cf165c5d8245aa4f) also mentioned [on the feature index page](https://universaldependencies.org/u/feat/index.html).
