### ISSUE TITLE
MISC attributes

### ISSUE THREAD

**Issue by Stormur** [UniversalDependencies/docs#896]
Maybe I am missing it, but is there a way to submit documentation for miscellaneous attributes? 

The validator is not complaining and there is only a [page](https://universaldependencies.org/misc.html) with a format different than for features and relations.

**Comment by dan-zeman** [comment]
I am not sure if it is a complaint that "the validator is not complaining" :-) The MISC column is mostly for annotations that are beyond the UD guidelines, so it is not regulated by the UD guidelines, with a few exceptions. The page you link to has been created because it is desirable that same things are annotated the same way even in MISC, but it still does not mean that all these attributes are part of universal, or language-specific guidelines (some of them are treebank-specific). If you have new attributes to document, you can submit a pull request for that page, or edit it directly and add your attributes there.

**Comment by Stormur** [comment]
Hehe, for sure it is not a complaint (I'm always happy to escape the tyrannic requests of the validator) :-)

It is more a quest for transparency: having introduced a totally language-specific new `MISC` feature, I would like to have it documented for everybody. OK, after the new release I will send a pull request!
