### ISSUE TITLE
Relation between Quoter and Quote

### ISSUE THREAD

**Issue by caffeine96** [UniversalDependencies/docs#904]
We have a minor question about dialog-style quotes where the quoter is followed by the quote. For instance,
`" I watched it with him . " : Mark`

#667 and several other examples point that there should be `parataxis` rel between the quoter phrase and the quote. However, these explicitly have a verb present in the quoter phrase (e.g.: Mark **said**). 

We just want to confirm if the relation still holds if the verb is absent in the quoter phrase as in the example stated above (i.e. `root(Mark)` & `parataxis(Mark, watched)`). We think of it as an instance of clausal ellipsis.

**Comment by dan-zeman** [comment]
> #667 and several other examples point that there should be `parataxis` rel between the quoter phrase and the quote. However, these explicitly have a verb present in the quoter phrase (e.g.: Mark **said**).

Note that the rules for reported speech were recently changed, so rather than `parataxis`, now it would probably be `ccomp` going from the speech verb to the head of the quoted phrase. See [here](https://universaldependencies.org/changes.html#reported-speech).

Due to lack of better solutions, I would be tempted to do the same in your case, that is, treat it as ellipsis of the speech verb.

**Comment by caffeine96** [comment]
Got it ! Thanks for the pointer!

**Comment by nschneid** [comment]
I don't see this as ellipsis. If I had to put a pronoun in place of the name I would use accusative case, suggesting it is not a subject. Same if the speaker is written before the quote, as in a dialogue:

    HER: blah blah
    HIM: blah blah

Seems like parataxis to me.

**Comment by dan-zeman** [comment]
> I don't see this as ellipsis. If I had to put a pronoun in place of the name I would use accusative case, suggesting it is not a subject. Same if the speaker is written before the quote, as in a dialogue:
> 
> ```
> HER: blah blah
> HIM: blah blah
> ```
> 
> Seems like parataxis to me.

Interesting. This argument is specific to English, while the question is universal and similar stuff may occur in any language, where similar evidence may not be available.

I'm not willing to fight against `parataxis`, though. Being a "garbage-can" type of relation, there are few if any bad consequences of using it, so if it works better in English, perhaps it can be a reasonable default for other languages, too.

**Comment by caffeine96** [comment]
> I don't see this as ellipsis. If I had to put a pronoun in place of the name I would use accusative case, suggesting it is not a subject. Same if the speaker is written before the quote, as in a dialogue:
> 
> ```
> HER: blah blah
> HIM: blah blah
> ```
> 
> Seems like parataxis to me.

This is interesting. Using pronouns to denote quoters is quite rare in our language (Gujarati), and possibly in other cognate languages (like Hindi). If at all they are used, the most likely one would be ergative. 
We thought a bit more about the ellipsis aspect. In contrast with our original comment, if it were in fact an ellipsis, the quoter phrase must have an ergative inflection. However, we usually see the nominative case being used. 

Keeping these two points in mind, which one do you feel might be more suited `parataxis` or `ccomp`?

**Comment by sylvainkahane** [comment]
In French, we won't use the accusative form of the pronoun but the so-called strong form used in isolation:
```
Marie la/le voit 'Marie sees her/him'
Qui vient? Elle ou lui? 'Who comes? Her or him? 

Elle : blabla
Lui : blabla
```
@nschneid The two forms are identical in English. Are you sure that it is the accusative form and not the strong form that is used?

**Comment by nschneid** [comment]
Perhaps "strong form" is an apt description (though in terms of the English pronoun paradigm it is indistinguishable from accusative/oblique case). My point was that it is not the _nominative_, which would be expected if it were a subject.

**Comment by Stormur** [comment]
Well, this accusative/strong form is also used in other contexts where a nominative would be prescriptively expected:

_It wasn't **me**_

So it seems that in certain circumstances a more emphatic form, using the "accusative", can substitute a nominative, i.e. more basic form. And with time, as perhaps in French and surely in Italian, where _lui_/_lei_ 'he/she' (originally an oblique form) has _de facto_ replaced _egli_/_ella_ 'he/she' (both from Latin _ille_ 'that (one)') and also _esso_/_essa_ 'it (m./f.)' (from _ipsum_/_ipsam_ 'self, the same (one)'), this strong form can become the main one, at least in some contexts. And this seems to be the case for introducing quotes in English (an isolated, probably weak position), so I personally do not see any problem in considering such strong forms subjects of an ellipsis. So absolutely `ccomp` here for me, in parallel with all other similar occurrences in other languages.

**Comment by amir-zeldes** [comment]
I don't think it's ccomp in English - notice also the lack of possibility to use "that", indicating it's not a subordinate CP:

  * Kim: "the weather is nice today"
  * * Kim: "that the weather is nice today"

The proposal to forgo `parataxis` in favor of `ccomp` for direct speech with a verb (i.e. 'Kim said "I'm hungry"') was motivated by three things:

1. Preserve the argument structure of the verb (otherwise it looks like "said" is intransitive in such sentences)
2. Uniform treatment of indirect and direct speech in spoken data, where quotation marks can't be observed (for a spoken 'Kim said the weather is nice today' we have no idead if it's "direct" or "indirect")
3. Remove the guideline about inverted speech, which makes little sense in languages where the speech verb can canonically follow the quote (so '"I'm hungry," said Kim' is maybe marked literary style in English, but in many languages it is perfectly normal)

None of these motivations apply to the 'name + colon' situation. Note that there are a lot of superficially similar construction without implied speech that behave similarly, where I think we also don't want ccomp:

  * Image: United Press
  * Oxford University Press: Oxford

Of course we could treat these as "United Press/nsubj made this image/obj" and "OUP/nsubj printed this in Oxford/obl", but I think this would be going too far.
