### ISSUE TITLE
To be a relative clause: relational or categorial property?

### ISSUE THREAD

**Issue by sylvainkahane** [UniversalDependencies/docs#909]
Relatives are currently annotated by a relational label: `acl:relcl`. It is quite problematic because to be a relative is not relational property. The consequence is that some relative clauses are well annotated with `acl:relcl`, but some are not annotated weirdly annotated. I have identified three problems.

1) Relatives clauses in coordination
This is quite common in several languages and these relative clause are `conj`:
http://universal.grew.fr/?custom=6378bc7eb0b9e
In French we have a lot of such cases, where, on top of that, the first conjunct is not a relative clause, so there is absolutely no `acl:relcl` label:
http://universal.grew.fr/?custom=6378bc7eb0b9e

2) Headless relative clauses
Here the `acl:relcl` is used between the relative pronoun and the clause. 
http://universal.grew.fr/?custom=6378bdb5aeb6a
But the dependent clause, annotated as `acl:relcl` is neither a true adjectival clause, nor a relative clause. It is the whole phrase including the relative pronoun which is a relative clause.

3) Other functions of relative clauses
In some languages relative clauses are used in other constructions than adjectival positions.
In French, we have the so-called predicative relative clauses:
_Je vois Marie qui approche_ ‘I see Mary approaching’, lit. I see Mary who/that approaches (no example in our corpora)
And relatives are used in cleft sentences, where we use the relation `adv:cleft`:
_C’est Marie qui parle_ ‘It’s Mary speaking’, lit. It’s Mary who/that speaks
http://universal.grew.fr/?custom=6378be8bdcfea
Or see this Italian corpus, which has a lot of relative clauses which are `root`:
http://universal.grew.fr/?custom=6378be8bdcfea

In consequence when we want to study the relative clauses in most corpus, we have quite complex requests to do to catch all the relative clauses and to avoid some other constructions. It would be much better to have a feature such as `RelativeClause=Yes` on the head of the relative clause (which would be the relative pronoun in headless relative clauses).
(By the way, a feature InterrogativeClause=Yes would be nice too.)

**Comment by nschneid** [comment]
I think you've repeated URLs by accident. Curious to see the French coordination cases.

**Comment by sylvainkahane** [comment]
Sorry. The link to the Italain corpus is:
http://universal.grew.fr/?custom=6378f479ace2e

**Comment by nschneid** [comment]
Some general comments:

- We recently overhauled the [guidelines for English relative clauses](https://universaldependencies.org/en/dep/acl-relcl.html). One change was adding `advcl:relcl` for use in adverbial relatives as well as *it*-clefts.
- I agree with you that relative status is a property of clauses that has been grafted onto deprels because UD doesn't have any other established convention for describing the properties of clauses as a whole. It would be nice to mark other kinds of clauses (interrogative, exclamative...) as well. I have thought about how features for English clause types [might be defined](https://github.com/nert-nlp/cgel/issues/10#issuecomment-1153191934). I think it is worth having a discussion about what the UD theory should say about clauses as constituents. Another place this has come up is with [multiple subjects](https://universaldependencies.org/changes.html#multiple-subjects) due to an entire clause serving as copular predicate.
- Because of how UD treats coordination, the problem of the true function being "hidden" for non-initial conjuncts where it might differ from that of the first conjunct is inevitable. (It comes up with other kinds of dependents as well, e.g. *ethnic/ADJ and gender/NOUN diversity*.) The party line is that the place to resolve this is in enhanced dependencies.

**Comment by bulbulistan** [comment]
I second @sylvainkahane's motion, doubly so when it comes to `conj`. One major problem I have with `conj` is that while the rest of UD maintains a strict distinction between clauses and non-clauses, `conj` does not, which makes it not only, well, a sore thumb, but also nigh useless. And so for example when one wants to study all clauses, one has to do tons of query black magic to do that, especially when one deals with copulas and alike. Whether this should be resolved by means of features or by means of subtypes, that we can discuss, but it should be resolved in the basic dependencies level.

**Comment by dan-zeman** [comment]
I just note that it should not be a feature in the FEATS column because it does not pertain to the word form. If a data provider wants to annotate clause types at their heads (and wants to avoid relation subtypes), it should be an attribute in MISC.

**Comment by Stormur** [comment]
This is a very complex issue which was causing our annotating team, too, some head-scratching lately.
 
>     1. Relatives clauses in coordination
>        This is quite common in several languages and these relative clause are `conj`:
>        http://universal.grew.fr/?custom=6378bc7eb0b9e
>        In French we have a lot of such cases, where, on top of that, the first conjunct is not a relative clause, so there is absolutely no `acl:relcl` label:
>        http://universal.grew.fr/?custom=6378bc7eb0b9e

 About co-ordinations, I also agree with the problems just discussed: you have to set up non-trivial queries to retrieve and include the "true heads" of co-ordinated element and to retrieve their dependencies. By the way, this is all very closely related to ellipsis, and I think this is the bigger problem... in general, I wonder if we might consider more than just one sybtype to ease cases such as these, to signal both syntactic as well as semantic phenomena (as it is common now).  

> It would be much better to have a feature such as `RelativeClause=Yes` on the head of the relative clause (which would be the relative pronoun in headless relative clauses). (By the way, a feature InterrogativeClause=Yes would be nice too.)

I would be in favour of this. But the relation of course always goes to the predicate, also in headless/free relatives, not on the "relative" element, which by the way ned not always be present.  


>     2. Headless relative clauses
>        Here the `acl:relcl` is used between the relative pronoun and the clause.
>        http://universal.grew.fr/?custom=6378bdb5aeb6a
>        But the dependent clause, annotated as `acl:relcl` is neither a true adjectival clause, nor a relative clause. It is the whole phrase including the relative pronoun which is a relative clause.

Interestingly, in Latin treebanks we just changed this kind of representation to a more common one. For this, we introduced a transversal `relcl` subtype ([`advcl:relcl`](https://universaldependencies.org/la/dep/advcl-relcl.html), [`ccomp:relcl`](https://universaldependencies.org/la/dep/ccomp-relcl), [`csubj:relcl`](https://universaldependencies.org/la/dep/csubj-relcl), [`xcomp:relcl`](https://universaldependencies.org/la/dep/xcomp-relcl) ). I think UD should give a common standard for this, even if I know that in literature both interpretations are present. 

>     3. Other functions of relative clauses
>        In some languages relative clauses are used in other constructions than adjectival positions.
>        In French, we have the so-called predicative relative clauses:
>        _Je vois Marie qui approche_ ‘I see Mary approaching’, lit. I see Mary who/that approaches (no example in our corpora)
>        And relatives are used in cleft sentences, where we use the relation `adv:cleft`:
>        _C’est Marie qui parle_ ‘It’s Mary speaking’, lit. It’s Mary who/that speaks
>        http://universal.grew.fr/?custom=6378be8bdcfea
>        Or see this Italian corpus, which has a lot of relative clauses which are `root`:
>        http://universal.grew.fr/?custom=6378be8bdcfea

I think that another very relevant ppint is that **not all clauses which contain a so-called relative element can be said to be relative clauses** (and conversely, relative clauses need not have a relative or anaphoric element inside). This rather seem one generalised way of subordinating clauses and/or, as in the Italian examples, to create textual coherence (called the "relative nexus" in Latin grammars, which devote quite some space to the use of relative pronouns). These two examples are in my opinion an `xcomp` in the first case and, more in general, a clausal subject in clefts. The relative is there with an anaphoric function, but the clause is not a relative clause in the sense of an adnominal expansion.

**Comment by Stormur** [comment]
> * We recently overhauled the [guidelines for English relative clauses](https://universaldependencies.org/en/dep/acl-relcl.html). One change was adding `advcl:relcl` for use in adverbial relatives as well as _it_-clefts.

There remains an ambiguity in the use of `advcl:relcl`, because we have both seemingly relative clauses referring to entire preceding clauses, but also headless relative clauses introduced by elements such as _when_, _where_, and so on. I suspect they are rather different.

**Comment by nschneid** [comment]
In English, following CGEL, we analyze free relative constructions not as clauses themselves, but as **nominals** containing a pronoun ("**whoever** lives here is...") or adverb ("**how** I work is...") modified by a relative clause.

Yes, it means that `acl:relcl` and `advcl:relcl` apply to both standard and free relatives. It has consequences for edeprels (in a standard relative, e.g. *the question I asked*, we would have an enhanced relation E:obj(asked, question), but that seems awkward for a free relative like *what I asked was...*).

Treating them as nominals means we don't need to subtype subjects/complement relations as `:relcl`.

**Comment by amir-zeldes** [comment]
I agree with everyone above that basic dependencies are inadequate for dealing with 'unlike coordination', since the basic premise of using conj (if I'm conj, ask my parent what my actual function is) assumes that the coordinate structures are 'the same'. I think there are three levels of handling this, with solutions falling closest to one of them:

1. Do nothing special for 'unlike coordinations' - this is basic dependencies, and similarly for nested binary constituent analyses of these structures
2. Label the whole span in some special way - this is how PTB constituents handle it, using category labels like `UCP` (unlike-coordinate phrase). Using annotations like `RelativeClause=Yes` for either a token or a span is in this ballpark, because it indicates something special going on, but does not allow a full relational structure to be read.
3. Label each of the relations holding between the subordinate units and their superordinate governors - this is what edeps do

Ultimately I feel like level 2. solutions are a band-aid: maybe we can now find and count all relative clauses, but we can't have the full structure (what exactly is being relativized? What represents it in the subordinate clause?), and it doesn't resolve other 'unlikes', such as having a `compound` ->conj `amod` modifier structure. If you want to know all this, then I think edeps are pretty much already the correct solution. For example we can find amod ->conj compound like this using an ANNIS search:

  * [tok ->dep tok_func=‎"compound‎" ->dep tok_func=‎"conj‎" & #1 ->edep[func=‎"amod‎"] #3](https://gucorpling.org/annis/#_q=dG9rIC0-ZGVwIHRva19mdW5jPSJjb21wb3VuZCIgLT5kZXAgdG9rX2Z1bmM9ImNvbmoiICYgIzEgLT5lZGVwW2Z1bmM9ImFtb2QiXSAjMw&_c=R1VN&cl=5&cr=5&s=0&l=10&o=random)

And the reverse like this: (incidentally, I just learned now this is more than twice as common as the previous in English!)

  * [tok ->dep tok_func=‎"amod‎" ->dep tok_func=‎"conj‎" & #1 ->edep[func=‎"compound‎"] #3](https://gucorpling.org/annis/#_q=dG9rIC0-ZGVwIHRva19mdW5jPSJhbW9kIiAtPmRlcCB0b2tfZnVuYz0iY29uaiIgJiAjMSAtPmVkZXBbZnVuYz0iY29tcG91bmQiXSAjMw&_c=R1VN&cl=5&cr=5&s=0&l=10&o=random)

I admit the queries are not exactly simple, but what we are looking for here is not simple, so I think if you want to be able to search for these, you can't make it much simpler than saying "I want an amod with a conj dependent, which is an enhanced compound dependent of something else".

PS - I'm not objecting to also using further annotations of clauses on other layers, which we also do, but it seems to me that edeps already deliver a pretty comprehensive solution where they're available.

**Comment by Stormur** [comment]
> In English, following CGEL, we analyze free relative constructions not as clauses themselves, but as **nominals** containing a pronoun ("**whoever** lives here is...") or adverb ("**how** I work is...") modified by a relative clause.

Can you please send me the reference? I am genuinely interested in this topic, it was a recent point of contention in our group recently!

**Comment by nschneid** [comment]
[CGEL](https://en.wikipedia.org/wiki/The_Cambridge_Grammar_of_the_English_Language), ch. 12.

Nicely summarized in [this textbook](https://www.cambridge.org/highereducation/books/a-students-introduction-to-english-grammar/EB0ABC6005935012E5270C8470B2B740#overview), ch. 12.

Also comes up in [this paper](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/D0D583318480CCEB18536C891286D48E/S002222670700477Xa.pdf/) (Payne, Huddleston, Pullum 2007).

**Comment by sylvainkahane** [comment]
@amir-zeldes I agree that free relatives are nominals and that the wh-word is the head. But I prefer Tesnière's analysis considering that wh-words have a double syntactic position, both as relativizers/nominalizers and pronouns. It means that the wh-word is also part of the relative clause as a pronoun, where it fills a syntactic position. Of course, it is reasonable to have a simpler annotation with only one position for the wh-word and to keep only the head position for free relatives and the pronominal position for relatives with antecedents. 

But what is wrong from my point of view is to consider that the main verb of a free relative depends on the wh-word by an `acl:relcl` relation. If I take your two examples:
1) "whoever lives here is...": Can we really consider that "lives here" is a clause in English?
2) "how I work is...": If "how" is an adverb, is it reasonable to consider it can be modified by an **adjectival** clause?

In Tesnière's analysis, the wh-word in its head position works as subordinating conjunction and the verb is its complement. By the way it is an obligatory complement, which is also very problematic for the `acl` labelling:
```
How I work is very efficient.
*How is very efficient.
```

**Comment by nschneid** [comment]
The CGEL analysis has the "fusion of functions" approach which I think is similar to what you're saying about a "double syntactic position"—but UD basic dependencies have no way for a word to serve two functions, so we are forced to say the pronoun/adverb is just the head.

> 1. Can we really consider that "lives here" is a clause in English?

A clause from which "whoever" is extracted.

> * "how I work is...": If "how" is an adverb, is it reasonable to consider it can be modified by an **adjectival** clause?

That's why we use `advcl:relcl` for ADV-headed relatives.

UD (frustratingly) doesn't make a complement/adjunct distinction for clausal dependents except in clause structure, so an `acl(:relcl)` of a PRON and an `advcl(:relcl)` of an ADV can be complements.

**Comment by amir-zeldes** [comment]
> But I prefer Tesnière's analysis considering that wh-words have a double syntactic position, both as relativizers/nominalizers and pronouns

@sylvainkahane I agree with this as well, and perhaps it could be expressed using enhanced dependencies (though I believe it is currently not expressed in UD English edeps). We could have:

  * Do what you want

obj(do, what)
e:obj(want, what)

If @nschneid agrees, I could take a stab at adding this to our English enhancer.

**Comment by nschneid** [comment]
Yeah, actually, I may have misstated the issue with enhanced dependencies. Looking at EWT, I see e.g. "what follows is the text..." has 

| Basic  | Enhanced |
|-------|-----------|
| nsubj(text, what) | E:nsubj(text, what) |
| acl:relcl(what, follows) | E:acl:relcl(what, follows) |
|                                        | E:nsubj(follows, what) |

Where it gets tricky is with embedded copulas and prepositions.

- For "Please speak to whoever you are comfortable with", the basic deps would have case(whoever, to) and obl(comfortable, with) [stranded preposition]. Should edeprels have both E:case(whoever, to) and E:case(whoever, with)? And I suppose obl:to(speak, whoever), obl:with(comfortable, whoever)?
- For "I want to sample **whatever dish this is**", [we have to promote the copula to avoid a self-edge](https://universaldependencies.org/en/dep/acl-relcl.html#cyclic-cases). Is there a better way to treat this in edeps? Note that there can also be a stranded preposition ("whatever dish this is about").
