### ISSUE TITLE
Improved iobj guidelines

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#916]
The https://universaldependencies.org/u/dep/iobj.html guidelines give some general principles but can be improved:

- the term "indirect object" can have many different interpretations outside of UD, which should be highlighted
- more examples from different languages
- per agreement of the core group, amend the policy for a sole overt object, which is currently problematic (especially considering cases with an object+ccomp). (Previous discussion in UniversalDependencies/UD_English-EWT#256, UniversalDependencies/UD_English-EWT#55, some of #832, etc.) The final portion starting with

   > In general, if there is just one [obj](https://universaldependencies.org/u/dep/obj.html)ect, it should be labeled obj, regardless of the morphological case or semantic role. For example, in English, *teach* can take either the subject matter or the recipient as the only [obj](https://universaldependencies.org/u/dep/obj.html)ect, and in both cases it would be analyzed as the obj:

   needs to be rewritten with `iobj` allowed if an `obj` can be inserted or a complement clause is present.

**Comment by nschneid** [comment]
Draft for changes page: AMENDMENT

> ### Sole `iobj`
> 
> The restriction that [iobj]() can only be used if there is also an overt [obj]() in the same clause is hereby removed. 
It is preferable not to have a relation whose label depends on the presence or absence of a sister phrase 
when its interpretation remains the same (like *them* in *teach them* vs. *teach them reading* vs. *teach them to read*).
> See [iobj]() for examples (note that specific criteria for identifying indirect objects will vary by language).

**Comment by Stormur** [comment]
I do not agree on this "sole `iobj`" use, since there is apparently no way to distinguish syntactically this alleged `iobj` from an `obj`. It seems to me that the reason to use `iobj` here is still relying on the possible occurrence of another object, even if it is not expressed, and/or on purely semantical grounds (recipient vs. theme).

**Comment by amir-zeldes** [comment]
@Stormur the argument as formulated above is that we shouldn't appeal to the absence of another dependent to alter the label of the current dependent. In the same way that an extent modifier (in English, usually `obl:npmod` or `obl:tmod`) does not become an object when the regular object is dropped:

  * I read books/obj
  * I read books all day/obl:tmod
  * I read all day/obl:tmod

The ellipsis of 'books' in the last example does not make us change "all day" into an object. In the same way, eliding the direct object should not change the label of the remaining `iobj`:

  * I told Kim/iobj the story/obj
  * I told the story/obj
  * I told Kim/iobj

Ellipsis should not be cause for changing what is still the same dependent formally and functionally (there is no change in marking). 

Note also that in languages where indirect objects have distinct marking from direct objects, the marking does not change to match direct object marking when we elide the indirect object. In English of course there is no case marking or other kind of distinction, but the criterion for identifying iobj is still not semantic: it hinges on alternation behavior (the fact that we can say "give the book to Kim" with 'to'), and we recognize already in using passivization as a criterion that alternations can be a valid, purely syntactic criterion.

**Comment by nschneid** [comment]
To put it another way, in English we rely on alternation tests like passivization to establish a lot of the dependency relations. People have all sorts of interpretations of the term "indirect object" in general, and specifically for English, there are differences of opinion as to which tests should be used to diagnose different types of objects. We decided that the dative alternation is a reasonably intuitive test to distinguish sole `obj` from sole `iobj`, but we recognize not all syntactic frameworks will analyze ditransitives the same way (and many of the modern ones don't use the term "indirect object" at all for languages like English, so we should revisit the name `iobj` for UDv3).

**Comment by sylvainkahane** [comment]
It would be much better to accept that double object constructions exist in many languages, English included. The criteria to decide to annotate one of the two objects as `iobj` are too specific (such as the alternation with an oblique complement in English) and debatable (it is `iob` and not `obj` which is relativisable and passivisable in the double object construction of English).
It would be much more useful from the typological point of view to indicate which one is the theme and which one is the recipient. See Haspelmath 2011, On S, A, P, T, and R as comparative concepts for alignment typology, https://doi.org/10.1515/LITY.2011.035. Note that in some languages, it is R (and not T) that aligns with P.

**Comment by nschneid** [comment]
@sylvainkahane TBC, are you saying that instead of `obj` and `iobj`, we should have `obj:theme` and `obj:recip` for double object constructions? (I think that's worth considering for UDv3, but for now we are stuck with `iobj`.)

**Comment by amir-zeldes** [comment]
@sylvainkahane I personally am interested in semantic roles, and of course we can use subtypes to do whatever we want in principle, but my understanding is that UD avoids using semantic criteria for dependency relations, at least for the primary relations, so unless we reconsider that precept, I think that is probably not an option.

**Comment by sylvainkahane** [comment]
I suggest to abandon `iobj` and to use only `obj`, with two `obj` in double object constructions. If we think that we lack information and we want to distinguish the two `obj`, we can introduce a semantic feature, such as R vs T.
But from the purely syntactic point of view, I don't see the need of `iobj`.

**Comment by Stormur** [comment]
> @sylvainkahane TBC, are you saying that instead of `obj` and `iobj`, we should have `obj:theme` and `obj:recip` for double object constructions? (I think that's worth considering for UDv3, but for now we are stuck with `iobj`.)

I think that this would be a good option: the main relation is simply `obj`, as we are dealing with double object constructions here; then, subtypes can be used for similar semantic distinctions, as always. And I am in favour of standardising them along the lines of S, A, P, T, R.

Since one of the more practical problems now is that having two `obj`/`ccomp`s is considered an error by the validator, but as already lengthily discussed under some specific circumstances (verbs of giving, dispossession, etc. etc.) we do not seem to have different kinds of arguments (here I totally agree with @sylvainkahane), I would advance this proposal:

> Let's make each language produce a list of all the verbs allowing for double objects, for which the validator won't rise an error.

This would be similar to how auxiliaries are treated now, and bases on the observation that we always seem to deal with closed classes here. E.g., this list in Latin would have not many more than five members: _doceo_, _posco_, _rogo_, _flagito_, _caelo_ (plus some prefixations of these).

**Comment by Stormur** [comment]
> @Stormur the argument as formulated above is that we shouldn't appeal to the absence of another dependent to alter the label of the current dependent. 
> ...
> The ellipsis of 'books' in the last example does not make us change "all day" into an object. In the same way, eliding the direct object should not change the label of the remaining `iobj`:

Exactly, but how can you say that in _We teach them_ you have an `iobj` instead of an `obj`, whereas there is no morphosyntactic distinction whatsoever? It is simply 1) because you know that there are utterances where you **could** say _We teach them chess_, a fact which we could indeed subsume under the phenomenon of ellipsis, which means that an element is missing, but conceptually **it is there**; 2) because you are associating one object, the animate/human/... one to a **semantic** role, and you want that role to be represented by the (allegedly) **syntactic** dependency `iobj` in question.

> In the same way that an extent modifier (in English, usually `obl:npmod` or `obl:tmod`) does not become an object when the regular object is dropped:
> 
>     * I read books/obj
> 
>     * I read books all day/obl:tmod
> 
>     * I read all day/obl:tmod

But these elements behave in a totally different way than the other objects above. Not only can they not be passivised, but they can also appear before the predicate (please correct me if I am mistaken):

* All day I read books

whereas 

* Kim I told the story 

is ruled out as a(n unmarked) sentence. You can even add _all the day_ to any ditransitive construction which already expresses its two arguments. So we are dealing with different phrases, here. 
 
> Note also that in languages where indirect objects have distinct marking from direct objects, the marking does not change to match direct object marking when we elide the indirect object. 

For sure, and these by all means are obliques in UD, unless we find some regular and explainable alternations in the expression of objects like in Spanish _veo la casa_ / _veo a Carlos_ (the latter has a superficial "dative" morphology determined by the animacy/specificity of the object).

**Comment by amir-zeldes** [comment]
> Kim I told the story

Actually this is fine, the phenomenon is sometimes called "Yiddish movement" in English, and is also available with normal objects:

  * Bagels I like

> It is simply 1) because you know that there are utterances where you could say We teach them chess, a fact which we could indeed subsume under the phenomenon of ellipsis, which means that an element is missing, but conceptually it is there; 

Yes, 1), but not 2). The argument in 2) appeals to semantic considerations and is not a diagnostic for deprels as I understand them in UD.

> we are dealing with different phrases, here

Indeed, and this is also the case in "I told Kim the story". Notice that in case marking languages, for example German, the direct object remains accusative regardless of whether the dative object is realized, and vice versa (and I'm not saying German has to analyze datives as objects, but if it did, they are not the same/confusable with accusatives):

  * jemandem/dat erzählen - tell someone/dat
  * etwas/acc erzählen - tell something/acc
  * jemandem/dat etwas/acc erzählen - tell someone/dat something/acc

So I think in languages like this it is pretty clear that a communication predicate with just one of the arguments (message or addressee) is identical to the predicate with both arguments, except that one has been dropped (preserving morphological case marking on the other). These dependents are not the same, they do not fill the same valency slots, and can carry different marking. 

To be clear, I am not appealing to their semantics: English `iobj` can have a range of senses, incl. benefactive, goal, recipient etc., and some of these can be marked using direct objects for other near synoymous predicates. The only criterion being suggested for English iobj is the possibility of double object, plus using the prepositional alternation to identify which argument we are looking at when only one is realized. Not doing this would mean that the subtree for "tell her" will be different in "tell her a story", which seems odd (why does adding the 'story' alter the deprel of 'her', which is doing the same job it was always doing?)

**Comment by dan-zeman** [comment]
> having two `obj`/`ccomp`s is considered an error by the validator

In fact it is not reported as an error by the validator, at least not yet. Such trees thus occasionally occur in the released data, as the two examples here from GUM (UD 2.11):
[http://hdl.handle.net/11346/PMLTQ-JSMW](http://hdl.handle.net/11346/PMLTQ-JSMW)

**Comment by Stormur** [comment]
> > having two `obj`/`ccomp`s is considered an error by the validator
> 
> In fact it is not reported as an error by the validator, at least not yet. Such trees thus occasionally occur in the released data, as the two examples here from GUM (UD 2.11): http://hdl.handle.net/11346/PMLTQ-JSMW

Ah, OK :thinking: But it seemed to me that a double `obj` was flagged somehow, and to have corrected something myself in that sense. Maybe I confused different things.

Is this done on purpose?

**Comment by dan-zeman** [comment]
> > > having two `obj`/`ccomp`s is considered an error by the validator
> > 
> > 
> > In fact it is not reported as an error by the validator, at least not yet. Such trees thus occasionally occur in the released data, as the two examples here from GUM (UD 2.11): http://hdl.handle.net/11346/PMLTQ-JSMW
> 
> Ah, OK 🤔 But it seemed to me that a double `obj` was flagged somehow, and to have corrected something myself in that sense. Maybe I confused different things.
> 
> Is this done on purpose?

Yes and no. I used to run such tests (not in the official validator but elsewhere) but I was looking at `obj`, `ccomp` and `xcomp`, which did not work (you can have object control, then `obj` co-occurs with `xcomp`). I'm not sure if I also saw a problem with `ccomp` but I focused on other tests and put this one aside when implementing the first batch of tests in the validator. Looking just at two `obj`s should be safe, though.

There is a similar test in [Udapi ud.MarkBugs](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/markbugs.py#L138-L140), and it affects the [treebank evaluation](https://github.com/UniversalDependencies/tools/blob/master/evaluate_treebank.pl#L424-L431) for star ranking. If you remember that something forced you to fix such errors, maybe it was Udapi.

**Comment by amir-zeldes** [comment]
> the two examples here from GUM (UD 2.11)

That's surprising, I'll need to check how it slipped through! One of these is a plain error (should be xcomp in a naming construction). The other one looks like a genuine non-standard usage of a resumptive pronoun AND a relative object pronoun in spoken English, but I don't think they actually co-refer:

  * I got a compliment on it **which** I didn't mention **this** earlier but I bought this at the Audubon Society

Gotta love real data :) Any recommendations on how to annotate this? Dislocated?? But I think "this" is actually a cataphor for what she's about to say, and "which" is something like "a compliment about which I did not mention the following". But syntactically it sure looks like two objects...

**Comment by nschneid** [comment]
`reparandum` for "which"? Or treat it as a subordinator with `mark`?

**Comment by Stormur** [comment]
> * I got a compliment on it **which** I didn't mention **this** earlier but I bought this at the Audubon Society

This looks very much like an `expl` and the equivalent of a "doubling clitic pronoun" in many languages. And it is interesting because it might even point to the loss of _which_ as a pronoun on its way to a complementiser, just like _that_, or _che_ in Italian. Meaning that it is not so trivial to decide which one is the `expl`!

**Comment by amir-zeldes** [comment]
Thanks for the suggestions! Of these I think I like `mark` best, because it's not really being repaired (it is an actual relative clause, and 'which' marks this), and it's not exactly expletive, since it does link back to the compliment in some way. I think it's maybe almost an unmarked `obl`, because this would basically be normatively grammatical if it had been "about which". So maybe `obl:npmod` is also an option? Otherwise `mark` could signal that it is the same as an indeclinable complementizer, like @Stormur is saying (something like dialectal "a compliment what/where I didn't say this", in which 'what/where' is a catchall not indicating grammatical function)
