### ISSUE TITLE
So called strong forms of pronouns

### ISSUE THREAD

**Issue by sylvainkahane** [UniversalDependencies/docs#919]
Romance languages have a remaining case opposition for pronouns. For instance, French 2SG has three forms:
 - a nominative _tu_: _tu pars_ 'you leave';
 - an accusative/dative _te_: _je te regarde_ 'I see you', _je te parle_ 'I speak to you';
 - and a so-called strong form _toi_, which is used in isolation, in dislocation, and after a preposition: _-Qui vient? -Toi._ '-Who comes? -You.'; Toi, tu pars. 'You, you leave', _je viens avec toi_ 'I come with you'.
 
I looked at the page on [Case](https://universaldependencies.org/u/feat/Case.html), and I didn't find a convenient value for strong forms. Any suggestion? Do I introduce a new value `Case=Stg`?
Note that Wolof has also cases on pronouns, but in UD_Wolof-WTB only nominative and accusative forms have a `Case` feature, but strong forms used in dislocations do not.

**Comment by amir-zeldes** [comment]
I don't think it's a distinct case, since the opposition doesn't really encode grammatical function. I think on paper the response "qui vient?" > "toi" is as much nominative as tu in "tu pars", and the same form in "je vien avec toi" is clearly not nominative.

Slavic languages also have variation between short pronoun forms and longer, perhaps more emphatic ones, like "mi" vs. "mnie" in Polish (both possible for me.DAT). In UD Polish I see they went with `Variant=Short` and `Variant=Long`. Maybe this or something similar could be standardized?

**Comment by sylvainkahane** [comment]
It is true that the strong form can also be used in subject or object positions, in case of contrast (_lui aurait trouvé la solution_ 'he (contrasted with someone else) would have found the solution') or in coordination (_elle me connait_ 'she knows me' vs _elle connait Kim et moi_ 'she knows Kim and me'). But it is not a variant because in _lui aurait trouvé la solution_ vs _il aurait trouvé la solution_, the meaning is different; and in _elle connait Kim et moi_, only the strong form _moi_ is possible.

**Comment by Stormur** [comment]
I don't think it is a `Case` (and from the examples that you give it might even not express one in particular). It seems something to be treated by means of `Form`, of which `Emphatic` is a possible value, and it might be suited to this case. `Variant` is not so well defined, but it seems to stay more on the stylistic side than on morphosyntactic variations like this one. I don't like too much the reported values `Short` and `Long` for Polish because they are extremely language specific, though not unique to Polish as phenomena.

**Comment by sylvainkahane** [comment]
@amir-zeldes @Stormur  Thanks for you comments. I think we will introduce a feature `Emph=Yes|No`:

- _moi_ = `Emph=Yes`
- _je_ = `Emph=No, Case=Nom`
- _me_ = `Emph=No, Case=Acc,Dat` (here I have a new question but I will open a new issue)
