### ISSUE TITLE
Neutralization: Do we annotate the form or the position?

### ISSUE THREAD

**Issue by sylvainkahane** [UniversalDependencies/docs#920]
What is the policy in case of neutralization of features?

1) In English, only the third person singular pronouns are marked for gender. Other forms neutralize the gender and do not have a `Gender` feature. Same thing in French or [German](http://universal.grew.fr/?custom=63f1eb941b204).

2) In German, the articles vary in case, but the neuter definite article _das_ has the same form for nominative and accusative cases. The annotation "disambiguate" it and [_das_ is marked `Case=Nom` or `Case=Acc`.](http://universal.grew.fr/?custom=63f1eb0d1d024) So, here we annotate the position rather than the form itself.

3) In French, the third person pronoun marks the opposition between nominative, accusative and dative (_il, le, lui_), but first or second persons neutralize the opposition between accusative and dative (_je, me_). If I annotate the form _me_, I should have `Case=Acc,Dat`.
If I annotate the positions and the possible commutation with _le_ and _lui_, I could annotate _me_ `Case=Acc` or `Case= Dat` according to the position. But there are cases where _me_ only commutes only with  the reflexive pronoun _se_ and we cannot know if it is an accusative or dative: _je me souviens_ 'I remember', _il se souvient_ 'he remembers'. Here `Case=Acc,Dat`seems to be the only possibility.

4) In French adjectives agree with the nouns: _la **gentille** dame_ 'the nice woman', _le **gentil** monsieur_ 'the nice man'. But many adjectives do not have any variation in gender: _libre_ 'free', _utile_ 'useful', _facile_ 'easy', _rouge_ 'red', _rose_ 'pink', …, as well as as adjectives borrowed to English like _fun_ or _cool_. In almost all cases we can recover the gender from the position, but do we want to do that?

Has UD a general policy concerning neutralization?

**Comment by dan-zeman** [comment]
I don't think there is a general policy and I think there can be at most some general recommendations, while any policy should be language-specific. As you observed, we neither stick strictly with position, nor with form. My general recommendation would be that, if in doubt, then form matters more than position; but it definitely does not mean that we should not disambiguate homonymous forms by context. Some form/position decisions may be more natural in some languages and situations than in others. And often the previous NLP tradition in that language will play a role.

Czech nouns have forms for 7 cases and 2 numbers. No noun has distinct forms for all 14 paradigm slots. But for almost every pair of slots, there is a noun whose forms in these two slots are not identical (the exception is vocative plural, which is always identical to nominative plural). So we annotate the single value of `Case` and `Number` that belongs to the position; if the same form fits in multiple paradigm slots, it is case syncretism, i.e., we treat it as multiple distinct forms that happen to be homonymous. But then there are nouns that do not inflect at all (e.g. acronyms such as _USA_ or _OSN_ “UN”). These do not get the `Case` feature at all. It would be probably possible to tell the case by context, but here it would be only about position and never about form. More importantly, this is how Czech corpora have been annotated for decades and we simply do not have the case value in the data. There is no force that could revisit the 2M words in Czech UD and add the feature.

Interestingly, German corpora approach the nouns (not just articles!) the same way, although most of the time the article will reveal the case of the nominal, while the noun itself will not. (But still, there are some case-specific forms of some nouns, so the `Case` feature of `NOUN` is justified.)

[In Danish, nouns have only genitive annotated](https://universaldependencies.org/treebanks/da_ddt/da_ddt-feat-Case.html#noun) and the non-genitive form of the noun has no `Case` feature. The same situation is resolved differently [in Swedish, where Case=Nom or Case=Gen is used](https://universaldependencies.org/treebanks/sv_talbanken/sv_talbanken-feat-Case.html#noun). This may again be caused by different pre-UD tagging customs but here at least one could automatically assign `Case=Nom` to Danish nouns that lack the feature (and yes, my preferred way of harmonizing the two languages would be adding the nominative to Danish rather than removing it from Swedish).

As for the French personal pronouns, I would probably prefer to disambiguate all three `Case` values if I were annotating manually from scratch, but if I were batch-processing data where this disambiguation was not available, I would back off to `Case=Acc,Dat` (I did this in Spanish). If it cannot be disambiguated for reflexives, an option could be to say `Reflex=Yes` and leave the `Case` empty (although somehow I hear `Case=Dat` in _je <b>me</b> souviens_, perhaps under the influence of Czech _já <b>si</b> pamatuji_).

As for the gender of French adjectives, again, one could in theory (if annotating from scratch) distinguish the gender everywhere, but I would probably say that there is a class of adjectives that distinguish `Gender` and there is another class that doesn't, [as it is currently done in Spanish](https://universaldependencies.org/treebanks/es_ancora/es_ancora-feat-Gender.html#adj).

**Comment by Stormur** [comment]
> 2\. In German, the articles vary in case, but the neuter definite article _das_ has the same form for nominative and accusative cases. The annotation "disambiguate" it and [_das_ is marked `Case=Nom` or `Case=Acc`.](http://universal.grew.fr/?custom=63f1eb0d1d024) So, here we annotate the position rather than the form itself.

Rummaging through treebanks, I found another neutralisation in German treebanks, namely _dem_ labeled as `Gender=Masc,Neut`. It does not seem to be systematic, though; for the same reason I would expect a neutralisation of gender for plural articles, for example, but this does not happen.

This seems to be a recurrent debate. I agree with most of the considerations here, but I am not inclined to delegate all similar decisions to "language-specific criteria". Probably some more defined guidelines are needed for this issue, which is pervasive among languages.

In particular, if UD's morphological features have to be linked to form, and if we are interested in an as less contextual as possible annotation, then probably "neutralised" annotations should be encouraged to be the norm.  



> [In Danish, nouns have only genitive annotated](https://universaldependencies.org/treebanks/da_ddt/da_ddt-feat-Case.html#noun) and the non-genitive form of the noun has no `Case` feature. The same situation is resolved differently [in Swedish, where Case=Nom or Case=Gen is used](https://universaldependencies.org/treebanks/sv_talbanken/sv_talbanken-feat-Case.html#noun). This may again be caused by different pre-UD tagging customs but here at least one could automatically assign `Case=Nom` to Danish nouns that lack the feature (and yes, my preferred way of harmonizing the two languages would be adding the nominative to Danish rather than removing it from Swedish).

Here I am of the opposite conviction. We would actually be annotating something that does not appear from the from, and then for coherence we should also annotate all other cases like `Dative` and `Accusative` contextually... all the while the forms staying the same. So I see the Danish approach as the only sensible one: there is one base form with no defined feature, and in some context we can mark "positively" a form with what we call a genitive suffix. 

This is different e.g. from Latin, or to stay with modern Germanic languages from Icelandic, where you factually have suffixes which convey a `Nom` case in opposition to others, e.g. _-us_/_-ur_.

**Comment by amir-zeldes** [comment]
I think it's somewhat inevitable that case annotation will vary by language. If you come at it from a very Eurocentric perspective, you could say about ergative languages that absolutives in intransitive arg0 (="subject") vs transitive arg1 (="object") could also be distinguished, and there is just a 100% syncretism in the language (I am not seriously arguing this, just trying to push a language independent 'universal guideline' position ad absurdum).

If a language does distinguish cases somewhere in its paradigms, but some forms are syncretic (as in basically all case marking IE languages), then I think it makes sense to want a contextually disambiguated annotation. The extreme case arguing for this would be when just one noun has syncretic nom/acc, and all other nouns have the distinction in form, I think we would not want a special `Acc,Nom` value just on that one noun (of course, if it's common and the data doesn't have that disambiguation, we may not have budget to annotate the distinction, but I think we should *want* to have it).

From a more practical perspective I think Dan's example of the IE vocative plural is illuminating. No IE language (except Irish) distinguishes Nom vs. Voc Pl., since, probably Proto-IE didn't distinguish them. If we want to use UD to study vocatives, some of which are roots (e.g. in the sentences 'Kim!' or 'Kids!'), we cannot afford to prohibit annotating all plural vocatives for `Case=Voc` just because they are always syncretic. The singular is not syncretic in many IE languages, and the only way to make `Case=Voc` identify exactly all vocatives would be to take a 'position' approach, not a form one.
