### ISSUE TITLE
nmod:npmod and obl:npmod documentation pages seem to be duplicates

### ISSUE THREAD

**Issue by lauren-lizzy-levine** [UniversalDependencies/docs#931]
I was trying to look up the difference between [nmod:npmod](https://universaldependencies.org/en/dep/nmod-npmod.html) and  [obl:npmod](https://universaldependencies.org/en/dep/obl-npmod.html) and I found that a bunch of the examples were the same and used the two different relations in the same spot. This was confusing to me, and I think it is an error. To my understanding, the examples on these pages should be right for obl:npmod because the heads in the examples are not nominal, and the examples for nmod:npmod should be revised.

**Comment by nschneid** [comment]
Yup. #478 may be helpful but we never finished documenting this

**Comment by amir-zeldes** [comment]
Right, I think (hope?) that the data is correct though, at least in EWT and GUM AFAIK. I agree with the characterization above (should be obl:npmod for governors which would otherwise take obl and vice versa), and if you find any contradictory cases I will definitely correct them, at least in GUM. I think several other corpora I've consulted follow this split, for example the new Hebrew Wiki TB:

  * [nmod:npmod](http://universal.grew.fr/?custom=64244e95075f8)
  * [obl:npmod](http://universal.grew.fr/?custom=64244ed4596f2)
