### ISSUE TITLE
Space in UD for language-specific discussions

### ISSUE THREAD

**Issue by Stormur** [UniversalDependencies/docs#954]
I was wondering what should be the best place for the community working on a given language to discuss language-specific issues inside the Universal Dependencies project. 

There seems to be a lack of something intermediate between the general docs and the individual treebank repositories, while at least ideally every language should follow the same guidelines.

My concern would be to not flood these issues, which are of a more general kind and bring forward a more typological debate, with discussions about some very specific annotational choices in the treebanks of a given language (in our case Latin, involving 5 treebanks). Still, I think it would be desirable to have them all in one place inside the pages of the UD project so that who is interested inside the community can take more easily part in it.

Is it possible to create language-specific "pages"? How are other groups of annotators dealing with similar organisational issues?

**Comment by sylvainkahane** [comment]
It would be nice to also have family-specific group and issues, for instance for Romance, Germanic, Slavic … languages. And people verifying the coherence of annotations for related languages.

**Comment by dan-zeman** [comment]
I strongly believe everything that is not treebank-specific should be **here,** for the following reasons:

- It is about language-specific guidelines, i.e., the contents of the docs repository. Therefore it should be in the issue tracker of the docs repository.
- For those of us who want to be able to keep track of everything, it is tremendously important that the number of places to be searched is minimized. Even now I have occasionally hard time when I am sure something has been already discussed but I cannot locate the issue no matter how hard I search... then it turns out it is hidden, for example, in the issue tracker of UD_English-EWT. Having separate issue trackers for individual languages, genera, families etc. sounds like a nightmare.

Instead, people should post here but make sure to use the language-specific (or genus-/family-specific) labels so that relevant issues can be easily filtered. That way it is also easier to maintain threads that have examples from multiple languages. Often an issue starts as a question in one language but ends as a truly cross-linguistic discussion, which is good.

If _Labels_ are not enough, maybe you can also use _"Projects"_ to organize the issues. I have no experience with that, but I have noticed that @nschneid used _Projects_ with certain issues.
