### ISSUE TITLE
Internally-headed / Headless Relative Clauses

### ISSUE THREAD

**Issue by mr-martian** [UniversalDependencies/docs#959]
How should relative clauses be annotated when the head noun is left out?

ὃς ἐξελεύσεται ἐκ σου οὗτος κληρονομήσει σε
REL come-forth from you he inherit-from you
"[one] who will come forth from you, he shall inherit from you"

If there was a noun preceding the relative pronoun, I would make ἐξελεύσεται `acl:relcl` from that, but since there isn't, should the verb be the head? or the relative pronoun?

**Comment by dan-zeman** [comment]
What is the relative pronoun? The word that you gloss "REL", i.e., _ὃς_?

And is _οὗτος_ "he" a personal or demonstrative pronoun in the main clause?

**Comment by mr-martian** [comment]
```
ὃς PRON PronType=Rel
ἐξελεύσεται VERB
ἐκ ADP
σου PRON PronType=Prs
οὗτος PRON PronType=Dem
κληρονομήσει VERB
σε PRON PronType=Prs
```
If there was a noun before ὃς, I would attach it to κληρονομήσει with `dislocated` and οὗτος with `nsubj`.

**Comment by dan-zeman** [comment]
I would attach the relative clause to the pronoun in the main clause:
`acl:relcl(οὗτος, ἐξελεύσεται)`

**Comment by Stormur** [comment]
There seems to still be a head, even if the noun phrase is represented "just" by a `PRON` (which by the way in this case actually looks very much as a univerbation of `DET` + `PRON`... or maybe `DET`? and this could solve problems maybe), so I would also attach it as proposed by @dan-zeman .

**Comment by mr-martian** [comment]
And what would it be if the pronoun also wasn't there? (I have a few such cases)

**Comment by Stormur** [comment]
In that case you can use clausal relations, maybe with the `:relcl` subtype as in Latin to mark them out. The relation would be between the matrix predicate and the one inside the free relative clause.

**Comment by amir-zeldes** [comment]
> I would attach the relative clause to the pronoun in the main clause acl:relcl(οὗτος, ἐξελεύσεται)

I don't think that's right - that would imply that there is a noun phrase headed by οὗτος governing the relative clause - an NP structured something like 'who will come forth he', headed by 'he', which is not normal Greek word order. 

I'm obviously not a native speaker of Classical Greek, but I think this is a correlate structure which should be analyzed as `dislocated`. I would take this to more literally mean something like "(he) who will come from you, that one will inherit you" (similar to paired WH pronoun + demonstrative in Slavic languages, like 'co ... to' in Polish), so either:

dislocated(κληρονομήσει, ὃς)
nsubj(κληρονομήσει,οὗτος)
acl:relcl(ὃς, ἐξελεύσεται)

Or if you want to treat the relative clause normally, you could say it's a dislocated clausal subject and keep the normal deprel on the relative pronoun:

nsubj(κληρονομήσει,οὗτος)
nsubj(ἐξελεύσεται,ὃς)
dislocated(κληρονομήσει, ἐξελεύσεται)

But then you lose the direct indication that this was a relative clause.

**Comment by dan-zeman** [comment]
> > I would attach the relative clause to the pronoun in the main clause acl:relcl(οὗτος, ἐξελεύσεται)
> 
> I don't think that's right - that would imply that there is a noun phrase headed by οὗτος governing the relative clause - an NP structured something like 'who will come forth he', headed by 'he'

Exactly. That's correct.

> similar to paired WH pronoun + demonstrative in Slavic languages

Agreed. Here are examples from Czech:
[http://hdl.handle.net/11346/PMLTQ-YCAE](http://hdl.handle.net/11346/PMLTQ-YCAE)

Here from Slovak:
[http://hdl.handle.net/11346/PMLTQ-NZLT](http://hdl.handle.net/11346/PMLTQ-NZLT)

Here from Polish:
[http://hdl.handle.net/11346/PMLTQ-TJHG](http://hdl.handle.net/11346/PMLTQ-TJHG)

Here from Ukrainian:
[http://hdl.handle.net/11346/PMLTQ-BLBC](http://hdl.handle.net/11346/PMLTQ-BLBC)

Here from Russian:
[http://hdl.handle.net/11346/PMLTQ-AQJY](http://hdl.handle.net/11346/PMLTQ-AQJY)

Similar annotations are found also in the South Slavic languages, except that they do not use the `:relcl` subtype, so it is plain `acl`.

**Comment by amir-zeldes** [comment]
Looking at the Polish examples, that is not the structure we are looking at here. In those examples, the relative clause invariably follows the pronoun, and does not precede it as in the Greek example. For example:

  * Legia sprzedała Zeigbo do włoskiej Venezii za kwotę blisko dziesięciokrotnie wyższą niż ta, za którą go kupiła - "Legia sold Zeigbo to Italian Venezia for an amount almost ten times higher than **that for which it bought him**"

The phrase "that for which is sold him" is indeed a relative clause modifying a demonstrative pronoun, and that is fine, but what we have in Greek would have been, in Polish:

  * ?który go kupił, ten sprzedał Zeigbo, lit. "which him bought, that sold Zeigbo"

I don't think the intended reading in Polish could be that this is a pre-poned relative clause headed by "that". I am also not a native speaker of Polish, but if I heard that, I would assume that the first clause is a hanging topic headless relative "(he) who bought him", and 'ten' "this one" is the proper subject which recapitulates the dislocation. Would you see it differently in Czech?

**Comment by mr-martian** [comment]
Found an example without a pronoun:
```
οὗ PRON PronType=Rel "where"
ἐάν SCONJ (discourse marker)
σοί PRON PronType=Prs "to you"
ἀρέσκῃ VERB "is pleasing"
, PUNCT
κατοίκει VERB "settle"
```
"settle wherever it pleases you"

**Comment by dan-zeman** [comment]
> * ?który go kupił, ten sprzedał Zeigbo, lit. "which him bought, that sold Zeigbo"
> 
> I don't think the intended reading in Polish could be that this is a pre-poned relative clause headed by "that". I am also not a native speaker of Polish, but if I heard that, I would assume that the first clause is a hanging topic headless relative "(he) who bought him", and 'ten' "this one" is the proper subject which recapitulates the dislocation. Would you see it differently in Czech?

I don't see it as a difference between Polish and Czech, I see it merely as a matter of taste. The reversed word order is less frequent but possible, and otherwise it still has the form of a relative clause coreferential with the pronoun in the main clause, so it is natural to use the same annotation.

There are six examples in the Polish treebank where the word order is reversed and the clause is still labeled `acl:relcl` and attached to the pronoun: [http://hdl.handle.net/11346/PMLTQ-FISU](http://hdl.handle.net/11346/PMLTQ-FISU). Though the query would not reveal if there are other similar cases that were not annotated this way. Czech PDT has 64 such examples: [http://hdl.handle.net/11346/PMLTQ-LI45](http://hdl.handle.net/11346/PMLTQ-LI45).

**Comment by mr-martian** [comment]
And here's one that's definitely not `advcl:relcl` or `dislocated`:

```
ὃς PRON REL
γὰρ SCONJ because
ἄν PART [discourse marker]
ἀκούσῃ VERB hear
, PUNCT
συγχαρεῖταί VERB laugh with
μοι PRON me
```
"because who[ever] hears will laugh with me"

So the relative clause `ὃς ἄν ἀκούσῃ` should be `nsubj` (`csubj`?) of `συγχαρεῖταί`.

**Comment by dan-zeman** [comment]
> So the relative clause `ὃς ἄν ἀκούσῃ` should be `nsubj` (`csubj`?) of `συγχαρεῖταί`.

We do these as `csubj` in Czech (http://hdl.handle.net/11346/PMLTQ-LU3W), although strict following of ellipsis-promotion would make them `nsubj`.

**Comment by amir-zeldes** [comment]
> I see it merely as a matter of taste

Mmm... I really hesitate to express a strong opinion about this as a non-native speaker, and Czech could be totally different, but I think except in the most ornate poetry, it's not really possible (or at least extremely not normal) to pre-pone a relative clause in Polish. Looking at the PML examples I think they are basically annotation errors (and a frequency of 6 out of 2747 relative clauses in the corpus lends some credence to this). For example:

  * Gdy Majster mówił "pan Lehmann" zamiast "Stary" zawsze to miało głębsze znaczenie. 

I would translate this to: "When the Master said "Mr. Lehmann" instead of "Old man", this always had a deeper meaning". The tree is saying that "this" is being expanded by a relative "when" clause, i.e. "[this when the master said]NP... always had a deeper meaning". But I think the choice of gdy for 'when' rather than an inflected pronoun points to it just being a normal adverbial clause. Otherwise it's hard to say when it is impossible to interpret any adverbial clause as definitely not modifying the subject NP... Do you think it's a restrictive preposed relative clause on "to"? I could see "to" just being a copula, or reading this as a hanging topic plus "to" as the subject (the two constructions are often hard to distinguish), but a relative clause seems like a very odd reading to me.

Similarly this one seems just plain wrong: "Ale jak płacimy, to się okaże na końcu - igra sobie Pan Marek z domysłami wątpiących" - 'but as we pay, it will turn out in the end, Mr. Mark plays with the conjectures of the doubters". This has "as we pay" as a relative clause to "it" in "it will turn out".

**Comment by amir-zeldes** [comment]
> So the relative clause ὃς ἄν ἀκούσῃ should be nsubj (csubj?) of συγχαρεῖταί.

We have these in Coptic occasionally and use `csubj` to the verb. This is similar to the English 'who steals my purse steals trash' type. I just looked at UD German, where these are quite common, and there it seems to vary between the nsubj and csubj solutions, with maybe a majority for csubj (HDT seems to do this consistently).

**Comment by mr-martian** [comment]
One further construction:

```
ἐποίησεν VERB make
Ἁβραὰμ PROPN Abraham
δοχὴν NOUN feast
μεγάλην ADJ great
, PUNCT
ᾗ PRON REL
ἡμέρᾳ NOUN day
ἀπεγαλακτίσθη VERB wean
Ἰσαὰκ PROPN Isaac
```
"Abraham made a great feast on the day Isaac was weaned"

Not sure what to do with `ᾗ ἡμέρᾳ ἀπεγαλακτίσθη` here.

**Comment by amir-zeldes** [comment]
> Not sure what to do with ᾗ ἡμέρᾳ ἀπεγαλακτίσθη here.

I think it's essentially the same as the previous except oblique, so the choices would be `advcl` from "make" to to "wean" (keeping the oblique relation to 'to which day'), or `obl` to "day" with `acl:relcl` to "wean".

**Comment by dan-zeman** [comment]
> For example:
> 
> * Gdy Majster mówił "pan Lehmann" zamiast "Stary" zawsze to miało głębsze znaczenie.
> 
> I would translate this to: "When the Master said "Mr. Lehmann" instead of "Old man", this always had a deeper meaning".

I cannot make strong claims about Polish either (my understanding is based solely on its similarity to Czech) but the first two results of the query look good to me and I did not examine the others (this one is third :-)). I don't think _to_ is a copula here because there is a verbal predicate _miało_ "had". I do agree that this example is borderline at best. I can see the possible thinking of the annotator, as _to_ is (not necessarily, but can be) coreferential with the event described in the subordinate clause, but I wouldn't mind `advcl` here.

> "Ale jak płacimy, to się okaże na końcu - igra sobie Pan Marek z domysłami wątpiących" - 'but as we pay, it will turn out in the end, Mr. Mark plays with the conjectures of the doubters". This has "as we pay" as a relative clause to "it" in "it will turn out".

I think the _jak płacimy_ clause can be translated "how we pay" (as an alternative to "as we pay"). It is hard to say because the neighboring sentences do not seem to be from the same document. (I assume the treebank consists of individual sentences but I have not found it stated in the README file.) Anyway, it would still make it `advcl` or borderline like the _gdy_ example above, and the same holds for one other sentence in the batch. So I would say that out of these 6 results, 3 look like good examples of corelatives, and 3 are problematic.

**Comment by amir-zeldes** [comment]
> he first two results of the query look good to me and I did not examine the others (this one is third :-))

Heh :) I thought I'd pick the shortest ones for discussion here, that's why I skipped ahead. But I can shorten the first one to the relevant part (ignoring the coordination), which is basically "what one had handy, that's what they used". I find it odd to read it as "that which one had handy is what they used" - sure, it's possible semantically, but the word order makes me read it as a hanging topic. 

Even in English you can say "whatever you have handy, you use it", the difference is that in Polish "whatever" could be synonymous with an indeclinable wh-relative pronoun 'co' "what". But I think it's telling that you get 'co' as the suspected relative pronoun, and not 'który'. In either case, if both readings are possible (transposed relative and hanging topic), then I would say the latter is much more plausible, since, at most, we can find 3 such cases in over 2700 examples, but hanging topics are pretty common... I'd also expect a pause to be possible if it's a hanging topic and less so for a relative. But again, I'm very much not a native speaker, so we should ask some Polish speakers.

**Comment by nschneid** [comment]
> Even in English you can say "whatever you have handy, you use it"

The resumptive pronoun sounds odd to me—I'd prefer "Whatever you have handy, you use."

**Comment by amir-zeldes** [comment]
> The resumptive pronoun sounds odd to me

Yeah, that's what makes it a 'correlate' structure, it's quite common and normal in Slavic languages, so that part is not unusual. The only question is, if the pre-poned clause is headed by "what", which is ambiguous between a relativizer (as in dialectal English "the book what I bought") and an NP, should we assume it's a pre-poned relative or a hanging topic NP. I'm arguing it's the latter for things which are basically: "what you have handy, that you use". Dan is saying it's reasonable to see the first part as acl:relcl to the pronoun "that", while I think they are separate phrases, unless you have "that which you have handy", in that order.

**Comment by Stormur** [comment]
> > I would attach the relative clause to the pronoun in the main clause acl:relcl(οὗτος, ἐξελεύσεται)
> 
> I don't think that's right - that would imply that there is a noun phrase headed by οὗτος governing the relative clause - an NP structured something like 'who will come forth he', headed by 'he', which is not normal Greek word order.

It might be unusual, but it is not something that never occurs. I suppose it can happen for stylistical reasons, focus, or movement of a "heavy phrase" to the margins. I performed a small rsearch on UDante for Latin, where it seems to occur 50 times (try `pattern {H -[acl:relcl]-> R ; R << H}` on Grew match), more than I thought (I unfortunately discovered that other treebanks have some annotation issues with `relcl`s...). Some are however very similar to the case in point here. 

But the `dislocated` analysis does look appealing when we have to deal with a pronoun. By itself, there is no problem in having a pronoun expanded by a (relative) clause, though. And in general, there is no a priori reason for a relative clause not to preceed its head, just strong tendencies, I would say ("implicit" ones do this more often than "explicit" ones, and so on).

> Or if you want to treat the relative clause normally, you could say it's a dislocated clausal subject and keep the normal deprel on the relative pronoun:
> 
> nsubj(κληρονομήσει,οὗτος) nsubj(ἐξελεύσεται,ὃς) dislocated(κληρονομήσει, ἐξελεύσεται)
> 
> But then you lose the direct indication that this was a relative clause.

This is the way I would go. The information about being a relative clause would not be lost, for one since we still have a relative element, but also because if this is a dislocation, then we could not really talk about an `acl:relcl` anymore.

**Comment by amir-zeldes** [comment]
> By itself, there is no problem in having a pronoun expanded by a (relative) clause, though

That's true, but pronouns are both information-structurally given and prosodically light, I think it would be quite odd to postpone them in favor of a much heavier relative clause.... Not saying it's 100% impossible, and I can sort of force my brain to parse sentences like that as if it's a relative clause, but the dislocated reading seems much more straightforward to me. For Classical Greek I guess we don't have native speakers to ask :(

**Comment by Stormur** [comment]
> Found an example without a pronoun:
> 
> ```
> οὗ PRON PronType=Rel "where"
> ἐάν SCONJ (discourse marker)
> σοί PRON PronType=Prs "to you"
> ἀρέσκῃ VERB "is pleasing"
> , PUNCT
> κατοίκει VERB "settle"
> ```
> 
> "settle wherever it pleases you"

So, this in Latin would be a case of `advcl:relcl`(κατοίκει,ἀρέσκῃ), with οὗ as oblique inside it: an "oblique free relative".


> And here's one that's definitely not `advcl:relcl` or `dislocated`:
> 
> ```
> ὃς PRON REL
> γὰρ SCONJ because
> ἄν PART [discourse marker]
> ἀκούσῃ VERB hear
> , PUNCT
> συγχαρεῖταί VERB laugh with
> μοι PRON me
> ```
> 
> "because who[ever] hears will laugh with me"
> 
> So the relative clause `ὃς ἄν ἀκούσῃ` should be `nsubj` (`csubj`?) of `συγχαρεῖταί`.

Analogously as before, a `csubj:relcl` in Latin. 


> > So the relative clause `ὃς ἄν ἀκούσῃ` should be `nsubj` (`csubj`?) of `συγχαρεῖταί`.
> 
> We do these as `csubj` in Czech (http://hdl.handle.net/11346/PMLTQ-LU3W), although strict following of ellipsis-promotion would make them `nsubj`.

But is this allowed by the validator, @dan-zeman? If so, I think this kind of annotation should be preferred, maybe with something like `nsubj:relcl`.

> One further construction:
> 
> ```
> ἐποίησεν VERB make
> Ἁβραὰμ PROPN Abraham
> δοχὴν NOUN feast
> μεγάλην ADJ great
> , PUNCT
> ᾗ PRON REL
> ἡμέρᾳ NOUN day
> ἀπεγαλακτίσθη VERB wean
> Ἰσαὰκ PROPN Isaac
> ```
> 
> "Abraham made a great feast on the day Isaac was weaned"
> 
> Not sure what to do with `ᾗ ἡμέρᾳ ἀπεγαλακτίσθη` here.

Could this not be a co-ordination? I see no easy way to accommodate for a relative clause either way. Does Ancient Greek not always require a relative element, be it a free or headed relative?

**Comment by mr-martian** [comment]
> Could this not be a co-ordination? I see no easy way to accommodate for a relative clause either way. Does Ancient Greek not always require a relative element, be it a free or headed relative?

Not sure what you mean - it has the relative pronoun `ᾗ PRON REL`

**Comment by Stormur** [comment]
> > Could this not be a co-ordination? I see no easy way to accommodate for a relative clause either way. Does Ancient Greek not always require a relative element, be it a free or headed relative?
> 
> Not sure what you mean - it has the relative pronoun `ᾗ PRON REL`

Sorry, I confused things, new and old, and thought the article and the pronoun coincided in this case. :pray: Then I agree with an `advcl:relcl`(ἐποίησεν,ἀπεγαλακτίσθη).

**Comment by dan-zeman** [comment]
> > We do these as `csubj` in Czech (http://hdl.handle.net/11346/PMLTQ-LU3W), although strict following of ellipsis-promotion would make them `nsubj`.
> 
> But is this allowed by the validator, @dan-zeman? If so, I think this kind of annotation should be preferred, maybe with something like `nsubj:relcl`.

You mean whether the validator allows a `VERB` to be attached as `nsubj`? The validator has to allow various strange combinations, partly due to promotion in ellipsis, and partly to allow words to be mentioned rather than used _('swam' is the past tense of 'to swim')._

So if you want to view the version without the corelative pronoun as ellipsis, you should be able to use `nsubj`. But I doubt they were viewed as ellipsis by the annotators of the Czech data. In the grammar, this is simply a "subject relative clause"; that term points at `csubj`. Besides, the PDT annotation does not distinguish `nsubj` from `csubj`, it is simply `Sb` (subject). The conversion procedure sees that it is a clause and a subject of another clause, hence it labels it `csubj`.

**Comment by Stormur** [comment]
> > > We do these as `csubj` in Czech (http://hdl.handle.net/11346/PMLTQ-LU3W), although strict following of ellipsis-promotion would make them `nsubj`.
> > 
> > 
> > But is this allowed by the validator, @dan-zeman? If so, I think this kind of annotation should be preferred, maybe with something like `nsubj:relcl`.
> 
> You mean whether the validator allows a `VERB` to be attached as `nsubj`? The validator has to allow various strange combinations, partly due to promotion in ellipsis, and partly to allow words to be mentioned rather than used _('swam' is the past tense of 'to swim')._
> 
> So if you want to view the version without the corelative pronoun as ellipsis, you should be able to use `nsubj`. But I doubt they were viewed as ellipsis by the annotators of the Czech data. In the grammar, this is simply a "subject relative clause"; that term points at `csubj`. Besides, the PDT annotation does not distinguish `nsubj` from `csubj`, it is simply `Sb` (subject). The conversion procedure sees that it is a clause and a subject of another clause, hence it labels it `csubj`.

OK, of course it does. :thinking: I would not see them as ellipses, but as an internal vs. external head, and this might actually warrant a treatment through `nsubj` as this head is nominal. I think a `csubj` is something else, it is an entire predication acting as subject, not  a nominal subject expressed through a clause... if I explained myself.

---

I looked more in detail to head-preceeding relative clauses in UDante Latin and I have to say that a dislocated correlation analysis as proposed by @amir-zeldes actually appears to me now as the most correct (or appealing) one. So, similarly to the Greek case, we have something like 

* _**quas** tulit calamitates illa civitas gloriosa in fide pro libertate Saguntum, ignominiose vos **eas** in perfidia pro servitute subire necesse est._
    * 'Those  sufferings, in short, which for liberty's sake the glorious city of  Saguntum endured in her loyalty, you in your disloyalty must undergo  with shame but to become slaves.'
    * More literally: '**which** sufferings for liberty's sake the glorious city of  Saguntum endured in her loyalty, you in your disloyalty must undergo **them** with shame but to become slaves.'

The editor also felt the "disconnection" of the two pieces by putting a comma, there is even some material (adverb and subject) between relative and pronoun, and in general this looks very much like a reprise as for other dislocations. The couples are always of the kind _ubi_/_ibi_ 'where', _qualis_/_talis_ 'of that kind', _qui_/_is_ 'he/she/it'...

This is different from truly preposed relative clauses (which are very rare):

* _Est igitur super **quod** gradimur **ydioma** tractando tripharium_
    * 'The **language** with **which** I shall be concerned, then, has three parts' 

In general, these latter relative clauses are much shorter, mostly just relative element + verb (here also an adverbial). Also, both kinds of relative clauses seem to be each concentrated in different works, probably a matter of style.

In the end, also Latin seems to give good arguments to treat occurrences as the one in the original post as dislocations... many elements appearing in the sentences are identical.

**Comment by dan-zeman** [comment]
> I would not see them as ellipses, but as an internal vs. external head, and this might actually warrant a treatment through `nsubj` as this head is nominal. I think a `csubj` is something else, it is an entire predication acting as subject, not a nominal subject expressed through a clause... if I explained myself.

I think you explained yourself well and I understand your view. I just do not share it :-)

**Comment by amir-zeldes** [comment]
> Sorry, I confused things, new and old, and thought the article and the pronoun coincided in this case. 🙏 Then I agree with an advcl:relcl(ἐποίησεν,ἀπεγαλακτίσθη).

I don't think it needs the `:relcl` subtype, I think it should just be `advcl(ἐποίησεν,ἀπεγαλακτίσθη)` (it's just in an oblique relation to ἐποίησεν and happens to be a clause; the relative part is internal to the ἀπεγαλακτίσθη clause)

**Comment by Stormur** [comment]
> > Sorry, I confused things, new and old, and thought the article and the pronoun coincided in this case. pray Then I agree with an advcl:relcl(ἐποίησεν,ἀπεγαλακτίσθη).
> 
> I don't think it needs the `:relcl` subtype, I think it should just be `advcl(ἐποίησεν,ἀπεγαλακτίσθη)` (it's just in an oblique relation to ἐποίησεν and happens to be a clause; the relative part is internal to the ἀπεγαλακτίσθη clause)

This is exactly the fact for which I see it as an internally headed (oblique) relative clause; in this case the head is the phrase where the relative determiner appears. It is an `advcl`, but since the connector is this relative element and not an `SCONJ` as we would expect in Greek, it should get the `relcl` subtype. I do not think there are ways in which we can see two "finite" clauses in a subordinating relation without any connecting element in Greek.
