### ISSUE TITLE
Short introduction page: wrong page linked?

### ISSUE THREAD

**Issue by francescomambrini** [UniversalDependencies/docs#968]
I am not sure if this is the right repository to open this Issue to, but the URL [https://universaldependencies.org/introduction.html], which is also linked at the home page for [A Short Introduction to UD](https://universaldependencies.org/introduction.html), now points to a documentation page for the Georgian UD Treebank (UD_Georgian-GLC).

**Comment by jnivre** [comment]
Thanks for reporting this. I think the problem was caused by an incorrect permalink in the Georgian introduction.md file, which I have tried to fix. It will take a while before the change propagates through the system, but hopefully it should be okay soon.

Joakim

**Comment by dan-zeman** [comment]
The website rendering system was down for 3 weeks because of the bug in [this commit](https://github.com/UniversalDependencies/docs/commit/af49a86de7db3b7d5ad8df01262014ac1083bec9#diff-134c0d83b2094bfcdc274836b635331ae3652e6c248eba47b528dff5ad68e5c2R10) (and one other, introducing a similar bug for Georgian features). I just fixed it by reverting the buggy commits.
