### ISSUE TITLE
Suggestion: DET table for English

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/docs#971]
As discussed here, I suggest we create a DET table with the known determiners and their features for English.  That way, we can unify that across treebanks.

https://github.com/UniversalDependencies/UD_English-EWT/issues/416#issuecomment-1685437948

As part of this process, I also suggest including features for words such as `another`, possibly by inventing a new feature which matches.  Currently EWT has no features on `another`, whereas GUM has `PronType=Art`.

So, for example, we have

```
a  Definite=Ind|PronType=Art
an Definite=Ind|PronType=Art
the   Definite=Def|PronType=Art

this Number=Sing|PronType=Dem
that Number=Sing|PronType=Dem
these Number=Plur|PronType=Dem
those Number=Plur|PronType=Dem

any   ??? labeled PronType=Ind in GUM
both ???  labeled PronType=Art in GUM
each ExtPos=PRON|PronType=Rcp   or PronType=Tot  or nothing
every  ??? labeled  PronType=Tot  in GUM

all   ???    labeled PronType=Tot in GUM
another ????     PronType=Art in GUM
some ???   PronType=Ind in GUM
no  ???    Polarity=Neg|PronType=Art in GUM

either   ???  labeled PronType=Art in GUM
neither  ???  labeled PronType=Art in GUM

such - there is a case where it has the xpos DT instead of PDT, which seems weird
yonder PronType=Art in GUM
```

furthermore, there are a couple instances of a typo not getting the proper features (in EWT, I believe): his/this, Thi$/this

and then there's PUD which is labeling "those" with the lemma "those" as opposed to "these"

there's also other DETs with the xpos PDT, such as `all`, `quite`, `half`, `both`, `such`, `nary`, `many`

**Comment by nschneid** [comment]
Here is a table from Quirk et al. 1985:

<img width="325" alt="image" src="https://github.com/UniversalDependencies/docs/assets/985263/b68006cc-1a5e-4849-b446-198dd200be45">

The ASSERTIVE group, discussed starting on p. 383, also includes `many`, `a few`, `much`, `little`, `less`, `least`, `fewer`, `fewest`, numerical `one`, `half`, `several`, `enough`, `other`, `others`, `another`.

So it seems reasonable to classify these as `PronType=Ind` unless a more specific feature applies (e.g. `PronType=Tot`).

I take it for a given word, the `PronType` feature should be the same regardless of whether it is tagged as DET or PRON?

**Comment by Stormur** [comment]
For words like _another_, there exists the feature `PronType=Con`, for "contrastive", which we are using in Latin. I think it can encompass _(n)either_ (equivalent to Latin _(ne)uter_, as it were), and maybe some _other_ elements, too. 

For _both_ I can suggest a treatment as `Tot` paired with a `NumType`. This is what we are doing for the equivalent _ambo_ in Latin: this is also what comes out of the table with the label "count".

I think that the label `PronType=Ind` is overused at the moment: the fact is that more or less everything pointed to deictically could be seen as "indefinite" in a sense, but this is misleading.

**Comment by dan-zeman** [comment]
> I take it for a given word, the `PronType` feature should be the same regardless of whether it is tagged as DET or PRON?

I believe it is generally true, but sometimes in some languages people treat one string as homonymous even within the `PRON` category, and give it two different values of `PronType` based on context. (Personally I prefer to avoid this approach unless its really coincidental string identity of words that also have different morphological paradigm.) If that happens, then you may want to project the distinction also across the `PRON`-`DET` boundary.

**Comment by nschneid** [comment]
> For _both_ I can suggest a treatment as `Tot` paired with a `NumType`. This is what we are doing for the equivalent _ambo_ in Latin: this is also what comes out of the table with the label "count".

`NumType=Card` because it implies exactly 2? I like that semantically. Currently the only DET receiving a NumType in English is half/NumType=Frac I believe.

> For words like _another_, there exists the feature `PronType=Con`, for "contrastive", which we are using in Latin. I think it can encompass _(n)either_ (equivalent to Latin _(ne)uter_, as it were), and maybe some _other_ elements, too.

Will this be added to the universal documentation as a possible value? If most treebanks don't use it it may be easier to stick with `Ind` for now than to have to make decisions about what `Con` means in English.

**Comment by AngledLuffa** [comment]
Are we any closer to a definitive answer about what to do with `another`?  That word in particular is different between the two biggest English treebanks, and because it's so evenly balanced, the models I train from the two keep switching between whether they give `another` a feature or not

**Comment by nschneid** [comment]
It appears that `PronType=Con` is only implemented for Latin: https://universaldependencies.org/ext-feat-index.html#prontype

I'd rather not start using it for English unless other languages are planning to start using it. My familiarity with other languages is limited but it appears that some French treebanks use `PronType=Ind` for "autre" ('other'): https://universal.grew.fr/?custom=650642a6bf400 I would go with that for now in English and if there's a wider decision to adopt `Con` it would be easy enough to revise as it's lexical.

**Comment by AngledLuffa** [comment]
Makes sense.  @amir-zeldes ?

**Comment by amir-zeldes** [comment]
Fine by me, I can add it in GUM/GENTLE. So just `PronType=Ind` for lemma="another" right? Any other changes needed in GUM?

**Comment by AngledLuffa** [comment]
Several others marked with ??? above are labeled differently between GUM and EWT: `any`, `both`, `every`, `no`, `some`, `all`, `either`, `neither`

but if we're happen with the current labels in GUM, then I suppose the change needed would be to add those features to EWT, not alter them in GUM

**Comment by nschneid** [comment]
Art should just be a/an/the. The rest should be Tot, Ind, or Rcp I think.
Plus PronType=Neg or NumType=Card as appropriate.

**Comment by nschneid** [comment]
How about the following as the features for DET (xpos DT or PDT or WDT):

Lexemes | `PronType` | Other feats
--------- | ------------- | ------------
_a_, _an_ | `Art` | `Definite=Ind`
_the_       | `Art`  | `Definite=Def`
_this_, _that_ | `Dem` | `Number=Sing`
_these_, _those_ | `Dem` | `Number=Plur`
_yonder_ | `Dem` | 
_all_, _each_\*\*, _every_ | `Tot` | 
_both_ | `Tot` | 
_any_, _some_, _another_, _either_ | `Ind` |
_such_\*, _quite_\*, _many_\* | `Ind` | 
_half_\* | `Ind` | `NumType=Frac`
_no_, _neither_, _nary_\* | `Neg` | 
_which_, _what_, _whatever_ | `Int` or `Rel` |

\* Only DET as a predeterminer (N.B. I am not thrilled with the current practice of tagging "such", "quite", and "many" as DET in their predeterminer uses as it seems like unnecessary multiplication of tag ambiguity, but it follows from treating every PDT as DET: UniversalDependencies/UD_English-EWT#412)
** Except reciprocal _each other_: see [PRON](https://universaldependencies.org/en/pos/PRON.html#reciprocal-pronouns)


> such - there is a case where it has the xpos DT instead of PDT, which seems weird

@amir-zeldes I think [this one](https://universal.grew.fr/?custom=6509090cef614) is an error - should be JJ/ADJ

**Comment by bguil** [comment]
I've written a Grew-match request which "implements" @nschneid's table.
It might help to have a global view of the `DET` that do not follow the table.
For instance: 
 - On [UD_English-GUM@dev](https://universal.grew.fr/?custom=650b07c6ea2ce&corpus=UD_English-GUM@dev)  &rarr; 418 occurrences
 - On [UD_English-EWT@dev](https://universal.grew.fr/?custom=650b07c6ea2ce&corpus=UD_English-EWT@dev) &rarr; 2375 occurrences
 - On [UD_English-ParTUT@2.12](https://universal.grew.fr/?custom=650b07c6ea2ce&corpus=UD_English-ParTUT@2.12)  &rarr; 812 occurrences

**Comment by nschneid** [comment]
Thanks @bguil. Looking at the queries made me realize there were issues with the last 2 rows of the table.

**Comment by nschneid** [comment]
Because *no* indicates a negation of all items in a set, should it be `PronType=Neg,Tot`? Or would that be confusing?

**Comment by nschneid** [comment]
Actually, I've changed my mind: let's go with plain `PronType=Neg` for *no*, *neither*, *nary*. Simpler is better I think (though an argument could be made that `Tot` and `Neg` are subtypes of `Ind`).

**Comment by dan-zeman** [comment]
> Because _no_ indicates a negation of all items in a set, should it be `PronType=Neg,Tot`? Or would that be confusing?

That would be confusing. `Neg` is for _no_, `Tot` is for _all_.

**Comment by Stormur** [comment]
I find `PronType=Neg` extremely problematic, if not misguided. I remember staring for a long time at the guidelines and comparing it to `Polarity=Neg` without understanding the rationale. Because what I observe is that all "negative pronouns" are pronouns/etc. of some kind with negative polarity: if we use `PronType=Neg`, we obscure the type. I would suggest to ditch `PronType=Neg` and to just use `Polarity=Neg`. So we will have indefinite negative pronouns/etc. as _nobody_ = _not any_, contrastive negative pronouns/etc. as lat. _neuter_ = __ne_+_uter_ "neither", and so on.



> > For _both_ I can suggest a treatment as `Tot` paired with a `NumType`. This is what we are doing for the equivalent _ambo_ in Latin: this is also what comes out of the table with the label "count".
> 
> `NumType=Card` because it implies exactly 2? I like that semantically. Currently the only DET receiving a NumType in English is half/NumType=Frac I believe.

`NumType=Card` because it involves a specific (discrete) quantity, and then we also add `NumValue=2`. But it is clear that _ambo_/_both_ are not numerals in the sense _duo_/_two_ are. Then there are also indefinite cardinal quantities like _many_ ("count" in the table), which also should get `NumType=Card`, but `PronType=Ind`. Then, something that we find in English and other languages, but not e.g. in Latin, are terms for non-discrete quantities ("non-count" in the table), for which probably we need a new value like `NumType=Quant`, or else. 

> > For words like _another_, there exists the feature `PronType=Con`, for "contrastive", which we are using in Latin. I think it can encompass _(n)either_ (equivalent to Latin _(ne)uter_, as it were), and maybe some _other_ elements, too.
> 
> Will this be added to the universal documentation as a possible value? If most treebanks don't use it it may be easier to stick with `Ind` for now than to have to make decisions about what `Con` means in English.

Why not start using `Con` anyway? Hoping that it will be "promoted" to universal status as I think it has a place there.

**Comment by nschneid** [comment]
At the end of the day, at least for English, the `Ind`/`Tot`/`Neg` distinction strikes me as more semantic than morphological. (There is nothing in common between the forms *all*, *each*, and *every* that suggests they belong together.) But the features are not capturing the full semantics: *all* and *every* are not interchangeable, yet they have the same features—there doesn't seem to be a goal of developing fine-grained features such that every DET or PRON with a different meaning receives a different combination of features.

From my perspective the best we can do now is converge on a table for English that aligns with https://universaldependencies.org/u/feat/PronType.html. A finer-grained universal theory of these features might be worth developing in the future, but I don't see English morphology as providing much guidance beyond what is already in the universal guidelines (the main opportunity I do see would be to add a feature to group together the _-ever_ items).

**Comment by Stormur** [comment]
> At the end of the day, at least for English, the `Ind`/`Tot`/`Neg` distinction strikes me as more semantic than morphological.

Well, of course it is. All `PronType`s are by nature!

> But the features are not capturing the full semantics: _all_ and _every_ are not interchangeable, yet they have the same features—there doesn't seem to be a goal of developing fine-grained features such that every DET or PRON with a different meaning receives a different combination of features.

Probably we will always have some kind of indeterminacy: else, at one extreme, we should have a specific tag for each form. But probably we can already do much with what we already have: for example, I was considering that _every_ might get a `NumType=Dist` :thinking: I wonder how much one can proceed in this direction

---

With regard to _another_, has a multiword treatment as _an_+_other_ never been considered? It seems rather straightforward, it is just a contrastive element with a mark for indefiniteness (_an_). Maybe this would avoid to being forced to choose a single label which will always be a "short blanket".

**Comment by nschneid** [comment]
> With regard to _another_, has a multiword treatment as _an_+_other_ never been considered? It seems rather straightforward, it is just a contrastive element with a mark for indefiniteness (_an_).

Historically yes, synchronically no. It would be an error to say/write "I have an other idea". Note the syllabification of /əˈnʌð.ɚ/ (not /ən ˈʌð.ɚ/).

**Comment by Stormur** [comment]
> > With regard to _another_, has a multiword treatment as _an_+_other_ never been considered? It seems rather straightforward, it is just a contrastive element with a mark for indefiniteness (_an_).
> 
> Historically yes, synchronically no. It would be an error to say/write "I have an other idea". Note the syllabification of /əˈnʌð.ɚ/ (not /ən ˈʌð.ɚ/).

The orthography might mirror the phonetic coalescence of the two elements, but couldn't they still be considered "syntactically active"? Besides, how semantically different is _another_ from _an+other_?

Now this might be a Pindaric flight, but if I think to Italian _un altro_ / _un'altra_, it is written separate though phonetically it is just one unit, and there is absolutely no way to distinguish any different use as supposedly _an other_ vs. _another_.  Also, please correct me if I am wrong, but is it at all possible to use _an other_ instead of the univerbation?

My point is that we are probably (once again) mislead by orthographic conventions here.

**Comment by nschneid** [comment]
I'm not sure how to test for a notion of "syntactically active" but my sense is that "another" is extremely well established as a word of English. It is listed in dictionaries (and not as a spelling variant of "an other"). As far as I am aware there is no tradition of tokenizing it as two words. (Just like we don't split "without" or "spreadsheet" or what have you.) So splitting it in UD would cause confusion IMO.

(There are probably more syntactic arguments that can be made here: e.g. stranding is possible, unlike semantically similar adjectives: _I ate one muffin and now I want another/*an additional_. But the bottom line is that _another_ is normally regarded/tokenized as one word so it would require an extremely compelling reason to change that.)

Similar expressions in other languages may not be as far along in grammaticalization; we cannot expect the UD tree to be exactly parallel across languages.

**Comment by Stormur** [comment]
Here we are getting back to the issue of "what is a word"... I am just perplexed that a string which is by all means transparent in all its components and behaviour is kept together just for (motivated) orthographic conventions (as a note: in my opinion _other_ should be considered a determiner rather than an adjective). The same cannot be said for _without_, I think. It may be just me, but I see much more confusion in keeping _another_ together, while having _an_ as a separate element in all other cases. But I fear the discussion would grow much more over the topic of `DET`s features here.

**Comment by amir-zeldes** [comment]
Splitting "another" would also lead to inconsistency with the tokenization in non-UD corpora, which I am very happy to say we have not diverged from so far. It's quite nice that tokenizers trained on the ~3M tokens in OntoNotes work quite well for UD data, since it's the same standard for what counts as a token.

**Comment by Stormur** [comment]
In fact, after some thought I recognise that splitting _another_ might not be the ideal choice, principally because both split elements would be functional, and since it is ultimately irrelevant if we just consider that features like `Definite=Ind` can simply be annotated on it together with others. Also, what I substantially would vie for is to consider _another_ as part of the paradigm of _other_, so maybe to lemmatise both the same way. But again, here the discussion goes beyond the topic of this issue, sorry.

**Comment by nschneid** [comment]
@amir-zeldes are you OK with the table in https://github.com/UniversalDependencies/docs/issues/971#issuecomment-1724761488?

**Comment by sylvainkahane** [comment]
Note that "lemma=other" exists with various DETs. 
In GUM: https://universal.grew.fr/?custom=650c7d874b8ac
In EWT: https://universal.grew.fr/?custom=650c7cefaf4f0
By the way, it is annotated with upos=NOUN in GUM and upos=ADJ in EWT. 
What is remarkable is that this lemma can never have the DET "an". It is a very strange property.
As a non-native speaker of English, I don't understand why "an other" is not possible and why it could be different from "another". So my intuition is the same as @Stormur and I don't see how you prove that "another" is something else than an orthographic quirk. @nschneid's answer was not sufficient.

**Comment by nschneid** [comment]
You are quite right that the blocking of the indefinite determiner is a strange property. It can be explained historically. But I have never seen an English dictionary, tokenizer, or reference grammar that treats "another" as an orthographic quirk. Here is CGEL for example:
<img width="622" alt="image" src="https://github.com/UniversalDependencies/docs/assets/985263/d12bf766-47c7-49ec-8076-a51e2af892ef">

**Comment by amir-zeldes** [comment]
> are you OK with the table 

Sorry, probably, I need to find a free moment to go over it in detail - will post here again once I've had a chance

**Comment by amir-zeldes** [comment]
OK, I've had a closer look now - the only thing I would change there is not treating "both" as a cardinal number. I agree it normally implies that there are two things, but it's still different from a cardinal number which gets a NumType IMO. We also don't assign these features to words like "pair" or "decade", even though they imply a count. Half seems OK though, since that's actually the English name of that number.

**Comment by nschneid** [comment]
OK, removed `NumType=Card` for "both"

**Comment by Stormur** [comment]
I'd just like to notice that `NumType` does not imply that a word is a cardinal number: that depends on the part of speech `NUM`, and if a word has one, it necessarily needs a `NumType,` while the converse is not true. The difference of _both_ from _two_ is given both by its part of speech and the presence of `PronType.` 

As for considering a `NumType` for words like _pair_ or _decade,_ well... it actually does not sound too much an adventurous idea now that I hear it :thinking:

**Comment by amir-zeldes** [comment]
OK, the table is now implemented in GUM as well (see the UD dev branch for results). Let me know if you notice anything off!
