### ISSUE TITLE
Why "VerbType" is not in the Lexical/Inflectional Features Table on Universal Features web page?

### ISSUE THREAD

**Issue by tolgahanturker** [UniversalDependencies/docs#972]

**Comment by tolgahanturker** [comment]
VerbType is not in the Lexical/Inflectional Feature table in the UD Universal Features [web page](https://universaldependencies.org/u/feat/#universal-features) . However, there is a section described under VerbType heading in the same page. Can someone comment about how to categorize "VerbType" while annotating?

Similar question can be asked also for "[PartType](https://universaldependencies.org/u/feat/all.html#parttype-particle-type)" which is also not in the Lexical/Inflectional Feature table, but there is a section about it on the same page.

**Comment by dan-zeman** [comment]
> However, there is a section described under VerbType heading in the same page.

I do not see any such section heading at [the page](https://universaldependencies.org/u/feat/#universal-features). It should not be there because `VerbType` does not have the status of universal feature.

Nevertheless, it has been used as a language-specific feature in a few treebanks and it has even a globally accessible documentation page (which however is not the same thing as being officially a "universal" feature).

Finally, the lexical/inflectional distinction on the page you originally referred to is there mainly to structure the features somehow but it is not so important, and it also does not work the same way in all instances and languages (see the disclaimer at the bottom of the page). But to answer your question, I would say that `VerbType` (and generally all the `*Type` features) is a lexical feature, which applies to the whole lexeme (all forms sharing a lemma) rather than individual inflected forms. Note that this does not mean that the same word cannot occur with different values. For example, some verbs in some languages have different senses, in one of them they would count as modals, in others as main verbs.
