### ISSUE TITLE
Update guidelines for fixed, flat, compound and be more careful about the term "multiword expression"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#989]
It was agreed at the [May 2023 Dagstuhl Seminar](https://www.dagstuhl.de/23191) that the UD guidelines are not clear enough about the distinction between MWEs marked by semantic idiosyncrasy, which may be associated with a variety of kinds of expressions, and syntactic criteria for the `fixed`, `flat`, and `compound` relations. ([Dagstuhl report](https://drops.dagstuhl.de/entities/document/10.4230/DagRep.13.5.22), p. 45)

@jnivre has led a rewrite effort. This issue will track the guidelines updates.

**Comment by nschneid** [comment]
^ adds a new heading to illustrate fixed/flat vs. compound. If we keep this a link should be added in the outline at the top of the page. But there's still no real explanation in the syntax overview of what `compound` is for, not even under [nominals](https://universaldependencies.org/u/overview/nominal-syntax.html).

**Comment by jnivre** [comment]
I am not sure such an explanation is needed in the syntax overview, which does not provide an exhaustive discussion of all relations, but is a construction-oriented description focusing on major construction types like nominals and clauses. In the case of compound, I think the relation definition is sufficient in itself. Moreover, since compounding is not restricted to nouns, it doesn't really belong in the nominals section either (except if we want to mention the special case of the nominal head being a noun-noun compound). A general discussion of compounding would have to go into a (new) section on "word formation" or "lexical relations".

**Comment by nschneid** [comment]
How about ^ this? It generalizes the MWE section to also cover compounds and headless structures.

**Comment by jnivre** [comment]
I see the point of doing this, but the current version is a bit of a rag-bag. Compounds and MWEs sort of fit together as "things that behave like single words", but flat expressions go beyond this (because they may be composed of phrases).

**Comment by nschneid** [comment]
I do think most flat expressions, like compounds and fixed expressions, are "quasi-lexical"—they tend to be proper names, or else borrowed foreign phrases that would be listed in a dictionary. The main exception is quoted foreign material. But apart from that, if two large units (e.g. sentences) appear next to each other without grammatical linkage, we don't call it `flat`—we call it `list` or `parataxis`.

**Comment by nschneid** [comment]
Removed recommendation of `flat:name` in light of UniversalDependencies/UD_English-EWT#468, but added an acknowledgment that some languages use subtypes.

Pages updated so far:
- https://universaldependencies.org/u/dep/compound.html
- https://universaldependencies.org/u/dep/fixed.html
- https://universaldependencies.org/u/dep/flat.html
- https://universaldependencies.org/u/overview/specific-syntax.html#lexical-relations-multiword-expressions-headless-structures

**Comment by jnivre** [comment]
Thanks, Nathan. The relation definitions look good to me now. However, I still find the initial paragraph on the “compound” relation out of place in the section on lexical relations, etc. I don’t see why we need to characterize the “compound” relation before explaining how it is (not) used, when we don’t do the same for “fixed” or “flat”. I would refer to simply remove this paragraph and rename the section “Multiword expressions and headless structures”. I think it reads much better that way, but I am curious to hear what others think.

Joakim

**Comment by sylvainkahane** [comment]
The [definition](https://universaldependencies.org/u/overview/specific-syntax.html#lexical-relations-multiword-expressions-headless-structures) start by "Structures analyzed with [fixed](https://universaldependencies.org/u/dep/fixed.html) and [flat](https://universaldependencies.org/u/dep/flat.html) are headless by definition"
I really don't like the examples given just after that, because both of them have clearly an internal syntactic structure:
1. _in spite of_: ok, it is a frozen expression, but it has a very clear syntactic structure, exactly as _in front of_, _in support of_, _in term of_, etc., which have a [normal analysis](https://universal.grew.fr/?custom=654d4b9504d71).
2. _Martin Luther King_: there are occurrences of _Luther King_ without _Martin_. So it is not so flat, and _Luther King_ works as the last name I think  and should be a phrase.

**Comment by nschneid** [comment]
I'm open to suggestions on reorganizing/changing examples. I just think it would be strange not to acknowledge `compound` as part of the general guidelines pages for UD syntax.

Just noticed this page also needs updating: https://universaldependencies.org/u/overview/syntax.html In fact, does all the discussion of MWEs belong there rather than under [Other Constructions](https://universaldependencies.org/u/overview/specific-syntax.html)?

**Comment by sylvainkahane** [comment]
> I'm open to suggestions on reorganizing/changing examples. 

Examples for `fixed` should be chosen among the things that have been annotated `fixed`: https://universal.grew.fr/?custom=654dc47a5079f
But even here, I am not sure I agree with all the choices made. Constructions such as _in order to_, _instead of_, _according to_, etc could be analyzed with a very standard syntactic structure. I do have the impression that we're mixing semantic criteria (frozenness) with syntactic ones. This is also a consequence of UD's initial choice to treat adpositions as dependents.

**Comment by nschneid** [comment]
@sylvainkahane I agree that the English `fixed` list is somewhat ad hoc (see e.g. UniversalDependencies/UD_English-EWT#400), and one of the priorities in connection with UniDive should be to decide what to do about that. But for the time being, we just need some good examples for the general guidelines.

**Comment by amir-zeldes** [comment]
> Constructions such as in order to, instead of, according to, etc could be analyzed with a very standard syntactic structure

I think that's a language-specific guidelines choice. In the case of these English items I agree that they are parallel to other constructions which are analyzed transparently, but this is true for almost any language - in UD French GSD we have "en ->fixed vigueur", which has a special legal meaning (a law is "in force"), but there is nothing special about the syntax AFAIK. In the English case we have some legacy choices from older editions of UD, and maybe those should have been decided differently, but I do not think it's unusual for fixed expressions to have some historically transparent syntax.

As a matter of principle, I think once we say something is `fixed` in UD, we assert that we no longer care about its etymological structure, even if it is transparent - we are saying that it functions as a unit. A better example is maybe "as well as", which also has a transparent etymological strucutre, but synchronically acts like a single coordinator, similar to "and" - so `fixed` says we recognize it as a multi-part version of "and", regardless of its origin.

**Comment by nschneid** [comment]
OK, I've merged the revised content into https://universaldependencies.org/u/overview/syntax.html and removed it from Other Constructions. Did my best to take into account the above suggestions to make things clearer. Also improved cross-linking within and across pages. How does that look?

**Comment by sylvainkahane** [comment]
Thanks @nschneid. I am ok with this version (and I agreed with @amir-zeldes too). I am not sure it is useful to have two separate sections, one on [Multiword function word](https://universaldependencies.org/u/overview/syntax.html#multiword-function-words) and another, farther, on [Multiword expressions and headless structures](https://universaldependencies.org/u/overview/syntax.html#multiword-expressions-and-headless-structures), especially because only multiword function words are annotated as MWEs in UD (which could be explicitly said).
By the way, if you want a good example in French, I like the adverb _quand même_  for which I would be unable to propose a reasonable internal structure: _quand même_ 'even so, really', lit. when even.

**Comment by jnivre** [comment]
Thanks, Nathan. Looks good to me too. I think the section on “Multiword function words” is still justified, because it describes one of four listed exceptions to the rule that function words do not have dependents.

Joakim

**Comment by jnivre** [comment]
I modified the overview table by moving “compound” to the “Special” group and replacing “MWE” with “Headless”, which seems appropriate for the two remaining relations in that group (“fixed” and “flat”). Since none of the other proposals was completely convincing, I agree with the comment by Marie that it is preferable to make a minimal change, so that people will recognize most of the table.
