### ISSUE TITLE
Annotations for adjectives referring to proper nouns vs common nouns

### ISSUE THREAD

**Issue by rhdunn** [UniversalDependencies/docs#994]
Currently, there is no way in the UD English treebanks to differentiate between adjectives that refer to common nouns and those that refer to proper nouns -- both are annotated as `ADJ+JJ`.

This makes the lemmatization rules inconsistent where exceptions need to be defined for all the proper noun derived forms. This covers things like:
1. references to places -- e.g. "the French revolution";
2. references to religions -- e.g. "the Jewish community";
3. references to political parties/alignments -- e.g. "the Republican party";
4. references to people (esp. scientists) -- e.g. "in Lagrangian mechanics".

It would be helpful in terms of things like validating lemmas to have common and proper noun adjectives differentiated e.g. in a feature annotation. I'm not sure of any cases where the distinction is necessary (i.e. if there are cases where a common and proper noun have the same form text). Therefore, this annotation would be lexical in the same way the `NumForm` is for numbers.

**Comment by nschneid** [comment]
Not sure I follow—could you elaborate on what this has to do with lemmatization? Are you referring to capitalization or something else?

**Comment by sylvainkahane** [comment]
The remark is that the distinction between proper vs common nouns also exist for adjectives. But it is something which is essentially semantic, because I don't think that adjectives referring to "proper noun" have different syntactic properties.
By the way, it is also not very clear that the distinction between proper and common nouns is syntactically motivated in most languages.

**Comment by rhdunn** [comment]
Yes, I'm referring to whether or not the lemma is capitalized. In common noun adjectives (west, etc.) the lemma should be lower case, whereas for proper noun adjectives (e.g. Saxon) the lemma should be capitalized.

For the other parts of speech and features it is possible to determine the casing that the lemma has. For adjectives, I'm needing to build a list of the adjectives that are capitalized/proper noun based.

**Comment by nschneid** [comment]
From a theoretical perspective in terms of relevance to morphosyntax, I don't see a strong need for the distinction (as @sylvainkahane points out it is semantic).

From a practical perspective, if it would essentially be redundant with the lemma being capitalized, I'm not sure what it buys us. It is easy enough for a script to check whether the lemma is capitalized. Building the list of capitalized adjectives would be necessary anyway to implement the new feature.

**Comment by rhdunn** [comment]
So IIUC for cases where the adjective is a common noun or based on a common noun (White, West, Eastern, etc.) the lemma should always be the lower case form, and when it is a proper noun then it should always be capitalized?

**Comment by leky40** [comment]
What about the languages do not have capital letters?

**Comment by amir-zeldes** [comment]
I think in practice the lemma of adjectives is capitalized where the normative, prescriptive orthogtaphy of the lanuage would capitalize them. We capitalize "French" in "the French language" because most people spell it that way, and an average English tutor would probably mark it an error if we wrote "the french language" - so "French" is considered the canonical form in this context. I don't think it corresponds to a strongly motivated syntactic distinction, it's just a lexicographic distinction.

**Comment by nschneid** [comment]
If we were doing *semantic* annotation it would be reasonable to have an entity type feature. Some UD treebanks have this in MISC. There are certainly orthographic differences between languages that this would normalize across (e.g. in French I believe capitalization is used for names of persons but not languages, which would standardly be capitalized in English).

If there is a *morphosyntactic* category of proper adjective in some language, e.g. different affixes, then it would make sense to have a morphological feature (but maybe it wouldn't apply to English).

> So IIUC for cases where the adjective is a common noun or based on a common noun (White, West, Eastern, etc.) the lemma should always be the lower case form, and when it is a proper noun then it should always be capitalized?

See https://github.com/UniversalDependencies/UD_English-EWT/issues/131#issuecomment-787093974. We haven't developed 100% complete guidelines for English lemmatization but that is where we currently are.

**Comment by rhdunn** [comment]
I'm working on a lemma validator (https://github.com/rhdunn/conllu-en-validator/blob/master/validator/lemma.py) for my English validation script. The adjective question came up as a result of that -- I'll make use of the lemma exceptions to handle capitalization.

I'm going to raise issues identified by this script once I have a full set of lemma validators so I can group the issues by things like missing CorrectForm annotations, POS tagging errors, etc..

**Comment by rhdunn** [comment]
I'll take that issue into consideration for my validator.

**Comment by dan-zeman** [comment]
I agree that the distinction is mostly semantic and it is definitely not syntactic, although proper capitalization is part of the grammar, so the semantics actually has some impact on the surface form. The same situation is with `PROPN` vs. `NOUN` in Czech: As the two tags are defined in UD, we do distinguish proper and common nouns to increase parallelism with other languages, but there is hardly much more to it than semantics and capitalization.

If there were a feature to distinguish "proper adjectives" and we wanted to use it, we would face the problem how to delimit it. Except for possessive adjectives (e.g. _Havlíčkův_ "Havlíček's", derived from a surname), adjectives derived from proper nouns are not capitalized (and I believe this is the case in many other languages): _francouzský_ "French", _židovský_ "Jewish" etc.

Note that morphological derivation can be optionally captured in MISC and we do it in Czech, using the [LDeriv](https://universaldependencies.org/misc.html#lderiv) MISC attribute:

<pre>
6  Havlíčkově  Havlíčkův  ADJ  _  Case=Loc|Gender=Fem|Gender[psor]=Masc|Number=Sing|Poss=Yes … LDeriv=Havlíček
</pre>

**Comment by jnivre** [comment]
For me this clearly goes beyond the morphosyntax that UD can be expected to cover. This doesn't mean that it may not be worth annotating, but I then think it should go into an additional annotation layer on top of UD (like existing efforts to annotate multiword expressions and co-reference), or possibly into the (notorious) MISC column. It should definitely not go into the basic part-of-speech tag distinctions.

**Comment by amir-zeldes** [comment]
Agreed, I don't think this is really a universal feature - each language has different conventions for what exactly is capitalized.

@rhdunn you could try using a lexicographic resource to establish whether a lemma normally has/allows capitalization. Both dictionary.com and WordNet capitalize the entry for French, including as an adjective, for example:

  * https://www.dictionary.com/browse/french
  * http://wordnetweb.princeton.edu/perl/webwn?s=french&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=

**Comment by Stormur** [comment]
In Latin we experimented with `NamedEntity` assigning it also to `ADJ`s, but this feature will be discontinued and made relive under other forms. This technique exploits a kind of "tag polysemy", in that `NamedEntity` tied to referential POSs (`NOUN`/`PROPN`) means that they are words indicating to such entities, while tied to relational POSs (`ADJ`) they refer to some property of those entities. 

I agree with many other comments here above in that no particular annotation is needed at a morphosyntactic level and spelling rules might be "clues but not leads", HOWEVER I would like to point out, as one of the possible reasons of the main poster's perplexity, that a subclass of these adjectives is indeed a straining point of the usual distinction between inflection and derivation. All these formations are so regular that one wonders if we could just do something like 

* _**Lagrangian** mathematics_
    * _Lagrangian_ `NOUN` (or `PROPN)` with lemma _lagrange_ and a feature like `Transposed=ADJ` 
        * (I believe that semantic informatio nshould not be forced into the lemma by means of capitalisation or similar; the form does the job) 

Are possessive forms in Czech, e.g. _karlův_/_karlova_/... from _Karl_ different in any way from the English adjectiviser _-an_? How they do not belong to the same lexeme? 

I understand the caution used by UD for these formation, but using `MISC` with `LDeriv` or similar just seems to me like pushing very relevant paradigmatic information to the margin.

Yes, this really opens up a true can of worms, but maybe we could start experimenting at least from this subclass of "proper adjectives"?

**Comment by martinpopel** [comment]
> In Latin we experimented with `NamedEntity`

I would suggest to use the [Entity](https://universaldependencies.org/misc.html#entity) annotations instead (coreference can be added here as well, it is supported by the validator using `--coref` and by [Udapi](https://github.com/udapi/udapi-python/blob/master/udapi/core/coref.py)).

> Are possessive forms in Czech, e.g. _karlův_  / _karlova_  /... from Karl different in any way from the English adjectiviser -an?

These possessive adjectives derived from proper nouns (personal names) are capitalized in Czech, i.e.  _Karlův_ / _Karlova_ (and the lemma _Karlův_ is thus capitalized as well). The English translation is _Karel´s_ (if it was the Czech name, or _Karl's_ in case of the German name). The English (Latin origin) suffix _-ian_ (e.g. _Charlesian_) would rather correspond to Czech suffix _-ovský_ (e.g. _karlovský_) and this kind of adjectives is not capitalized in Czech and is more commonly derived from surnames, e.g. _čapkovský styl_ means _the style of Karel Čapek_.

> How they do not belong to the same lexeme?

That's the tradition of keeping separate lemma for adjectives and nouns even if the derivation is very regular.
That said, this tradition has been broken on the tectogrammatical layer of annotation (of PDT and PCEDT), where it [has been decided](https://ufal.mff.cuni.cz/pdt2.0/doc/manuals/en/t-layer/html/ch04s02.html) that _Karlův_ will have t-lemma _Karel_. However, it is not the goal of UD to go so deep as the t-layer.

> Lagrangian NOUN (or PROPN) with lemma lagrange

_Lagrangian_ is perhaps not the best example because [it can actually be a noun](https://en.wiktionary.org/wiki/Lagrangian#Noun), in which case I think it should have lemma _Lagrangian_ (BTW: The Czech translation is _lagrangián_ or even _lagranžián_.)

> I understand the caution used by UD for these formation, but using MISC with LDeriv or similar just seems to me like pushing very relevant paradigmatic information to the margin.

I consider `LDeriv` quite appropriate. Of course, it cannot cover all the peculiarities of derivational morphology, but that goes clearly beyond the UD project, and there are related projects for this, e.g. [UDer](https://ufal.mff.cuni.cz/universal-derivations).
